### ISSUE TITLE
找不到插件在哪显示

### ISSUE THREAD

**Issue by zhl111** [muzuiget/dualsub-support#101]
youtube网站怎么也加载不出来，所有的插件都关了也不行，似乎不是冲突问题。我用的是centbrowers

**Comment by zhl111** [comment]
之前的版本用的挺好，还能用以前的版本吗

**Comment by zhl111** [comment]
发现是有的视频有显示插件，有的视频不显示插件。这是什么情况？

**Comment by muzuiget** [comment]
把不能显示的视频地址发一下咯。

**Comment by tt253605057** [comment]
> 把不能显示的视频地址发一下咯。
部分视频不能显示插件，例如 https://www.youtube.com/watch?v=H6tF3N8B8uQ

**Comment by muzuiget** [comment]
这个视频本身就没有字幕功能的，广告、直播类都是不显示菜单的。
