### ISSUE TITLE
是否可以参考【Netflix 同時字幕で英語学習】这个扩展一些功能

### ISSUE THREAD

**Issue by Danguor** [muzuiget/dualsub-support#103]
【Netflix 同時字幕で英語学習】是款付费订阅的扩展，不过是针对日文母语的使用者开发的
https://chrome.google.com/webstore/detail/netflix-%E5%90%8C%E6%99%82%E5%AD%97%E5%B9%95%E3%81%A7%E8%8B%B1%E8%AA%9E%E5%AD%A6%E7%BF%92/gibmkmmdicoffkhjkfimmjkojjopoagg
有几个比较有特色的功能：
1.调整播放速度；
2.单句退后复读；
3.英语在线划词翻译，但只支持英日词典；

**Comment by muzuiget** [comment]
这些功能都考虑添加。

**Comment by muzuiget** [comment]
在 v1.8.0 里已经可以选择文本了，不知道是否和其它划词翻译扩展兼容？
