### ISSUE TITLE
建议字幕能换行及下拉至底部

### ISSUE THREAD

**Issue by sunday10** [muzuiget/dualsub-support#104]
<img width="635" alt="QQ20200604-001851@2x" src="https://user-images.githubusercontent.com/14009345/83661652-0191e600-a5f9-11ea-8c15-4b48ec00453a.png">

<img width="736" alt="QQ20200604-001630@2x" src="https://user-images.githubusercontent.com/14009345/83661675-09ea2100-a5f9-11ea-8c85-ea35883854e4.png">

![QQ20200604-001216@2x](https://user-images.githubusercontent.com/14009345/83660999-1fab1680-a5f8-11ea-8dd3-e8450884cdd2.png)

希望能跟图1官方字幕自动换行。
还有能跟图1官方字幕位于底部。滑动鼠标时字幕是往上显示。

**Comment by muzuiget** [comment]
换行问题不好改，因为原本的设计就是把换行符去掉，双语字幕一行一个语言。因为很多英语 `CC 字幕` 两三个单词就换一行，也就是每行都不是一句完整的句子，一句对白占三四行是常见。你截图你的自动字幕也是 6、7 单词就强制换一行，并不是一句完整句子。所以原本两行合成一行有可能太长，但是人工创建的字幕很少这样。解决方法就是缩小字体，或者扩大视频显示。

第二个问题，你确实可以长按字幕拖曳的，只是目前在非全屏下，似乎坐标定位有点偏移。

**Comment by sunday10** [comment]
第一个问题明白了。
第二个问题试过往下拉，但只能到图三的位置，没法再往下了。

**Comment by muzuiget** [comment]
> 滑动鼠标时字幕是往上显示。

这是有意不这么做的，因为要和官方播放器状态做交互，需要做更多逆向工程分析播放器的接口，获取状态栏的位置，高度等等，而且每个网站设计都不一样，这很麻烦，固定位置就是最简单。而且有些人也不喜欢这种滑动效果。

默认是限制最低位置，避免和状态栏重叠，毕竟重叠了会有抢焦点问题。看你的截图，似乎确实偏高了，YouTube 的最低位置就是状态栏高度高一点点。

**Comment by sunday10** [comment]
好的。明白了。thx.

**Comment by muzuiget** [comment]
可以用“用户样式”来临时解决一下这个问题，[YouTube 比例缩放字体大小](https://dualsub.netlify.app/zh-cn/styling-user?id=youtube-%e6%af%94%e4%be%8b%e7%bc%a9%e6%94%be%e5%ad%97%e4%bd%93%e5%a4%a7%e5%b0%8f)。
