### ISSUE TITLE
字体边缘的透明度

### ISSUE THREAD

**Issue by molkes** [muzuiget/dualsub-support#106]
调节字体透明度时不同步调节字体边缘的透明度，结果字幕看起来像是调暗了颜色，没有透明效果。

**Comment by muzuiget** [comment]
你可以边缘效果改成“边框”或者“阴影”。

**Comment by molkes** [comment]
我试过了全部边缘效果，情况照旧。

**Comment by muzuiget** [comment]
在“通用”的“基础样式”，切换为“无”。

**Comment by molkes** [comment]
> 在“通用”的“基础样式”，切换为“无”。

已调整，情况照旧。

**Comment by muzuiget** [comment]
不打算为这个属性添加可视化控件了，要实现这个效果，使用[用户样式](https://dualsub.netlify.app/zh-cn/styling-user)来自定义。
