### ISSUE TITLE
隐藏字幕语言

### ISSUE THREAD

**Issue by molkes** [muzuiget/dualsub-support#107]
抱歉，我先前在#93 请求隐藏YouTube工具栏，现在才发觉选项不通用。请去掉YouTube的隐藏工具栏选项，改为在“通用 > 字幕菜单”，增加隐藏机器翻译选项。这样才能让bilibili等其它网站隐藏工具栏。

**Comment by muzuiget** [comment]
现在就有单独能隐藏“机器翻译”呀。

**Comment by molkes** [comment]
我打错了，是“字幕语言”。

**Comment by muzuiget** [comment]
在 v1.7.0 里，YouTube 那个”隐藏“选项已经移除，并引入 [用户样式](https://dualsub.netlify.app/zh-cn/styling-user) 来解决这个问题。
