### ISSUE TITLE
字幕单个单词无法选择

### ISSUE THREAD

**Issue by spgu** [muzuiget/dualsub-support#108]
对于youtube字幕，我相信有很多人要针对有的单词进行单个查阅，就是要用eJOYEnglish这种插件进行选取单个单词查阅，咱们这个插件以前旧版本是可以实现选取单词的，现在新版本一直不能选取某个单词进行查阅，这太不方便了，别的功能真的很多，希望改进一下

**Comment by muzuiget** [comment]
已经计划做了 #72
