### ISSUE TITLE
设置快捷键关闭和开启字幕

### ISSUE THREAD

**Issue by skyrimplayerr** [muzuiget/dualsub-support#109]
如题

**Comment by muzuiget** [comment]
在 v1.8.0 已实现，可以在设置里自定义，默认是：

* <kbd>Alt</kbd> + <kbd>S</kbd> 显示
* <kbd>Alt</kbd> + <kbd>H</kbd> 隐藏
* <kbd>Alt</kbd> + <kbd>T</kbd> 切换
