### ISSUE TITLE
b站播放视频的下方工具栏会被屏蔽，建议屏蔽bilibili.com

### ISSUE THREAD

**Issue by onelone** [muzuiget/dualsub-support#111]
如上

**Comment by muzuiget** [comment]
怎么屏蔽法？是字幕出现时的遮挡吗？

你可以用浏览器的扩展权限来单独屏蔽 bilibili。

**Comment by onelone** [comment]
就是下面进度条和下面一栏会直接没有，如你所说浏览器的扩展权限关了之后好了，再打开不屏蔽也是好的，可能就出现在我这种老是重装系统的人身上，初次玄学

**Comment by muzuiget** [comment]
不太可能啊，没有添加工具栏相关的代码啊。
