### ISSUE TITLE
Duaslub下载youtube字幕没有反应

### ISSUE THREAD

**Issue by carli0215** [muzuiget/dualsub-support#114]
https://dualsub-exporter.netlify.app/ 下载youtube链接几乎都没有反映
https://www.youtube.com/watch?v=Q8fnx85k3_k
https://www.youtube.com/watch?v=ZPwt4D47rCM
https://www.youtube.com/watch?v=cVTwmZStnbo

**Comment by muzuiget** [comment]
已经修复。
