### ISSUE TITLE
怎么能安装旧版办

### ISSUE THREAD

**Issue by spgu** [muzuiget/dualsub-support#115]
怎么能安装旧版办，就是最早以前没有更新前的版本，最早的版本youtube选词的时候，youtube会自动停止，结果翻译软件，特别好用，不知道更新以后以后为什么老是实现不了这个功能，新版本可以选词，但是不会自动停止，字幕一直在动，没法准确选择，感觉后来跟新的版本都没有以前的好用，用的好好的，为什么要更新，已经等了好几个月了，一直解决不了这个问题。唉

**Comment by XiaoPanPanKevinPan** [comment]
有個網站叫做 Crx4Chrome ，仔細看了下它專門搬運穀歌應用程式商店的插件，似乎個版本都有，可以看下。

[Crx4Chrome 上 Dualsub 的舊版本清單](https://www.crx4chrome.com/history/121922/)

服用方法：
1. 找到你要的舊版本並下載
2. 將其作為一個壓縮檔，並解壓縮
3. 在Chrome上打開 chrome://extensions/
4. 刪除原本的 Dualsub
5. 開啟右上角 [ 開發人員模式 ] 開關
6. 點擊 [ 載入未封裝項目 ] 並選擇解壓的資料夾。如果你喜歡，也可以直接把資料夾拖曳過去。
7. 大功告成！

**Comment by spgu** [comment]
> 你好，还有以前的设置教程吗，我选的0.8.1版本，就是需要开通系统字幕才可以，但是里边需要填写自己设置的代码，现在官网没有介绍了。请问哪里还可以找到呢，现在的字体太小了，想着放大一些呢
![Snipaste_2020-06-22_21-53-09](https://user-images.githubusercontent.com/51852502/85289719-d7826400-b4d2-11ea-8f86-70a0c7a3c546.png)

**Comment by spgu** [comment]
对于我自己来说，只需要满足我，英文在上 中文在下，且英文字体大，中文字体小就行。然后最重要一点就是能结合第三方插件实现单个词取词翻译，并且取词的时候能自动停止视频，查询完后自动播放就可以了

**Comment by spgu** [comment]
能感觉到楼主很用心，一直在回复大家提出的问题。但是感觉新版本好像不用开启系统自带字幕就可以翻译，但是实现不了取词了。直接需要获取系统字幕不行吗，别的改动都挺喜欢的，

**Comment by muzuiget** [comment]
我试了一下，v0.8.1 版也是不会自动暂停视频，不知道你是否在使用其它扩展而产生这种效果。

[v0.8.1 文档](https://5eb5761d65fde3e904243b36--dualsub.netlify.app/zh-cn/setting)。

现在 1.x 版本除了不能自动暂停视频外，还有哪些取词问题？

**Comment by spgu** [comment]
你好，我英文不是很好，也是抱着学习英文的态度观看英文视频的，所以有时候不光看整个句子的意思，有时候会通过单词查询软件查看单个单词的意思和读法，我用的是软件是EJOY见附件（https://ejoy-english.com/en/），这个插件只要鼠标一挨到单词，视频就会暂停，鼠标移开以后就会自动播放，他需要打通/识别系统自己的字幕，见附件，以前我是把你的软件和EJOY插件结合着用，你的插件实现双语，EJOY实现单个单词意思查询，你的软件早期版本也是需要打开系统自带的字幕才可以实现双语，所以EJOY软件可以结合这用，现在你的更新的版本实现双语不用打开系统字幕就可以，所以这个软件就没法识别你的软件翻译的字幕。你的插件现在的版本也可以取词，但是我取词的时候，视频一直在播放，那这个就尴尬了，字幕一直在走啊，没法选取啊，并且你的取词需要鼠标单击选中才行，如果可以实现鼠标一挨着字幕就暂停视频，就会翻译就可以了。相当于替代EJOY的插件的功能。别的感觉都还行，主要这个是硬伤，对于需要查询单个单词的用户是没法解决的问题，很严重哦。谢谢，另外就算我安装了旧版本，chrome浏览器也会自动给我更新成最新版本，所以很无语了，如果你软件的新版本可以解决这个问题，就不用来回这么折腾，我是有点不明白，为什么你最新的版本舍弃不再打开系统字幕就能直接翻译 。

发件人: muzuiget<mailto:notifications@github.com>
发送时间: 2020年6月23日 下午 1:37
收件人: muzuiget/dualsub-support<mailto:dualsub-support@noreply.github.com>
抄送: spgu<mailto:spgu@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [muzuiget/dualsub-support] 怎么能安装旧版办 (#115)


我试了一下，v0.8.1 版也是不会自动暂停视频，不知道你是否在使用其它扩展而产生这种效果。

v0.8.1 文档<https://5eb5761d65fde3e904243b36--dualsub.netlify.app/zh-cn/setting>。

现在 1.x 版本除了不能自动暂停视频外，还有哪些取词问题？

―

**Comment by spgu** [comment]
[cid:image001.png@01D64CC4.D1EB2D40][cid:image004.png@01D64CC4.FA3D4A30][cid:image005.png@01D64CC4.F9987EB0]
发件人: muzuiget<mailto:notifications@github.com>
发送时间: 2020年6月23日 下午 1:37
收件人: muzuiget/dualsub-support<mailto:dualsub-support@noreply.github.com>
抄送: spgu<mailto:spgu@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [muzuiget/dualsub-support] 怎么能安装旧版办 (#115)


我试了一下，v0.8.1 版也是不会自动暂停视频，不知道你是否在使用其它扩展而产生这种效果。

v0.8.1 文档<https://5eb5761d65fde3e904243b36--dualsub.netlify.app/zh-cn/setting>。

现在 1.x 版本除了不能自动暂停视频外，还有哪些取词问题？

―

**Comment by muzuiget** [comment]
因为 v0.x 版本只是生成静态字幕文件，用原生的渲染器绘制，而 v1.x 自己实现渲染器，好处是能支持其它网站，也方便添加更多功能，那明显是 EJOY 扩展特别针对 YouTube 的字幕渲染器做了适配。

我看你的需求大概就是如此：

**1. 鼠标悬停在英语字幕上，才显示中文**

这个倒是可以用“用户样式”实现，

```
.dualsub-renderer .legend-1 {
    visibility: hidden;
}
.dualsub-renderer:hover .legend-1 {
    visibility: visible;
}
```

或者模糊效果

```
.dualsub-renderer .legend-1 {
    filter: blur(10px);
}
.dualsub-renderer:hover .legend-1 {
    filter: none;
}
```

**2. 悬停字幕暂时暂停字幕**

这需求暂时不好做，因为需要和播放器交互，目前还不支持，如果你在用油猴扩展的话， 可以凑合用以下代码：

```
(async () => {
    const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
    let video = null;
    let renderer = null;
    while (video === null || renderer === null) {
        await sleep(1000);
        video = document.querySelector('video');
        renderer = document.querySelector('.dualsub-renderer');
    }
    renderer.addEventListener('mouseenter', () => video.pause());
    renderer.addEventListener('mouseout', () => video.play());
})();
```

另外，按道理，用开发者模式装扩展，是不会自动更新的。Chrome 就是如此，总是强制更新扩展。

**Comment by muzuiget** [comment]
另外你也可以用 Dualsub 显示中文字幕，英文还是用原生字幕显示。
