### ISSUE TITLE
No tool bar icon in Firefox

### ISSUE THREAD

**Issue by mosaic-greg** [muzuiget/dualsub-support#116]
Hi I've installed the dualsub addon into firefox. No toolbar icon is showing when I play videos in Youtube or Netflix. I'm using version 68.4.2esr (64-bit), Windows. I've restarted Firefox. How can I make the toolbar icon appear?

**Comment by mosaic-greg** [comment]
No problem, I see Firefox support was dropped in v1.0.0

Release Date: 2020-05-08

**Comment by muzuiget** [comment]
Yes, Firefox version keep in v0.8.1, but the latest is v1.8.0.

**Comment by SJTUboy** [comment]
@muzuiget   I was wondering why stopping Firefox support?

**Comment by muzuiget** [comment]
I answer you on the other issue.
