### ISSUE TITLE
字幕位置的问题

### ISSUE THREAD

**Issue by SpoonerCake** [muzuiget/dualsub-support#117]
在播放视频时，如果想要快进或者切换到某个位置，字幕会遮住中间的进度条，导致进度条选中不了，每次都要把字幕拖到上面，而且无法再拖回去，之前好像会自动变换。
![QQ截图20200626124143](https://user-images.githubusercontent.com/49234232/85821092-6e3c7280-b7aa-11ea-8052-c01612e97e17.png)
![QQ截图20200626124128](https://user-images.githubusercontent.com/49234232/85821095-6e3c7280-b7aa-11ea-89e8-81d4838e42d7.png)

**Comment by muzuiget** [comment]
你怎么拖到最底下？本来就限制了最底边缘的。

如果你想像原生字幕那样自动移动，可以用“用户样式”，使用以下代码：

````
.ytp-autohide .dualsub-renderer {
    margin-bottom: -32px;
}
```

**Comment by SpoonerCake** [comment]
感谢~完美解决

**Comment by lemako** [comment]
我则是字幕的位置太高了，请问有没有什么办法能低一点，已经试过重置默认设置依旧很高，是不是因为我电脑默认缩放问题？
![1](https://user-images.githubusercontent.com/38862056/95656312-2581ad00-0b40-11eb-8f2a-028eb3342607.png)
![2](https://user-images.githubusercontent.com/38862056/95656315-2a466100-0b40-11eb-9c29-19dd294e19f0.png)

**Comment by muzuiget** [comment]
> 我试了一下，原来可以自己用鼠标拖动字幕，但是全屏的时候字幕高度正常，非全屏的时候就显得略高了一点，这是因为限制了最低高度吗？

错觉而已，底部距离是固定值，全屏的时候，YouTube 下方进度条高度会变大，画面变大也让你觉得字体变小。你可以把“设置”里“通用”，“底部边距”改成 0。如果你会 CSS，可以写个样式插件自己定位，例如：

```
.dualsub-renderer {
    bottom: 8px !important;
}
```
如果中日双语，显示片假名时，我习惯会把日语放在上方，避免片假名撑大了两行间的距离。

> 这三个文章看不到，是还没写好吗？

太懒了，啊哈哈，因为我估计没什么人用。不过其实不难理解的，例如默认的“日语学习”主题，“隐藏下划线”，勾选的是“条件样式”而不是“组件样式”的那个，你可以自己揣摩一下区别。
