### ISSUE TITLE
打开新的视频时，自动启用上次设置的字幕

### ISSUE THREAD

**Issue by skyrimplayerr** [muzuiget/dualsub-support#119]
现在的版本中，在打开新的视频时，要重新设置字幕的语言和主题样式，希望下个版本中能够默认的启用上次设置的语言和样式

**Comment by muzuiget** [comment]
难道现在不是吗？

**Comment by skyrimplayerr** [comment]
打开部分视频的时候，默认设置会被清空

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: muzuiget<mailto:notifications@github.com>
发送时间: 2020年6月28日 10:27
收件人: muzuiget/dualsub-support<mailto:dualsub-support@noreply.github.com>
抄送: skyrimplayerr<mailto:panpiandongpch@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [muzuiget/dualsub-support] 打开新的视频时，自动启用上次设置的字幕 (#119)


难道现在不是吗？

―

**Comment by muzuiget** [comment]
自动选择是一个逻辑复杂的，先看一下文档 [使用自动选择](https://dualsub.netlify.app/zh-cn/appendix?id=%e4%bd%bf%e7%94%a8%e8%87%aa%e5%8a%a8%e9%80%89%e6%8b%a9)。

自动关闭就是新打开视频没有之前视频相同的语言。

自动选择是一个比较复杂的问题，每个人都有不同偏好，所以只能用代码来设置，你看看那个文档能不能满足。
