### ISSUE TITLE
为什么我的选项全是关闭？

### ISSUE THREAD

**Issue by yff0216** [muzuiget/dualsub-support#120]
为什么我的选项全是关闭？

**Comment by yff0216** [comment]
全部都是关闭（0）

**Comment by muzuiget** [comment]
该视频没有字幕。

**Comment by yff0216** [comment]
> 该视频没有字幕。
不会吧，因为我手动去点齿轮自动翻译，是有字幕的

**Comment by muzuiget** [comment]
发个视频地址看看。

**Comment by yff0216** [comment]
> 发个视频地址看看。

https://www.youtube.com/watch?v=mTnXCWzFi5w
怎么能贴图上来呢？

**Comment by yff0216** [comment]
> 发个视频地址看看。


https://wwe.lanzous.com/i2CXPe856ra
麻烦你下载了看看，我拍了一个视频

**Comment by muzuiget** [comment]
你的视频我试了一下，没有问题。

你这是所有 YouTube 视频都是这样，还是个别视频有问题？切换视频后，手动一次刷新呢？

**Comment by yff0216** [comment]
> 你的视频我试了一下，没有问题。
> 
> 你这是所有 YouTube 视频都是这样，还是个别视频有问题？切换视频后，手动一次刷新呢？

所有的都是这样，怎么刷新都还是这样？会是哪里的问题呢

**Comment by muzuiget** [comment]
升级到最新 Chrome 吗？

**Comment by scutxd** [comment]
建议你提供一下浏览器的版本号，这样作者好定位。不过看你的现象可能和我一样，也是因为使用了老的浏览器版本的原因。
已经通过作者给我的回复，采用老版本的方法搞定了。建议你也可以试试。

**Comment by yff0216** [comment]
> 建议你提供一下浏览器的版本号，这样作者好定位。不过看你的现象可能和我一样，也是因为使用了老的浏览器版本的原因。
> 已经通过作者给我的回复，采用老版本的方法搞定了。建议你也可以试试。

版本 83.0.4103.116（正式版本） （64 位）

**Comment by scutxd** [comment]
你可以参考我提的那个issue试试。

**Comment by muzuiget** [comment]
按 F12 调处开发者控制台，截图看看有什么错误输出。
