### ISSUE TITLE
在Cent Browser 版本 3.5.3.50不正常使用

### ISSUE THREAD

**Issue by scutxd** [muzuiget/dualsub-support#121]
版本
Cent Browser 版本 3.5.3.50（正式版本） （64 位） (portable) (Chromium 67.0.3396.99)
Dualsub 1.8.0

在此版本无法正常显示，但是在0.6.5版本时是正常的，能否开放老版本的下载？

**Comment by muzuiget** [comment]
我没有保留 v0.6.5 版本的 zip，或者你可以用 Firefox 的 xpi 文件 https://addons.mozilla.org/en-US/firefox/addon/dualsub/。

**Comment by scutxd** [comment]
抱歉，您是说cent browser可以使用firefox的扩展？

**Comment by scutxd** [comment]
![image](https://user-images.githubusercontent.com/28666253/86877204-ef83f580-c118-11ea-88b7-b5950bb577aa.png)
查看网页，应该是没有正常获取到字幕信息。如截图中所述，显示的字幕为0。

**Comment by muzuiget** [comment]
我意思是 Firefox 商店可以下载历史版本 https://addons.mozilla.org/en-US/firefox/addon/dualsub/versions/ 把 xpi 改会 zip 就能用 Chrome 开发者模式安装。

不打算开源，我感觉就是 Chromium 67 内核太旧，部分 JS 特性不支持，如果你会 JS，看下开发者控制台有没有错误输出。

**Comment by scutxd** [comment]
非常感谢，已经通过你说的方法能用了。
