### ISSUE TITLE
希望也能支持Firefox, 谢谢！

### ISSUE THREAD

**Issue by SJTUboy** [muzuiget/dualsub-support#122]
![image](https://user-images.githubusercontent.com/13373715/86794890-94fa8300-c09f-11ea-944f-b8528929c3d1.png)

**Comment by muzuiget** [comment]
截至在 v0.8.1 版本里，Chrome 活跃用户接近 4 万，而 Firefox 版只有 1 千，为了支持 Firefox 用户，成本有点大。

Firefox 和 Chrome 的渲染效果有细微差别，比如表单输入控件，Chrome 在各个操作系统都是一致的，而 Firefox 在每个系统都不同(用系统原生样式)，需要花额外精力兼容。不追求完美的话，这个问题可以勉强解决。

最大问题是，Firefox 商店要求提供扩展源代码，要给审核人员审查(但是可以不公开)，源代码还要求写文章指导如何构建，审核人员可能会跑一次对比是否和提交的 zip 文件一致。这就蛋疼了，都 2020 了，不是源代码都在一个文件夹，打包就完事，而是各种构建脚本，私有 npm 仓库。

在 v0.8.1 版本我都是专门写个脚本来生成这种能审核的源代码，真是太麻烦了。新版本更复杂的模块划分，专门生成这种源代码更麻烦，再也不想做，想想看 Firefox 版才 1 千个用户，不值得。

**Comment by scutxd** [comment]
没有使用过firefox，firefox提供[从 Google Chrome 移植](https://developer.mozilla.org/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Porting_from_Google_Chrome)这个教程，我觉得你可以试试。

**Comment by muzuiget** [comment]
不单纯是 WebExtension API 移植，其它 HTML 特性也略有不用。

**Comment by SJTUboy** [comment]
感谢muzuiget解惑！
