### ISSUE TITLE
add funimtaion

### ISSUE THREAD

**Issue by 01MrHacKeR01** [muzuiget/dualsub-support#126]
i really appreciate what u do u only one who do it for free
i just wanted to recommend and hope u add funitmation
it is a  popullar free anime service and good luck 
I really didnt find a place else to write this or an email

**Comment by muzuiget** [comment]
Hi, I can try to add support it. But can you provide a test video which has Englisht/Japanese subtitle.

I just found one only has English subtitle https://www.funimation.com/shows/no-guns-life/renegade-extended/

**Comment by 01MrHacKeR01** [comment]
look i have search a lot and all what i see is only english sub 
and i have searched why is that and found that : https://www.funimation.com/forum/topic/15058/funimation-can-t-watch-japanese-animes-in-their-original-language
but i heard old shows had japanese subtitle but i didnt found it so i asked on funimation reddit 
and most of shows has only english subtitle so i think japanese is not important 
when i find a show have japanese subtitle i will tell u and thx for responsing

**Comment by 01MrHacKeR01** [comment]
> Hi, I can try to add support it. But can you provide a test video which has Englisht/Japanese subtitle.
> 
> I just found one only has English subtitle https://www.funimation.com/shows/no-guns-life/renegade-extended/

"There aren't any funimation (or Crunchyroll) shows which have hiragani/katakana subtitles. Japanese production committees do not license those rights to them. You might find some shows having romaji subs every other episode for the opening/ending theme songs, but not for the main show itself."

**Comment by muzuiget** [comment]
Implemented in v1.10.0.

Please note that this playlist-type url is not supported:

```
https://www.funimation.com/shows/attack-on-titan/to-you-in-2000-years-the-fall-of-shiganshina-part-1/
```

Only supports the standalone player url: 

```
https://www.funimation.com/player/96837/
```

In the former url, there is a link `Open standalone player page for Dualsub` added to the video description, help switch to the later url.

Because the former url doesn't includes the video id, it is hard to track the video has changed eg, playing next episode video.

**Comment by muzuiget** [comment]
The url `https://www.funimation.com/shows/` is supported in v1.11.0

**Comment by 01MrHacKeR01** [comment]
> The url `https://www.funimation.com/shows/` is supported in v1.11.0
thank u very much 
I appreciate what u do and thanks for fast reponse 
and doing it for free 
thx very much really
