### ISSUE TITLE
add crunchyroll :]

### ISSUE THREAD

**Issue by 01MrHacKeR01** [muzuiget/dualsub-support#127]
crunchyroll is another free streaming service for anime but more bigger than funimation
the reason that i mentioned funimation first that u use vpn to unblock content which doesnt have ur language
but crunchyrol many vpns dont work with him but still have more bigger large library and have many subtitles to translate not only english
so good luck and i hope u add him i am sorry if i am anoying u 
Crunchyroll : https://www.crunchyroll.com

**Comment by muzuiget** [comment]
Implemented in v1.11.0

**Comment by 01MrHacKeR01** [comment]
> Implemented in v1.11.0

thank u very much
I appreciate what u do and thanks for fast reponse
and doing it for free
thx very much really
Good Luck
