### ISSUE TITLE
Two different languages ​​overlap in the arrangement

### ISSUE THREAD

**Issue by 01MrHacKeR01** [muzuiget/dualsub-support#129]
okay there is a problem it is not big but i hope u fix it
this happened when something english is a Name or term so it didnt translate (that is normal i perfer that)
but the problem here my language which is arabic are from right to left
and English is left to right so the Order of words is change like it is in photo
i think it fixed by UTF-8 font format  i am not sure really
as i think it is not a big problem but for more better experience and comfort
and i think this problem is not only in arabic and english 
it happens when two languages one right to left and another left to right Overlap
![Opera Snapshot_2020-07-23_105550_www netflix com](https://user-images.githubusercontent.com/68344950/88269562-8ed9e880-ccd4-11ea-98ba-0c03e01fc4bf.png)

**Comment by muzuiget** [comment]
The red one is human translation and the green one is machine translation?

**Comment by 01MrHacKeR01** [comment]
> The red one is human translation and the green one is machine translation?

the blue one is human translate (the right translate order)
and the green one is  machince translation (wrong order)

**Comment by muzuiget** [comment]
The machine translation should the same as you get from https://translate.google.com/ If Google return the text is left-to-right, we need to revert it in the layout.

Some tips:

Try add `ar` to the "Language Style" option, check if your browser revert it for you, [document](https://dualsub.netlify.app/en-us/appendix?id=using-language-style).

If not, then add a [plugin](https://dualsub.netlify.app/en-us/plugin) with type `Style`, with code:

```
.dualsub-renderer .subtitle[lang="ar"] .content {
    unicode-bidi: bidi-override;
}
```

**Comment by 01MrHacKeR01** [comment]
> The machine translation should the same as you get from https://translate.google.com/ If Google return the text is left-to-right, we need to revert it in the layout.
> 
> Some tips:
> 
> Try add `ar` to the "Language Style" option, check if your browser revert it for you, [document](https://dualsub.netlify.app/en-us/appendix?id=using-language-style).
> 
> If not, then add a [plugin](https://dualsub.netlify.app/en-us/plugin) with type `Style`, with code:
> 
> ```
> .dualsub-renderer .subtitle[lang="ar"] .content {
>     unicode-bidi: bidi-override;
> }
> ```

i dont think it is google translate issue i write it their and it was right 
i dont think i understand what u said as solve
there are en-us
what should i right ar-??

**Comment by muzuiget** [comment]
Please read the document link.

**Comment by 01MrHacKeR01** [comment]
> Please read the document link.

i read it but i found box in dualsub option 
what should i write on it
and where should i type code

**Comment by muzuiget** [comment]
**Step 1:**

Add `ar` to the "Language Style" option

![Screenshot_20200729_182519](https://user-images.githubusercontent.com/330812/88789249-18a01f00-d1c9-11ea-8082-b0bb58c340bb.png)

**Step 2:**

Create a Style Plugin, name `Style for Arabic`

![Screenshot_20200729_182619](https://user-images.githubusercontent.com/330812/88789309-2e154900-d1c9-11ea-92b2-5008c02554bd.png)

**Step 3:**

Enable the cteated plugin on All websites:

![Screenshot_20200729_182627](https://user-images.githubusercontent.com/330812/88789340-3a010b00-d1c9-11ea-96e0-6383a85547bc.png)

**Comment by muzuiget** [comment]
To create a plugin, switch to "Manage" tab and click the plus `+` icon button.

**Comment by muzuiget** [comment]
Can you paste the original English subtitle text which translated with machine(the green one)?

**Comment by 01MrHacKeR01** [comment]
> Can you paste the original English subtitle text which translated with machine(the green one)?

okay i did it and it become worser 
the letters become left to right not words 
it is like dualsub become "buslaud"
so no 
and green one
"لقد كان Tohsaka يفعل كل شيء لفترة طويلة"
in github this problem exist and many text inputer

**Comment by 01MrHacKeR01** [comment]
> Can you paste the original English subtitle text which translated with machine(the green one)?

i mean when i am writing 1-MrHacKeR أسمي هو 
i should write first MrHacKeR 
second اسمي
third هو
but the right i should right
first اسمي
second هو 
third MrHackeR
but if i write that
i will get "اسمي هو mrhacker"
my language is right to left

**Comment by muzuiget** [comment]
Does this correct?

![Screenshot_20200730_005007](https://user-images.githubusercontent.com/330812/88829035-a5b19b00-d1fe-11ea-8cc6-4468b7c1fd9e.png)

**Comment by muzuiget** [comment]
> > Can you paste the original English subtitle text which translated with machine(the green one)?
> 
> i mean when i am writing 1-MrHacKeR أسمي هو
> i should write first MrHacKeR
> second اسمي
> third هو
> but the right i should right
> first اسمي
> second هو
> third MrHackeR
> but if i write that
> i will get "اسمي هو mrhacker"
> my language is right to left

More confuse, please use former English, use `correct` for `not wrong`, the word `right` make me confuse.

**Comment by muzuiget** [comment]
Maybe you should attach a image, I am not sure I will see the same render result in my browser.

**Comment by 01MrHacKeR01** [comment]
> Does this correct?
> 
> ![Screenshot_20200730_005007](https://user-images.githubusercontent.com/330812/88829035-a5b19b00-d1fe-11ea-8cc6-4468b7c1fd9e.png)

yes it is correct
the main problem is when an english term not translates or name of persons like "john"
it doesnt translate because it is term but in fact google translate cant translate name like john or some terms
so the problem happenes when there is an english word in arabic scentence
and when i do ar in language style
it become reverse letters of word it make "أرز" to "زرأ"
like "word" to drow"

**Comment by 01MrHacKeR01** [comment]
> Maybe you should attach a image, I am not sure I will see the same render result in my browser.

i edited it now
explain to me more what u want to know

**Comment by muzuiget** [comment]
Why not provides a Google Translate screenshot?

**Comment by 01MrHacKeR01** [comment]
> Why not provides a Google Translate screenshot?

what do u want me to write there ?

**Comment by 01MrHacKeR01** [comment]
> Why not provides a Google Translate screenshot?

it work fine in google translate

**Comment by 01MrHacKeR01** [comment]
> Why not provides a Google Translate screenshot?

it really works read this
:
I want to write with wordpress:

H2O is water.

Instead, he appears:

H2O is water.  

And I notice in the second case that the end of the line is the first and the first line is the end and i get dizzy what is the reason?

In fact, it's not wordwork, it's just a misunderstanding of the following point:

If the direction of writing from left to right, the beginning of the line is the far left and the end of the far right and we use this direction when writing English text as the following sentence:

Here's the end of the line.

Bilal Barakat passed here

Here's the beginning of the line.

If the direction of writing from right to left, the beginning of the line is the story of the right and the end of the far left and we use it when writing in Arabic as a sentence:

Here's the beginning of the line.

Our group....is infinitely distinguished.

Here's the end of the line.

Mistakes occur when you type from left to right in Arabic

Or from right to left in English.

The mistake you mentioned in your question is that the sentence shows:

H2O is water.

Instead of:

H2O is water.

Is because you write in Arabic but in a left-to-right writing direction.

So:

If you want to write Arabic text (in general) because it can be entered by English words or symbols, choose the direction of writing from right to left by pressing both right-wing Ctrl+Shift keys.

If you want to write english text (in general) because it can be entered by Arabic words or symbols, choose the direction of writing from left to right by pressing both left-handed Ctrl+Shift keys.

So ctrl+SHIFT's function is to determine the direction of writing rather than switching languages, it is not a substitute for ALT+SHIFT as some think, but rather to determine the direction of writing....

By the way you can see the direction of writing from the shape of the field marshal if it is in the form of a column the direction of writing from left to right and if it is a column with a police from above to the left the direction of writing from right to left

Also by the way you can switch between directions in the wordword using the button in the home tab near the shading bucket and its shape looks like ¶ with an arrow next to it to indicate the direction ....

**Comment by muzuiget** [comment]
Find an English source text, translate it to Arabic in https://translate.google.com/. The translated text should English/Arabric mixed. Then post the screenshot of https://translate.google.com/ here.

**Comment by muzuiget** [comment]
That is use screenshots to tell me what the source string and the translated string are. You paste them with text-format, what they look on my browser not always the same as yours.

**Comment by 01MrHacKeR01** [comment]
![git](https://user-images.githubusercontent.com/68344950/90986328-5868e500-e582-11ea-98b3-4a459491cbb1.png)

**Comment by 01MrHacKeR01** [comment]
google translate doing it right form
But dualsub makes it in wrong form
![git2](https://user-images.githubusercontent.com/68344950/90986406-e8a72a00-e582-11ea-9aaa-2327a3b55776.png)

**Comment by 01MrHacKeR01** [comment]
> That is use screenshots to tell me what the source string and the translated string are. You paste them with text-format, what they look on my browser not always the same as yours.

answer me bro

**Comment by muzuiget** [comment]
All right, here is the solution:

Step 1: 

Add `ar` to the "Language Style" option.

Step 2:

Create a new plugin, type "Style", with this code:

```
.dualsub-renderer .subtitle[lang="ar"] .content {
    direction: rtl;
}
```

Result:

![Screenshot_20200906_161726](https://user-images.githubusercontent.com/330812/92321435-83f8ce80-f05c-11ea-9d5c-ae6f3eceaa7e.png)

**Comment by 01MrHacKeR01** [comment]
> All right, here is the solution:
> 
> Step 1:
> 
> Add `ar` to the "Language Style" option.
> 
> Step 2:
> 
> Create a new plugin, type "Style", with this code:
> 
> ```
> .dualsub-renderer .subtitle[lang="ar"] .content {
>     direction: rtl;
> }
> ```
> 
> Result:
> 
> ![Screenshot_20200906_161726](https://user-images.githubusercontent.com/330812/92321435-83f8ce80-f05c-11ea-9d5c-ae6f3eceaa7e.png)

thx it is really work i tested it so many times and on numbers too
so should i close this or leave it for people who dont know how to do it
and i hope u find a way to make people notice how to do that

**Comment by muzuiget** [comment]
Maybe someone write a tutorial about this on Arabric.
