### ISSUE TITLE
SUGGESTION: Adding support for ARD and ZDF websites

### ISSUE THREAD

**Issue by DanijelC** [muzuiget/dualsub-support#131]
Hi,
I appriciate you work, this extension is very useful for learning new language.

It would be nice if you could add support for two popular german video websites:
https://www.ardmediathek.de
https://www.zdf.de

**Comment by muzuiget** [comment]
It looks like they only have German language?

**Comment by DanijelC** [comment]
Yes , they have only German content. 
For learning German would help a lot.
Would it be a problem to implement it?

**Comment by muzuiget** [comment]
Implemented in v1.12.0

**Comment by DanijelC** [comment]
Tnx :)

**Comment by muzuiget** [comment]
Upload the Chrome store, waiting for review.

Or you can install it with developer mode:

https://dualsub-static.netlify.app/files/dualsub-latest.zip

**Comment by DanijelC** [comment]
It works perfectly.
Tnx a lot.
