### ISSUE TITLE
自动换行， 新增快捷键

### ISSUE THREAD

**Issue by soytom** [muzuiget/dualsub-support#133]
1， 希望支持自动换行。目前，每种语言只有一行字幕，字体稍微大一些，50px以上，就很容易超出播放器界限。
![image](https://user-images.githubusercontent.com/69085097/89106146-0983d000-d45a-11ea-8963-ae666924f650.png)

2， 鼠标动作可以做成快捷键，一键切换 文本选择/位置移动。 这两种功能都是需要的，每次要到设置界面来回切换很不方便。

3， 新增快捷键，跳到上一行字幕，跳到下一行字幕，无限/2次/3次重复当前字幕。不知道是否能实现。Potplayer播放视频可以实现这些功能，不过那是离线视频。
![Annotation 2020-08-02 004301](https://user-images.githubusercontent.com/69085097/89106118-d3465080-d459-11ea-87f8-bd15e7e9b5c7.jpg)

**Comment by muzuiget** [comment]
问题 1：见 #124 

问题 2：即使切换到“文本选择”，按住 Alt 键还是可以移动位置。

问题 3：打算以后加上字幕对白浏览功能才做。

**Comment by muzuiget** [comment]
自动换行已在 v1.13.0 实现。

**Comment by soytom** [comment]
> 自动换行已在 v1.13.0 实现。
字幕偶尔会出现偏移背影，产生3D字体效果，影响阅读。

![image](https://user-images.githubusercontent.com/69085097/89731032-7d376580-da76-11ea-8ba2-a6df16957406.png)

![image](https://user-images.githubusercontent.com/69085097/89731067-c25b9780-da76-11ea-9dae-fba5a421c369.png)

**Comment by soytom** [comment]
> > 自动换行已在 v1.13.0 实现。
> > 字幕偶尔会出现偏移背影，产生3D字体效果，影响阅读。
> 
> ![image](https://user-images.githubusercontent.com/69085097/89731032-7d376580-da76-11ea-8ba2-a6df16957406.png)
> 
> ![image](https://user-images.githubusercontent.com/69085097/89731067-c25b9780-da76-11ea-9dae-fba5a421c369.png)

实践证明 是因为描边功能失效导致的 关闭描边功能即可

**Comment by muzuiget** [comment]
是的，那个错位就是描边造成的，这个问题暂时很难解决，因为 Chrome 描边实现有 [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=815111)。

Dualsub 用了一种曲线方法重新实现描边，也就是在对文本描绘两层，底层的字重稍微大一点，颜色为描边色。出现这种情况就是以为自动换行之后，第二行两层的坐标不对齐，造成原因不明。

两个临时解决方法：

1. 去掉描边，“通用” -> “基础样式”  切换为“无”，然后使用其它边缘效果。

2.  添加一个样式插件，取消外边缘，代码

```
.dualsub-renderer {
    padding: 0;
}
```

副作用就是字幕会紧贴视频边缘。

**Comment by muzuiget** [comment]
换行描边问题已在 v1.15.0 解决，直接更新即可，不需要上述任何临时绕过方法。
