### ISSUE TITLE
登录账号后的YouTube无字幕，退出登录后又会显示

### ISSUE THREAD

**Issue by 1809693385** [muzuiget/dualsub-support#136]
![2](https://user-images.githubusercontent.com/20138649/89732758-8aa71c80-da83-11ea-9efa-b37546a9fcf7.png)
https://www.youtube.com/watch?v=zqhfd79fbFs
账号退出登录后字幕又有了
![3](https://user-images.githubusercontent.com/20138649/89732841-f6898500-da83-11ea-9fe9-f451d6ff8902.png)

**Comment by muzuiget** [comment]
我无法重现，只可能个别情况出现，在安装或者更新扩展后需要对已打开的页面做一次全刷新。

如果你总是 100% 在未登录时出现这个问题，这倒是算是 bug。

**Comment by CraKeyBoy** [comment]
可以给 google 提问题反馈，我之前也遇到过，后来提了反馈就没问题了。

**Comment by muzuiget** [comment]
这个问题是 100% 出现的吗？还是偶然出现？出现几率是否高？

**Comment by CraKeyBoy** [comment]
应该不是插件的问题,我在其他浏览器看也是没有字幕，包括手机的浏览器，应该是google做了什么限制。和账号有关系。

**Comment by frank6996** [comment]
确实是和账号有关。我大概一个多月前开始用 Dualsub，使用大号看 YouTube 正常用了一段时间，然后某天 Dualsub 就怎么也加载不出来字幕了，之后到现在就一直加载不出来，期间尝试过重新安装插件和浏览器也没用。昨天试了一下，切小号看 YouTube 的话，Dualsub 就能显示字幕，再一切回大号就显示不出字幕了，Chrome 和 Edge 都是这种情况。

**Comment by muzuiget** [comment]
Dualsub 加载不出来字幕菜单时，YouTube 原生字幕菜单是正常的吗？如果是这样，怀疑 YouTube 在改版，只有部分账号能看到新版本。

**Comment by frank6996** [comment]
> Dualsub 加载不出来字幕菜单时，YouTube 原生字幕菜单是正常的吗？如果是这样，怀疑 YouTube 在改版，只有部分账号能看到新版本。

原生字幕菜单正常，字幕也都可以显示。就是插件加载不出字幕。

**Comment by muzuiget** [comment]
现在还反复出现这个问题吗？

**Comment by frank6996** [comment]
> 现在还反复出现这个问题吗？

还是有那个问题, 我提交了问题反馈也没有用. 甚至在 YouTube 帮助论坛发布了相关问题(https://support.google.com/youtube/thread/67600518?hl=zh-Hans), 目前仍然没有得到解决.

**Comment by muzuiget** [comment]
打开一个视频后，不刷新页面，再继续播放下一个带字幕的视频，是否能抓取到列表？

**Comment by muzuiget** [comment]
或者你试下用 v0.8.1 版本 https://addons.mozilla.org/en-US/firefox/addon/dualsub/versions/ 下载后用 Chrome 开发者模式加载，看看旧版本能否抓取到字幕列表。

如果能，那我可以在新版本加上旧版本那个抓取方法。

**Comment by frank6996** [comment]
> 打开一个视频后，不刷新页面，再继续播放下一个带字幕的视频，是否能抓取到列表？

播放下一个带字幕的视频也没有刷出来字幕列表.

**Comment by frank6996** [comment]
> 或者你试下用 v0.8.1 版本 https://addons.mozilla.org/en-US/firefox/addon/dualsub/versions/ 下载后用 Chrome 开发者模式加载，看看旧版本能否抓取到字幕列表。
> 
> 如果能，那我可以在新版本加上旧版本那个抓取方法。

是用火狐浏览器下载了之后把 xpi 后缀的文件解压, 然后用 chrome 浏览器的开发者模式加载已解压的扩展程序吗? 我这样安装后插件没法正常使用, 视频下方显示的是"需要刷新页面获取字幕信息", 刷新也没有用, 插件图标右键后选项也是灰色的.

**Comment by muzuiget** [comment]
对，是那样加载。出现“需要刷新页面获取字幕信息”，说明 YouTube 对你的账号应用了新的改版代码，这就麻烦了，如果我重现不了，就无法做兼容。

**Comment by 1809693385** [comment]
最新版本1.15.2解决YouTube无字幕问题了，请问这个都是强制的自动更新吗？有没有方法禁止新版本自动更新的呢？

**Comment by randyysr** [comment]
我的账号今天也突然出现这个问题了，退出账号或者换小号就能正常使用……我的Dualsub版本为1.15.2……这该怎么办好？

**Comment by randyysr** [comment]
我发现不能正常使用Dualsub的网页按F12看到的错误有18条。
![image](https://user-images.githubusercontent.com/47297779/96010537-78c36a80-0e74-11eb-88f2-609a2df210e7.png)
而退出账号，正常使用的Dualsub的网页错误只有1条。
![image](https://user-images.githubusercontent.com/47297779/96010619-9690cf80-0e74-11eb-9e31-6e5aecd51013.png)

**Comment by randyysr** [comment]
> 最新版本1.15.2解决YouTube无字幕问题了，请问这个都是强制的自动更新吗？有没有方法禁止新版本自动更新的呢？

您的账号是突然自动恢复了吗？我反而是今天突然出现Dualsub不能用了……版本是1.15.2

**Comment by randyysr** [comment]
我的chrome版本是 86.0.4240.75（正式版本） （64 位）

> 我的账号今天也突然出现这个问题了，退出账号或者换小号就能正常使用……我的Dualsub版本为1.15.2……这该怎么办好？

**Comment by muzuiget** [comment]
我一直都没处理过这个问题，楼上两位情况互换，可能是 YouTube 在改动测试用户群了。

@1809693385 Chrome 总是强制自动更新扩展，甚至 Chrome 本身也是自己强制更新。除非你以[开发者模式安装](https://dualsub.netlify.app/zh-cn/install)。

**Comment by randyysr** [comment]
> 我一直都没处理过这个问题，楼上两位情况互换，可能是 YouTube 在改动测试用户群了。
> 
> @1809693385 Chrome 总是强制自动更新扩展，甚至 Chrome 本身也是自己强制更新。除非你以[开发者模式安装](https://dualsub.netlify.app/zh-cn/install)。

今天Dualsub恢复正常了，看来就是YouTube账号的问题，Dualsub不好用的时候，Adblock也一样不太好用……

**Comment by muzuiget** [comment]
这几天我的账号会出现个小问题，跳转到下一个视频时，字幕列表抓取失败。

可以的话，更新到最新的 `v1.18.0` 试试，测试一下：

1. 首屏视频是否成功？
2. 跳转到下一个视频是否成功？

注意，下一个视频是在同一个浏览器标签页打开，例如左键点击 YouTube 右方侧边栏的视频链接。

**Comment by randyysr** [comment]
> 这几天我的账号会出现个小问题，跳转到下一个视频时，字幕列表抓取失败。
> 
> 可以的话，更新到最新的 `v1.18.0` 试试，测试一下：
> 
> 1. 首屏视频是否成功？
> 2. 跳转到下一个视频是否成功？
> 
> 注意，下一个视频是在同一个浏览器标签页打开，例如左键点击 YouTube 右方侧边栏的视频链接。

其实这两天我的Dualsub又突然不好用了，是首屏不成功。我刚刚试了下，同一个浏览器标签页打开下一个视频，Dualsub就又成功了……

**Comment by muzuiget** [comment]
尝试给 Firefox 做兼容时突然能重现这个问题了，也就是首屏不行，跳转时行。

发布了 `v1.19.1` 版本。

**Comment by randyysr** [comment]
> 尝试给 Firefox 做兼容时突然能重现这个问题了，也就是首屏不行，跳转时行。
> 
> 发布了 `v1.19.1` 版本。

用了两天，感觉问题解决了，但由于这个问题在过去是无规律出现，时而好用时而不好用，因此还不确定在未来运行的稳定性如何~

**Comment by muzuiget** [comment]
我当这个问题已经解决了，如果再次出现另开帖讨论。

**Comment by JiuJingMianQiu** [comment]
我现在也遇到这个问题了，我是没有办法自动翻译了，只能显示自动英文字幕，点自动翻译不管哪种语言都不会显示字幕
