### ISSUE TITLE
mac跟windows两个系统打开dualsub会冲突，而且mac无法使用颜色字体之类的功能

### ISSUE THREAD

**Issue by intchris001** [muzuiget/dualsub-support#138]

**Comment by muzuiget** [comment]
和什么冲突？能截个图吗？

**Comment by intchris001** [comment]
我用windows 和mac 同时打开dualsub ，会导致字体和颜色无法显示 ，就算设置了颜色也没用 ，不知道是不是dualsub不兼容mac的原因 ，mac可以显示字幕却添加不了颜色 。并且同一个账号这两个设置却是通用的，导致只能黑白显示的mac 现在也只能黑白的字幕在windows上

**Comment by muzuiget** [comment]
应该是 Chrome 扩展配置同步问题，如果两边都登录了相同的 Chrome 账号，在 Windows 上修改的配置马上被同步到 Mac 上了，然后自动应用新配置。

更新到最新的 v1.14.0 就好了，从这个版本开始就不再使用同步配置储存了，更新后先打开一下扩展的选项页面，会自动迁移到本地配置储存。
