### ISSUE TITLE
bilibili的翻译不好用

### ISSUE THREAD

**Issue by bmh2550428640** [muzuiget/dualsub-support#142]
![QQ截图20200508130](https://user-images.githubusercontent.com/62734803/91185019-e0d0bc80-e71f-11ea-95f6-a5d993cbf756.png)
完全没有显示，youtube是可以的

**Comment by muzuiget** [comment]
要B站自己本身提供原文字幕才行啊 https://www.bilibili.com/read/cv1368832/

**Comment by muzuiget** [comment]
比如这种 https://www.bilibili.com/video/BV1kE411H7gm

状态栏本身有 “CC” 按钮出现。

**Comment by bmh2550428640** [comment]
> 比如这种 https://www.bilibili.com/video/BV1kE411H7gm
> 
> 状态栏本身有"CC"按钮出现。

哦哦，这样啊
