### ISSUE TITLE
请问程序员大佬，YOUTUBE的字母自动选择功能有没有优先级的功能。

### ISSUE THREAD

**Issue by yaoniming-158** [muzuiget/dualsub-support#145]
比如一个片子，本身有外挂英语字母，但是如果是自动选择功能每次选择的字幕都是“en.asr”。有没有办法优先“en”，没有“en“才去选择”en-asr“
我的设置：
[en][1]
[zh][en][1]
[zh-hans, zh][2]
[en][zh-hans][2]
尝试改成这样好像也不行，
[en, en-us, en-gb, en.cc][1]
[en.asr][1]
[zh][en][1]
[zh-hans, zh][2]
[en][zh-hans][2]

**Comment by muzuiget** [comment]
现在本来就是优先选择 ` en` 的，你的格式错了，末尾连续的 `[]` 才能忽略，应该是

```
[en][][][][1]
[zh][en][][][1]
[zh-hans, zh][][][][2]
[en][zh-hans][][][2]
```

**Comment by yaoniming-158** [comment]
> 现在本来就是优先选择 ` en` 的，你的格式错了，末尾连续的 `[]` 才能忽略，应该是
> 
> ```
> [en][][][][1]
> [zh][en][][][1]
> [zh-hans, zh][][][][2]
> [en][zh-hans][][][2]
> ```

谢谢！我做了如下修改好像有改善。我把en，从第一行拿掉了。
[en-us, en-gb, en.cc][1]
[en, en.asr][1]
[zh][en][1]
[zh-hans, zh][2]
[en][zh-hans][2]
