### ISSUE TITLE
如何单独更改每行字幕的字体？(已解决；原标题：建议加入两个好用的新功能)

### ISSUE THREAD

**Issue by BlinVin** [muzuiget/dualsub-support#147]
①自定义字幕字体，想用某俊黑体…orz
②自定义字幕位置：可以更加精细地调整字幕横向移动的位置
谢谢谢谢谢谢谢大佬

**Comment by muzuiget** [comment]
1. 可以使用插件功能，主要是浏览器不能枚举操作系统的字体，所以不能提供 GUI 下拉框选择。

新建一个“样式”类型的插件，代码如下：

```
.dualsub-renderer {
    font-family: "微软雅黑", sans-serif;
}
```

把 `微软雅黑` 换成你的字体名字，插件文档 https://dualsub.netlify.app/zh-cn/plugin

2. 不明白什么叫"横向移动的位置"，你是不想字幕居中显示？

**Comment by BlinVin** [comment]
谢谢大佬，我也觉得第二个要求有点多余了，主要是想使字幕能够摆放地更加自由，万分感谢

**Comment by muzuiget** [comment]
可以的。

```
.dualsub-renderer .subtitle-1 {
    font-family: "字体2", sans-serif;
}
.dualsub-renderer .subtitle-2 {
    font-family: "字体2", sans-serif;
}
```

**Comment by BlinVin** [comment]
爱你💖
