### ISSUE TITLE
It does not work with Chinese videos

### ISSUE THREAD

**Issue by clehea** [muzuiget/dualsub-support#148]
Dear Sirs,
I use DualSub on Youtube, and I can see it works very well with videos in English language.
However, it does not work with videos in Chinese language.
Please check and fix it.
Many thanks!

**Comment by BlinVin** [comment]
Please note that DualSub can be used only if the video has CC subtitle files in the subtitle option on the web page

**Comment by clehea** [comment]
Thank you for your reply!

Vào Th 5, 17 thg 9, 2020 vào lúc 10:31 BlinVin <notifications@github.com>
đã viết:

**Comment by muzuiget** [comment]
Dualsub can only loads the subtitles provided by YouTube itself, and YouTube auto-generated subtitle not supports Chinese.
