### ISSUE TITLE
关于dualsub问题想咨询下

### ISSUE THREAD

**Issue by LeeLiu9102** [muzuiget/dualsub-support#150]
Hi，您好
我们目前有一个项目寻求dualsub类似功能，看到dualsub后对其非常感兴趣，因为我不是编程背景，也有些地方想请教一下。
不知是否可以email我一个您的联系方式，我的email是lee@spacerim.com
如有打扰，望请见谅。

**Comment by muzuiget** [comment]
私信可以 muzuiget [AT] gmail.com
