### ISSUE TITLE
add amazon.com for us people

### ISSUE THREAD

**Issue by caonimazx1009** [muzuiget/dualsub-support#152]
Hi, 
Could you please add amazon.com in extension? Because all US location amazon prime can not watch movie in https://www.primevideo.com/ any more.

**Comment by muzuiget** [comment]
Can you provide a example video url?

Do "Prime Video" and "Amazon Video" are difference brand? Like "Hulu Japan" #144, if they have difference code-base, they should treat as difference website.

**Comment by caonimazx1009** [comment]
https://www.amazon.com/Name-Game/dp/B08761FKM2/ref=sr_1_1?dchild=1&keywords=the+boys&qid=1601870102&s=instant-video&sr=1-1

https://www.primevideo.com/detail/The-Boys/0KRGHGZCHKS920ZQGY5LBRF7MA

Like this. I think they are same brand. But all USA amazon prime member no longer use https://www.primevideo.com/.  But i am not sure about code-base thing. 

![image](https://user-images.githubusercontent.com/52088599/95039016-8cfdaf80-069d-11eb-9ec5-04c09d344f35.png)

**Comment by caonimazx1009** [comment]
sorry I just try again, looks like prime video works for me now. Thank you for your time!
