### ISSUE TITLE
最近几天netflix识别不出字幕

### ISSUE THREAD

**Issue by kingcraftliu** [muzuiget/dualsub-support#153]
字幕语言栏显示关闭（0），浏览为chrome最新 86.0，所用netflix插件有super netflix搭配netflix 1080p

**Comment by gnafrgb** [comment]
同上
在Netflix無法抓到字幕
用edge測試也是一樣

**Comment by muzuiget** [comment]
发布了 v1.15.2，修复了这个问题。

**Comment by kingcraftliu** [comment]
确认1.15.2解决了问题，谢谢

**Comment by gnafrgb** [comment]
1.15.2已解決
感謝
