### ISSUE TITLE
显示的平假名和日语有重叠看不清，并且字体大小似乎是跟随日语字体的

### ISSUE THREAD

**Issue by Stephen2252Ro** [muzuiget/dualsub-support#154]
![image](https://user-images.githubusercontent.com/64295584/96274913-a5f25300-1003-11eb-98cd-2954dbf18f7b.png)
如图，日语和汉语都好着，但是出现的平假名就是和日语重叠，完全挡住了。我就是想显示这三种字幕，平假名由于一般音频中不提供，所以只能使用主题等设置自动生成。就出现了上述问题。求救！

**Comment by muzuiget** [comment]
似乎是 Chrome 86 开始出现这种情况，已经找到解决方法，下个版本修复。

**Comment by Stephen2252Ro** [comment]
我的浏览器是edge，chrome没试过，希望尽快修复，辛苦了

**Comment by muzuiget** [comment]
新版 Edge 也是 Chromium 内核的，所以一样的问题。

**Comment by muzuiget** [comment]
已发布 v1.17.0，修复了这个问题。

不过 Edge 商店审核实在太慢，居然还在审核 v1.16.0 版。

**Comment by Stephen2252Ro** [comment]
太强了，那我下个chrome的插件，通用反正






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "muzuiget/dualsub-support"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月18日(星期天) 下午3:22
收件人:&nbsp;"muzuiget/dualsub-support"<dualsub-support@noreply.github.com&gt;;
抄送:&nbsp;"罗庆尧"<2252806415@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [muzuiget/dualsub-support] 显示的平假名和日语有重叠看不清，并且字体大小似乎是跟随日语字体的 (#154)





 
已发布 v1.17.0，修复了这个问题。
 
不过 Edge 商店审核实在太慢，居然还在审核 v1.16.0 版。

**Comment by Stephen2252Ro** [comment]
Chrome插件的最新版本大概什么时候上线

**Comment by muzuiget** [comment]
已经上传了，时间不定，有时候秒通过，有时候几小时，有时候要一天，而 Edge商店固定要两天。

如果你等不及，可以用开发者模式安装 zip 文件：https://dualsub.netlify.app/zh-cn/install

**Comment by Stephen2252Ro** [comment]
Great!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "muzuiget/dualsub-support"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月18日(星期天) 晚上9:48
收件人:&nbsp;"muzuiget/dualsub-support"<dualsub-support@noreply.github.com&gt;;
抄送:&nbsp;"罗庆尧"<2252806415@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [muzuiget/dualsub-support] 显示的平假名和日语有重叠看不清，并且字体大小似乎是跟随日语字体的 (#154)





 
已经上传了，时间不定，有时候秒通过，有时候几小时，有时候要一天，而 Edge商店固定要两天。
 
如果你等不及，可以用开发者模式安装 zip 文件：https://dualsub.netlify.app/zh-cn/install

**Comment by Stephen2252Ro** [comment]
![image](https://user-images.githubusercontent.com/64295584/96371342-d2d57000-1193-11eb-98b8-5b39535a35cd.png)
 像这种平假名和日语字体大小一致的话会不会能看起来舒服点。如果可以提供个自主设置平假名字体大小的选项就好了。

**Comment by muzuiget** [comment]
现在就可以，假设你用默认设置样式配置。

新建一个组件样式，名称 `大号平假名样式`，组件选择 `平假名`，字体大小设置为 `42` 像素。

![Screenshot_20201018_232317](https://user-images.githubusercontent.com/330812/96372382-1da5b680-1199-11eb-9c50-9178b2b155e0.png)

新建一个条件样式：名称 `字面全为假名样式`，组件样式勾选 `大号平假名样式`，条件激活“字面”，填写 `^[\u3040-\u309f\u30a0-\u30ff]+$`。

![Screenshot_20201018_232323](https://user-images.githubusercontent.com/330812/96372386-1f6f7a00-1199-11eb-807f-c18980362dd1.png)

切换回主题样式，在 `日语学习`，条件样式勾选 `字面全为假名样式`。

![Screenshot_20201018_232333](https://user-images.githubusercontent.com/330812/96372388-21d1d400-1199-11eb-95fa-08b15a1ead69.png)

在字幕菜单中选择 `日语学习`。

![Screenshot_20201018_232425](https://user-images.githubusercontent.com/330812/96372392-24ccc480-1199-11eb-9ba0-68b26784e59c.png)

“条件样式”就是把“组件样式”在仅符合某个条件时应用。

**Comment by muzuiget** [comment]
看真点你的需求，如果你仅仅想把注音部分都弄成正文一样的字体大小，那就定一个组件样式，组件选择”平假名“，然后设置字体大小就行了。

**Comment by muzuiget** [comment]
不过你这个需求很奇怪，要是我对平假名也注音的话，最好也是小字体，但是加空白，让其下方的正文假名一一对应好看点。

**Comment by muzuiget** [comment]
啊我傻了，在默认的组件样式 `显示平假名` 里字体大小就行了，不需要另外定义一个组件样式。

**Comment by Stephen2252Ro** [comment]
行吧，你图中的效果就挺好得了。如有其它需求再问你吧。太感谢

**Comment by muzuiget** [comment]
不过你处于什么原因也把假名正文显示平假名呢？一般我都用来显示罗马字的。

**Comment by Stephen2252Ro** [comment]
额 学习日语~ 知道读音，知道日语汉字，知道意思。有助于学习日语

**Comment by Stephen2252Ro** [comment]
就是为了学日语 买了个奈飞会员
