### ISSUE TITLE
Issues with furigana

### ISSUE THREAD

**Issue by dhilzyi** [muzuiget/dualsub-support#155]
hello, 
recently i got a problem with furigana character

as you can see they end up like in back kanji which is i cant read the hiragana,the first i use this extension is not problem
it happen to all videos and i dont know how to fix this
![image](https://user-images.githubusercontent.com/68381636/96444473-86903b80-1238-11eb-9984-65980dc96a77.png)

thanks

**Comment by muzuiget** [comment]
This already fixed in v1.17.0, the Chrome Store version is avaiable, and the Edge Store version still in review.

**Comment by dhilzyi** [comment]
ah im using microsoft edge right now,ok i'll wait thank you so much !
