### ISSUE TITLE
字幕不顯示 當選擇機器翻譯時

### ISSUE THREAD

**Issue by as921921** [muzuiget/dualsub-support#156]
"機器翻譯" 都不選擇時 會顯示 英文（自動產生） YOUTUBE 上也有顯示字幕
但是一旦選擇任何翻譯的語言時，字幕整個都消失了（包含英文字幕都不見了），
我是用CentBrowser

**Comment by muzuiget** [comment]
从 `v1.16.0` 开始，重写了翻译功能，原文数据会发送到 Dualsub 服务器翻译。

所以确保 https://dualsub.netlify.app/api 能够正常访问。

主要是我不想局限在 YouTube 自带的翻译，想做一些优化处理，现在扩展设置多了个“自动翻译”设置标签页，文档迟点会补上。

**Comment by as921921** [comment]
點擊打開 https://dualsub.netlify.app/api 只會顯示 {"code":0}
這是正常的嗎？  (我機器翻譯現在還是一樣，只要選擇任一翻譯字幕，字幕就都會直接消失）

**Comment by muzuiget** [comment]
这是，正常，说明网络通了。

浏览器版本和扩展版本各是什么，更新到最新版本再试。

**Comment by as921921** [comment]
Cent Browser 版本 4.2.10.171 (正式版本) (32 位元) (Chromium 80.0.3987.163)，Dualsub 1.18.0 
(我機器翻譯現在還是一樣，只要選擇任一翻譯字幕，字幕就都會直接消失）英文（自動翻譯的也會一起消失呢）

我用chrome 是正常的

**Comment by muzuiget** [comment]
内核太旧了，可能不支持特性。
