### ISSUE TITLE
Can not use Dualsub to youtube Firefox version 82.0 and others version, October 2020.

### ISSUE THREAD

**Issue by Lukchard-john** [muzuiget/dualsub-support#157]
![image](https://user-images.githubusercontent.com/72117095/96670945-41345100-1393-11eb-8fd3-2ddf90b6c8a8.png)

**Comment by muzuiget** [comment]
All right, I had upload a new version `v0.8.2` for Firefox.

Note: This version won't be listing on Dualsub homepage, because the `v0.x` version is deprecated.
