### ISSUE TITLE
youtube subtitles not working on firefox

### ISSUE THREAD

**Issue by appleplants** [muzuiget/dualsub-support#159]
I'm getting  "Require page reload to get subtitle data" on youtube videos, and the problem persists after reloading the page/redownloading dualsub/reopening firefox. However, dualsub works on incognito. I cleared all cookies for youtube but maybe it'll take some time to kick in? i was wondering if there was anything else i ought to do for dualsub to work off incognito?

**Comment by muzuiget** [comment]
See #157

**Comment by appleplants** [comment]
hi i'm sorry, i'm still running into the same problem. is there anything you recommend?

**Comment by muzuiget** [comment]
I test it on Firefox 82, please update to latest Firefox.
