### ISSUE TITLE
Not working in chrome browser after when change pc and after profile sync.

### ISSUE THREAD

**Issue by ozknozsrt** [muzuiget/dualsub-support#161]
I have been using the extension long time but I was change my pc and when I'm synced my profile the extension couldn't work anymore. If anyone solved this issue, please can reply to me. By the way I trying on Youtube.

As you can see in screenshot the extension couldn't get languages:
![image](https://i.hizliresim.com/Aztph7.png "Screenshot")

**Comment by ozknozsrt** [comment]
Oh, and another thing.. I opened a new guest account on chrome and I installed dualsub while on that guest account. And then looks like:
![image](https://i.hizliresim.com/si7OLj.png "Screenshot")

Why that happening?

**Comment by muzuiget** [comment]
This issue already report in #136 (with Chinese), and didn't resolve yet.

This because YouTube is doing [A/B testing
](https://en.wikipedia.org/wiki/A/B_testing), so some accounts are on new testing layout, but my account isn't on testing, so I can't debug it.

**Comment by ozknozsrt** [comment]
I got it. But actually now I see it working on some videos by chance. Even from my own synced account. That is so interesting.

**Comment by muzuiget** [comment]
Please update to latest version `v1.18.0`, and try again.

1. It is fine on initial video?
2. It is fine on next video.

The next video should open on the same browser tab, eg: left click the YouTube right sidebar video links.

**Comment by ozknozsrt** [comment]
Oh yeah, it's working! 🎉🎉
Thank you so much, you're amazing
