### ISSUE TITLE
机器翻译失效 不能访问dualsub.netlify.app/api

### ISSUE THREAD

**Issue by randyysr** [muzuiget/dualsub-support#163]
与问题#156 情况相同，一旦开启机器翻译，字幕就全没了，我用多台设备、不同网络测试https://dualsub.netlify.app/api 都不能访问。

**Comment by muzuiget** [comment]
服务器忘记续费了，现在重开了。

**Comment by randyysr** [comment]
> 服务器忘记续费了，现在重开了。

正常了，感谢，好人一生平安！
