### ISSUE TITLE
the solution to change user agent not working on amazon prime some of the times , any permanent solutions?

### ISSUE THREAD

**Issue by Vijayofficialhere** [muzuiget/dualsub-support#166]

**Comment by Vijayofficialhere** [comment]
Not working at primevideo.com sometimes

**Comment by muzuiget** [comment]
Please provide your OS and browser version, and the way how you change the UserAgent.

**Comment by Vijayofficialhere** [comment]
I am using windows and this version - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36 and I change the user agent via inspect element and in Network Conditions.

**Comment by muzuiget** [comment]
So, what is "not work" mean? Load the wrong subtitle file, or the subtitle is not sync?

**Comment by Vijayofficialhere** [comment]
Now it's getting ok like I used the previous solution but sometimes even that is not working where I need to refresh everything

**Comment by muzuiget** [comment]
Track on #151
