### ISSUE TITLE
b站视频 机器翻译失效

### ISSUE THREAD

**Issue by 2016011ak47** [muzuiget/dualsub-support#167]
这个是https://www.bilibili.com/video/BV1MC4y1t7U2?p=7&t=367 视频地址，我试了多个视频机器翻译都是无效，作者你可以试一下你这边是否有效

**Comment by muzuiget** [comment]
确保能访问 https://dualsub.netlify.app/api 正常应该返回 `{"code":0}`。

现在问题是 netlify.app 的服务器在中国访问经常抽风。

**Comment by 2016011ak47** [comment]
![image](https://user-images.githubusercontent.com/16641052/98512388-350c2700-22a1-11eb-853e-3f605e07c7c3.png)
测试一下可以访问

**Comment by 2016011ak47** [comment]
另外我用的google浏览器版本 86.0.4240.183（正式版本） （64 位）,作者用的也是一样版本吗？

**Comment by muzuiget** [comment]
和浏览器版本没关系，就死网络问题，只是没做超时错误处理而已。

当你访问通了就再重试一下咯。

**Comment by 2016011ak47** [comment]
![image](https://user-images.githubusercontent.com/16641052/98522009-2462ad80-22af-11eb-9021-d82d447312f9.png)
可以获取到字幕语言，
但是获取不到机器翻译
![image](https://user-images.githubusercontent.com/16641052/98522129-46f4c680-22af-11eb-9825-34a894bf197e.png)

**Comment by 2016011ak47** [comment]
我试过了用VPN，也无法获取机器翻译
![image](https://user-images.githubusercontent.com/16641052/98522582-d8643880-22af-11eb-8c55-f6ab20d99b14.png)

**Comment by 2016011ak47** [comment]
![image](https://user-images.githubusercontent.com/16641052/98522824-1cefd400-22b0-11eb-8460-bcd46af64da7.png)

**Comment by muzuiget** [comment]
所有 B 站视频都是？试下其它网站，例如网易云音乐 https://music.163.com/#/song?id=584155

**Comment by muzuiget** [comment]
在扩展设置里，翻译引擎切换回 Google，微软的现在好像还有点问题。

**Comment by muzuiget** [comment]
统一在 #171 跟进。
