### ISSUE TITLE
增强模式下的谷歌翻译，在视频的后半段失灵

### ISSUE THREAD

**Issue by DefetC** [muzuiget/dualsub-support#168]
比如此视频：https://www.youtube.com/watch?v=baYjrl7LYyY&list=PLlZto3smtTPvmQcbDVVO9HAsc0iuMTu2o&index=17

差不多1小时20分钟时，翻译失灵，本应显示中文，但是直接显示为英文原文：
![image](https://user-images.githubusercontent.com/20338520/98491505-287bd480-2289-11eb-8333-e128da8f2e8f.png)
![image](https://user-images.githubusercontent.com/20338520/98491519-3598c380-2289-11eb-9051-991d12dd0deb.png)

将翻译模式设为普通，则可以正常翻译：
![image](https://user-images.githubusercontent.com/20338520/98491581-7264ba80-2289-11eb-8978-a5d10c1f6e03.png)
![image](https://user-images.githubusercontent.com/20338520/98491593-7a245f00-2289-11eb-8266-4461ed838688.png)

这似乎不是个例，在别的视频我也遇到过。我猜测这是否是因为视频长度过长造成的？

**Comment by muzuiget** [comment]
和视频长度没关系，和文本数据量有关系。

Google 的翻译服务每次有最大长度限制，文本量太大只好一个个分批次请求，同一时间堆积太多等待翻译的文本，避免超时，只好把后续的文本跳过了，按原文返回。

普通模式也是一样的，只是你测试那个时间点刚好能够完全翻译完。扩展在本地是有翻译缓存的，相同的文本只翻译一次，所以你再选择增强模式，不会再向服务器翻译一次，而是重用上次的。

现在翻译系统还在重写中，暂时把所有数据都用 Dualsub 自己的服务器翻译。

顺便说说，你这个视频用增强模式没意义，那个人工字幕，看上去其实也是机器字幕转过来的，没有标点符号，全是小写，太多没意义的口语词，没办法完整分隔出一个完整的句子。

**Comment by muzuiget** [comment]
对于这个问题，有三个解决方案：

1. 对于普通模式，重用 YouTube 自己的翻译文本，这个功能迟点想办法加回去。
2. 分段请求，比如先翻译 5 分钟后的文本，一边播放一边翻译后续文本，当然这样在跳转都某个时间点时，翻译会有一点延迟。
3. 开通付费模式，给 VIP 用户插队的权利。

**Comment by DefetC** [comment]
确实普通模式也遇到了。

我觉得我一开始用的时候（大概一年前？）没有碰到过类似的问题，我之前看的一些视频文本量也很大。 是之前运气好文本量正好够用吗？

我现在是现在看到后面就直接切换youtube字幕自带的自动翻译。

vip的话，我是有心加入的。

最后感谢大佬，这个插件真的是帮大忙了！

**Comment by muzuiget** [comment]
不是，在 v1.17.0 才开始改动的 https://dualsub.netlify.app/zh-cn/changelog?id=v1170

就是这个版本开始引入“翻译模式“这个功能，之前的版本就是简单下载两个字幕文件(原文和译文)，然后按时间轴合并了事。

如果你有留意，YouTube 的翻译相当简单粗暴，就是原文一条对应译文一条，每条之间没有关系的，也就是没有上下文，当一个比较长的句子被断成两条字幕，翻译质量就变差了。机器识别字幕更是离谱，凑够 12 个左右单词就当一条来翻译，翻译质量更加惨不忍睹。

所以我希望自己搞套算法，对字幕原文做些预处理，提高翻译质量，不过这样就无法重用 YouTube 译文字幕了。

**Comment by muzuiget** [comment]
统一在 #171 跟进。
