### ISSUE TITLE
prime video上用不了

### ISSUE THREAD

**Issue by leoooodanno00** [muzuiget/dualsub-support#169]
Netflix、hulu、Disney+都可以用，图标是亮的，但用prime video时图标是灰色的，都按不了，我是在这个网站是看的https://www.amazon.com/gp/video/storefront/ref=topnav_storetab_atv?node=2858778011 试了好多部片，都没一个可以调出字幕

**Comment by leoooodanno00** [comment]
还有一个，就是Disney上的曼达洛人的字幕有点太快了，其他的都没问题，就这个一直调不准，字幕总比音频快好多

**Comment by muzuiget** [comment]
Prime Video 本来就没有在 `amazone.com/*` 上启用，有过类似的问题 #152，似乎切换回 `primevideo.com` 就行了。

Disney 所有视频都是这样，还是偶人某个视频是这样，官方自带的字幕有这个问题吗？

**Comment by leoooodanno00** [comment]
Disney的就那部剧这样，而且是第二季，第一季正常，我看国家地理和漫威的剧也都正常，我的设置都是默认的（之前改了，但调不好，又改回默认了）

**Comment by leoooodanno00** [comment]
剧名《the Mandalorian》，官方自带的字幕正常

**Comment by muzuiget** [comment]
Disney+ 这个小问题先不管了，又得重新花钱订阅。
