### ISSUE TITLE
油管看视频不用机器翻译能正常使用，但是用翻译就不显示字幕了，不管翻译成什么语言都是这样

### ISSUE THREAD

**Issue by orionGGG** [muzuiget/dualsub-support#170]

**Comment by muzuiget** [comment]
确保能访问 https://dualsub.netlify.app/api 正常应该返回 `{"code":0}`。

或者使用修改扩展设置：

1. 网站 -> YouTube -> 自动生成字幕模式，改成 `普通`。
2. 机器翻译 -> 翻译引擎，改成 `谷歌`。
3. 机器翻译 -> 翻译模式，改成 `普通`。

这样会使用 YouTube 自带的翻译译文。

**Comment by muzuiget** [comment]
统一在 #171 跟进。
