### ISSUE TITLE
最近的机器翻译改动说明帖

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#171]
从版本 `v1.17.0` 开始实现新的机器翻译功能，在此帖说明相关改动，如果有相关问题也可以在这里回复。

### 主要改动

在支持的多个视频网站中，只有 YouTube 原生提供机器翻译功能。

在  `v1.17.0` 之前，在 YouTube 和其它网站会使用不同的翻译方式，在 YouTube 会使用原生翻译，其余网站则通过 Dualsub 的服务器来翻译。

在 `v1.17.0` 之后，所有网站都使用统一的翻译方式，YouTube 也可以通过 Dualsub 的服务器来翻译，以提供不同的翻译结果。

迟一点会在官网写一篇比较详细的文章说明两者差异。

### 新加设置

新的翻译功能添加了几个设置，会影响翻译结果：

* 网站 -> YouTube -> 自动字幕模式
* 机器翻译 -> 基本 -> 翻译引擎
* 机器翻译 -> 基本 -> 翻译模式

具体说明见文档 https://dualsub.netlify.app/zh-cn/setting

现阶段主要是想测试相关功能，**在默认设置下，YouTube 也通过 Dualsub 的服务器来翻译。**

### 常见问题

> 请使用最新的版本测试，以[更新日志](https://dualsub.netlify.app/zh-cn/changelog)为准，因为审核速度原因，Edge 商店的版本总是有点滞后。

如果你遇到机器翻译失效的问题，也就是选择了“机器翻译”字幕菜单后，字幕没有显示，多半是访问 Dualsub 的服务器有问题。

确保能访问 https://api.dualsub.xyz/ 正常应该返回 `{"code":0}`，如果网速不佳，考虑通过代理访问。

如果你在 YouTube 下不想通过 Dualsub 的服务器来翻译，可以把设置改成：

* 网站 -> YouTube -> 自动字幕模式，改为 `普通`。
* 机器翻译 -> 基本 -> 翻译引擎，改为 `谷歌`。
* 机器翻译 -> 基本 -> 翻译模式，改为 `普通`。

在这种设置下，会使用 YouTube 使用原生翻译。

**备注：** YouTube 并非能翻译任意字符串，也就是 YouTube 只提供译文字幕，Dualsub 把原文字幕和译文字幕按相同时间轴合并显示，所以在 YouTube 通过插件加载的本地字幕，也只能通过 Dualsub 服务器翻译。

**Comment by xuebing22** [comment]
![image](https://user-images.githubusercontent.com/74288018/98777270-63b60900-242b-11eb-967b-42574e2cf803.png)
在b站无法捕捉到字幕语言，机器翻译那里也都是0，请问这种情况要如何解决？

**Comment by muzuiget** [comment]
贴一下视频地址。

**Comment by xuebing22** [comment]
> 贴一下视频地址。

试了十来个，好像b站的视频都不可以

**Comment by muzuiget** [comment]
为什么不直接贴地址。

**Comment by 2016011ak47** [comment]
https://www.bilibili.com/video/BV1qk4y197bB?p=20&t=8
这里翻译引擎设置为google,机器翻译还是没有生效
 另外我测试了https://music.163.com/#/song?id=584155 机器翻译还是没有生效

**Comment by xuebing22** [comment]
比如这个
https://www.bilibili.com/video/BV1X4411R7Ry?from=search&seid=2906852055171920533

**Comment by muzuiget** [comment]
这视频本来就没有 CC 字幕，虽然它有显示 CC 图标，但是它的字幕列表是空的。

**Comment by muzuiget** [comment]
@2016011ak47 我测试了，还能用，所以是你的网络问题，看来要考虑换个服务器提供商了。

**Comment by 2016011ak47** [comment]
![image](https://user-images.githubusercontent.com/16641052/100193475-d5637c00-2f2e-11eb-946c-61da61bcb911.png)
https://api.dualsub.xyz/ 这个接口在挂vpn情况下，现在无法访问，是服务挂了吗？

**Comment by muzuiget** [comment]
见 #174，那个地址目前挂了。
