### ISSUE TITLE
设置自动翻译代码

### ISSUE THREAD

**Issue by TaoChingChung** [muzuiget/dualsub-support#175]
格式为 `[字幕语言][机器翻译][语言工具][主题样式][限制序号]`：

```
一个菜单对应一个方括号。
可以用英文逗号分隔多个值。
最后的限制序号用 0 表示没有限制。
末尾连续的 [] 可以省略。
```

那我想要,无论有什么语言的视频,只要有字幕自动显示翻译后的中文字幕 这种怎么实现呢？`[][[zh-hans]][][][1]` 这样？

**Comment by muzuiget** [comment]
这种无法实现，无非就是如何选择原始语言，问题是无法判断有哪些原始语言，虽然一般会选择视频的原声语言，但是没有足够的信息来判断，所以你只好写上偏好的原始语言，例如

```
[en, ja][zh-hans][][][1]
```

这样，只要原始语言有英语或日语，就会自动选择，英语优先。

**Comment by TaoChingChung** [comment]
好的谢谢大佬~ 我还是使用[ORIG][zh-hans][][][1]来试试看~
这种应该是如果有字幕的话都能翻译成中文吧~

**Comment by muzuiget** [comment]
你没看清楚 `[ORIG][zh-hans][][][1]` 是无效的，因为没有 `ORIG` 这个变量，我那个例子是理论上技术想法。

**Comment by TaoChingChung** [comment]
OK~Get了~ 谢谢大佬~
