### ISSUE TITLE
chrome浏览器升级后，用这个插件经常假死

### ISSUE THREAD

**Issue by godisplayer** [muzuiget/dualsub-support#176]
Google Chrome 已是最新版本
版本 87.0.4280.66（正式版本） （64 位）
![捕获](https://user-images.githubusercontent.com/2177811/100001298-e365af80-2dfd-11eb-929a-9afc1f91c078.PNG)

**Comment by muzuiget** [comment]
这是正常的，不是假死，这是 Chrome 的安全策略，只要升级扩展版本，如果扩展权限有变动，Chrome 自动禁用，提示你确认新权限再启用。

最近更换了服务器地址，#174，“能够访问哪些网址数据”也是一种权限，所以权限有变动。
