### ISSUE TITLE
選擇機器翻譯項目後字幕就無法顯示

### ISSUE THREAD

**Issue by cyruskuo** [muzuiget/dualsub-support#177]
原本使用都正常，這週版更後即出現問題
只選「字幕語言」時，原生英文字幕可顯示
再選「機器翻譯」時，字幕就無法顯示

![螢幕截圖 2020-11-24 13 20 17](https://user-images.githubusercontent.com/74948985/100052606-3de02980-2e59-11eb-89d7-be9dfc3d5e8b.png)

![螢幕截圖 2020-11-24 13 21 44](https://user-images.githubusercontent.com/74948985/100052633-46d0fb00-2e59-11eb-802e-ded8867becb0.png)

**Comment by muzuiget** [comment]
见 #174

**Comment by cyruskuo** [comment]
> 见 #174

收到，感謝。

**Comment by cyruskuo** [comment]
v1.23.0 | https://api-1.dualsub.xyz | OK

回報，剛測了下，v1.23.0在chrome上仍不OK，機器翻譯仍無法顯示。

**Comment by muzuiget** [comment]
确保能访问 https://api-1.dualsub.xyz/ 正常应该返回 `{"code":0}`。

**Comment by cyruskuo** [comment]
是返回 {"code":0}沒錯
但仍無法顯示機器翻譯

<img width="425" alt="螢幕截圖 2020-11-26 08 29 19_cr" src="https://user-images.githubusercontent.com/74948985/100294777-be6e6980-2fc2-11eb-9900-f734ff0204d2.png">

**Comment by muzuiget** [comment]
确实是 bug，看漏眼了，就 YouTube 人工字幕翻译失败。

已经发布了 v1.23.1，升级一下即可。

**Comment by cyruskuo** [comment]
已正常，感謝。
