### ISSUE TITLE
可否新增一个下载字幕的功能 & 机器翻译不起效

### ISSUE THREAD

**Issue by hzpwan** [muzuiget/dualsub-support#178]
我看了软件的文档，知道dualsub的翻译会比油管自带的翻译好，所以我想下载下来，开发者能否新增这个功能呢？

另外：Win10 Chrome 1.23.0 点击机器翻译后，字幕并没有出现 [#174](https://github.com/muzuiget/dualsub-support/issues/174)看了这个，但实际并不OK = =

帮忙看一下，十分感谢~

**Comment by muzuiget** [comment]
> 我看了软件的文档，知道dualsub的翻译会比油管自带的翻译好，所以我想下载下来，开发者能否新增这个功能呢？

短期内没有精力做这个功能，直接合并 YouTube 的译文的话，已经有 https://dualsub-exporter.netlify.app/

> 另外：Win10 Chrome 1.23.0 点击机器翻译后，字幕并没有出现 #174看了这个，但实际并不OK = =

确保能访问 https://api-1.dualsub.xyz/ 正常应该返回 {"code":0}。

**Comment by muzuiget** [comment]
确实是 bug，看漏眼了，就 YouTube 人工字幕翻译失败。

已经发布了 v1.23.1，升级一下即可。

**Comment by 2016011ak47** [comment]
![image](https://user-images.githubusercontent.com/16641052/100321064-1aee7a80-2ffd-11eb-80a9-bd8b9919fc4f.png)
升级之后https://www.bilibili.com/video/BV1qk4y197bB?p=1 b站无法获取字幕语言， 但是我测试youtube是正常

**Comment by muzuiget** [comment]
看上去 B 站改版了，要重新兼容。

**Comment by muzuiget** [comment]
B站问题已经在 v1.23.2 修复。
