### ISSUE TITLE
希望添加一个字母的设置插件跟随Google的同步功能

### ISSUE THREAD

**Issue by suzukiying** [muzuiget/dualsub-support#179]

**Comment by muzuiget** [comment]
之前就是用上同步功能的，最后还是删了，几个原因：

* 同步存储有各种限制，限制读写频率，限制容量。
* 接口不好用，行为诡异，见 #138
* 扩展的设置，复杂部分也就是”样式“和”插件“本身就有导出和导入功能。
* 登录了 Chrome 账号就自动登录 Google 所有网站，这个功能神烦。
* 要支持 Edge，不想和有深度 Chrome 依赖。
