### ISSUE TITLE
迪士尼＋的好像都用不了了诶

### ISSUE THREAD

**Issue by leoooodanno00** [muzuiget/dualsub-support#180]
试了几个视频，字幕语言那是0，都没有了，都是关闭状态

**Comment by muzuiget** [comment]
我现在没有 Disney+ 账号了，不方便测试。所以最好先确定是否真的出问题：

1. 确保是 https://www.disneyplus.com/ 地址。
2. 测试一下热门的影片，例如漫威那些。
3. 网站原生的字幕菜单有字幕。

**Comment by Liqianyu** [comment]
经过测试，DualSub 1.25.0 对Disney +的支持确实不完善。
1.部分资源完全无法显示任何字幕，包括原字幕。用网站自带的可以显示，但DualSub无法调用。
这种资源当然也无法调用任何翻译。
测试资源：汉密尔顿、寻梦环游记
2.部分资源可以显示官方字幕，但调用翻译会出问题。例如简体和繁体中文只有GN(谷歌标准)可以成功翻译。如果调用其他会直接不显示任何字幕。例如翻译至日语韩语，选择任何翻译引擎也无法正常翻译。
测试资源：头脑特工队
如果有需要愿提供Disney +账号给开发者@muzuiget 用于调试。

**Comment by neweva** [comment]
v1.28.0 
大部分都可以顯示字幕
但問題是 所有字幕都超前顯示1秒或以上 很難受啊

**Comment by muzuiget** [comment]
@Liqianyu 谢谢详细的测试，可以的临时借用一下账号测试，发送到我的邮箱 muzuiget [at] gmail.com。

**Comment by muzuiget** [comment]
更新了文档 https://www.dualsub.xyz/website.html

Disney+ 我分为 C 级，意味住我并没有太大动力去修复兼容性问题。

**Comment by muzuiget** [comment]
在 v1.31.0 修复了，测试通过以下视频：

* 汉密尔顿
* 寻梦环游记
* 头脑特工队
