### ISSUE TITLE
啥时候能添加一下对safari的支持

### ISSUE THREAD

**Issue by tedyhang** [muzuiget/dualsub-support#181]

**Comment by muzuiget** [comment]
Safari 之前我稍微研究过了，不想支持。

无论 Chrome、Edge 和 Firefox，随便你用什么开发工具，创建和发布同一个 zip 文件到商店就完事了，代码都是通用的。

苹果非要搞特殊，需要用 MacOS，用 XCode 去专门处理重新打包，然后走 App Store 那一套流程，还开发者账号等等，恶心的一逼。

另外 WebExtension API 也是阉割实现，像 uBlock Origin 这样扩展也[不是官方支持](https://github.com/gorhill/uBlock#safari-macos)，要 fork 代码出来改。

所以 MacOS 里装个 Chrome 完事了，对开发者和用户都省事。

要是想用 Netflix 的 4K，还不如用 netlifx-1080p 这种曲线方式来实现，改 UserAgent 之类的方法。
