### ISSUE TITLE
I can't see the extension icon in the toolbar

### ISSUE THREAD

**Issue by vinniec** [muzuiget/dualsub-support#183]
I have firefox 78.5.0esr.
It seems that your extension works because I can interact with the settings window under the title of the currently  playing video on youtube and I can see the transcript on the side, but since I can't see the button on the toolbar I can't see the subtitles on the video.

**Comment by muzuiget** [comment]
Dualsub for Firefox version is `v0.8.x`, which is deprecated. I keep this version on Firefox because it still "just work".

The subtitle menu toolbar is below the video title.

**Comment by vinniec** [comment]
Where exactly? I have only these two things:
[01.jpg](https://0x0.st/i7hH.jpg): in the first image, if I press the blue button I get this configuration panel circled in red 
[02.jpg](https://0x0.st/i7hX.jpg): in the second image, if I press on "open stranscript" i get the trascription circled in red
But I don't know where i can get the double subtitles, i can see only the youtube normal subtitles

**Comment by muzuiget** [comment]
Sorry for the late response.

This is a bug, because YouTube has changed the page code. I have released a new version `v0.8.3` to fix this.

**Comment by vinniec** [comment]
Thanks, when I return in front of my pc i check it!
