### ISSUE TITLE
使用了Auto Select双字幕, 字体很大. 但是无论在theme style中对于first/2nd的样式怎么设置都不起作用 

### ISSUE THREAD

**Issue by rsyqvthv** [muzuiget/dualsub-support#185]
使用auto select:

```
[zh-hans, zh][][][][1]
[en][zh-hans][][][1]
[en][][][][2]
```

这时转到theme style设置中, 

first: 勾选了large font
second: 勾选了small font

之后在component style中设置

large font: font size: 24
small font: font size: 12

除了以上设置之外, 其他都是默认.

结果在youtube中显示字幕统一都是很大的字体, 第一第二字幕都是一样. 

**请问** 怎么在设置了auto select后调整第一和第二字幕的大小.

感谢.

**Comment by muzuiget** [comment]
自动选择和字体设置没有关系，你要确保在“主题样式”菜单(即第四列)并非`关闭`，也就是应用了某个“主题样式”，无论你手动选择还是自动选择，可以一下文档 https://www.dualsub.xyz/style-tutorial.html。

**Comment by muzuiget** [comment]
工具按钮页面的“主题样式”菜单条目，就是设置页面的“主题样式”侧边栏的菜单条目。

**Comment by muzuiget** [comment]
如果你只需要处理 YouTube 字体，也可以用[插件来动缩放](https://www.dualsub.xyz/plugin-example.html?id=%e6%a0%b7%e5%bc%8f%ef%bc%9ayoutube-%e6%af%94%e4%be%8b%e7%bc%a9%e6%94%be%e5%ad%97%e4%bd%93)。

**Comment by rsyqvthv** [comment]
感谢您的及时回复, 我终于明白还需要在扩展按钮的弹出菜单中, 为每个subtitle设置相应的style, 这样才能应用. 

逻辑上我以为在设置界面的样式中设置了主题样式, 便能自动应用了. 

感谢您的回复. 问题解决了.
