### ISSUE TITLE
b站视频 播放一半的时候 自动翻译一直显示英文

### ISSUE THREAD

**Issue by 2016011ak47** [muzuiget/dualsub-support#187]
https://www.bilibili.com/video/BV19k4y1C7kA?p=13&t=2586
在这个视频里播放到 43：01 后面时候都是显示英文 之前都可以正常显示中文
![image](https://user-images.githubusercontent.com/16641052/102467571-6a1f4c80-408b-11eb-8650-1abc083cfc57.png)

**Comment by muzuiget** [comment]
这是正常的，翻译功能是自建服务器实现的，有限制单次最大字符数量，超出的字符按原文返回，资源有限，目前不打算放宽了。

这种直播类视频目前确实是个问题，说话多，又不加剪辑，时间长，所以单次翻译文本量大。目前只能完整翻译，以后看看能不能优化根据播放时间分批次翻译，类似“视频缓冲”机制，也就是只翻译接下来要播放的一小段。

不过这种纯粹从 YouTube 搬运的视频，可以在 YouTube 观看，例如你这个视频 https://youtu.be/ADzLv1nRtR8 这样你可以直接使用 YouTube 自带的翻译，见文档 https://www.dualsub.xyz/translation-youtube.html 备注一节。

或者你用其它工具把 YouTube 的字幕下载回来，通过 Dualsub 的本地字幕功能加载显示。
