### ISSUE TITLE
Netflix 改版了 不支持了

### ISSUE THREAD

**Issue by LM-Firefly** [muzuiget/dualsub-support#189]
不支持新版 Netflix

**Comment by muzuiget** [comment]
我试了一下，还可以啊，用这个测试视频 https://www.netflix.com/watch/80094026

**Comment by LM-Firefly** [comment]
> 我试了一下，还可以啊，用这个测试视频 https://www.netflix.com/watch/80094026

我这里不行啊 我重新安装看看
![屏幕截图 2020-12-18 111414](https://user-images.githubusercontent.com/20715220/102570441-4d822380-4122-11eb-9ad3-24d77db90fe9.png)
