### ISSUE TITLE
支持美国国内的Amazon Prime Video？

### ISSUE THREAD

**Issue by finneck** [muzuiget/dualsub-support#190]
primevideo.com是给美国国外客户的网站。美国国内的网站是https://amazon.com/primevideo ，不知道可否尝试一下让dualsub支持这个网站？谢了！

**Comment by muzuiget** [comment]
请看文档 https://www.dualsub.xyz/website.html 并提供必要信息。

**Comment by muzuiget** [comment]
见 #194
