### ISSUE TITLE
機器翻譯選擇中文簡體或中文繁體後字幕就無法顯示

### ISSUE THREAD

**Issue by cyruskuo** [muzuiget/dualsub-support#191]
是服务器失效问题 or 其它bug造成?

![螢幕截圖 2020-12-26 11 07 57](https://user-images.githubusercontent.com/74948985/103144804-ca3c7f80-476a-11eb-8c50-a2badd2d6b29.png)

![螢幕截圖 2020-12-26 11 08 07](https://user-images.githubusercontent.com/74948985/103144816-e809e480-476a-11eb-96ed-9d76208c9d50.png)

![螢幕截圖 2020-12-26 11 08 17](https://user-images.githubusercontent.com/74948985/103144820-ec360200-476a-11eb-9e5f-c91c9fd2900d.png)

![螢幕截圖 2020-12-26 11 08 24](https://user-images.githubusercontent.com/74948985/103144823-ef30f280-476a-11eb-8a46-6c2404584d84.png)

![螢幕截圖 2020-12-26 11 08 45](https://user-images.githubusercontent.com/74948985/103144824-f2c47980-476a-11eb-932c-a215dc922961.png)

![螢幕截圖 2020-12-26 11 11 56](https://user-images.githubusercontent.com/74948985/103144841-3c14c900-476b-11eb-8d2e-ff093d68b904.png)

**Comment by muzuiget** [comment]
默认使用 Dualsub 服务器的翻译接口，如果网络不好，你可以设置回使用 YouTube 的翻译接口。

原因见 https://www.dualsub.xyz/translation-youtube.html

**Comment by muzuiget** [comment]
噢，你意思是其它语言都行，就中文不行？

**Comment by cyruskuo** [comment]
> 噢，你意思是其它语言都行，就中文不行？

是的。

**Comment by muzuiget** [comment]
是服务器的问题，已经修复。

**Comment by cyruskuo** [comment]
> 是服务器的问题，已经修复。

已正常運作，感謝。
