### ISSUE TITLE
Not working on Amazon Prime

### ISSUE THREAD

**Issue by elizamegan4** [muzuiget/dualsub-support#194]
Amazon prime - at least in the States - now operates from the https://www.amazon.com/* site, not the https://www.primevideo.com/* site, which Dualsub reads. Therefore, the extension doesn't even show as active when I'm watching amazon prime, it remains grayed out. 

Thank you.

**Comment by muzuiget** [comment]
Please read the related documents on https://www.dualsub.xyz/website.html

Question, the `https://www.amazon.com/primevideo` redirection is base on viewer's "browser IP location" or "account registered location"?

**Comment by elizamegan4** [comment]
Thank you for your answer. 

I changed my "account registered location" to Prague, CZ, and I was still directed to amazon.com, so I assume it's based on the browser IP location.

So would I need a VPN to change my "browser IP location" in order to access primevideo.com? Does Dualsub does plan on adding the https://www.primevideo.com/* domain?

**Comment by elizamegan4** [comment]
> Thank you for your answer.
> 
> I changed my "account registered location" to Prague, CZ, and I was still directed to amazon.com, so I assume it's based on the browser IP location.
> 
> So would I need a VPN to change my "browser IP location" in order to access primevideo.com? Does Dualsub does plan on adding the https://www.primevideo.com/* domain?

sorry, I meant do you plan to add the https://www.amazon.com/* site.

**Comment by muzuiget** [comment]
I will implement it if I have time.

**Comment by muzuiget** [comment]
Amazon stills redirect to `amazon.com` when I using USA account and Hong Kong proxy.

I am not sure how you change your account region, if you change by the top-right icon button, it just open a new tab for the region url, eg: `www.amazon.ca`.

Good news is `www.amazon.com` has a similar as `www.primervideo.com`, so the some code can re-use.

Bad news is the video url not has a fixed prefix, some prefix I found:

* `https://www.amazon.com/gp/video/*`
* `https://www.amazon.com/Amazon-Video/*`

But I don't like to declare the permission `https://www.amazon.com/*`, it will cause my extension to review more time or even reject.

**Comment by weiyuchou** [comment]
The audio and the subtitles are out of sync. In other words, the subtitles from the extension are not the same as the one from prime video, it seems the subtitles are still from the same episode, but just a little bit faster compared to the original one.

**Comment by muzuiget** [comment]
It this only happen when display two subtitles?

There is a "time aligning“ feature, it can reduce stuttering caused by misalignment between two subtitles.

Or you provide a the video url to test.

**Comment by weiyuchou** [comment]
No, even the English subtitle from the Dualsub doesn't match the English one from the PrimeVideo.
The below link is the screenshot of the issue.
https://upload.cc/i1/2021/04/30/Bxahzd.png

Here's the URL for testing.
https://www.primevideo.com/

Thanks a lot.

**Comment by muzuiget** [comment]
Your url is not a video url.

**Comment by weiyuchou** [comment]
The issue occurs in all videos in the PrimeVideo.

**Comment by weiyuchou** [comment]
I tried it again. And it works now. It seems the problem has been resolved. Thanks a lot.

**Comment by muzuiget** [comment]
I didn't change any thing.

**Comment by weiyuchou** [comment]
I guess if there is an advertisement before the video, the subtitle from the Dualsub starts loading with the advertisement playing causing the subtitles from the Dualsub to display sooner than they should. After reloading the video several times, there are not any advertisements playing before the video, then it works well.

**Comment by muzuiget** [comment]
I didn't see any advertisement before the video, it this related to the account subscription plan?

But there is a promo video before the video, but you can skip it by click the button on the down-right button, this does'nt matter to the subtitle time.

**Comment by muzuiget** [comment]
Amazon's account system is quite complex and difficult to test.

Also, the extension needs to request permission to access `https://www.amazon.com/*`, this permission maybe let some users have misgiving: why a subtitle application needs to access this site data? Because people treat Amazon more as a shopping site than a video site.

So I decided not to implement this feature.

It is recommended that users create an new account on primevideo.com to use Dualsub.
