### ISSUE TITLE
Not appearing on chrome - either youtube or iQiyi

### ISSUE THREAD

**Issue by gempazz** [muzuiget/dualsub-support#196]
![image](https://user-images.githubusercontent.com/77121908/103932280-87d75300-5119-11eb-9967-2150713abf28.png)
![image](https://user-images.githubusercontent.com/77121908/103932353-9e7daa00-5119-11eb-8b2e-b3a70ffcc98b.png)

Hi
Can you please help me with this issue? I can't seem to get the subtitles load up on the video at all?
Thank you

**Comment by muzuiget** [comment]
I tested, it still works on YouTube and iQiYi, use the videos on your screenshots.

![Screenshot_20210109_105142](https://user-images.githubusercontent.com/330812/104081296-b0219780-5268-11eb-8865-53cef445bc91.png)

Maybe you can teset the Dualsub settings and try again.

**Comment by gempazz** [comment]
Hi thanks for replying.

I reset the settings and it worked for 1 episode (3) but for the 4th episode I have this problem
![image](https://user-images.githubusercontent.com/77121908/104109518-a29afa80-52c6-11eb-815e-c367742abacd.png)

Also for the pinyin I can't seem to get it to show, would you be able to advise?
![image](https://user-images.githubusercontent.com/77121908/104109530-c100f600-52c6-11eb-9a08-a937c6fe283c.png)

Thank you for your help!

**Comment by muzuiget** [comment]
That is known issue, I also get it on the same video. Some of videos subtitle is encrypted, no way to decrypt them.
