### ISSUE TITLE
请问可以支持全局默认设置吗？

### ISSUE THREAD

**Issue by nbl97** [muzuiget/dualsub-support#197]
每次点开一个新视频都要重新点插件图标，选择相应的字幕设置。因为我看的视频大部分都是英语，所以设置基本一致，每次点就很麻烦。能否提供一个全局设置？

**Comment by muzuiget** [comment]
就是[自动选择](https://www.dualsub.xyz/guide.html?id=%e4%bd%bf%e7%94%a8%e8%87%aa%e5%8a%a8%e9%80%89%e6%8b%a9)功能。
