### ISSUE TITLE
Arte.tv: can you please add your extension to this video streaming site?

### ISSUE THREAD

**Issue by simone966** [muzuiget/dualsub-support#198]
Hi DualSub

Can you please add your extension on www.arte.tv?
It's a major European  culture video streaming channel.

It usually carries perfectly-matching subtitles (for most videos) in: 
- French
- German
and sometimes also
- English
- Spanish
Thank you!
SA

**Comment by muzuiget** [comment]
Supported in `v1.32.0`.

See the [screenshots](https://www.dualsub.xyz/screenshot.html?id=arte) and [detail](https://www.dualsub.xyz/website-detail.html?id=arte)

**Comment by simone966** [comment]
Thank you Dual Sub!


But on Chrome, if I go to www.arte.tv, I cannot show the second subtitle yet


Simone

On 19 Jan 2021, at 13:11, muzuiget <notifications@github.com> wrote:


Supported in v1.32.0.

See the screenshots <https://www.dualsub.xyz/screenshot.html?id=arte> and detail <https://www.dualsub.xyz/website-detail.html?id=arte>

**Comment by muzuiget** [comment]
Make sure you update to `v1.32.0`.

Please post the issue video link.
