### ISSUE TITLE
youtube not working

### ISSUE THREAD

**Issue by myururdurmaz** [muzuiget/dualsub-support#199]
![image](https://user-images.githubusercontent.com/1057861/106096335-67ae1900-6146-11eb-94d2-6e020d5dcf85.png)

test url : https://www.youtube.com/watch?v=v9YoPIwBmHU

browser

![image](https://user-images.githubusercontent.com/1057861/106096382-7d234300-6146-11eb-97c1-9e4ac4e7fcc0.png)

**Comment by muzuiget** [comment]
Dualsub for Firefox is deprecated. It is recommend to switch to Chrome version.

**Comment by myururdurmaz** [comment]
I'm using only firefox. Should I uninstall the plugin?

**Comment by muzuiget** [comment]
Yes
