### ISSUE TITLE
Port to Firefox?

### ISSUE THREAD

**Issue by joaoeudes7** [muzuiget/dualsub-support#200]
Hi, great extension! Have plan to create a version to firefox?

**Comment by c2xusnpq6** [comment]
https://addons.mozilla.org/zh-TW/firefox/addon/dualsub/ @joaoeudes7 `備註：Firefox 版本已經廢棄，但基本功能還能用，對於新用戶，建議使用 Chrome 版本。 `

We need Firefox version!!!!!!!!!!!!!!!!!!!!

**Comment by muzuiget** [comment]
Currently reasons block to support Firefox:

**Firefox renders the HTML tag `<ruby>` difference from Chrome**

I need to rewrite the rendering code to support Firefox, this is teach issue can be solved if I spend more time on it.

**Firefox Store requires [source code submission](https://extensionworkshop.com/documentation/publish/source-code-submission/)**

In the version `v0.8.x`, I indeed did as it says, I wrote a build system for Firefox Store, but actually they didn't read it, they just check whether you submit the source code archive.

In the new version `v1.x`, source code is more complicated, so I don't want to follow this ridiculous requirement again, it just wasting developer's time.

If I fixed the tech issue, I will submit a new version to Firefox Store, but without source archive, If the reviewers reject it, then the only way to use in Firefox is install it in the Developer Mode.

**Comment by muzuiget** [comment]
Firefox has difference content scripts model from Chrome, see [bugzilla 1208775](https://bugzilla.mozilla.org/show_bug.cgi?id=1208775).

This rather painful on porting, and Google launch Manifest V3 on Chrome 88, better to update to Manifest V3 first.

**Comment by muzuiget** [comment]
Just note that `v1.41.0` re-add support for Firefox.
