### ISSUE TITLE
大神，跪求更新一下字幕下载功能

### ISSUE THREAD

**Issue by lylaiety** [muzuiget/dualsub-support#201]
现在的字幕下载功能，每次都要手动选择字幕语言，没有默认选项。希望能添加一个设置默认字幕语言选项。
另外跪求YouTube视频播放列表批量下载字幕功能。

**Comment by hunandy14** [comment]
路過看到，批量下载字幕 jdownloder 可以實現。

**Comment by muzuiget** [comment]
你是说 https://dualsub-exporter.netlify.app/ ？

讲真我都不想维护了，因为我自己都不用了，服务器部署在 Google 云上，更新起来又要翻墙又麻烦。还能用就凑合咯，搞抬贵手点击多几次。
