### ISSUE TITLE
想請問為什麼自己新增的ass字幕會沒辦法正常播放

### ISSUE THREAD

**Issue by hunandy14** [muzuiget/dualsub-support#204]
字幕源是這個：
https://github.com/hunandy14/jimaku/blob/master/%E3%81%A8%E3%82%82%E3%83%BC%E3%81%BF%E3%83%81%E3%83%A3%E3%83%B3%E3%83%8D%E3%83%AB%20Tomo-mi%20channel/%E3%81%9D%E3%82%8C%E6%A8%99%E6%BA%96%E8%AA%9E%E3%81%A1%E3%82%83%E3%81%86%E3%82%89%E3%81%97%E3%81%84%E3%81%A7%EF%BC%81%E3%80%90%E9%96%A2%E6%9D%B1%E3%81%A7%E9%80%9A%E3%81%98%E3%81%AA%E3%81%84%E9%96%A2%E8%A5%BF%E5%BC%81%E3%80%91%EF%BC%91%EF%BC%96%E9%81%B8/subtitles.ass

字幕是用aegisub生成的，有試著把他轉成str就可以正常掛載了。請問這個ass檔是有什麼原因不能掛載嗎。
另外不知道能不能新增一個從檔案載入的功能，目前看起來是只能手動打開複製手動貼上的樣子。

**Comment by muzuiget** [comment]
你那个 ass 文件我测试了，可以正常处理。你在“类型”那里选择了“字幕 ASS”了吗？

从文件直接载入字幕目前不是很好做，因为那个插件编辑器是通过一些工具代码自动生成的，并不是专门手写，所以不好加功能。

**Comment by hunandy14** [comment]
感謝回覆，我今天重新測試了一次可以正常掛載字幕了

好的，了解
