### ISSUE TITLE
关于语言选择代码

### ISSUE THREAD

**Issue by eAtlantis000** [muzuiget/dualsub-support#205]
请问如何设置第二行机翻仅为英文或简体中文，字幕语言是只有英文或者中文么？还是因为YouTube大多数视频字幕是英文
目前自己的代码是：
[][en][SKIP][第一字幕][1]
[en][zh-hans，zh][SKIP][第二字幕][2]
变更过第二行[2]中的2为1，但是第二行内容始终默认关闭，求解决方案

还有就是和插件无关的，油管字幕怎么看见非英语字幕，搜索界面上明明显示视频有字幕，但是进入视频点开设置却没有字幕选项，有的视频字幕和视频压在一起了，但是还有视频中没有自带的也不显示

**Comment by muzuiget** [comment]
第一个问题我没看懂，文档中那个示例已经适合大部分视频了

```
[zh-hans, zh][][][][1]
[en][zh-hans][][][1]
[en][][][][2]
```

第二个问题

> 油管字幕怎么看见非英语字幕，搜索界面上明明显示视频有字幕，但是进入视频点开设置却没有字幕选项

这个应该是上传者自己的设置问题，标记了有字幕，但是没实际上传字幕文件。

> 有的视频字幕和视频压在一起了，但是还有视频中没有自带的也不显示

压到视频图像里的字幕，没办法二次处理的了，那已经是视频画面的一部分。
