### ISSUE TITLE
YouTube機器翻譯失效

### ISSUE THREAD

**Issue by CrazyLayKer** [muzuiget/dualsub-support#206]
重置設定後翻譯功能依然失效，使用以下設定仍然只有英文字幕。

![image](https://user-images.githubusercontent.com/71445791/107881310-c7663b80-6f1e-11eb-9c16-49fda8040adb.png)
![image](https://user-images.githubusercontent.com/71445791/107881336-e4027380-6f1e-11eb-9b7f-68216aeacd24.png)
![image](https://user-images.githubusercontent.com/71445791/107881620-19f42780-6f20-11eb-85cb-8f6c21e77889.png)
![image](https://user-images.githubusercontent.com/71445791/107881610-01840d00-6f20-11eb-9792-2d96a32c0030.png)

是否可能與其他擴充功能衝突？
相關擴充功能列表（據我所知皆無類似功能）：
Improve YouTube! (Testing)
Audio Only Youtube
AdBlock — 最佳廣告攔截程式
Dmooji 彈幕君 - YouTube彈幕助手
PocketTube: Youtube Subscription Manager

**Comment by muzuiget** [comment]
首先确保是最新的版本的 Dualsub 和 Chrome 浏览器

确保能正常访问 https://api.dualsub.xyz，如果你在扩展设置页面里，看到公告内容，说明能服务器功能是正常的。

如果你确实连接服务器有问题，修改相关配置，翻译功能直接使用 YouTube 译文，文档见 https://www.dualsub.xyz/website-detail.html?id=youtube
