### ISSUE TITLE
YouTube人工字幕顯示異常（個例?）

### ISSUE THREAD

**Issue by CrazyLayKer** [muzuiget/dualsub-support#207]
Dualsub設定已重置為預設設定。
影片來源：https://www.youtube.com/watch?v=DmmMADg-qPU&ab_channel=Insider
![image](https://user-images.githubusercontent.com/71445791/107881943-a6ebb080-6f21-11eb-906d-9af50d567759.png)
![image](https://user-images.githubusercontent.com/71445791/107881928-91768680-6f21-11eb-9d6f-d0b512fe076f.png)
![image](https://user-images.githubusercontent.com/71445791/107881993-e5816b00-6f21-11eb-9afc-51d2d98a3e54.png)
![image](https://user-images.githubusercontent.com/71445791/107882063-4ad55c00-6f22-11eb-9b53-f42fdf40a7ed.png)

同時使用的相關擴充功能列表：
Improve YouTube! (Testing)
Audio Only Youtube
AdBlock — 最佳廣告攔截程式
Dmooji 彈幕君 - YouTube彈幕助手
PocketTube: Youtube Subscription Manager

**Comment by muzuiget** [comment]
这个描边效果问题，很早之前存在的，某些视频宽度下偶然会出现，我觉得已经解决了，你那个视频我也重现不了。

确保是最新的 Chrome 和 Dualsub。
