### ISSUE TITLE
v1.36.0 netflix is not working

### ISSUE THREAD

**Issue by chtbof** [muzuiget/dualsub-support#208]

**Comment by muzuiget** [comment]
Still works

![www netflix com_watch_80094026](https://user-images.githubusercontent.com/330812/108434463-a71de000-7282-11eb-8637-3de0b5d1b3bd.jpg)

Please provide more details with function is not working.

**Comment by chtbof** [comment]
![photo_2021-02-19_08-05-46](https://user-images.githubusercontent.com/22293553/108438067-72615700-7289-11eb-8dbf-9c85cce9f886.jpg)

**Comment by chtbof** [comment]
Dual sub not working in Taiwan

**Comment by muzuiget** [comment]
台湾版的 Netflix 吗？

试下这个视频 https://www.netflix.com/watch/80094026

**Comment by chtbof** [comment]
是的, 無法顯示, 在youtube是正常的

**Comment by muzuiget** [comment]
麻烦在 Netflix 选好字幕后，然后按 F12，呼出 DevTools，看看 Console 里有没有什么错误显示。

**Comment by chtbof** [comment]
![image](https://user-images.githubusercontent.com/22293553/108699898-d1042a80-7540-11eb-8c90-b7502238f3fb.png)
1.37.0 還是一樣, consloe 沒有錯誤

**Comment by chtbof** [comment]
V 1.37.0 YOUTUBE  翻譯ERROR 
![image](https://user-images.githubusercontent.com/22293553/108704660-4a068080-7547-11eb-9c04-77fc2a21fd89.png)

**Comment by muzuiget** [comment]
Netflix 应该改版了，我今天也遇到了，等下发个小版本修复。

翻译问题是昨天更新了服务器的问题，已经修复。

**Comment by muzuiget** [comment]
Netflix 问题已在 `v1.37.1` 修复。
