### ISSUE TITLE
微軟的翻譯引擎大概只會翻譯一半的字幕...

### ISSUE THREAD

**Issue by Bob-YsPan** [muzuiget/dualsub-support#209]
設定模式為這樣
![image](https://user-images.githubusercontent.com/46966555/108591248-b09e6980-73a2-11eb-91ff-9ea4211e8824.png)

以這部影片為例：
到大約4:45都還有正確字幕
![image](https://user-images.githubusercontent.com/46966555/108591200-6e752800-73a2-11eb-8fa0-6fd0557c5822.png)

不過到了影片後半邊卻只有英文
大概測試了2-3部影片，好像微軟的翻譯都會在影片一半的位置失效
![image](https://user-images.githubusercontent.com/46966555/108591295-fd824000-73a2-11eb-8cc5-757138a275d5.png)

有什麼解法或是之後會改善呢？
感謝你們。

**Comment by muzuiget** [comment]
我偶然也会这样，应该是服务器这边的问题，似乎随机出现，反正很少人用，暂时不管了。

现在 Dualsub 翻译是分段翻译的，避免一次过翻译整个字幕，而浪费翻译资源，例如视频没看完就提前关掉。

其实 Google 和微软翻译下来感觉没多大差别。

**Comment by Bob-YsPan** [comment]
我是想說有時候像科學名詞比較多的影片
有時候谷歌的服務會修飾的太多一點
所以想借微軟的引擎感覺對詞語的修飾相對比較輕量…
可惜只能翻譯一半時長的影片…

**Comment by Bob-YsPan** [comment]
這個問題解決了
謝謝啦～

不過還有一個小小的問題
我再另外開一個issue
希望可以未來版本解決一下

**Comment by Bob-YsPan** [comment]
不好意思剛剛測試不是很完整
Sorry

我大概列一下測試的結果：
``

**Comment by muzuiget** [comment]
我还没开始修呢。

**Comment by muzuiget** [comment]
版本 v1.40.0 已发布，修复了这个问题。

**Comment by Bob-YsPan** [comment]
謝謝啦
我最近測試
最近如果都測試OK的話我會把Issue close

**Comment by Bob-YsPan** [comment]
到目前為止測試正常
感謝
