### ISSUE TITLE
突然不能翻译了

### ISSUE THREAD

**Issue by rocksea1973** [muzuiget/dualsub-support#210]
两排都是英文，任何一个语种都没有反应

**Comment by muzuiget** [comment]
是服务器挂了，现在再试下。

**Comment by rocksea1973** [comment]
> 是服务器挂了，现在再试下。

油管还是不行

**Comment by muzuiget** [comment]
直接打开 https://api.dualsub.xyz/ 看看是否返回 `{"code":0}`，否则检查一下你的网络，或者重置一下扩展的设置。

**Comment by rocksea1973** [comment]
> 直接打开 https://api.dualsub.xyz/ 看看是否返回 `{"code":0}`，否则检查一下你的网络，或者重置一下扩展的设置。
返回是 {"code":0}  我是翻了，但是油管可以上啊，也重置了，我甚至重装插件了，还是不行

**Comment by xuebing22** [comment]
我也有同样的问题，只能显示英文字幕，无法翻译

**Comment by muzuiget** [comment]
隔段时间再试，或者使用 `v1.38.0` 之后的“简单模式”。

**Comment by muzuiget** [comment]
隔段时间再试，或者使用 `v1.38.0` 之后的“简单模式”。

**Comment by rocksea1973** [comment]
> 隔段时间再试，或者使用 `v1.38.0` 之后的“简单模式”。

简单模式可以用，但要把油管自己的字幕键点亮，标准模式还是老样子

**Comment by muzuiget** [comment]
突然想到一个可能原因，你的系统时间是否准确，先同步一下系统时间试试。

**Comment by rocksea1973** [comment]
> 突然想到一个可能原因，你的系统时间是否准确，先同步一下系统时间试试。

虽然是没动过系统时间，我还是重新同步了一下，没用，还是老样子

**Comment by muzuiget** [comment]
刚刚我在更新服务器，你现在再试下，更新到最新的 Chrome 88+ 和 Dualsub 1.39.0。

**Comment by rocksea1973** [comment]
> 刚刚我在更新服务器，你现在再试下，更新到最新的 Chrome 88+ 和 Dualsub 1.39.0。

chrome 89.0.4389.72版，标准模式还是不行，另，出现一个新现象，就是标准模式下的英文字幕跟油管自己的字幕一样有一条黑色半透明的背景，不晓得是不是插件自带，以前没有。我印象里1.37是正常工作的

**Comment by migelanlol** [comment]
Microsoft Edge 89.0.774.45 ， 可以正常翻譯了，但同上自帶一條黑色背景

**Comment by muzuiget** [comment]
出现黑色背景只是我更新了设置选项默认值，你可以在设置选项里改回描边的，下个版本会加个“快速设置”在弹出页面的。

**Comment by muzuiget** [comment]
@rocksea1973 你这个情况真是奇怪，有没有试过干脆卸载扩展，然后再安装回去？

**Comment by rocksea1973** [comment]
> @rocksea1973 你这个情况真是奇怪，有没有试过干脆卸载扩展，然后再安装回去？

终于搞定，我其实在前面第三条回复里就讲已经重装了，呵，刚又卸掉，重装了一次，好了

**Comment by muzuiget** [comment]
玄学， 关贴了。
