### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by cazzz10** [muzuiget/dualsub-support#211]
not working after last update

**Comment by neweva** [comment]
me too

**Comment by muzuiget** [comment]
Dualsub server is down yesterday night, fixed now.

**Comment by neweva** [comment]
one more thing
since the last update
Disney plus display not thing

**Comment by muzuiget** [comment]
@neweva I also have received private email tell me about it, see #212

**Comment by cazzz10** [comment]
still not working for me

**Comment by muzuiget** [comment]
Open https://api.dualsub.xyz/ check if it response `{"code":0}`, or reset the extension settings.

**Comment by cazzz10** [comment]
it is writing code i reset it still the same

**Comment by muzuiget** [comment]
Please provide the video url.

**Comment by cazzz10** [comment]
all netflix videos not working. youtube working

**Comment by muzuiget** [comment]
Netflix is a known bug, fixed in `v1.37.1`.

**Comment by cazzz10** [comment]
thanks worked
