### ISSUE TITLE
Not working on Disney Plus

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#212]
It looks like Disney Plus has update their website.

The issue is Dualsub can't display the subtitle on the video above, but the toolbar show the subtitle language list correctly.

Currently I don't have Disney Plus account to test. If someone have account help me do the test.

1. Open the a video, like https://www.disneyplus.com/video/3898abdd-ee03-470a-b157-66e65b5b9db0
2. Select any subtitle in Dualsub toolbar.
3. Click the player button to switch to fullscreen.
4. Press F12 to open DevTools, switch to Console
5. Enter code `document.fullscreenElement.id` and run, attach the screenshot here.

**Comment by neweva** [comment]
![Uploading Xnip2021-02-23_15-45-38.png…]()

**Comment by neweva** [comment]
<img width="1440" alt="Xnip2021-02-23_15-45-38" src="https://user-images.githubusercontent.com/9881748/108815875-1e8ba080-75f0-11eb-9c06-b48e9b0e2bdc.png">

**Comment by muzuiget** [comment]
The command result is fine, maybe other reason.

And I notice the error:

![Screenshot_20210223_211358](https://user-images.githubusercontent.com/330812/108848671-3c6efa80-761c-11eb-98ee-5158da4f1baa.png)

The `m3u8` file is the subtitle files list, it looks like the server block your access, are you using a proxy?

**Comment by neweva** [comment]
<img width="1440" alt="Xnip2021-02-24_19-31-40" src="https://user-images.githubusercontent.com/9881748/108994675-0d698f00-76d7-11eb-8a05-b1b5458e9933.png">
是的 我確實是用proxy 來觀看Disney plus HBO MAX等
上圖所示 是當我開啟Disney Plus 原字幕時候 也是 m3u8:1 error
但能正常 播放字幕

另外 播放HBO MAX 如果播放的視頻有片頭的話 會不能正常顯示字幕 需要刷新後才可能播放字幕
<img width="1440" alt="Xnip2021-02-24_19-25-02" src="https://user-images.githubusercontent.com/9881748/108995371-f7a89980-76d7-11eb-8599-d173f136abdc.png">

最後 如果您是因為帳號問題 可以私下聯繫我
感謝您的付出

**Comment by muzuiget** [comment]
Disney+ 的网站的技术架构特别复杂，不同视频还能有不同的字幕数据结构，所以你试试其它不同类型的视频，是否都有问题。

Disney+/HBO 除了账号外，还得另外买个美国的代理，我最近暂时没时间调试了，如果基本功能还能用，先凑合下。

如果你愿意提供账号，发个邮件到 muzuiget [at] gmail.com，目前只需确定你的邮件地址，暂时不需要你的账号，以后有需要再联系你。

**Comment by muzuiget** [comment]
这个问题已经解决，等新版本发布。

**Comment by muzuiget** [comment]
v1.39.0 已发布，修复了这个问题。
