### ISSUE TITLE
在Brave瀏覽器上使用youtube 字幕字體大小樣式失效

### ISSUE THREAD

**Issue by vauselor** [muzuiget/dualsub-support#213]
![字幕問題](https://user-images.githubusercontent.com/79667366/109215800-a17a4a00-77ee-11eb-9284-f9b2f584405f.png)
如標題在Brave瀏覽器上使用youtube字幕字體大小樣式失效
但在Netfilx上使用正常

**Comment by muzuiget** [comment]
你是不是用了"插件”功能自定义了样式？

**Comment by vauselor** [comment]
我沒有使用插件
但後來我把瀏覽器整個重新安裝就正常了
謝謝
