### ISSUE TITLE
u didnt get me last time i mean that we can add subtitle not download it we upload it to playback video

### ISSUE THREAD

**Issue by 01MrHacKeR01** [muzuiget/dualsub-support#214]
the idea like +sub extension it allow u to upload ur own subtitle to video and control it
also add time delaying or earlier it is in +sub too it is easier than edit every sub and easy to use if it was feauture and  friendly
Here is the example 
chrome extension : https://chrome.google.com/webstore/detail/%20sub/lpobdmdfgjokempajoobgfdnhjbjlnpm
github : https://github.com/plussub/plussub
and i appreciate ur good and fixing feedback

**Comment by muzuiget** [comment]
Currently you can load local subtitle file with the Dualsub plugin feature: https://www.dualsub.xyz/plugin-usage.html?id=subtitle-plugin

**Comment by 01MrHacKeR01** [comment]
> Currently you can load local subtitle file with the Dualsub plugin feature: https://www.dualsub.xyz/plugin-usage.html?id=subtitle-plugin

is that only support *.vtt extension 
most of subtitle are *.ass and *.srt
also i perfered it was in GUI in dual sub or video gui to be easier to user 
also add time delay or earlier cuz if sub not sync with it u need to make it forward or back ward and also plz make it in gui of dualsub or in video playpack cuz it will be easier then edit it with notepad or program and more friendly normal user also to compare it to video to know how much left u need to do and test it and see u wanna add more or less and as i said there is good example in +sub extension i got this idea from there and it will make ur extension very good and more funiction

**Comment by muzuiget** [comment]
Dualsub supports vtt/srt/ass/ttml.

I think this requirement is unnecessary, websites like Netflix/Disney+ provide subtitles themself, usually we don't need to get the subtitle from other websites.

Also, a movie may has difference version(eg: Director Cut Version/Extended Version), and difference framerate(eg: blueray/webrip), so there a step to pick the match version file. I prefer move the step to the 3rd website, Dualsub submit the movide URL/ID to the 3rd website, it should return the match file directly, user should not do the complex UI action is the small toolbar popup page.

**Comment by 01MrHacKeR01** [comment]
> Dualsub supports vtt/srt/ass/ttml.
> 
> I think this requirement is unnecessary, websites like Netflix/Disney+ provide subtitles themself, usually we don't need to get the subtitle from other websites.
> 
> Also, a movie may has difference version(eg: Director Cut Version/Extended Version), and difference framerate(eg: blueray/webrip), so there a step to pick the match version file. I prefer move the step to the 3rd website, Dualsub submit the movide URL/ID to the 3rd website, it should return the match file directly, user should not do the complex UI action is the small toolbar popup page.

no probably not but for me my main language is arabic i have a lot of content i cant find it in my country in any streaming service
so i had to either pirate it or use vpn and i see pirating is something bad and consdier stealing so i use vpn to watch that content and in vpn country they dont interest to add my country language that is why i need to add  subtitle cuz my country subtitle is not provided by website 
also for difference version i knew this problem and i find solve that i should delay or make it earlier this feature i knew it from +sub extension u can check it it his delay and earlier time value that u can change from UI
also i perfer u add in gui the opition to add subtitle even in a small (+) shape
and add time delayer or earlier

**Comment by 01MrHacKeR01** [comment]
> Currently you can load local subtitle file with the Dualsub plugin feature: https://www.dualsub.xyz/plugin-usage.html?id=subtitle-plugin

also ur method i got some troubles the code area should i open subtitle file and copy the code from it to the code area
also there is also websites opitions 
but not all website are there like funimation
also where is plugin statues i tried to find it but i cant also dont forget the replay that i wrote before that

**Comment by muzuiget** [comment]
Please use formal English, your English is hard to understand, add punctuation, correct letter case, and no abbreviations.

**Comment by 01MrHacKeR01** [comment]
> Please use formal English, your English is hard to understand, add punctuation, correct letter case, and no abbreviations.

no i  need this feature and people like my case because for me ,my main language is arabic i have a lot of content (shows and series)  i cant find it in my country in any streaming service
so i had to either get this show or series from pirated websites or i use vpn to get that content that is not avalibe in my country and i see getting shows or series or movies is something bad and consider as stealing so i use vpn to watch that content (shows and series and movies ) and in that country ( the country i access from by using vpn ) the company  dont interest to add my country language .that is why i need to add subtitle cuz my country subtitle is not provided by website and not there>
also for director cut  version. it is probably one popluar one but the problem come that there is extended intro (for streaming service logo or some small addition scene) i knew this problem and i find solve that i can change the time of subtitle by making the Sentences appear late or early a a feature that i told u to add it which were at +sub extension u can check it .it allow u to make  delay time value that u can change from UI
also i perfer u add this feature in gui 
also the current existing feature to add subtitle in dualsub . i got troubles with it
there is a  code area in plugin tab . what should i write?
under the code area there is website area . not all website are in website area . like there is not funimation.com
and in the method that u give me to add subtitle it say go to plugin status . i didnt find plugin status tab or area

conclusion add a button in GUI of dualsub that allow us to add subtitle i need this subtitle cuz i use vpn to watch unavailable content (shows,movies and series ) which are not Available in my country in any streaming service 
and when i use vpn my language subtitle is not supported that why that 
sry for terrible eng u may now know how i really need this feature

**Comment by muzuiget** [comment]
Didn't read.

If you don't use formal English, this issue will be marked as invalid. Please add punctuation, correct letter case, and no abbreviations.

**Comment by 01MrHacKeR01** [comment]
> Didn't read.
> 
> If you don't use formal English, this issue will be marked as invalid. Please add punctuation, correct letter case, and no abbreviations.

I did correct it it is the eng the I know
the conclusion add subtitle feature in GUI to can upload subtitle to the website 
I need this feature because the streaming service doesn't support my language
 and I need the feature of making delay in subtitle because if there Is a streaming service intro before the video
 like the feature in +Sub extension

**Comment by 01MrHacKeR01** [comment]
I even use Grammarly lol
and also I didn't find "Plugin Status" tab . where  is it in dualsub options

**Comment by muzuiget** [comment]
As I said before, you can load the external subtitle file through the "Plugin" feature, you can always adjust the subtle delay with any subtitle editor, then paste the content to Dualsub.

The "Plugin Status" tab is became to the "Website" section.check the url checboxs to enable the plugin.

**Comment by 01MrHacKeR01** [comment]
> As I said before, you can load the external subtitle file through the "Plugin" feature, you can always adjust the subtle delay with any subtitle editor, then paste the content to Dualsub.
> 
> The "Plugin Status" tab is became to the "Website" section.check the URL checkboxes to enable the plugin.

the URL checkboxes are not available for some website like funimation.com hidive.com Crunchyroll 
make an option to add URLs

**Comment by 01MrHacKeR01** [comment]
> As I said before, you can load the external subtitle file through the "Plugin" feature, you can always adjust the subtle delay with any subtitle editor, then paste the content to Dualsub.
> 
> The "Plugin Status" tab is became to the "Website" section.check the url checboxs to enable the plugin.

also it is hard to make delay u need to edit every "time value" for each sentence and u would get spoiled by reading them or seeing them

**Comment by muzuiget** [comment]
Dunalsub has drop support for Funimation and Crunchyroll since [v1.36.0](https://www.dualsub.xyz/changelog.html?hl=en&id=v1360).

I don't want to spend time on a rare use feature. the website or the subtitle creator has responsibility create a synchronized subtitle for the video.

**Comment by 01MrHacKeR01** [comment]
> Dunalsub has drop support for Funimation and Crunchyroll since [v1.36.0](https://www.dualsub.xyz/changelog.html?hl=en&id=v1360).
> 
> I don't want to spend time on a rare use feature. the website or the subtitle creator has responsibility create a synchronized subtitle for the video.

okay but funimation and crunchyrol
are not available in Website" section in plugin status

**Comment by muzuiget** [comment]
Because after remove support for funimation.com and crunchyrol.com, it also remove the declare permissions in the extension manifest, so the extension can't access the funimation.com and crunchyrol.com the data any more.

If you look for similar feature, use Greasemonkey instead.

**Comment by 01MrHacKeR01** [comment]
> Because after remove support for funimation.com and crunchyrol.com, it also remove the declare permissions in the extension manifest, so the extension can't access the funimation.com and crunchyrol.com the data any more.
> 
> If you look for similar feature, use Greasemonkey instead.

so dualsub no longer works with crunchyrol and funimation but why

**Comment by muzuiget** [comment]
I had rewrite some low level code of Dualsub, it's difficultly to compatible with crunchyrol and funimation, and they are unpopular websites, drop support for them.

**Comment by 01MrHacKeR01** [comment]
> I had rewrite some low level code of Dualsub, it's difficultly to compatible with crunchyrol and funimation, and they are unpopular websites, drop support for them.

can u give me the way or method u used it before to support funimation in the main page not playpack page ?

**Comment by muzuiget** [comment]
What call "the way or method"? That's hundred lines JavaScript.

**Comment by 01MrHacKeR01** [comment]
> What call "the way or method"? That's hundred lines JavaScript.

explain it more , someone i know had a trouble to support funimation to his extension  so how could u do that With detail

**Comment by 01MrHacKeR01** [comment]
> What call "the way or method"? That's hundred lines JavaScript.

i mean how the idea or how u figure to solve it 
also can code help him if he saw it ?

**Comment by muzuiget** [comment]
Funimation and Crunchyrol use `<iframe>` to show the player, this behavior like embed YouTube player to non-YouTube websites, so you need to handle two page in the same time, in JavaScript, you need to access `window.frame` object to get the `<iframe>` page information, this make the code rather complex.

**Comment by muzuiget** [comment]
I close this issue because nothing to change.
