### ISSUE TITLE
Pinyin not showing in Brave/Chrom

### ISSUE THREAD

**Issue by gempazz** [muzuiget/dualsub-support#215]
Hi, 
Please see attached photos. I've tried to enable pinyin but cannot get it to show.
![Screenshot 2021-02-28 at 21 06 03](https://user-images.githubusercontent.com/77121908/109433603-2a6ccd80-7a09-11eb-910c-f0915444a008.png)
![Screenshot 2021-02-28 at 21 06 26](https://user-images.githubusercontent.com/77121908/109433609-2c369100-7a09-11eb-995d-4020ef5676cc.png)

Could you please advise.

Thank you

**Comment by gempazz** [comment]
![image](https://user-images.githubusercontent.com/77121908/109433637-4f614080-7a09-11eb-85ce-64db37de605e.png)
*pinyin not showing

**Comment by muzuiget** [comment]
Maybe your network issue, have you try again later?

**Comment by gempazz** [comment]
Hi, 

I've tried it just now and still not showing. I've the add-on for a couple months but never got the pinyin to show. 

Thanks

**Comment by muzuiget** [comment]
Open https://api.dualsub.xyz, it should reponse `{"code":0}`.

**Comment by gempazz** [comment]
Hi 

Yes it did. What should I do next? The Pinyin is not showing still.

**Comment by muzuiget** [comment]
Have you try other websites or videos?

**Comment by gempazz** [comment]
I've also tried netflix and youtube and along with other videos - none of it works

**Comment by muzuiget** [comment]
Do you have the correct system time? Some encryption-related things rely on accurate system time. Try to synchronize your system time with the network.

**Comment by gempazz** [comment]
what do you mean by system time? like the timezone and such? If so then that is accurate for where I am. 
How do I synchronise the system time with the network?

**Comment by muzuiget** [comment]
The system time is show on your desktop tray area, if you using Windows 10, it is bottom-right corner, does the time displaying match reality world time? It should not delay/earlier then the reality world time too much.

Search "windows 10 force internet time sync" on YouTube, there are many videos tell you how to to sync it.

**Comment by gempazz** [comment]
I use MacOS and it was matching the world time however I forced a sync again anyway, restarted the browsers and no results :(

**Comment by muzuiget** [comment]
Open the extension settings page, can you see this?

![Screenshot_20210304_044549](https://user-images.githubusercontent.com/330812/109869984-83a45d80-7ca4-11eb-9ef8-cb7b3d5180aa.png)

Or just a empty page?

**Comment by gempazz** [comment]
![image](https://user-images.githubusercontent.com/77121908/109870256-c7c23e80-7c61-11eb-9bef-650352f36e5a.png)
Hi it is empty for me

**Comment by muzuiget** [comment]
This really strange. Are you using Chrome 88+, and the extension install from Chrome Store?

**Comment by gempazz** [comment]
Hi I think I got it to work
![image](https://user-images.githubusercontent.com/77121908/109871269-f1c83080-7c62-11eb-92f9-f5d80b29a4e6.png)
I uninstalled and reinstalled the extension and I need to set the Language Tool Kit as Mandarin. 

Thank you very much for your help :)

**Comment by muzuiget** [comment]
What? your first screenshot show you have known how to use.

**Comment by gempazz** [comment]
Oh you are right??? I'm not too sure - I guess uninstalling and re-install somehow works?

**Comment by muzuiget** [comment]
Maybe just network issue, when you try, you forgot to select the "Mandarin" first.
