### ISSUE TITLE
Prime Video 无法翻译

### ISSUE THREAD

**Issue by shayvr** [muzuiget/dualsub-support#217]
近日发现亚马逊的Prime Video 影片无法翻译，只显示原片字幕，没有翻译字幕出现，两个月前是好的；
同一个Chrome浏览器的另一个标签页播放Netflix影片，可以正常翻译。

**Comment by muzuiget** [comment]
是网络卡住了吧，有没有重试过？把翻译引擎换回“谷歌”。

**Comment by shayvr** [comment]
> 是网络卡住了吧，有没有重试过？把翻译引擎换回“谷歌”。

网络正常，已经持续一两周了，换过电脑也是同样状况，翻译引擎是设定为谷歌。

**Comment by muzuiget** [comment]
你意思是一直只有在 Prime Video 无法翻译，在其它网站却行？

**Comment by muzuiget** [comment]
等等，重新看下你的问题，你意思是工具栏菜单没有显示出字幕列表？

**Comment by shayvr** [comment]
> 等等，重新看下你的问题，你意思是工具栏菜单没有显示出字幕列表？

PrimeVideo播放时，工具栏有显示字幕列表，但是没有译文同步出现。

**Comment by muzuiget** [comment]
这还真诡异，能不能发现 DevTools 截图。

打开视频，按 F12 叫出 DevTools 工具，然后选择好字幕，看下 Console 那个页面有没有什么错误输出。

**Comment by muzuiget** [comment]
如果把“机器翻译”和”语言工具“都设置为关闭，字幕能不能正常显示呢？

**Comment by shayvr** [comment]
> 如果把“机器翻译”和”语言工具“都设置为关闭，字幕能不能正常显示呢？

PrimeVideo 原片英文字幕开启，“机器翻译”和”语言工具“都设置为开启或者关闭，屏幕上都只显示原片英文字幕

**Comment by shayvr** [comment]
> 这还真诡异，能不能发现 DevTools 截图。
> 
> 打开视频，按 F12 叫出 DevTools 工具，然后选择好字幕，看下 Console 那个页面有没有什么错误输出。

可以选择字幕，没有错误

**Comment by muzuiget** [comment]
试下 v1.42.0 是否修了。

不过[布局问题](https://www.dualsub.xyz/website-detail.html?id=amazon-prime-video)仍然未解决。

**Comment by shayvr** [comment]
> 试下 v1.42.0 是否修了。
> 
> 不过[布局问题](https://www.dualsub.xyz/website-detail.html?id=amazon-prime-video)仍然未解决。

V1.42.0，Prime Video无法选字幕，只有“关闭”，点不开。看Netflix仍然是正常的

**Comment by muzuiget** [comment]
有没有试过那个改 UserAgent 的方法？
