### ISSUE TITLE
Firefox Update

### ISSUE THREAD

**Issue by mrjamesbos** [muzuiget/dualsub-support#218]
Hi, thanks for adding support for Firefox.

One issue I encountered as soon as I accepted the update - the dropdown options below each video disappeared (see attached for example).

Thanks again for creating this magnificent tool, it has helped me tremendously with my language studies.

![Learn a Language Using Double Subtitles on Firefox](https://user-images.githubusercontent.com/36686580/110295950-d8016180-8045-11eb-97d6-cd8a19cba5e6.jpg)

**Comment by muzuiget** [comment]
The menus have move to the browser toolbar.

![Screenshot_20210308_174752](https://user-images.githubusercontent.com/330812/110304390-84d3e280-8036-11eb-8bb1-79b53bdf034d.png)
