### ISSUE TITLE
希望支持美国的Paramount Plus

### ISSUE THREAD

**Issue by dancwj** [muzuiget/dualsub-support#219]
www.paramountplus.com

**Comment by muzuiget** [comment]
看上去是新上线的网站，但又是要付费才能的看货，连个免费测试的视频都没有，美帝视频网站都喜欢搞这一套。

就等有没有人能分享账号了，具体见 https://www.dualsub.xyz/website-level.html

**Comment by dancwj** [comment]
> 看上去是新上线的网站，但又是要付费才能的看货，连个免费测试的视频都没有，美帝视频网站都喜欢搞这一套。
> 
> 就等有没有人能分享账号了，具体见 https://www.dualsub.xyz/website-level.html

请问你有私人邮箱吗？

**Comment by muzuiget** [comment]
有，muzuiget [at] gmail.com，先发个确认邮件，互相确认后，再发送账号。

**Comment by muzuiget** [comment]
已在 v1.45.0 实现。

**Comment by dancwj** [comment]
> 已在 v1.45.0 实现。

多谢！
