### ISSUE TITLE
不支持移动端浏览器 安装了打不开窗口

### ISSUE THREAD

**Issue by Broma7** [muzuiget/dualsub-support#220]

**Comment by muzuiget** [comment]
你是用 Kiwi 浏览器吧，这个浏览器最新版其实是 Chrome 77 内核，估计不支持某些新的 JavaScript 特性。

现在 Dualsub 支持 Firefox 了，试下用 Firefox 手机版运行 Dualsub 好点，至少 Firefox 第一手支持扩展。
