### ISSUE TITLE
youtube 无法正常使用

### ISSUE THREAD

**Issue by wuliangzhixian** [muzuiget/dualsub-support#221]
youtube 就算打开教程里那个视频 我点击出现的字幕菜单 字幕语言显示为0 机器翻译也是0 我之前是可以正常使用的 想问下咋回事 现在就啥也没有 然后有的时候点还点不出来 什么都没有 感觉像是卡住了

**Comment by muzuiget** [comment]
我重新测试了，目前正常。

一个可能是 YouTube 在改版，对部分用户做 A/B 测试，如果你登录了 YouTube，试下退出账号再试。

**Comment by wuliangzhixian** [comment]
你好 我重新登录了 还是不行 依旧是什么翻译都没有 点击视频的字幕的话是油管自带的那个英文翻译…… 到底咋回事qaq主要是之前用的很好呀 还有别的可以解决的方法吗

**Comment by wuliangzhixian** [comment]
字幕语言选项显示是 0 我重新安装并且重启浏览器 也没啥用

**Comment by muzuiget** [comment]
更新到最新版本，重置扩展设置。

**Comment by muzuiget** [comment]
你怎么安装就怎么更新咯，最新版本是 v1.53.1。

**Comment by wuliangzhixian** [comment]
更新完了依旧是没办法使用 我用的chrome浏览器……怎么办啊啊啊

**Comment by muzuiget** [comment]
请你具体描述情况。

**Comment by wuliangzhixian** [comment]
字幕语言选项显示是 0 字幕翻译那里可以选择语言 但是打开油管播放视频仍然没有出现字幕。 以前是可以正常使用的 软件我也更新到最新了

**Comment by muzuiget** [comment]
贴下视频地址。

**Comment by wuliangzhixian** [comment]
https://www.youtube.com/watch?v=cbH9avLPanU&t=10s&ab_channel=EnglishLessons4U-LearnEnglishwithRonnie%21%5BengVid%5D

**Comment by muzuiget** [comment]
你这个视频我显示正常。

要不你试下退出 YouTube 登录，或者换浏览器试下。

**Comment by muzuiget** [comment]
发现这两天，切换到下一个视频时，确实无法获取字幕列表，只能手动刷新一次，在 v1.53.4 修复了。
