### ISSUE TITLE
突然无法使用。

### ISSUE THREAD

**Issue by jyczf** [muzuiget/dualsub-support#222]
昨天安装了可以正常翻译（除了 Amazon Prime), 但今天突然只能出英文字幕但不能翻译。换了Chrome 和 Edge ，重装是同样的问题。

**Comment by muzuiget** [comment]
看服务器日志，一直都正常，现在呢？

**Comment by jyczf** [comment]
昨天正常了，谢谢。不过Amazon Prime 还是不行。

**Comment by muzuiget** [comment]
Amazon Prime 是已知问题，见 https://www.dualsub.xyz/website-detail.html?id=amazon-prime-video

**Comment by jyczf** [comment]
在 Amazon Prime 下 DUALSUB 的图标是灰的，无法调用。

**Comment by jyczf** [comment]
Amazon Prime 美国的和中国的不一样？用网站上的链接是去的中国目录？

**Comment by muzuiget** [comment]
Prime Video 现在有两个运营网站，一个是 `www.primevideo.com` ，一个是 `www.amazon.com`，如果你的账号是美国账号，会强制将你重定向到 `www.amazon.com`，现在 Dualsub 不支持 `www.amazon.com`，也没声明在这个网站上启用。

见 #194
