### ISSUE TITLE
关于youtube自动字幕断句问题

### ISSUE THREAD

**Issue by Yuelioi** [muzuiget/dualsub-support#224]
大佬你好，我是一个字幕翻译爱好者，youtube下载的CC字幕，处理以后是没有断句的。
一直在研究断句问题，现在也写了很多断句规则进行判断，但是效果没有咱们这插件好
我看到官方文档 dualsub会对断句加以优化
能取取经么？

**Comment by muzuiget** [comment]
就像文档所说，主要按停顿时间判断，至于多长停顿就该断了，还要综合考虑每行字符数长度动态调整，这就很有学问了。

我喜欢用 TED-ed 的视频来调参，毕竟语速合理，还有人工字幕做对照。

**Comment by Yuelioi** [comment]
感谢！:  )
