### ISSUE TITLE
DeepL for translation engine

### ISSUE THREAD

**Issue by ravenCondol** [muzuiget/dualsub-support#226]
No issue, it works great! Was just wondering if https://www.deepl.com/translator could be added to list of engines?

Thank you for wonderful addon!

BTW do you have BTC/ETH address? 👍

**Comment by muzuiget** [comment]
DeepL is a paid service, and the free API from it's homepage also has many restrict, if you [search the GitHub issues](https://github.com/search?p=3&q=DeepL&type=Issues), many projects have disscussion on this topic.

**Comment by ravenCondol** [comment]
Sad, thank you anyways!
