### ISSUE TITLE
高级样式的使用方法

### ISSUE THREAD

**Issue by devinhoshiya** [muzuiget/dualsub-support#227]
对三种动词使用不同的颜色，请问如何设置呢？不知如何修改 - 动词对应的词的颜色。
怎么获取对应动词的词呢
是否需要条件样式，不清楚如何使用
麻烦更新下
高级：组件样式
高级：条件样式
高级：使用示例

非常感谢

**Comment by devinhoshiya** [comment]
自己已经解决，感谢开发的插件

**Comment by muzuiget** [comment]
在“组件样式”里建立三个组件样色，例如 Color1、Color2、Color3，组件类型选择“正文文本”，然后分别设置三种颜色。

然后在“条件样式”里建立三个条件样式，例如 Verb1、Verb2、Verb3，“组件样式”里勾选一个 ColorN，然后“词类”里勾选某个动词。

新建一个主题样式，把三个“条件样式”选上。

在弹出页的字幕菜单，语言工具选择“日语分析”，主题样式里选择刚刚新建的主题样式。

**Comment by devinhoshiya** [comment]
嗯嗯，理解了 条件的意思。希望可以出 字幕下载，想要打印出来，感谢！
