### ISSUE TITLE
国内使用bug

### ISSUE THREAD

**Issue by xuzizhong** [muzuiget/dualsub-support#228]
需要用vpn全局模式  日语分析和翻译才有效  是不是你的网站服务器被墙了啊   官网也是要全局才能打开

**Comment by muzuiget** [comment]
没有吧，我广州电信宽带，和手机的移动信号都能上。

**Comment by xuzizhong** [comment]
湖北移动进不了

**Comment by muzuiget** [comment]
用站长工具测试 https://ping.chinaz.com/www.dualsub.xyz 大部分地区都是通的，没有被墙，所以这个问题只能你自己解决了。
