### ISSUE TITLE
not working on Hulu

### ISSUE THREAD

**Issue by SIMPO18** [muzuiget/dualsub-support#229]
Hulu本身自带English CC，但插件的第一列字幕语言显示为0，没有可供选择的字幕

**Comment by muzuiget** [comment]
手头没有 Hulu 账号测试，你愿意借用一下吗？

**Comment by SIMPO18** [comment]
***@***.***:Allen100

在 2021年3月24日，23:02，muzuiget ***@***.***> 写道：

﻿

手头没有 Hulu 账号测试，你愿意借用一下吗？

**Comment by muzuiget** [comment]
如果你有意分享借用账号，发送邮件 muzuiget [at] gmail.com

**Comment by muzuiget** [comment]
v1.47.0 已发布，修复了 Hulu。
