### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by twtytei** [muzuiget/dualsub-support#232]
能把 https://ed.ted.com/ 也支持进去吗？用的也是youtube

**Comment by muzuiget** [comment]
这种嵌入外部播放器页面是不会支持的了，因为技术上很多难以解决的问题。

扩展除了解析网站字幕数据之外，还得知道当前页面的播放器信息，例如节点位置，这样才能正确把字幕显示在上面，所以所以要求页面要有一些固定“套路”，例如 YouTube 地址 `https://www.youtube.com/watch?v=LaLvVc1sS20`，有 `/watch?v=LaLvVc1sS20` 表示这是一个专门的播放器页面，页面里有一个 HTML 的 `<video>` 节点。

而嵌入外部播放器页面情况复杂，比如可能有多个播放器存在（即使肉眼看上去只显示一个），还有 `<iframe>` 之类跨页面通信问题，无法很好解决，所以最好还是点击一下跳到 YouTube 本身观看。

**Comment by muzuiget** [comment]
这个网站本身自带的播放器倒是可以支持。

**Comment by muzuiget** [comment]
1.47.0 已发布，添加对 TED 自身播放器页面支持。
