### ISSUE TITLE
转换的字幕能以文件形式导出吗？

### ISSUE THREAD

**Issue by finalcreator** [muzuiget/dualsub-support#234]
能把自己设置的字幕以srt导出吗？希望以后能增加这个功能。

**Comment by 01MrHacKeR01** [comment]
> Can I export the subtitles I set in srt? Hope to add this feature in the future.

just download the orginal translation and translate it with google translate

**Comment by muzuiget** [comment]
可以用 https://dualsub-exporter.netlify.app/ 只能合并 YouTube 自身提供的译文字幕。

**Comment by finalcreator** [comment]
> 可以用 https://dualsub-exporter.netlify.app/ 只能合并 YouTube 自身提供的译文字幕。

这个导出来是什么格式的文件呢，貌似不是字幕文件格式。

**Comment by finalcreator** [comment]
> 可以用 https://dualsub-exporter.netlify.app/ 只能合并 YouTube 自身提供的译文字幕。

如果能选择导出srt就好了。

**Comment by muzuiget** [comment]
用其他字幕编辑工具转换一下就好，默认用 ass 是因为可以方便自定义字体，默认输出是一大一小的字体。
