### ISSUE TITLE
无法在Netflix上使用

### ISSUE THREAD

**Issue by Chen19961020** [muzuiget/dualsub-support#236]
2021/03/28 04:00
无法在netflix上使用插件，标准模式为空

**Comment by Chen19961020** [comment]
谷歌浏览器

**Comment by muzuiget** [comment]
我没有账号了，试下这个免费视频 https://www.netflix.com/watch/80094026 正常吗？

**Comment by Chen19961020** [comment]
> 我没有账号了，试一下这个免费视频 [https://www.netflix.com/watch/80094026 ](https://www.netflix.com/watch/80094026)正常吗？

呃...没有效果 进入netflix播放页面，插件点开就只是空的。

**Comment by muzuiget** [comment]
v1.47.0 发布了，更新一下再试试。

**Comment by Chen19961020** [comment]
> v1.47.0发布了，更新一下再试试。

OK!已完美解决，现在一切正常，所有功能均可用，谢谢！
