### ISSUE TITLE
在disney+上使用字幕插件会有延迟

### ISSUE THREAD

**Issue by ieloug1** [muzuiget/dualsub-support#237]
从Disney+网站上下载官方字幕，然后复制到插件里，播放视频时字幕会有延迟

**Comment by muzuiget** [comment]
这是有可能的，如果你仔细对比播放器时间和字幕里的时间轴，如果时间应该是一致的，说明字幕本身就是和画面不同步的。

Disney+ 视频流是 m3u8 格式的，除了字幕信息外，还有片头广告等数据，Dualsub 应该自动做了修正，所以如果你其它工具下载字幕，没做这个处理的话，你要自己同字幕编辑器手动修正，大概3秒钟左右。

**Comment by ieloug1** [comment]
> 这是有可能的，如果你仔细对比播放器时间和字幕里的时间轴，如果时间应该是一致的，说明字幕本身就是和画面不同步的。
> 
> Disney+ 视频流是 m3u8 格式的，除了字幕信息外，还有片头广告等数据，Dualsub 应该自动做了修正，所以如果你其它工具下载字幕，没做这个处理的话，你要自己同字幕编辑器手动修正，大概3秒钟左右。

了解了

**Comment by muzuiget** [comment]
你这是加载人工翻译中文字幕吗？

**Comment by ieloug1** [comment]
> 你这是加载人工翻译中文字幕吗？

是的，我在本地打开人工翻译的中文字幕和从Disney+网站上下载的官方英文字幕，然后比较时间轴，发现基本一致。但是导入到插件后，字幕和视频中的对话至少相差一秒钟以上

**Comment by muzuiget** [comment]
你用什么工具下载的，目前 Disney+ 的字幕都是分成 N 个 webvtt 文件的，十分蛋疼。

**Comment by ieloug1** [comment]
> 你用什么工具下载的，目前 Disney+ 的字幕都是分成 N 个 webvtt 文件的，十分蛋疼。

https://greasyfork.org/en/scripts/404223-disney-subtitles-downloader
一个油猴脚本

**Comment by muzuiget** [comment]
一样的做法，也是解析 m3u8，然后把多个 webvtt 合成一个文件。

**Comment by ieloug1** [comment]
> 一样的做法，也是解析 m3u8，然后把多个 webvtt 合成一个文件。

学习了。您的工具很不错！我还是在其他网站上用吧
