### ISSUE TITLE
在使用Vimium插件下Dualsub无法检测到字幕

### ISSUE THREAD

**Issue by simonwu53** [muzuiget/dualsub-support#238]
关闭Vimium后, Dualsub可以正常显示字幕语言. 

Vimium: 1.66
Dualsub: 1.47.0
系统: Win10/Ubuntu20.04
Chrome: v89

**Comment by muzuiget** [comment]
想不到怎么会有冲突，是哪个网站呢？所有网站，还是个别？

**Comment by simonwu53** [comment]
Sorry 之前的信息有误... 我又试了几遍发现是“Adblock Plus - 免费的广告拦截器”这个插件导致的。开了这个插件Dualsub就不能再在YouTube视频里找到字幕了，禁用拦截广告插件就好了。

有个例外，在同时开启两个插件情况下，如果浏览器设置保存关闭之前的标签页，直接打开浏览器，之前关闭的视频是能看到字幕的。除此之外，有那个去广告插件 Dualsub就搜不到字幕。

**Comment by muzuiget** [comment]
同样想不出为何会有冲突，是无法嗅探到字幕列表，还是选了字幕看不到显示？

建议用 ublock origin，我也是用这个过滤广告，没有问题。

**Comment by simonwu53** [comment]
谢谢推荐插件 Windows下目前没问题了。其他平台不知道什么原因抓不到字幕列表，只有关闭一个选项，插件全关了也不行... 可能因为我在国外网络不太一样？不过Win下能用了 感谢！

**Comment by muzuiget** [comment]
如果在所有网站都不能嗅探到字幕数据，那才可能是和其它扩展有冲突，或者你本地网络有问题。

如果只是某个网站不行，那么可能和你的网络或账号有关，返回该地区或账号专供的代码，而 Dualsub 不能识别。

**Comment by simonwu53** [comment]
更新到1.48.1 字幕抓取和翻译都恢复了
