### ISSUE TITLE
youtube下翻译失效

### ISSUE THREAD

**Issue by zjhxyz** [muzuiget/dualsub-support#239]
版本
1.47.0
不管选择啥语言都是显示原字幕，控制台有如下报错：

Uncaught (in promise) {}
cook | @ | content.js:formatted:1956 | |
-- | -- | -- | -- 
  | async function (async) |  - | -  |  
  | cook | @ | content.js:formatted:1953
  | touch | @ | content.js:formatted:1950
  | initial | @ | content.js:formatted:1944

**Comment by muzuiget** [comment]
看上去就是访问 Dualsub 服务器失败，只能检查你的网络，或者稍后再试。或者用“简单模式”，这会直接用 YouTube 的译文。

**Comment by feipinxiang** [comment]
> 看上去就是访问 Dualsub 服务器失败，只能检查你的网络，或者稍后再试。或者用“简单模式”，这会直接用 YouTube 的译文。

服务器是指 dualsub.xyz 么？ 如果是的话给这个域名加上代理是否会解决有的时候不显示翻译的问题？

**Comment by muzuiget** [comment]
是，但 IP 和域名都没被墙，但是服务器在东京，所以不确定个别地区是否能直接访问。

**Comment by muzuiget** [comment]
扩展用的是 `api.dualsub.xyz` 这个域名。

**Comment by zjhxyz** [comment]
> 看上去就是访问 Dualsub 服务器失败，只能检查你的网络，或者稍后再试。或者用“简单模式”，这会直接用 YouTube 的译文。

```
正在 Ping api.dualsub.xyz [167.179.112.172] 具有 32 字节的数据:
来自 167.179.112.172 的回复: 字节=32 时间=114ms TTL=51
来自 167.179.112.172 的回复: 字节=32 时间=110ms TTL=51
来自 167.179.112.172 的回复: 字节=32 时间=101ms TTL=51
```

https://api.dualsub.xyz/ 访问显示
{"code":0}

网络没有问题，而且我把断句和翻译模式都改成了普通还是一样....

**Comment by muzuiget** [comment]
断句模式在本地处理的，而且只对机器字幕，毕竟机器字幕的时间轴精确到每个单词。

**Comment by zjhxyz** [comment]
> 断句模式在本地处理的，而且只对机器字幕，毕竟机器字幕的时间轴精确到每个单词。

简单模式下面机器翻译列表是空的，只有关闭...

**Comment by muzuiget** [comment]
贴一下视频地址。

**Comment by zjhxyz** [comment]
> 贴一下视频地址。

所有youtube都是这样, netflix是工作正常的

**Comment by muzuiget** [comment]
Netflix 又没有简单模式，还是不清楚到你你什么问题，截个图咯。

**Comment by zjhxyz** [comment]
![image](https://user-images.githubusercontent.com/47225710/113306979-395fdc00-9337-11eb-8273-fd4e692d710c.png)
我的问题是翻译无效，如上图。

你说尝试简单模式，所以下图是简单模式：
![image](https://user-images.githubusercontent.com/47225710/113306927-29e09300-9337-11eb-98b4-85d994dd370a.png)
简单模式这个标签下面机器翻译是空的

抱歉 netflix是我搞错了，netflix只有标准模式，然后也是无效的：
![image](https://user-images.githubusercontent.com/47225710/113307595-e5a1c280-9337-11eb-903d-b109c91c6fe8.png)

**Comment by muzuiget** [comment]
标准模式的翻译，如果网络是通的，试下同步一下系统时间，确保是真实时间。

简单模式那个机器翻译，这可真是诡异了，所有视频都是这样？

**Comment by muzuiget** [comment]
标准模式的翻译，如果网络是通的，试下同步一下系统时间，确保是真实时间。

简单模式那个机器翻译，这可真是诡异了，所有视频都是这样？

**Comment by muzuiget** [comment]
自己试了一下，还真是这样。

**Comment by zjhxyz** [comment]
> 标准模式的翻译，如果网络是通的，试下同步一下系统时间，确保是真实时间。
> 
> 简单模式那个机器翻译，这可真是诡异了，所有视频都是这样？

时间一直都是同步的，刚刚又同步了下没啥用。

对，所有视屏都这样。

很习惯使用这个软件了，自动翻译真的超级棒，之前一直好好的，突然无法工作了，昨天实在忍不住来报告了哈哈

**Comment by muzuiget** [comment]
我明天修复简单模式那个问题。

如果你急着使用，可以用开发者模式安装 v1.46.0 版。

旧版本可以从 Firefox 商店下载 https://addons.mozilla.org/en-US/firefox/addon/dualsub/versions/ Chrome 浏览器也通用的。

**Comment by zjhxyz** [comment]
> 我明天修复简单模式那个问题。
> 
> 如果你急着使用，可以用开发者模式安装 v1.46.0 版。
> 
> 旧版本可以从 Firefox 商店下载 https://addons.mozilla.org/en-US/firefox/addon/dualsub/versions/ Chrome 浏览器也通用的。

老版本解决了👍

另外谢谢，很棒的软件，特别是断句功能。👍

**Comment by muzuiget** [comment]
v1.48.0 已发布，修复了简单模式的机器翻译菜单问题。

**Comment by zjhxyz** [comment]
1.48.0简单模式下翻译列表出现了！谢谢。

今天发现1.46下，标准模式翻译也有失效报“Uncaught (in promise) {}”的情况。
奇怪的是，如果重新加载扩展，会有机率修复（大概50%概率）。

**Comment by muzuiget** [comment]
看上去仍然是网络问题，翻译不成功只能保持显示原文了。

**Comment by muzuiget** [comment]
这两天可能是服务器问题，我检查了运行日志，确实有些翻译请求没正确完成，连接 Google 的服务器超时，刚刚优化了下，看看是否有改善。

如果仍然有问题，试下把翻译引擎换成微软的。

**Comment by zjhxyz** [comment]
试了几天，现在好了，没有问题了，close，赞一个👍
