### ISSUE TITLE
youtube 在自动播放下一个视频的时候字幕不会跟着更新

### ISSUE THREAD

**Issue by feipinxiang** [muzuiget/dualsub-support#240]
在“视频1”播放完毕自动跳转下一个“视频2”的时候有时候字幕仍会是 1的字幕，有的时候刷新页面会更新字幕但也有的时候不会更新。不确定这是youtube的机制问题还是插件加载路径的问题。
Google Chrome版本 89.0.4389.90
Dualsub 1.47.0

**Comment by feipinxiang** [comment]
可能是youtube的问题，因为我按youtube自带的那个“CC”按钮 叠加的字幕也是上一个的

**Comment by muzuiget** [comment]
嗯，这是已知问题，上个版本改成优先使用最后抓取到的字幕数据，出现这种情况就是，当你进入第二个视频页面时，画面数据比字幕数据早完成下载，即视频缓冲完可以播放了，但是字幕数据还未完成下载。

下个版本会优化这个情况，根据视频 ID，先不显示或者新数据到达时自动刷新。

**Comment by muzuiget** [comment]
如果你用“简单模式”，就是会接管原生的渲染功能，所以出现一样的效果。

**Comment by muzuiget** [comment]
v1.48.0 已发布，修复了这个问题。
