### ISSUE TITLE
是否可能实现live caption的翻译?

### ISSUE THREAD

**Issue by RunStar99** [muzuiget/dualsub-support#241]
![image](https://user-images.githubusercontent.com/46420475/113253581-ff231a00-92f7-11eb-8b89-e754765209d2.png)
chrome 89版中新增了live caption功能,可以直接对任意视频音频生成实时字幕, 不知道能不能实现这个live caption的翻译.
Thanks for dualsub, thanks for internet, the world is at our fingertips!

**Comment by muzuiget** [comment]
不行的，Chrome 没有暴露 API 接口出来，拿不到原文的。

也研究过能不能魔改 Chromium 源码，还是一样不行，模型文件属于 Chrome 私有文件(也就是你开启这个功能后下载那堆文件)，自行编译的 Chromium 也用不了。

**Comment by muzuiget** [comment]
而且那个显示文本那个框框也不是个网页，以为着用 `about:inspect` 也不能获取文本，所以无解。

**Comment by muzuiget** [comment]
最离谱是这个功能比 YouTube 自身的机器字幕还好，甚至包括了大小写。

**Comment by RunStar99** [comment]
那看来只能等谷歌逐步开放了, 这个live capiton在安卓上目前也是只支持pixel手机

**Comment by lweo** [comment]
现在有chrome的live caption api接口了。一个利用实例 https://chrome.google.com/webstore/detail/pppkdkcchlonlocoiejjinmkdncfblji

**Comment by muzuiget** [comment]
@lweo 没看懂这个扩展干嘛的。
