### ISSUE TITLE
Amazon Prime not giving option to choose subtitles

### ISSUE THREAD

**Issue by Hebelihii** [muzuiget/dualsub-support#243]
Amazon prime not giving choice to choose any subtitles with chrome. Works for youtube and netflix. Tried Edge and Mozilla with same issue. Tried reinstalling plugin and clearing cookies. Tried resetting settings.

Below screenshot shows I dont have option for selecting language,
![image](https://user-images.githubusercontent.com/81832623/113455602-c11b1880-9413-11eb-98d9-825f10a09e1e.png)

Show I tried to view: The Expanse
OS: Windows 
User agent: Linux 
Browser: Chrome

Below errors from console:
DevTools failed to load SourceMap: Could not load content for http://sourcemaps.aka.amazon.com/1.0.31132.0/sourcemaps/vendors.4269c2fa6c05b90302c3.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for http://sourcemaps.aka.amazon.com/1.0.31132.0/sourcemaps/commons.763c43f6f0308f08aeff.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for http://sourcemaps.aka.amazon.com/1.0.31132.0/sourcemaps/nav.51417228c19542e51bac.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for http://sourcemaps.aka.amazon.com/1.0.31132.0/sourcemaps/payment-state-msg.ccb339d81b501763dc08.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for http://sourcemaps.aka.amazon.com/1.0.31132.0/sourcemaps/detail.8766c8e34a72cefe071b.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for http://sourcemaps.aka.amazon.com/1.0.31132.0/sourcemaps/pangaea-banner.d1238bf77c26fc3ec4ed.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for http://sourcemaps.aka.amazon.com/1.0.31132.0/sourcemaps/cookie-compliance-notification.f34613d69190ebc56008.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for http://sourcemaps.aka.amazon.com/1.0.31132.0/sourcemaps/detail-hover.c0ccd673822e7e21a71c.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for http://sourcemaps.aka.amazon.com/1.0.31132.0/sourcemaps/998.a2b74755a19fc64a8fd0.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED

**Comment by muzuiget** [comment]
v1.48.0 is a big upgrade, I update some lower code related website adapt, because I don't have Prime Video account now, I didn't re-test it, I am not sure it it still works.

**Comment by muzuiget** [comment]
The errors from Console is the website itself errors.

**Comment by Hebelihii** [comment]
> v1.48.0 is a big upgrade, I update some lower code related website adapt, because I don't have Prime Video account now, I didn't re-test it, I am not sure it it still works.

Is there any way to use older version?

**Comment by Hebelihii** [comment]
> > v1.48.0 is a big upgrade, I update some lower code related website adapt, because I don't have Prime Video account now, I didn't re-test it, I am not sure it it still works.
> 
> Is there any way to use older version?

With firefox I was able to try older versions but did not help my issue. Can it be related as Prime video asked me to update my location to Finland?

**Comment by muzuiget** [comment]
Dualsub only has one build file, so all browser use the same build file.

You can download the older version xpi file from Firefox Store, then rename `.xpi` to `.zip`, then extract it then install in with Chrome/Edge Developer Mode.

Maybe v1.47.0/v1.46.0 still works, I am not sure, you tell me if your re-try, then I can rewrite the related code.

Note: #151 still not fixed, but v1.48.0 the lower code(let's call is *framework*) help to fix it. when the framework code is stable, I will finally fix the #151.

**Comment by Hebelihii** [comment]
I tried old versions with your instructions. 1.47 and 1.46 with both Edge and Chrome but unfortunately issue persists. I noticed this error in developer mode:

![image](https://user-images.githubusercontent.com/81832623/113472999-716a3a80-946f-11eb-811b-3edaeff76c4a.png)

**Comment by muzuiget** [comment]
Or try v1.46.0/v1.45.0 ?

**Comment by Hebelihii** [comment]
> Or try v1.46.0/v1.45.0 ?

Any version does not seem to help. Tried these and older ones and they all have the same issue. I dont know is it related to my amazon account region or something.

**Comment by muzuiget** [comment]
That mean it broken on Prime Video for a while.

**Comment by muzuiget** [comment]
This bug fixed in v1.50.2
