### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jvschiavo** [muzuiget/dualsub-support#245]
What is the license of your software?

Sorry, I could not find it anywhere.

**Comment by muzuiget** [comment]
This is private software.

**Comment by jvschiavo** [comment]
Do you have any intentions of making it open-source? It looks like it is a great piece of software! :)

**Comment by muzuiget** [comment]
I don't have plan to open source.

If you just looking similar extension for Dual subtitle for YouTube, there are some open source extensions on GitHub.
