### ISSUE TITLE
Parts of the subtitle missing for long sentences

### ISSUE THREAD

**Issue by b92303008** [muzuiget/dualsub-support#246]
For longer sentences, only parts of the subtitle are shown. For example, for the sentence "The recruit doesn't know because I haven't taught him", the "because I haven't taught him" part is missing. The Chinese subtitle works fine at the same time, though. 

Any help would be appreciated.

**Comment by muzuiget** [comment]
Can you post the video url? Has you try difference translation-engine or translation-mode?

**Comment by muzuiget** [comment]
如果你会中文，我们直接用中文讨论。

**Comment by b92303008** [comment]
您好，感謝您這麼迅速的回覆。

情況如圖，https://imgur.com/GggAlIg ， https://imgur.com/6H9PJjU 。 您提到的引擎和模式都試過了，問題感覺有點像是字幕寬度被限制住，所以被拆成兩句以上。但前半顯示了，而後半卻沒來得及跟上就換下句台詞。

非常感謝您對這個插件的付出以及這次的幫助。

**Comment by muzuiget** [comment]
呃，这好象不是翻译问题，两个语言都是原文字幕吧？

感觉是英文字幕的时间轴有点奇怪，它应该是几句话拆成三个时间轴，类似：

```
00:00.000 --> 10:00.000
AAA

00:00.000 --> 10:00.000
BBB

00:00.000 --> 10:00.000
CCC
```

而不是：

```
00:00.000 --> 10:00.000
AAA
BBB
CCC
```

现在 Dualsub 是假设时间轴没有重叠，只取了第一个符合播放时间的条目。

因为原始的 webvtt 字幕是有位置信息的，这似乎是欧美的习惯，原生渲染效果就是有时字幕位置会靠左或者靠右(贴近说话人的画面位置)，Dualsub 时会忽略掉位置信息的。

看你是看 Netflix，我现在没账号了，可以的话可以把英文字幕另存一份给我？方法是按 F12 打开 DevTools，切换到 Netwoks 标签页，然后用过字幕菜单加载字幕，回到 DevTools，搜索 `.vtt` 就能看到字幕文本内容了。

**Comment by b92303008** [comment]
您好，不好意思這方面我是大外行，按您說的做了幾次還是找不到字幕文本。能否麻煩您截個圖讓我照著做，多謝了。

**Comment by muzuiget** [comment]
首先打开出问题的视频地址，在 Dualsub 菜单关闭所有字幕语言，然后按 F5 刷新一次页面。

然后按 F12，弹出开发者工具 DevTools，如果以右侧边栏面板显示，可以点击右上角的三点按钮，`Dock side` 右边的图标，让它弹出以独立窗口显示。

![Screenshot_20210409_091847](https://user-images.githubusercontent.com/330812/114115751-fc3ab180-9915-11eb-910a-8dc886397163.png)


然后切换到 Network 面板，`Filter` 输入框输入 `resource-type:fetch`。

回到视频窗口，在 Dualsub 菜单里选择英文字幕，并等待字幕显示出来。

回到 DevTools 窗口，列表里应该出现一条记录，选择它，然后右边切换到 `Response` 面板，你会看到字幕数据，也就是有时间轴的文本，然后右键菜单 `Open in new tab`，然后会打开新地址并提示下载了。

![Screenshot_20210409_092832](https://user-images.githubusercontent.com/330812/114115904-4c197880-9916-11eb-9dd3-5ce07d97432b.png)

可以关掉 DevTools 窗口了。

最后把那个文件发送到我邮箱 `muzuiget[at]gmail.com`。

**Comment by muzuiget** [comment]
从收到的字幕文件看，确实是如猜测的时间轴有重叠了：

```
121
00:02:56.927 --> 00:02:59.930 position:34.76%,start align:start size:38.57% line:79.29% 
<c.white><c.mono_sans>Sir, I got lost</c.mono_sans></c.white>

122
00:02:56.927 --> 00:02:59.930 position:23.33%,start align:start size:61.43% line:84.62% 
<c.white><c.mono_sans>on the way to college, sir!</c.mono_sans></c.white>
```

是通过 `position` 来换行的，真是诡异的用法。

下个版本我处理这个问题。

**Comment by muzuiget** [comment]
v1.49.0 已发布，修复了这个问题，试下有没有效果。

**Comment by b92303008** [comment]
您好，上次時間軸重疊的問題似乎解決了，不過好像有新問題出現。嚴格來說，這個新問題其實原本就有，就是節目到最後幾分鐘字幕完全變成另一集或是我根本認不出是哪個節目的字幕。我以為和時間軸重疊是同一個原因，所以上次沒特別提出，但新發修正後問題好像更嚴重了，甚至是剩下三分之一時原先的字幕就結束了，剩下時間完全沒有字幕。我截了目前看來有這問題的兩個節目的圖，也把這兩個節目的字幕檔一併發到您的信箱了。不好意思又給找了麻煩。

https://imgur.com/ieG7AhB
https://imgur.com/lUEMu2V
https://imgur.com/OFw8HZ6
https://imgur.com/8gKJD3V
https://imgur.com/RwQw4Q9
https://imgur.com/vXeSTWm

**Comment by muzuiget** [comment]
已经有人提出了 #247。

**Comment by muzuiget** [comment]
v1.49.1 已发布，修复了那个视频后段使用错误的字幕错误问题。
