### ISSUE TITLE
Netflix 一到 20:00 （20分钟）就会变成不是本集的字幕

### ISSUE THREAD

**Issue by devinhoshiya** [muzuiget/dualsub-support#247]
同时开了 中文字幕和日文字幕，到20分钟就会跳到其他字幕（应该是其他集）
几乎全部视频都是
source:https://www.netflix.com/watch/80196120?trackId=200257859

**Comment by muzuiget** [comment]
是最近出现的吗？还是所有视频都是这样？我是怀疑 Netflix 开启了预读功能，即预读下一集的视频数据。

现在 Dualsub 总是使用最新抓到的字幕数据，也就是 20 分钟时抓取到新的字幕数据，然后加载显示了。解决方法是把视频 ID 判断是否为当前集的字幕。

**Comment by devinhoshiya** [comment]
抱歉，我也是使用没多久，应该是最近的，我看的几乎所有视频都是如此，我留意到都是在 20:00 开始跳，是需要更新版本了吗

**Comment by muzuiget** [comment]
我没有付费账号了，只能用这个[免费纪录片视频](https://www.netflix.com/watch/80094026)测试，但只有一集，无法测试多集连播的情况，你试试这个视频是否也会这样？

**Comment by muzuiget** [comment]
呃，我打开你那个地址，你看得是不是封面的预告短片？即小窗口居中显示那种。

**Comment by muzuiget** [comment]
看上我是我没登录，重定向到封面页了。

**Comment by devinhoshiya** [comment]
我发的链接只是举例有那些视频出现问题而已，我看过很多日本动漫也是一样的问题。

我也看你发的那个链接，我看了前面两集和后面两集，前面的都没有什么问题，在结束 4 分钟前左右，也会出现一样的问题（不是本集的字幕），但是最后一集没有出现字幕不对的问题

我的那个链接最后一集也没有出现问题

如果有需要，我可以提供 Netflix 的帐号

**Comment by muzuiget** [comment]
最后一集没问题，我猜 Netflix 加了预读功能了，这样，我先加上视频 ID 判断，如果不行，再向你要账号测试。

**Comment by muzuiget** [comment]
呃，还是想彻底搞清楚原因，如果你愿意借用账号，请发送到 `muzuiget[at]gmail.com`，谢谢。

**Comment by muzuiget** [comment]
v1.49.1 已发布，修复了这个问题。

**Comment by devinhoshiya** [comment]
感谢，已经没有出现问题了
