### ISSUE TITLE
插件库加载不出来；不支持字幕下载

### ISSUE THREAD

**Issue by GooDong** [muzuiget/dualsub-support#252]
好像原来有一个插件系统库？现在木有了吗。。

另外字幕下载功能，好像也没有。哈哈哈

**Comment by muzuiget** [comment]
什么叫插件系统库？如果你是指加载本地文件字幕，现在是独立“文件”设置页，只是官网文档没更新而已。

字幕下载功能，扩展里一直都没有，只有一个网站 https://dualsub-exporter.netlify.app/

**Comment by muzuiget** [comment]
字幕下载功能见 #253。
