### ISSUE TITLE
关于字幕下载功能

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#253]
好多人提问有没有字幕下载功能，在这个帖子统一回复和讨论。

**目前 Dualsub 是没有字幕下载功能的，最近也没有计划添加这个功能。**

因为我不想 Dualsub 成为一个助长视频盗版的工具，亦即用户仅仅用 Dualsub 来下载字幕，而不在线观看视频。

例如，大家都知道迪士尼的法务部是全球出了名的小器，假如 Dualsub 直接能导出 Disney+ 的字幕，那么迪士尼认为这样做损害的它的利益，轻则让 Google 把我的扩展下架，重则让我吃官司，惹不起惹不起，我不愿意冒这样的风险。

而 YouTube 相当友善，虽然它自己的网站不直接提供字幕下载功能，但它的[开发者 API 有这个接口](https://developers.google.com/youtube/v3/docs/captions/download)，甚至官方文档还[推荐了几个第三方网站](https://support.google.com/youtube/answer/9861599)，所以我们可以假设下载字幕是 YouTube 允许的。当然，视频上传者可以特别声明禁止其它下载他们的字幕，但是这也有商榷的地方，毕竟视频上传者本身就同意了 YouTube 相关协议，第三方网站遵守 YouTube 的协议即可。

所以如果要下载 YouTube 字幕，Dualsub 已经有个配套网站可以使用 https://dualsub-exporter.netlify.app/ 这个网站会在服务器里合并字幕，所以也不能下载 YouTube 那些非公开，或者付费才能看的视频。代码有点陈旧了，是 0.x 版本的产物，功能和算法不同于现在的 1.x 版本。

换句话说，就是 YouTube 和其它视频网站不同，YouTube 是“[用户生成内容](https://zh.wikipedia.org/wiki/%E7%94%A8%E6%88%B7%E7%94%9F%E6%88%90%E5%86%85%E5%AE%B9)”网站，本身就是鼓励分享和传播，观众下载字幕替他们翻译甚至是好事。而 Disney+ 这种“专业制作内容”网站，基本上就是收费的，就是不允许你随意分享和传播的。

当然可能有些人说，下载字幕并不是为了压盗版视频，而是学习外语，制作记忆卡片，背单词用。那这样可以导出一部分不带时间轴的文本，相当于一个“摘抄本”功能，这算是合理使用，这个功能是可以考虑的。

如果你有其它疑问，可以跟帖讨论。

**2021-07-19 更新：**

网站 https://dualsub-exporter.netlify.app/ 已关闭，不再提供字幕下载服务。

**Comment by xiaoxinmiao** [comment]
对于新上传的视频来说，https://dualsub-exporter.netlify.app/ 这个网址也下载不了视频了

我就是为了学习，一个星期前还是可以下载字幕的，但是现在突然下载不了了

youtube：

https://www.youtube.com/watch?v=YE4fOUBXQDE

**Comment by muzuiget** [comment]
我试了下，你那个视频还是能下啊。

**Comment by narulmcto** [comment]
可以更新一下 https://dualsub-exporter.netlify.app/ 的断句算法吗，yotube自带的断句算法太差劲了

**Comment by muzuiget** [comment]
断句只对语音识别的自动字幕有效，因为自动字幕才有每个单词的具体时间信息，这样才能重新断句。但是自动字幕的翻译字幕却不是，所以把原文重新断句后，就和译文完全对应不上。

所以要在这个网站实现扩展的类似功能，只能把前后端都重写了，现在暂时没这个精力。

**Comment by narulmcto** [comment]
> 断句只对语音识别的自动字幕有效，因为自动字幕才有每个单词的具体时间信息，这样才能重新断句。但是自动字幕的翻译字幕却不是，所以把原文重新断句后，就和译文完全对应不上。
> 
> 所以要在这个网站实现扩展的类似功能，只能把前后端都重写了，现在暂时没这个精力。

那么是否能在扩展里加入导入srt字幕功能呢，扩展的断句要比网站好太多了，但是无法导出字幕，目前只能用录屏的方法录下来，对于视频清晰度有损。然后在视频编辑软件里把录屏下来的字幕 裁剪贴到高清源画面上，这样十分耗时

**Comment by muzuiget** [comment]
现在扩展和服务端都是针对在线播放而优化的，所以机器翻译是分段发向服务端处理的，而非一次性翻译全部文本，也就是边播放边翻译，每隔几分钟才发送一次翻译请求。

服务器资源有限，这种优化是必须的。所以如果要把 Dualsub 当字幕下载工具用，亦即短时间内发送多次请求来完成全部文本翻译，会破坏这种”优化“。除非你正常地完整看了一次视频，否则扩展里就没有整个字幕的译文。如果要做导出功能，还得在 UI 方面做个更多设计。

当然如果仅仅是下载 YouTube 的原始字幕文件，网上已经有很多这种的工具，没必要特意做。

**Comment by muzuiget** [comment]
一个想法就是引入用户系统提供付费功能，付费用户可以暂时“越权”一次性翻译全部文本。

**Comment by narulmcto** [comment]
请问，观看一些英语软件教程时，字幕会遮住视频，导致软件细节看不到，有无办法让字幕在视频下方的无视频区域显示？

**Comment by muzuiget** [comment]
现在不是可以拖动字幕位置吗？

**Comment by narulmcto** [comment]
“服务器资源有限，这种优化是必须的。”   这个请问，有没有存在 在播放完一遍视频、浏览器缓存了所有翻译字幕后，导出srt字幕的可能性呢

**Comment by muzuiget** [comment]
理论上可以。

**Comment by narulmcto** [comment]
目前是否有办法修改字幕呢，有些翻译不太正确，我想修改它，然后录下改后的字幕来分给其他学习相关视频的人

**Comment by muzuiget** [comment]
这不就导出一样的需求。

**Comment by L1cardo** [comment]
可以支持safari浏览器嘛

**Comment by muzuiget** [comment]
理论上代码是支持 Safari 的，但是苹果的发布流程实在太折腾，还得专门用 macOS 重新打包和注册开发者账号，懒得折腾。

**Comment by L1cardo** [comment]
@muzuiget 我自己通过苹果官方的方法转换成safari插件了，但是没有显示界面

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/33802186/120729037-c595a780-c510-11eb-8a75-885d4f309815.png">

**Comment by hzc54188** [comment]
哥，Dualsub Exporter 能支持一下油管视频列表吗？一个列表一百多个视频我快被搞死了

**Comment by hzc54188** [comment]
![image](https://user-images.githubusercontent.com/24639554/125164361-68061200-e1c4-11eb-81b5-f6d0f5f165b3.png)

**Comment by muzuiget** [comment]
Dualsub Exporter 已经不打算更新了，凑合用。

**Comment by eAtlantis000** [comment]
可以仅对油管开放简单模式下的字幕下载么？

**Comment by narulmcto** [comment]
邮件已收到，我会尽快查看
