### ISSUE TITLE
youtube無法簡翻中

### ISSUE THREAD

**Issue by ircopdd** [muzuiget/dualsub-support#255]
https://www.youtube.com/watch?v=b-dIvIz8ukE

[zh][zh-hant][][LAST][1]
[zh-hans][zh-hant][][LAST][1]

沒有作用 一樣顯示簡體

**Comment by muzuiget** [comment]
现在语言前缀相同的话，就跳过翻译步骤的了，以防有些用户不主动关闭翻译功能，节省一点服务器资源。如果有需要，下个版本可以加个设置选项是否强制翻译同种语言。

不过中文的简繁转换，我其实想用“语言工具”这个功能来实现，用类似 [OpenCC](https://github.com/BYVoid/OpenCC) 这样的项目，仅仅对汉字转换，这样避免改动非汉字文本，这样看上去“安全”一点。

**Comment by ircopdd** [comment]
麻煩你加入 

不然就沒有翻譯的功能了 謝謝

如果只是對漢字轉換 會有[发 髮] [后 後]之類的錯別字 

希望還是能提供google翻譯選項

**Comment by ircopdd** [comment]
> 现在语言前缀相同的话，就跳过翻译步骤的了，以防有些用户不主动关闭翻译功能，节省一点服务器资源。如果有需要，下个版本可以加个设置选项是否强制翻译同种语言。
> 
> 不过中文的简繁转换，我其实想用“语言工具”这个功能来实现，用类似 [OpenCC](https://github.com/BYVoid/OpenCC) 这样的项目，仅仅对汉字转换，这样避免改动非汉字文本，这样看上去“安全”一点。

麻煩你加入

不然就沒有翻譯的功能了 謝謝

如果只是對漢字轉換 會有[发 髮] [后 後]之類的錯別字

希望還是能提供google翻譯選項

**Comment by muzuiget** [comment]
v1.53.0 已经重新允许翻译同类语言了，没有添加设置选项，就跟之前的一样。
