### ISSUE TITLE
HBOMax全屏后无法显示字幕

### ISSUE THREAD

**Issue by heleny2** [muzuiget/dualsub-support#256]
前两天使用时还一切正常，试了下自带CC和外挂字幕都出现了这个问题

**Comment by muzuiget** [comment]
HBOMax 自己的字幕也是这样吗？

我现在没有账号测试，你愿意借用一会账号测试吗？如果愿意，发送到我的个人邮箱 `muzuiget@gmail.com`。

**Comment by muzuiget** [comment]
已在 v1.52.1 里修复。
