### ISSUE TITLE
在Youtube双字幕一到迷你播放器模式下就失效

### ISSUE THREAD

**Issue by MinecraftTAO** [muzuiget/dualsub-support#258]

**Comment by muzuiget** [comment]
正常， 只支持独立的视频页。其它非视频页都会忽略，非视频页是指搜索页、索引页、封面页等等。

实际上你启用了迷你模式后，地址已经变成 `https://www.youtube.com/` 而不是 `https://www.youtube.com/watch` 了，实际上相当于切换了页面，所以 Dualsub 就停止渲染了。
