### ISSUE TITLE
完全相同的设置，edge的日文分析跟翻译不起作用，chrome正常

### ISSUE THREAD

**Issue by chiljin** [muzuiget/dualsub-support#259]
![微信截图_20210512103008](https://user-images.githubusercontent.com/84056183/117909667-3af4ca80-b30d-11eb-8a16-3428b3950dc7.png)
![微信截图_20210512103057](https://user-images.githubusercontent.com/84056183/117909679-434d0580-b30d-11eb-8de6-4436d22b3572.png)

完全相同的设置，edge的日文分析跟翻译不起作用，chrome正常
https://api.dualsub.xyz/ 这个打开显示{"code":0}
望解答，谢谢！

**Comment by muzuiget** [comment]
Edge 商店审核太慢了，还是旧版本 1.52.1，如果要及时更新，用 Edge 安装 Chrome 商店的版本即可。

**Comment by chiljin** [comment]
> Edge 商店审核太慢了，还是旧版本 1.52.1，如果要及时更新，用 Edge 安装 Chrome 商店的版本即可。

感谢！可以用了！~
