### ISSUE TITLE
疑似新版本导致观看Youtube时出现问题

### ISSUE THREAD

**Issue by Chriszxy007** [muzuiget/dualsub-support#260]
Chrome中从youtube首页点击任意视频，或者点击当前视频的右侧的推荐时并不显示字幕，字幕语言一栏只显示关闭。刷新网页或者将视频用新标签页打开（例如从google搜索里点击视频或者右键选择视频在新标签页中打开链接）才能正常显示字幕，字幕语言一栏也显示正常。已试过关闭其他所有的Chrome插件，问题依旧。（插件版本1.53.4；浏览器版本90.0.4430.212）

Edge则全程没有问题。（插件版本1.52.1；浏览器版本90.0.818.56）

后来我把Edge装上了插件的最新版本（1.53.4），无论是直接从chrome网上应用店里添加还是下载解压后添加，都同样出现了一开始的情况，故怀疑是新版本的问题。

**Comment by muzuiget** [comment]
所以你是 v1.53.3 是正常，反而 v1.53.4 不正常？

应该是 YouTube 在改版了，v1.53.4 刚刚好就是修复你上面说的问题，应该是 YouTube 在 A/B 测试中，新旧版本网站在交替使用了。

**Comment by Chriszxy007** [comment]
原来如此。
感谢回复，期待解决问题的新版本到来。

**Comment by muzuiget** [comment]
发布了 v1.54.0，修复了这个问题，两个情况都兼容了，因为我今天突然也遇到旧版本的情况。

**Comment by Chriszxy007** [comment]
新版本已修复，谢谢。

**Comment by ron159** [comment]
> 发布了 v1.54.0，修复了这个问题，两个情况都兼容了，因为我今天突然也遇到旧版本的情况。

请问Edge插件商店是审核太慢的原因吗？我今天也遇到了相同的问题，找了一圈，然后去谷歌插件安装了最新版本，正常使用了。看了一下edge商店的版本落后一些。

**Comment by muzuiget** [comment]
Chrome 和 Firefox 几乎都是几分钟事，现在 Edge 审核起码花 5 天，而且不能取消当前的审核版本，也就是想再发新版也得等之前的版本审核完成才行，所以发新版我也是等 Chrome 上了过 1-2 天，没人报告严重 bug 再提交 Edge 版，所以 Edge 商店的版本起码落后 Chrome/Firefox 一星期了。
