### ISSUE TITLE
Japanese analysis 功能失效

### ISSUE THREAD

**Issue by jackcao53** [muzuiget/dualsub-support#261]
更新了版本以后，Japanese analysis功能失效了，显示不出来平假名了？而且原来自动翻译是可以的，现在不能用了？只有视频本身有字幕才能调用了？

**Comment by muzuiget** [comment]
新版本把“语言工具”菜单从工具栏弹出页面移除了，节省一点显示空间，移动到了“主题样式”那里（毕竟要样式一起使用才有效）。

你到设置页面的“主题样式”里重新选择一下就 OK，或者干脆重置一下，重新生成的“日语学习”样式默认自动选择的。
