### ISSUE TITLE
有些油管和b站英文视频无法识别

### ISSUE THREAD

**Issue by mc-zheng** [muzuiget/dualsub-support#262]
标准语言中没有选项，只有关闭

**Comment by muzuiget** [comment]
贴一下视频地址。

**Comment by mc-zheng** [comment]
比如， https://www.youtube.com/watch?v=6rhmByxprjA&t=132s  ，  https://www.bilibili.com/video/BV1844y1r7Pi  ，

**Comment by muzuiget** [comment]
这是正常的，本来要网站自己提供字幕才能显示。B站那个，即使它有“字幕”按钮，但是字幕列表是空的。

这种情况你可用 Chrome 的实时字幕功能来显示，当然，这样就没办法机器翻译了。

**Comment by mc-zheng** [comment]
好的，谢谢了，插件帮了大忙
