### ISSUE TITLE
Line spacing for subtitles/word wrap

### ISSUE THREAD

**Issue by jamseong** [muzuiget/dualsub-support#263]
Is there a way to adjust the spacing between multiple language subs and word wrapping?

![image](https://user-images.githubusercontent.com/13956100/120248436-04cfaa00-c22c-11eb-8b45-27b293b5b8ae.png)

**Below is how the subtitle is usually wrapped in Netflix:**
![image](https://user-images.githubusercontent.com/13956100/120248464-1f098800-c22c-11eb-913a-9c0ec73bc550.png)

**Comment by muzuiget** [comment]
You can use custom style, There is a feature call "Plugin" in Dualsub.

Open Dualsub setting page, switch to the "Plugin" tab, add a “style” type plugin, with the code below:

```
.dualsub-renderer {
    max-width: 800px;
    letter-spacing: 1px;
}
```

You can change the `800px` to your prefer width value, the default width is the video width.

The check the "Website" you want to enable this plugin, the reload the video page.

![Screenshot_20210601_113315](https://user-images.githubusercontent.com/330812/120262868-29c82980-c2cd-11eb-9698-64193952d665.png)

**Comment by jamseong** [comment]
The `max-width` works perfectly! For the line spacing I think I worded that incorrectly; I meant the margin in between the two different language subtitles:

![image](https://user-images.githubusercontent.com/13956100/120266487-dca97080-c256-11eb-86e8-891bfa57654a.png)

**Comment by muzuiget** [comment]
How about:

```
.dualsub-renderer {
    max-width: 800px;
}

.dualsub-renderer .subtitles {
    gap: 8px;
}
```

Change the `gap: 8px` for your requirement, by default is `4px`;

**Comment by jamseong** [comment]
That works wonders! Thanks for your speedy responses 👍
