### ISSUE TITLE
Safari的问题

### ISSUE THREAD

**Issue by L1cardo** [muzuiget/dualsub-support#264]
我自己通过苹果官方的方法转换成safari插件了，但是没有显示界面
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/33802186/120729722-751f4980-c512-11eb-9c17-1e7344fce6fb.png">

**Comment by L1cardo** [comment]
通过检查元素发现这个问题，不知道有没有用
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/33802186/120729746-823c3880-c512-11eb-81ea-6d4006366617.png">

**Comment by muzuiget** [comment]
看上去是不支持[解构赋值](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)，但是这个特性 Safari 明明是已经支持的了。

**Comment by L1cardo** [comment]
我不太懂js，也不知道怎么弄

**Comment by muzuiget** [comment]
或者你用右上放那个 `{}` 格式化一下代码，看看是哪一行的报错。

**Comment by L1cardo** [comment]
> 或者你用右上放那个 `{}` 格式化一下代码，看看是哪一行的报错。

点击不了的，可能文件太大了

**Comment by L1cardo** [comment]
通过格式化再编译，我得到了格式化以后的文件，错误提示在这里
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/33802186/120952479-b4050780-c77d-11eb-8b3b-aa33d9a6953d.png">

**Comment by muzuiget** [comment]
看上去是代码压缩之后，语义变了，按照源码，应该是先执行 1122 行部分，然后再执行 1123 行部分，但是 1122 行末尾是个逗号，Safari 先执行了 1123 行部分。

**Comment by muzuiget** [comment]
不过我不打算花时间兼容了，我还是这个观点 #181。

**Comment by L1cardo** [comment]
好的 那我没办法使用了   
打扰了

**Comment by muzuiget** [comment]
装个 Chrome，皆大欢喜。

**Comment by L1cardo** [comment]
> 装个 Chrome，皆大欢喜。

没办法4k是个硬伤。。 
等大厂支持吧

**Comment by muzuiget** [comment]
我决定食言了，见 #268。
