### ISSUE TITLE
突然无法在HBO视频中显示字幕

### ISSUE THREAD

**Issue by Supgb** [muzuiget/dualsub-support#267]
对于有字幕的视频，该插件的subtitle language选项保持为close(0)，无法正确选择存在的字幕。之前一段时间是可以正常使用的，似乎不知道什么原因导致了它无法查找到HBO视频中的字幕。在Youtube上表现正常。

**Comment by muzuiget** [comment]
就是 HBO Max 改版了咯，需要重新适配。

我现在没账号了，如果你愿意借用一下，发送到我邮箱 `muzuiget@gmail.com`。

**Comment by muzuiget** [comment]
v1.60.3 已发布。
