### ISSUE TITLE
支持 iOS 版本的 Safari

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#268]
苹果在 WWDC 2021 [宣布 iOS 版本的 Safari 也支持扩展](https://developer.apple.com/videos/play/wwdc2021/10027)。

对我来说是刚需了，我一直还想魔改 WebView 来曲线实现手机版，这下好了，自带浏览器原生支持扩展，省事不少。

所以桌面版的 Safari 也顺理成章值得去做兼容了。

估计最大的工作量就是专门为手机屏幕适配一个布局界面。

大家有什么建议可以这里讨论。

理论上现在代码应该可以跑在 Safari 15 上了，不过我只有一台 iPhone 8，暂时不想升级到 iOS 15 beta 版，如果有勇士可以自己看[官网文档](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari)，自己打包测试。

**更新  2021-06-30**

* v1.62.0 开始支持 Android 版 Firefox，但是[需要使用 Nightly 版本](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/)运行。

**更新  2021-07-05**

* 兼容桌面版的 Safari 14
* 支持 YouTube 移动版 `https://m.youtube.com/`

**更新 2021-08-27**

*  苹果转死性？[苹果允许部分应用开发者为客户提供无需支付佣金的直接购买方式](https://www.solidot.org/story?sid=68709)。

**更新 2021-09-27**

好消息，开发版本现在已经成功在 Safari 15 上跑起来了，在 macOS/iOS/iPadOS 上都能用。

坏消息是，原来 iPhone 的 Safari 不支持 [FullScreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API#element.requestfullscreen)，现在只有 iPad 支持了。

![Screenshot_20210927_112738](https://user-images.githubusercontent.com/330812/134841319-02cbea4e-3595-4a38-8b17-6419c4883d4d.png)

FullScreen API 即是“全屏 API"，可以让视频播放器全屏时保留 HTML 实现的控制栏、进度条、字幕和弹幕等功能，如果不支持，全屏时则会被强制由系统的播放器接管，类似“画中画”，相当于把视频的投射外部播放器来播放，HTML 实现的东西被留在浏览器里面。

现在只能曲线救国，以“网页全屏”来实现”伪全屏“，“网页全屏”就是让视频刚好填满整个网页（B 站有这个功能，但是 YouTube 没有），如果把浏览器的地址栏隐藏了，那就”全屏“了。

这个问题不解决好，就上架的话，可能会被不明真相的 iPhone 用户喷差评了。

**更新 2021-09-28**

发布版本 `v1.70.0`，这个版本开始兼容 Safari for macOS/iPadOS/iOS。

**更新 2021-10-01**

发布版本 `v1.70.1`，这个版本修复更多 Safari 兼容问题。

解决了上面提到的 iPhone 版本 FullScreen API 问题，对 `m.youtube.com` 添加一个自定义 CSS 样式，让播放器填满整个网页，当向下滚动到某个高度，Safari 的地址栏会自动隐藏，这时播放器刚好和屏幕一样的高宽，实现了“伪全屏”。

所以这个版本能在 iPhone 上愉快地双语字幕了。

**更新 2021-11-13**

在 v1.76.0 下已经[将背景页重写为非持久化模式](https://developer.chrome.com/docs/extensions/mv2/background_pages/)，即 manifest.json 中的 `persistent` 设置为 `false`，这种模式兼容 Safari for iOS 和 Manifest V3 的 API 要求。

这个版本开始算是在 iOS 功能上算是稳定的一版。

**Comment by neweva** [comment]
哈～我還以為現在MacOS已經支持

**Comment by L1cardo** [comment]
可以先看看现在的safari扩展在iOS上是什么样的，然后再根据现有的布局进行调整吧

**Comment by muzuiget** [comment]
当然是先兼容桌面版的。

**Comment by L1cardo** [comment]
> 当然是先兼容桌面版的。

我的意思是，现兼容Mac版本，然后Mac版本直接在iOS Safari上运行看看效果

**Comment by muzuiget** [comment]
兼容流程是：
1：先让代码在 Safari 跑起来，桌面版的 Safari 能跑，理论上 iOS 的 Safari 也能跑了，iOS 也显示宽屏版布局。
2：然后给 iOS 设计一个窄屏版布局。

**Comment by L1cardo** [comment]
https://developer.apple.com/videos/play/wwdc2021/10104/

**Comment by L1cardo** [comment]
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/33802186/124102042-941de680-da92-11eb-8bef-811144a1f067.png">
没想到作者偷偷更新了，还是safari更新了，最新的1.62.0在Safari上运行完美

[Dualsub.zip](https://github.com/muzuiget/dualsub-support/files/6747119/Dualsub.zip)
附上一个我自己打包的app，经过开发者账户签名的

**Comment by muzuiget** [comment]
主要是 #279 的改动，改掉后就跑通了。

我自己也测试目前 v1.62.0 在 Safari 下有几个 bug：

1. 弹出页面是透明背景，问题不大，指定为白色即可。
2. 移动字幕每次拖曳只能移动一点距离，看来对 `drag` 系列事件，各浏览器行为也不一致，不过 Firefox 也不支持拖曳的，所以干脆禁用这个功能。
3. 一些原生 UI 组件有点布局瑕疵，这个不想管了，毕竟 Firefox 89 后也是改用跨平台 UI 组件样式了。

**Comment by muzuiget** [comment]
@L1cardo 你可以自己打包，但是请勿上传到官方 App Store。

**Comment by L1cardo** [comment]
1. 可以根据浏览器的主题颜色来更改背景色，以至于晚上用白色不会亮瞎眼
2. 可以取消drag事件，而用具体的设置来设定位置的数值
3. 目前这个版本具备Safari运行的条件，我使用下来没有什么问题，希望尽快送去Apple审核，我猜审核会花很长时间，可能会涉及到版权问题。

**Comment by muzuiget** [comment]
1. 弹出页也就是几秒钟的事，没必要了。
2. 本来就有，快速设置第一栏，即时生效。如果是 Chrome，手动拖曳一次，这个值会临时失效。
3. 最大问题是，上架 Apple Store，年费 99 刀，所以不是很迫切，等 iOS 15 出来也无妨，毕竟在 macOS 总是能用 Chrome/Firefox 的。

版权我倒不觉得是问题，我连[字幕导出功能都不做](https://github.com/muzuiget/dualsub-support/issues/253)，我看现在 Safari 也是一堆 Youtube/Netflix 增强扩展。

**Comment by wangxin6** [comment]
MacOS Big Sur 11.5.2
Safari 14.1.2 (16611.3.10.0.6)


You can’t open the application “Dualsub” because this application is not supported on this Mac.

> <img alt="image" width="1006" src="https://user-images.githubusercontent.com/33802186/124102042-941de680-da92-11eb-8bef-811144a1f067.png">
> 
> 没想到作者偷偷更新了，还是safari更新了，最新的1.62.0在Safari上运行完美
> [Dualsub.zip](https://github.com/muzuiget/dualsub-support/files/6747119/Dualsub.zip)
> 附上一个我自己打包的app，经过开发者账户签名的

MacOS Big Sur 11.5.2
Safari 14.1.2 (16611.3.10.0.6)

环境下打开app提示出错：

You can’t open the application “Dualsub” because this application is not supported on this Mac.

请问应该如何安装？谢谢

**Comment by muzuiget** [comment]
安装不了的，开发者自签名的程序都是有期限的，只能直接重新编译和签名。

**Comment by wangxin6** [comment]
OK。继续chrome

**Comment by L1cardo** [comment]
百度怎么重签名，命令行签个名就行了

**Comment by dongliang** [comment]
已经支持ios了吗？有人成功吗？成功的发个截图。

**Comment by L1cardo** [comment]
> 已经支持ios了吗？有人成功吗？成功的发个截图。

@dongliang iOS上面各个软件都有客户端，就用客户端看了呀

**Comment by muzuiget** [comment]
更新了 Safari 15 上的支持情况。

**Comment by L1cardo** [comment]
1. 目前的版本在最新的iOS15稳定版上运行还是可以的，只是偶尔会有机会不会处罚该插件，只能重启Safari浏览器来修复。
2. iPhone上面就像作者说的不支持全屏观看视频，而且iPhone上面的设置页面需要对手机屏幕尺寸重新设计，不然会有显示不全。
但是本人还是不建议iPhone上使用本插件，第一是没办法全屏，第二是因为每个视频网站都会有自己app，app的体验会更好
	> FullScreen API 即是“全屏 API"，可以让视频播放器全屏时保留 HTML 实现的控制栏、进度条、字幕和弹幕等功能，如果不支持，全屏时则会被强制由系统的播放器接管，类似“画中画”，相当于把视频的投射外部播放器来播放，HTML 实现的东西被留在浏览器里面。
3. iPad上面的Safari更接近macOS，所以能较好的支持，弹出框和设置页面都能很好的显示
4. macOS更不用说了，是运行这个插件最好的苹果平台了。

各平台的截图如下：

<img width="300" alt="image" src="https://user-images.githubusercontent.com/33802186/134939620-81d9aedf-199f-438a-8920-16992faea572.png">

<img width="800" alt="image" src="https://user-images.githubusercontent.com/33802186/134940850-bf47d9f1-6349-4d46-9d33-06b0cfea0ee9.png">

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/33802186/124102042-941de680-da92-11eb-8bef-811144a1f067.png">

**Comment by L1cardo** [comment]
iOS版本我打包了你们也安装不上，所以自行探索怎么打包安装
macOS版本我打包了一份，通过我自己的开发者账号签名了，也通过了苹果的认证，应该不会出现类似“无法打开”的问题
[Uploading Dualsub.zip…]()
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/33802186/134941283-81a96c5e-eba4-48f7-a3c0-67990c14697e.png">

**Comment by muzuiget** [comment]
> 目前的版本在最新的iOS15稳定版上运行还是可以的，只是偶尔会有机会不会处罚该插件，只能重启Safari浏览器来修复。

"处罚“，这是错别字还是原本意思？这个问题是因为扩展的背景页被定时杀掉了，因为 iOS 不允许 `persistent` 属性。相信你打包时肯定在 `manifest.json` 里改了，要解决这个问题得改一些底层代码，需要一些时间。

> 但是本人还是不建议iPhone上使用本插件，第一是没办法全屏，第二是因为每个视频网站都会有自己app，app的体验会更好

如果单纯看视频，当然是 App 更好，问题是 App 不提供双语字幕啊，所以还得用浏览器扩展，比如 YouTube 的 App 连机器翻译都没有的，但我可以在网页版的的 YouTube 上实现，至少目前，能够在 `m.youtube.com` 上正常使用就够了。

最后干扰点按那个问题，我没遇到，这可是纯粹的 Web Extension，实在想不到哪个地方代码会有和”干扰点按“有关系的东西，要么可能是你打包配置问题。

**Comment by dongliang** [comment]
ipad版本已经上架 appstore 了吗？ 这直接决定我买不买ipad. 我目前的日常使用习惯是在一个6.67寸的安卓手机上用 yandex 浏览器看英文的教学视频

**Comment by L1cardo** [comment]
@muzuiget “触发”，不是“处罚”，打错字了
命令我用的是xcode自动转换的命令，代码没有进行任何更改，出现”干扰点按“问题应该是苹果新系统的安全策略，我之前转换的其他的插件也出现该问题

你可以自行下载试用一下我编译的版本，或者使用最新的xcode自行编译试试

我的环境：
macOS Monterey beta 7
Xcode 13

**Comment by muzuiget** [comment]
@L1cardo 如果你没改掉 `manifeset.json` 那个 `persistent` 属性为 `false`，在 iOS 会被警告不兼容才对，所以不清楚你的 zip 的压缩包从哪里搞来了，我是建议[用 Firefox 的 XPI 文件](https://addons.mozilla.org/en-US/firefox/addon/dualsub/versions/)。

> 你可以自行下载试用一下我编译的版本，或者使用最新的xcode自行编译试试

不好意思，我不会运行陌生人提供的程序，我的确使用最新的 XCode 13 打包，但我的系统是最新的 Big Sur 11.6，没有这个问题。

我这里用“打包”一词，因为确实只是把上传到 Chrome 商店那个 zip 文件用 XCode 转换成 Safari 能安装的文件，而非用手写的源代码“编译”出来。

**Comment by muzuiget** [comment]
@dongliang 上架还早着呢，苹果每年要收上架费 99 美元，即是 688 人民币，每年还得倒贴那么多钱，我就不愿意了。要么就像其它“免费应用“塞广告，要么就对用户收取“安装费”，不想付钱愿意折腾的话，也可以自己用 XCode 打包的。

上架这个话题还得从长考虑，现阶段先把 Safari 兼容搞好。

**Comment by L1cardo** [comment]
1. persistent 属性是要改为 false 啊，不然我怎么运行的iOS版本，这个有什么好纠结的
2. 插件是chrome插件商店直接下载的，任何人都能下载到，什么叫“不清楚你的 zip 的压缩包从哪里搞来了”，你的语气这里就不对
3. 前端哪里有闭源，你的插件上传之前只不过是进行了压缩，没有进行编译，js代码又不会被编译成二进制，能直接看到代码，修改一下岂不是很容易
4. 你的插件出现问题，先不说我这里有没有操作失误，至少不能排除你的插件的问题，我好心给你提供我的环境打包出来的包，供你做排除bug调试用，你又以“不会运行陌生人提供的程序”为由拒绝，搞得我会在程序里植入什么东西一样
5. 你自己不提供macOS的版本，没关系，最初本来就不是针对macOS平台的，可以理解，我辛辛苦苦打包出来供需要的人来使用，你又是这个态度


那不好意思了，我道歉，不应该动你的插件和源码，希望该项目越做越好！

**Comment by muzuiget** [comment]
怎么好好的讨论，突然变得阴阳怪气？

你之前的回复不就是说了 `代码没有进行任何更改`，但是没改怎么能跑起来，Chrome 商店又不提供直接下载 crx 链接，所以我只好怀疑你的 crx 是从第三方下载的，是不是改了什么才有那个问题，正如你所说，前端代码谁都可以修改并重新打包。

这个帖子本来就是记录兼容 Safari 15 的进度情况，并不是我 `你自己不提供macOS的版本`，而是我自行测试好再放出来，”放出来“可能是上架官方商店，或者写一篇 Safari 的打包和安装教程让用户自己操作。

扩展源码本来就很容易被修改，即是第三方出于好意抢先打包，我也不推荐用户使用第三方提供的安装源，不然呢，出问题被骂的是作者。

**Comment by muzuiget** [comment]
再在主帖添加更新信息。

**Comment by wangxin6** [comment]
目前还是需要自行打包？

**Comment by muzuiget** [comment]
对，我还在研究上架方面的东西。

不从 Apple Store 安装，按照那个官网文档用那个 XCode 命令转换一下就行了，可以自己注册开发者账号签名，只不过每 7 天要操作一次。

V2EX 最新讨论 https://www.v2ex.com/t/805383

**Comment by eAtlantis000** [comment]
所以请问一个代码盲如何能完成在iPad上看双语油管视频的操作？个人表示上面唯一看懂的两个字是”打包“

**Comment by muzuiget** [comment]
除了上架官方商店外，没有办法。苹果那些变态的 App 检验机制，即使放出自行打包的安装文件，其它人的手机也安装不了。

最快靓正的方法，买台安卓机，哪怕二手都行，还有真全屏效果。

**Comment by eAtlantis000** [comment]
手机是安卓的，所以可以在上面看油管双语视频了么？求个简易教程

**Comment by muzuiget** [comment]
安卓可以用 Kiwi 浏览器，可以从 Google Play 安装，或者[下载 APK](https://github.com/kiwibrowser/src.next/releases)手动安装（展开那个“Assets”）。

然后像桌面版访问 Dualsub 的 Chrome 商店地址安装了。

**Comment by eAtlantis000** [comment]
@muzuiget 谢谢解惑！

**Comment by mengpeilee** [comment]
<img width="718" alt="截圖 2022-01-28 下午5 33 45" src="https://user-images.githubusercontent.com/16790195/151522615-9750212e-7f7f-4ff0-8556-9a3dddad6e92.png">
在 Mac Safari 上 First Subtitle / Second Subtitle 會顯示亂碼且無法作用，請問該如何解決？

**Comment by muzuiget** [comment]
奇怪，我在 macOS 上没这个问题，在 iOS 倒是出现了，总是出现在第一次安装后，初始化设置数据时。

解决方法，进入扩展设置页面， 点击右上角“重置”链接一下就好了。

**Comment by mengpeilee** [comment]
@muzuiget it works! 謝謝！不過好奇是什麼原因造成在第一次安裝時造成中文亂碼🤣 
我看 HTML header 有放入 UTF8，應該沒問題才對

**Comment by muzuiget** [comment]
@mengpeilee 我也找不到原因，我只在 iOS 上出现这个问题。另一个现象是，在 iOS 安装后，通过系统设置里的 Safari 扩展管理页面，打开 Dualsub 的设置页面，第一次时总是个空白页（通过电脑连接开发者工具，确实打开了个 `about:blank` 页面）。

这似乎就是 iOS 的 bug，写个 hello 级别的扩展就能重现。

**Comment by muzuiget** [comment]
设置页面没有乱码，乱码都是存盘的设置数据，所以我怀疑是 Safari 那个 `storage` API 的序列化包含 Unicode 的字符串的问题，至于怎么第一次才乱码就不得而知了。

**Comment by muzuiget** [comment]
代码早已支持 Safari，但是没打算上架 App Store，此帖关闭。

**Comment by muzuiget** [comment]
@dssbbuh You can pack the exntension file youself https://developer.apple.com/documentation/safariservices/safari_web_extensions

But it is so difficult if you are not a developer.

**Comment by muzuiget** [comment]
The extension file is Chrome/Edge Store's `.crx` or Firefox Store's `.xpi`.

You can get one from <https://addons.mozilla.org/en-US/firefox/addon/dualsub/versions/>, and extract it as zip file.

**Comment by muzuiget** [comment]
Follow this docs <https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari>

Use  command `xcrun safari-web-extension-converter` to convert the extension directory to a XCode project, and build it as an normal App.
