### ISSUE TITLE
Icon does not appear in Firefox toolbar

### ISSUE THREAD

**Issue by SonicAwareness** [muzuiget/dualsub-support#270]
After installing this plugin and visiting a video page (e.g., YouTube), the plugin icon never appears in the Firefox toolbar.

**Comment by muzuiget** [comment]
Are you using Firefox 89？

**Comment by muzuiget** [comment]
v1.60.1 works fine on Firefox 89.

**Comment by hunterlee01123** [comment]
> 
> 
> Are you using Firefox 89？

I have the same problem.FF version 90.0b8(64-bit)

**Comment by muzuiget** [comment]
Please provide more details, screenshot or the DevTools error message.

**Comment by garywill** [comment]
Icon not shown (no erroe message), option page can't open on Firefox 78 

When open option page (Dualsub 1.61.1) :
```
Uncaught TypeError: Intl.DisplayNames is not a constructor
    <anonymous> moz-extension://1a471cd9-8d9d-4fa1-a1e6-e52449846765/options.js:1
    <anonymous> moz-extension://1a471cd9-8d9d-4fa1-a1e6-e52449846765/options.js:1
    <anonymous> moz-extension://1a471cd9-8d9d-4fa1-a1e6-e52449846765/options.js:1
options.js:1:58488
```

1.60.1:
```
Uncaught TypeError: Intl.DisplayNames is not a constructor
    <anonymous> moz-extension://1a471cd9-8d9d-4fa1-a1e6-e52449846765/options.js:1
    <anonymous> moz-extension://1a471cd9-8d9d-4fa1-a1e6-e52449846765/options.js:1
    <anonymous> moz-extension://1a471cd9-8d9d-4fa1-a1e6-e52449846765/options.js:1
options.js:1:58557
```

**Comment by muzuiget** [comment]
@garywill Your Firefox is too old, Dualsub only supports latest stable version browser.
