### ISSUE TITLE
Dual subtitles not working in France

### ISSUE THREAD

**Issue by Jasonario** [muzuiget/dualsub-support#271]
Hey there! I was using Dual Sub regularly to learn french while watching netflix in preparation for me moving there. Well I just arrived in France and realize that Dualsubs no longer works! I don't know if it's related to me being here or not but I can no longer get any subtitlies to show. It just gives me no options for any subtitles. It's not working on any platform now (not youtube and not netflix). Any help would be appreciated! Thank you!

<img width="1758" alt="Screen Shot 2021-06-13 at 2 26 03 AM" src="https://user-images.githubusercontent.com/42015581/121791847-bb4d6a80-cbee-11eb-80cb-5fcada077728.png">

**Comment by muzuiget** [comment]
Can you post the full video url? I guess there is a unknown url format.

**Comment by Jasonario** [comment]
Sure, it's https://www.netflix.com/watch/80187152?trackId=14170287&tctx=3%2C0%2C166fb14e-ac22-43ff-887f-7b2a2bb4f9b6-204911032%2C64a7ebae-dc86-4af8-935a-68d41ff2f175_78622187X3XX1623579192464%2C%2C

**Comment by muzuiget** [comment]
This url actually is handed by Dualsub.

**Comment by muzuiget** [comment]
> It's not working on any platform now (not youtube and not netflix)

Your mean it is also not work on YouTube?

**Comment by Jasonario** [comment]
Correct it's not showing any languages for any platform

**Comment by Jasonario** [comment]
That's why it's weird it USED To work great, and all of a sudden it no longer functions at all

**Comment by muzuiget** [comment]
That is strange, try to uninstall the extension and reinstall from Chrome Store. If it still not works, or try Firefox version.

**Comment by Jasonario** [comment]
Same problem on Firefox. Also I've already uninstalled and reinstalled the plugin twice on chrome
![Uploading Screen Shot 2021-06-13 at 1.24.22 PM.png…]()

**Comment by Jasonario** [comment]
Okay you may find this odd, but it turns out that NONE of the Dual subtitle extensions on chrome were working, not just yours. I actually went ahead and signed up a whole new account on Netflix WHILE HERE IN FRANCE and I guess it registered the Geo for my account. And now it's working. I think Netflix got confused because I'm no longer in the states. Either way, it's working now. Really stupid bug but not your fault. Thanks so much for the brilliant plugin!

**Comment by muzuiget** [comment]
So, it's Netflix region-restriction?

The Dualsub subtitle menus should show the same menu-items as the Netflix native subtitle menus.

**Comment by Jasonario** [comment]
I believe so, after a while it was giving me an error code and not letting me use netflix at all because it thought I was using a VPN (which I'm not). So, I think netflix got really confused with me lol. Regardless, it's solved for now. Thank you!
