### ISSUE TITLE
字幕的选定/拖动功能在youtube上影响了进度条的选中

### ISSUE THREAD

**Issue by sexfio** [muzuiget/dualsub-support#275]
事实上这个功能阻止了选中进度条，导致无法拖动进度条，建议加个字幕选中功能的屏蔽

**Comment by muzuiget** [comment]
因为 Dualsub 会将自己的渲染层放在播放器 HTML 节点的最上层，以优先获得鼠标响应，当然这会遮挡原生播放器的一些交互，比如进度条和菜单。完美的做法就是插在和原生字幕差不多的位置，然而实际上很麻烦，因为也会被原生播放器的代码干扰到。

所以唯一做法就是对某个网站专门写个 CSS 样式，不知道你是哪个网站，如果你确实不需要鼠标交互，你可以建立一个类型为“样式”的插件：

```
.dualsub-renderer {
    pointer-events: none;
}
```

然后在该网站是启用。

这样鼠标交互会“穿透”给原生播放器，当然有可能还是遮挡一部分进度条预览图。
