### ISSUE TITLE
[回報][Issue]官網語言切換異常

### ISSUE THREAD

**Issue by CrazyLayKer** [muzuiget/dualsub-support#277]
切換語言後不分中英皆顯示Page Not Found。

**Comment by muzuiget** [comment]
好像只是首页才出现这个问题，你点上方的“文档”再切换就可以了。

或者你先看旧版本 https://dualsub.netlify.app/

**Comment by muzuiget** [comment]
发现文档系统的官网 https://docusaurus.io/  自己也出现这个问题，它最近发布重写的 v2 版本，仍然在 beta 版本。

**Comment by muzuiget** [comment]
已经修复。
