### ISSUE TITLE
关于Google无障碍设置中实时字幕问题！

### ISSUE THREAD

**Issue by lewoer** [muzuiget/dualsub-support#278]
1.  Google浏览器在设置中有实时字幕功能，目前只是针对英文，dualsub这个插件能够提取这个字幕内容进行翻译吗？虽然不知道这个功能能否实现，是否有什么限制条件，但是感觉实现后好多视频都能无障碍观看了。

**Comment by muzuiget** [comment]
见 #241

**Comment by lewoer** [comment]
看到了，那就只能看英文字幕了，虽然有时候累点。
