### ISSUE TITLE
不是兼容安卓版火狐么？老版和新版都不能用

### ISSUE THREAD

**Issue by Broma7** [muzuiget/dualsub-support#280]

**Comment by muzuiget** [comment]
怎么不能用请具体说明。

至少我用 Firefox 89 打开 `https://www.youtube.com/` 是可以的，也即是需要设置浏览器为桌面版。

YouTube 的手机版 `https://m.youtube.com/`，这个网址适配仍然在开发中。

**Comment by muzuiget** [comment]
有图有真相。

![1](https://user-images.githubusercontent.com/330812/124223421-4490f680-db36-11eb-85d3-f135656db6e0.png)

**Comment by Broma7** [comment]
可以了 谢谢

**Comment by muzuiget** [comment]
v1.63.0 已支持 https://m.youtube.com/
