### ISSUE TITLE
导入字幕的功能是不是取消了？

### ISSUE THREAD

**Issue by 9Panda3** [muzuiget/dualsub-support#281]
![image](https://user-images.githubusercontent.com/61393145/124306676-4d66e400-db99-11eb-82b0-5f930daa874b.png)
之前在类型这里可以选择上传的字幕格式，现在没有了不知道是取消了还是改变位置了，看了使用文档也没找着说明。

**Comment by muzuiget** [comment]
就是顶部的“文件”。

**Comment by muzuiget** [comment]
格式不用选择了，自动检测，只是要选择语言。

**Comment by 9Panda3** [comment]
好的，感谢告知。
