### ISSUE TITLE
突然之间YTB不能翻译中文了

### ISSUE THREAD

**Issue by xibaibai9527** [muzuiget/dualsub-support#282]
我很确定刚安装的时候是可以的，看了一个视频，再看第二个的时候就不行了，只显示两排英文
曾经以为是服务器问题，切换到微软翻译也是一样，放了两天再看，还是不能翻译

用的是edge 90.0.818.56，插件版本1.62.1
![截图04](https://user-images.githubusercontent.com/19858971/124384623-ca629c80-dd04-11eb-83ed-039a3541fa6e.jpg)

**Comment by muzuiget** [comment]
所有视频都是这样？

有没有试过卸载然后重装？

**Comment by muzuiget** [comment]
有点奇怪为什么你的弹出页面会出现横向滚动条。

**Comment by muzuiget** [comment]
确认下你是否能访问 https://api.dualsub.xyz/

**Comment by xibaibai9527** [comment]
好了，我访问了一下上面的网站，然后再加入到代理白名单，再打开ytb就可以上了……
看来是网络问题。

横向条应该是缩放问题吧，我win7系统DPI缩放125%，浏览器自动调整到125%，刚才我试了一下改成浏览器100%，横向条就没了
很多pc上的早古软件不适配dpi缩放都有这个问题，我都已经习惯了

**Comment by muzuiget** [comment]
那个地址并没有被墙吧。

**Comment by xibaibai9527** [comment]
dualsub.xyz全部被墙了，移动网

**Comment by muzuiget** [comment]
![Screenshot_20210705_235643](https://user-images.githubusercontent.com/330812/124496912-abd7d080-ddec-11eb-980d-64a8c5b10cc7.png)

应该只是你本地移动问题，爱莫能助。
