### ISSUE TITLE
Firefox 兼容有问题 不显示字幕选择

### ISSUE THREAD

**Issue by LM-Firefly** [muzuiget/dualsub-support#283]
![图片](https://user-images.githubusercontent.com/20715220/124463991-36f1a000-ddc6-11eb-99cd-be4cc6f03699.png)

**Comment by muzuiget** [comment]
这种情况两种原因：

1. 没有权限访问当前网址。
2. 你点得太早，当前网页还在加载。

**Comment by LM-Firefly** [comment]
> 
> 
> 这种情况两种原因：
> 
>     1. 没有权限访问当前网址。
> 
>     2. 你点得太早，当前网页还在加载。

就是Netflix 一直是这样
![图片](https://user-images.githubusercontent.com/20715220/124525041-3392fe80-de30-11eb-864e-e700eea53d64.png)

**Comment by muzuiget** [comment]
YouTube 会这样吗？试下重置扩展设置。

**Comment by LM-Firefly** [comment]
> 
> 
> YouTube 会这样吗？试下重置扩展设置。

也是这样 重置了 也没用
![图片](https://user-images.githubusercontent.com/20715220/124567373-855e7780-de76-11eb-89fd-15f2b223db59.png)

**Comment by muzuiget** [comment]
那么按一下 F12 调出开发者控制台，看看是否有错误输出。

**Comment by LM-Firefly** [comment]
> 
> 
> 那么按一下 F12 调出开发者控制台，看看是否有错误输出。

没看到有错误 
![图片](https://user-images.githubusercontent.com/20715220/124734318-92976700-df47-11eb-91b9-a6a83870dc82.png)

**Comment by muzuiget** [comment]
还是重现不了。

有没有试过卸载重装扩展，已经使用最新稳定版的 Firefox？
