### ISSUE TITLE
希望能支持discovery plus网站

### ISSUE THREAD

**Issue by xinli6** [muzuiget/dualsub-support#284]
网站：discoveryplus.com
维基：
[Discovery+ - Wikipedia
https://en.wikipedia.org › wiki › Discovery+](https://en.wikipedia.org/wiki/Discovery%2B)
测试视频：可以提供账号密码。

**Comment by muzuiget** [comment]
好的谢谢，麻烦发送到我个人邮箱 `muzuiget [at] gmail.com`.

**Comment by xinli6** [comment]
***@***.***

Jab716ko

谢谢，需要美国节点才能登录网页。

muzuiget ***@***.***>于2021年7月5日 周一下午11:48写道：

**Comment by xinli6** [comment]
已发，请查收。谢谢

**Comment by muzuiget** [comment]
无法支持，原因：此网站不提供独立的字幕文件，字幕数据是嵌入到每个分片视频中的。
