### ISSUE TITLE
字母突然变得很小

### ISSUE THREAD

**Issue by 604649280** [muzuiget/dualsub-support#285]
![微信截图_20210705121838](https://user-images.githubusercontent.com/80362736/124498944-312a9900-dd8b-11eb-83a0-239f5c2b606b.png)

**Comment by muzuiget** [comment]
v1.63.0 把样式的字体大小单位从像素改成了百分比，如果你一直使用默认生成的样式，重置一下就好了，或者手动改一下。

* 大号字体 `42px -> 110%`
* 小号字体 `32px -> 90%`
