### ISSUE TITLE
Text Size?

### ISSUE THREAD

**Issue by AYMENJD** [muzuiget/dualsub-support#286]
how i can change the size of the text ?

**Comment by muzuiget** [comment]
There a few ways, it depends your requirements.

* If you know what is CSS, you can add a type "script" plugin in the setting page.
* If you don't know what is CSS, read [this docs](https://www.dualsub.xyz/docs/styles-guide), there is a GUI editor for you.

**Comment by muzuiget** [comment]
Please read the [Quick Start](https://www.dualsub.xyz/docs/quickstart) first.

**Comment by weiyuchou** [comment]
Was the extension setting page removed? Can't find it

**Comment by muzuiget** [comment]
@weiyuchou which setting page?
