### ISSUE TITLE
不支持快捷键了吗？

### ISSUE THREAD

**Issue by yuzlxt** [muzuiget/dualsub-support#288]

**Comment by yuzlxt** [comment]
之前可以设置快捷键切换字幕显示隐藏的，我觉得很好用啊，为什么没有了？

**Comment by muzuiget** [comment]
因为我自己几乎不使用，维护起来很麻烦，要让设置即时生效，需要太多代码处理状态。

这种小众需求完全可以写一段小脚本实现：

```
document.addEventListener('keydown', (event) => {
    if (event.altKey && event.key === 's') {
        const node = document.querySelector('.dualsub-renderer');
        node.style.display = '';
        return;
    }
    if (event.altKey && event.key === 'h') {
        const node = document.querySelector('.dualsub-renderer');
        node.style.display = 'none';
        return;
    }
    if (event.altKey && event.key === 't') {
        const node = document.querySelector('.dualsub-renderer');
        node.style.display = node.style.display === '' ? 'none' : '';
        return;
    }
});
```

创建一个脚本类型的“插件”粘贴上面代码即可，当然你用油猴也可以。

用脚本反而更加灵活，没 GUI 界面对普通用户不怎么友好就是。

**Comment by yuzlxt** [comment]
哈哈！好了。谢谢作者大大！
我之前设置的是ctrl+/切换字幕，我感觉显示和隐藏快捷键没什么必要，直接一个快捷键切换显示隐藏就好了。
其实我并不懂JS，所以想设置成ctrl+/有点懵逼。(我用的暴力猴，当然都一样。我之前甚至不清楚里面的脚本用的是什么语言。)
不过我自己研究了一下，查了查资料，弄好了。开心。
再次谢谢作者大大！
这是我改的脚本，去掉了单独显示和隐藏的快捷键，只保留了切换快捷键。希望能帮助其他需要的人。
document.addEventListener
('keydown', (event) => 
{
    if (event.ctrlKey && event.key === '/')
    {
        const node = document.querySelector('.dualsub-renderer');
        node.style.display = node.style.display === '' ? 'none' : '';
        return;
    }
}
);

**Comment by yuzlxt** [comment]
![图片_1](https://user-images.githubusercontent.com/42287503/124910399-2176b300-e01e-11eb-8b68-703a2d2e5fa6.Png)
