### ISSUE TITLE
希望可以支持 CW Seed

### ISSUE THREAD

**Issue by LM-Firefly** [muzuiget/dualsub-support#289]
网站：cwseed.com
维基百科 : [CW电视网](https://zh.wikipedia.org/wiki/CW%E9%9B%BB%E8%A6%96%E7%B6%B2)
测试视频：https://www.cwseed.com/shows/forever/pilot/?play=1ef0d762-bc9e-4a1f-95b4-0678897d759f
网站免费的 不需要账号

**Comment by muzuiget** [comment]
![Screenshot_20210709_210744](https://user-images.githubusercontent.com/330812/125082395-c0bca880-e0f9-11eb-8880-d4452e5c8a3e.png)

通过 `iframe` 标签实现的播放器，实际地址其实是 `https://player.theplatform.com/` 就像第三方网址嵌入 YouTube 视频一样。

要支持得涉及相当复杂的跨页面通信，以及扩展权限申请问题，之前放弃支持 https://www.funimation.com/ 和 https://www.crunchyroll.com/ 也是这个原因，不需支持这种网站，可以减少一大堆代码。

https://www.cwtv.com/ 之前我也分析过了，跟 https://www.cwseed.com/ 一样的。

一个做法是专门弄个 iframe 特别版，仅支持这种“守旧派”网站。

**Comment by dongliang** [comment]
期待 iframe 特别版 兼容更多的网站
