### ISSUE TITLE
希望可以支持在线教育网站 edx.org

### ISSUE THREAD

**Issue by xibaibai9527** [muzuiget/dualsub-support#290]
这里的哈佛，MIT等顶级高校开的课程是真的好，比国内的强太多了，我学计算机很多人推荐我来这里注册个账号，唯一的问题就是语言障碍，幸好这个扩展解决了翻译问题。
https://www.edx.org/

这个网站的课程随意下载，还提供视频地址和字幕，youtube和b站都能找到下载，
但是这里的节奏和大学是同步的，一般每年九月就更新新的课程视频和作业，各大视频网站找到的都有些过时了。（主要是作业和视频不配套，就比较麻烦）

注册账号后随便选择一门课，按下enroll now的红色按钮登记，就能点开课程查看视频了，大部分都自带官方英文字幕
![截图14](https://user-images.githubusercontent.com/19858971/125160000-48afba80-e1ad-11eb-8eb1-46ee53f1ff91.jpg)

MIT的这门python入门实在是讲的太棒了，以下是课程地址
https://learning.edx.org/course/course-v1:MITx+6.00.1x+2T2021/block-v1:MITx+6.00.1x+2T2021+type@sequential+block@c81c3de20ec54c37a04a8b3d1806e82c/block-v1:MITx+6.00.1x+2T2021+type@vertical+block@15e84e85efa14f5caea081e22ec8ec54

希望能支持，拜谢

**Comment by muzuiget** [comment]
很遗憾，一样使用 `iframe` 做法的网站，兼容起来极度麻烦，见这个链接 https://github.com/muzuiget/dualsub-support/issues/289#issuecomment-877186464

**Comment by xibaibai9527** [comment]
那太遗憾了，这么好的网站 :(
不过，这个网站提供了MP4文件和字幕的下载，我看扩展里有个功能叫做“文件”，是否是把本地字幕用软件合并翻译后再输出的意思？这样也能间接使用了，但我没找到输出的地方呢？

**Comment by muzuiget** [comment]
获取字幕文本不是问题，edx 直接显示 srt 文件链接给你下载，甚至 mp4 文件也给你下载，主要是整合在 edx 的播放器上显示问题。

设置 “文件” 是让你加载本地硬盘上的字幕，勾选了下方网站单选框后，会在该网站的“字幕语言“菜单里显示。

正如我 https://github.com/muzuiget/dualsub-support/issues/289#issuecomment-877186464 里说一样，只能专门做个 iframe 特供版，一套代码要同时兼容两种技术方案实在困难。

**Comment by xibaibai9527** [comment]
我明白了，叹气，谢谢

**Comment by muzuiget** [comment]
Won't fix, see #414
