### ISSUE TITLE
按照字幕时间轴快进快退

### ISSUE THREAD

**Issue by ficapy** [muzuiget/dualsub-support#291]
为了方便练习听力，希望能实现shift + 左/右 按照字幕时间轴快进或者快退到句子开头

**Comment by muzuiget** [comment]
要支持全部网站，一时之间实现不了，要单独对每个网站做适配，还要做一个字幕数据浏览面板才行。

如果是 YouTube 可以先用它的解说词功能。

**Comment by ficapy** [comment]
哈哈，确实，工作量有点大，希望作者早日走上商业化，到时候就能有更多精力优化了

**Comment by muzuiget** [comment]
所以你是有意支持付费功能吗？

**Comment by ficapy** [comment]
> 所以你是有意支持付费功能吗？

良好的商业化会让开发者花费更多的精力改善作品，提供更好的服务，作者可以考虑面向全球用户开发，做得好，有价值总有人愿意付费的。我现在每年软件支出大概3000-4000.

**Comment by ficapy** [comment]
这两个面向外语学习的，都是月付三刀
https://forum.languagelearningwithnetflix.com/
https://appforlanguage.com/

**Comment by muzuiget** [comment]
我的确有收费的想法，即使扩展客户端免费，每个月还得出服务器费用，用爱发电难以长久。
