### ISSUE TITLE
报告bug

### ISSUE THREAD

**Issue by sexfio** [muzuiget/dualsub-support#293]
youtube 页面切换出去再切换回来有时候会不翻译
还有时候打开的时候就不翻译，刷新几次才翻译，都是在youtube

**Comment by muzuiget** [comment]
如果这只是最近 12 小时内发生，多半是服务器问题，因为服务器的主机提供商自己在抽风。

![Screenshot_20210714_015022](https://user-images.githubusercontent.com/330812/125559215-fad13da6-c27d-4902-b113-e73d99d8b8a9.png)

**Comment by muzuiget** [comment]
现在还在抽 https://status.vultr.com/，Silicon Valley 节点。

**Comment by sexfio** [comment]
![image](https://user-images.githubusercontent.com/15652960/126104718-a46bc7af-4a67-4a4e-b1a4-7347ed9658e7.png)

**Comment by muzuiget** [comment]
这不是很明显一个网址，见 https://github.com/muzuiget/dualsub-support/issues/297
