### ISSUE TITLE
为什么不能拖拽调整字幕位置了呢？

### ISSUE THREAD

**Issue by handsomeli0** [muzuiget/dualsub-support#294]
我记得前天还可以呢，今天突然发现拽不了字幕了，咋回事？

**Comment by muzuiget** [comment]
最近版本删除了这个功能。

其中以一个原因，兼容性问题，拖曳代码在各浏览器实现行为不一致，只能在 Chrome 有效，Firefox 和 Safari 都不行，需要更多精力和代码去做兼容。

根本原因，现在要适应众多网站，全屏/非全屏布局，还支持手机浏览器，还要考虑竖屏/宽屏等等，更希望是自动适应字体大小和底边距。“允许用户拖曳”和“自动适应布局”相冲突。原来的做法是如果拖曳过了，就让“自动适应布局”失效，维护起来比较麻烦。

替代方法：

1. 使用“快速设置“的”底部边距“调整相对高度。
2. 使用 Dualsub 的”插件“功能，执行一段 JS 脚本实现，比如可以使第三方的拖曳库。

**Comment by muzuiget** [comment]
要不就回到问题原点，为什么需要拖曳？是因为遮挡了视频画面，还是原生菜单，需要暂时移开一下。

**Comment by handsomeli0** [comment]
确实是因为有时候字幕遮挡视频画面，需要暂时移开一下

**Comment by handsomeli0** [comment]
确实是因为有时候字幕遮挡视频画面，需要暂时移开一下

**Comment by muzuiget** [comment]
或者你可以用快捷键将它暂时隐藏 #288。
