### ISSUE TITLE
收费计划

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#295]
这篇帖子讨论 Dualsub 的收费计划，内容可能会随时更新。

## 为什么

Dualsub 的第一个公开版本发布在 2018-09-17，到现在差不多 3 年了，从简单的双语字幕功能，进化到现在众多字幕功能，我花费了大量精力在上面，一直都是靠爱发电，完全免费。为了后续开发维护，我希望能回回血，所以考虑收费。

## 收费功能

目前对服务端功能收费，即 Dualsub API 服务器 `api.dualsub.xyz`。

标准模式下的机器翻译、中文分析、日文分析功能依赖服务端，如果你使用这些功能，某些情况下要付费。

如果不想付费，你可以仅使用客户端的功能。

提示：对于 YouTube，简单模式的机器翻译会使用 YouTube 的译文数据，不依赖服务端。

## 计费方案

使用按流量计费策略，具体请阅读[如何计算流量消耗](https://www.dualsub.xyz/zh/docs/how-is-traffic-calculated)。

在 v1.65.0 开始，你会在设置页面里的“网络”面板看到相关信息。

## 账号系统

账号是一个随机字符串，用途类似**超市的不记名购物卡**，流量额度用完即弃，这意味没有挂失、也没有充值。

账号可能通过邮箱接收，但邮箱只用作联系方式，并不能假定邮箱拥有者会使用这个账号。

例如，一个邮箱接收多个账号，同一个也账号可以给不同的人或设备同时使用。

## 购买方式

基准价格按每千字符数和人民币比例计算。

如果支付宝或者微信直接转账人民币，按基准价格收费。

如果是其它支付平台，算上抽成、汇率和手续费，会比基准价格贵。

初步考虑支付平台：

* [PayPal](https://www.paypal.com)
* [Stripe](https://stripe.com/)

## 免费额度

有，提供免费额度可以让用户评估付费功能。

但付费用户也一样享受免费额度，实扣额度是减去免费额度。

## 测试计划

接入支付平台需要时间，计费和账号系统也需要测试，大概分几个阶段：

| 阶段 | 服务端       | 用户                 | 开始时间   |
| ---- | ------       | ----                 | ----       |
| 1    | 高免费额度   | 免费获得测试账号     | 2021-07-16 |
| 2    | 高免费额度   | 低价格购买测试账号   | 未确定     |
| 3    | 正常免费额度 | 正常价格购买正式账号 | 未确定     |

## 常见问题

**为什么账号使用随机字符串**

两个好处，一是计费系统实现简单，毕竟只需要关心剩余额度就够了， 不需要搞邮箱验证，密码找回这些功能。二是保障隐私，表明不会特意跟踪用户，我可以以任何方法把随机生成的账号发放出去就行了，邮箱也不是必需的。

**为什么支付宝和微信要直接转账**

老掉牙的问题了，中国大陆几乎所有支付渠道对个人开发者不友好，需要公司资格和签约，注册公司也有额外成本，无数第三方免签方法神鬼乱舞。

现阶段最简单的方法还是直接转账，就街边小贩一样，只要你信任对方就行，还怕我跑了不成。

最大的问题就是无法即时自动发送账号，得我专门找个时间来操作。

**Comment by wangxin6** [comment]
不用中文分析和日文分析，定价会与全功能一致么？

**Comment by muzuiget** [comment]
这两个功能我打算免费了，反正用得人不多，而且基于开源的方案。

目前只有翻译打算收费。

**Comment by muzuiget** [comment]
我觉得要措辞要严谨点：所有服务端功能都是收费，只是中文分析和日文分析属于当前的免费额度里。

**Comment by eAtlantis000** [comment]
所以支付宝咋付费？没搞懂

**Comment by muzuiget** [comment]
@eAtlantis000 直接转账。

**Comment by wangxin6** [comment]
1.价格和其他翻译软件比呢？百度，有道，deepl等。
2.多种定价方式。字数（1w，10w，100w），时间（包月，包年，买断）

**Comment by muzuiget** [comment]
价格明天发文档，因为要算上免费额度。

目前只能说比百度，有道这些贵一点，毕竟我也不是做个代理纯转发翻译流量，这个价格除了上游翻译商 API 价格外，还应该包含我过去到现在所有的工作量。

按流量计费，没有包时，毕竟随机匿名账号，解决不了共享问题。

**Comment by wangxin6** [comment]
"还应该包含我过去到现在所有的工作量。" - 付费方为过去的白嫖用户承担费用？

**Comment by muzuiget** [comment]
收费只是从现在开始，没有谁欠谁的说法。

那句话只是表示“不要直接和上游翻译商的价格比”，这就像去餐厅食饭只算原材料费用觉得贵，而不算餐厅自身的成本。

**Comment by wangxin6** [comment]
理解并支持作者的收费计划。

希望可以出包月卡或者包年卡

**Comment by weirhjaklweh** [comment]
白嫖两年了，支持收费，就怕突然消失了

**Comment by haihuche** [comment]
是不是开始收费了？YouTube翻译不行了https:/ww.dualsub.xyz/errors/no-quota≥ 是收费不能翻译的意思？

**Comment by muzuiget** [comment]
你打开那个网址，就会跳到 https://github.com/muzuiget/dualsub-support/issues/297

**Comment by 9Panda3** [comment]
如果是收费，希望可以有更多翻译引擎可供用户自行选择配合使用（填入自己申请的api），Google的体验还是不太好，目前大部分的翻译引擎api都有免费的计划，如彩云（个人感觉体验最好），百度，有道等。

**Comment by muzuiget** [comment]
不好意思，使用自己申请的 API 功能是不会有的。

我相信不少人也有这个想法，我这里统一说下理由：

大多数人都不知道什么叫 API，如何申请，国内服务商还诸多注册要求，让用户为一个功能付两次钱，这就劝退了一大堆用户了。

技术上哪怕我愿意做这种功能，得在客户端专门给这些服务商分别做适配，工作量也不少了，也把扩展权限弄复杂了。而用我自己的服务器转发，一切容易调试，也随时可以更新修复问题。

最重要的一点，Dualsub 服务端并不是简单转发翻译文本做中间商赚差价，正如这篇[优化 YouTube 翻译](https://www.dualsub.xyz/zh/docs/improve-youtube-translation)文章所说，Dualsub 服务端自己实现一套方法解决“因为断句而丢失上下文”的问题，比如翻译 YouTube 机器字幕，除了文本外，还得一些关键时间轴数据传给服务器，以辅助提高翻译准确度。

当然，可能有的用户处于隐私需求，不想把翻译文本传给我这种陌生开发者的服务器，但我觉得这目前也不是什么问题，Dualsub 就支持加载本地字幕的，用户总是可以用第三方工具下载字幕文件，然后用第三方工具翻译字幕文件，然后再用 Dualsub 加载显示。

**Comment by TobySkarting** [comment]
> Dualsub 服务端自己实现一套方法解决“因为断句而丢失上下文”的问题

真的好用，是普通機翻不能比的：

![msedge_4Q08GVMNak](https://user-images.githubusercontent.com/9109405/126318052-562e0e4c-f842-4fa0-b4f9-ebad3667bc8d.jpg)
![msedge_mQ00wE1QSM](https://user-images.githubusercontent.com/9109405/126318057-1f636f1f-28c0-47c7-9740-8d10d8275fcd.jpg)
![msedge_wnTF4X9VFF](https://user-images.githubusercontent.com/9109405/126318063-3e673464-20e1-4f76-b9de-d7852fc1c302.jpg)

**Comment by muzuiget** [comment]
主帖更新：添加了文档链接[如何计算流量消耗](https://www.dualsub.xyz/zh/docs/how-is-traffic-calculated)。

**Comment by Aircloud2021** [comment]
兄弟你好，这个插件很好用，请问具体的收费标准是什么，以及如何购买，我找不到你的邮箱地址

**Comment by Aircloud2021** [comment]
请问有导出字幕的方法吗？
另外：建议兄弟在淘宝开个小店，这样显得正规一点，还可以自动发货，一举两得，岂不美哉~

**Comment by muzuiget** [comment]
导出字幕见 #253。

帖子已经说了，注册麻烦，付费人数不多的话，先手工操作算了，等真的很多人付费再做也不迟。

**Comment by Kzero01R** [comment]
建议增加可以用快速键开关字幕功能，因为有时候看影片它有中文字幕，Dualsub 的字幕就会挡住

**Comment by muzuiget** [comment]
@Kzero01R 快捷键代替方法见 #288。
