### ISSUE TITLE
2021-08-03 免费测试账号

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#297]
[English](https://github.com/muzuiget/dualsub-support/issues/308)

**收费测试已经结束，服务器暂时恢复回免费模式一段时间，以后就需要付费[购买账号](https://www.dualsub.xyz/zh/docs/paid-features/pricing-and-purchasing)。**

请先阅读官网文档[收费功能](https://www.dualsub.xyz/zh/docs/paid-features/overview)。

发送标题为“申请测试账号”的邮件到 `dualsubstudio+testing@gmail.com` ，我会给你一个额度为 100 万字符数的账号。

如果你愿意：

* 邮件正文告知一下你的每日平均使用流量，在扩展设置页面的“网络”标签页查看。

注意事项：

* 请不要用其它标题，要像个正常邮件，否则可能会被邮箱系统自动判断为垃圾邮件而得不到及时处理。
* 不要重复发送邮件，重复发送我也只会给一个账号。
* 测试账号仅仅在测试期间有效，正式收费时会即时失效，因为服务器会清档。
* 这也是为了统计付费意愿，希望用户按照正常使用习惯使用。

**Comment by xibaibai9527** [comment]
刚看到字幕突然不翻译了，上来一看竟然开始收费了。
看了下我自己的统计，我主要是在ytb上看cs50的编程课，上了5节课，竟然用了85w字节量 -_-b

邮件已发送，请通过

**Comment by muzuiget** [comment]
数据几个版本前就开始统计，只是在 v1.65.0 才显示出来，你留意下那个开始时间。

**Comment by xibaibai9527** [comment]
反馈：输入账号后，打开视频，回到上次中断的地方播放3秒，再看账号中一下用了3K的字符量
整个视频看完之后（18分钟），用掉了17K的字符量

感觉这个数据略夸张啊，是否统计有误？

**Comment by muzuiget** [comment]
3K 是字幕分段，也就是每次只翻译当前播放的一部分。字符量和视频长度没关系，尤其是那些直播碎碎念的视频，说话密集用量就多。

你可以这么测试：在扩展管理页面右上角开启开发者账号，然后 Dualsub 那个卡片多了个叫“背景页”的链接，点击会打开一个开发者工具页面，然后切换到"网络“面板。

然后播放你的视频，你会看到所有 Dualsub 和 `api.dualsub.xyz` 收发的所有数据，其中 `translate` 就是翻译功能，`contents` 里就是字幕数据，另外还有其它参数。

只有 `contents` 里的字符数会收费，是算 Unicode 字符数，不是单词数，例如 `Hello world` 算 11 个，而不是 2 个。

**Comment by xibaibai9527** [comment]
明白了，100万字符不是100万个单词的翻译量，而是指1M的流量，这样一个视频十几K就不算多了

**Comment by hermitcai** [comment]
请问发送邮件之后 多久可以收到测试账号

**Comment by muzuiget** [comment]
人工发，不定时，我收到收会尽快发送。

**Comment by hermitcai** [comment]
谢谢

**Comment by mrjamesbos** [comment]
I just sent an email with a request for a test account, thanks @muzuiget

**Comment by deyu260** [comment]
如何设置才能免费使用youtube自己的翻译功能？

**Comment by muzuiget** [comment]
“简单模式”下显示的字幕。

**Comment by Bob-YsPan** [comment]
@deyu260 
> 如何设置才能免费使用youtube自己的翻译功能？

> “简单模式”下显示的字幕。

剛剛我測試了一下，
簡單模式要啟用的話
要記得打開YouTube自己的CC字幕開關
顯示出來的就是外掛處理過的CC字幕了

剛剛試出來順便提醒一下開不出簡單模式的用戶

**Comment by dongliang** [comment]
邮件已发送，请通过，在线等，急

**Comment by muzuiget** [comment]
主帖更新：添加了文档链接[如何计算流量消耗](https://www.dualsub.xyz/zh/docs/how-is-traffic-calculated)。

**Comment by leira1114** [comment]
郵件發送，希望可以用

**Comment by CrazyLayKer** [comment]
已申請，希望開放加密貨幣付費，使用USDT、BUSD等穩定幣可以避免價格大幅波動。

**Comment by muzuiget** [comment]
暂时不考虑加密货币。

**Comment by leoooodanno00** [comment]
邮件已发送, 顺便问一下大概还要多久才能出付费系统，什么时候才能购买账号

**Comment by muzuiget** [comment]
见官网文档[定价和购买](https://www.dualsub.xyz/zh/docs/paid-features/pricing-and-purchasing)。

**Comment by wangxin6** [comment]
用量少，有超过30天的套餐么？

**Comment by muzuiget** [comment]
暂时不考虑，目前 30 天只是软限制，类似食品保质期，过期几天**可能**还能用，但不保证能用。

过期时间就是为了有计划淘汰这些“买了又不及时用完"的账号，不然系统里留着这种账号，升级重构计费系统时就要费劲兼容。

**Comment by sYsguard** [comment]
Hi, 'no quota'  it's no longer free anymore?

**Comment by muzuiget** [comment]
@sYsguard see [Pricing and Purchasing](https://www.dualsub.xyz/docs/paid-features/pricing-and-purchasing).
