### ISSUE TITLE
插件在亚马逊中无法使用

### ISSUE THREAD

**Issue by Humbuishu** [muzuiget/dualsub-support#298]
插件在亚马逊中仍无法使用，是由于我使用的插件版本过低吗

**Comment by muzuiget** [comment]
如果你是说 `amazon.com` 这些域名，那确实不支持的了，因为它的账号系统非常复杂，除了账号地区属性外，还有诸多如 `amazon.de` 和 `amazon.jp` 这些子域名，根本无法测试。

另外就是扩展需要申请 `*.amazon.com` 这种域名的权限，估计很多用户不喜欢(尤其是那些不看亚马逊视频的)，毕竟亚马逊账号还有购物方面的私人信息，比其它纯视频的域名更加敏感。

所以我的建议只能是专门用来看注册一个能在 `primevideo.com` 使用的账号，这个小号就用来看视频，大号继续用来购物。

**Comment by Humbuishu** [comment]
> 如果是说你`amazon.com`这些域，那确实不支持的了，因为它的账号系统非常复杂，除了账号域外，还有地图如`amazon.de`和`amazon.jp`这些子域，根本无法测试。
> 
> 另外需要扩展需要申请这个`*.amazon.com`域名的权限，估计很多用户不喜欢（尤其是那些不看亚马逊视频的），创建亚马逊帐户还有其他网站的私人信息，比其他纯视频的域名更敏感。
> 
> 所以我的建议只能用来看注册一个能在`primevideo.com`使用的账号，这个小号就用视频，大号继续备份。

不好意思，我没太懂您的建议，是如果单独注册prime 的账号，您的插件就可以正常运转了吗

**Comment by muzuiget** [comment]
不是这个意思，而是我说这个扩展，只对 `primevideo.com` 这个域名做了适配，而没有对 `amazon.com` 做适配。但是现在时刻是不是能用，我不能 100% 保证，因为我已经没这个网站的测试账号了，有可能网站已经改版了。

但是没有收到明确说不能用的报告，所以可以假设，现在应该还能用。

**Comment by SerendipityWYB** [comment]
现在amazon.com确实用不了了

**Comment by muzuiget** [comment]
没什么好做的。
