### ISSUE TITLE
Subtitle language shows close (0) in www.iq.com

### ISSUE THREAD

**Issue by beambeammm** [muzuiget/dualsub-support#299]
I was able to use dualsub extension last week, but now the subtitle language shows close (0), and machine translation shows close (18) in www.iq.com. Please let me know how to fix it. Thank you.
<img width="1440" alt="Screen Shot 2564-07-21 at 16 09 43" src="https://user-images.githubusercontent.com/87755676/126464750-c633ae43-1e13-4b06-86a9-d98fc44fca63.png">

**Comment by xvnn** [comment]
I have the same issue on iq.com :(
Dual Sub works on other streaming website

**Comment by muzuiget** [comment]
Fixed in v1.65.1

**Comment by b92303008** [comment]
I have the same issue on Netflix. A fix will be much appreciaed. Thank you.
![image](https://user-images.githubusercontent.com/82116058/126772799-14c8ee35-6141-480f-9d33-b317469d4ca4.png)

**Comment by muzuiget** [comment]
@b92303008 please create another issue.

**Comment by muzuiget** [comment]
This issue fixed in v1.65.1
