### ISSUE TITLE
翻译偶尔出现<[Object, Object]>

### ISSUE THREAD

**Issue by zhuliangyu** [muzuiget/dualsub-support#300]
![image](https://user-images.githubusercontent.com/11518998/126530994-1095d8d9-fc5b-4039-b58e-36cf78416f82.png)

如何重现:
无规律, 偶尔会出现
只要出现<[Object, Object]>之后所有的句子都不会翻译中文, 但是英文字幕在更新. 
![image](https://user-images.githubusercontent.com/11518998/126531448-86811b25-9029-4ff4-9ea0-b788f4ae9e26.png)

需要手动refresh page

**Comment by muzuiget** [comment]
应该是网络错误，错误字符串搞错了，下个版本修复。

**Comment by muzuiget** [comment]
v1.65.2 已修复。
