### ISSUE TITLE
翻译出现 Error: Extension context invalidated.

### ISSUE THREAD

**Issue by Boms** [muzuiget/dualsub-support#302]
英文翻译中文出现，出现后一直显示这个错误信息。手动刷新页面后，恢复正常。

**Comment by muzuiget** [comment]
这个意思是无效的扩展上下文，就是扩展被重启了，新的扩展实例被创建，原因是可能是

* 后台自动更新了扩展版本，最可能是这个。
* 手动禁用然后启用。
* “扩展管理器”类的扩展自动重启。

这个问题只能刷新当前页面解决，这样页面才能和新的扩展实例通信。
