### ISSUE TITLE
建议加回是否显示字幕的快捷键

### ISSUE THREAD

**Issue by Boms** [muzuiget/dualsub-support#303]
估计作者本意是通过配置，控制字幕显示与否。
不过我个人使用情况是，同一个视频字幕，有时也可能根据情况切换是否显示字幕。以前用快捷键切换，非常便捷。现在不能用快捷键切换，操作比较繁琐。尤其是在全屏显示的情况下，要先退出全屏状态再操作。

**Comment by muzuiget** [comment]
快捷键代替方法问题见 #288。
