### ISSUE TITLE
The dropdown menu for subtitle language shows nothing to choose from

### ISSUE THREAD

**Issue by b92303008** [muzuiget/dualsub-support#304]
The dropdown menu for subtitle language shows nothing to choose from. Tried various shows/movies on both chrome and edge. The version installed is 1.65.2, which I believe is up to date. Below are the screenshots. Please let me know what other details you need to fix the issue. Thank you.

![image](https://user-images.githubusercontent.com/82116058/126864988-70dbbfa9-5a49-4b34-bd52-1180a3edd9fa.png)
![image](https://user-images.githubusercontent.com/82116058/126865000-e36892e0-2b5e-48a4-848e-c94b7309dba6.png)
![image](https://user-images.githubusercontent.com/82116058/126865017-d30fb5af-4ee5-4566-9c0c-73ff3eb05afb.png)
![image](https://user-images.githubusercontent.com/82116058/126865460-8a6b4c99-4817-41c1-9602-9075e33e96d9.png)
![image](https://user-images.githubusercontent.com/82116058/126865469-605afaac-ee1b-4833-8968-2bdce8987181.png)
![image](https://user-images.githubusercontent.com/82116058/126865471-a081e9a9-af27-4193-9844-adda734eba79.png)

**Comment by muzuiget** [comment]
看你的界面，我们还是用中文讨论吧。

没有头绪，按 F12 弹出开发者控制台，看看收否有错误输出。

**Comment by b92303008** [comment]
您好，下面是控制台顯示的錯誤訊息，還需要什麼請再跟我說，謝謝。
![image](https://user-images.githubusercontent.com/82116058/126899769-dfd962b0-e157-412c-b90b-5469a1a6419c.png)

**Comment by muzuiget** [comment]
看上去是 Netflix 自己的错误，爆栈了。

看界面你似乎在用了 Netflix 的其它扩展，因为播放器默认界面不是这样的，有没有试过关掉其它 Netflix 扩展？

**Comment by b92303008** [comment]
> 看上去是 Netflix 自己的错误，爆栈了。
> 
> 看界面你似乎在用了 Netflix 的其它扩展，因为播放器默认界面不是这样的，有没有试过关掉其它 Netflix 扩展？

是的，不過關掉後仍然沒有字幕可選擇，下面是控制台的截圖。
![image](https://user-images.githubusercontent.com/82116058/126900415-0925b0fa-4365-440a-abbe-c5adf43ab7ad.png)

我再試了用edge開，這次只有Dualsub這個擴展，依樣沒有字幕可選，控制台的截圖如下。
![image](https://user-images.githubusercontent.com/82116058/126900534-be382950-3ed2-4b70-b1e5-afc92db258ee.png)
![image](https://user-images.githubusercontent.com/82116058/126900545-af5be740-927d-45fd-b624-47f0dbf50d98.png)
![image](https://user-images.githubusercontent.com/82116058/126900554-ca9691a2-ef7b-45a5-ac1b-a1262cf575be.png)

**Comment by muzuiget** [comment]
Netflix 自己的字幕菜单有字幕选择吗？

**Comment by b92303008** [comment]
> Netflix 自己的字幕菜单有字幕选择吗？

有的。
![image](https://user-images.githubusercontent.com/82116058/126901760-7d224cf8-f47b-479f-af8b-3e07bdd189ae.png)
![image](https://user-images.githubusercontent.com/82116058/126901778-85bce6ba-a86a-413c-b6cf-4471374fb2d0.png)

**Comment by muzuiget** [comment]
贴下视频地址？

**Comment by muzuiget** [comment]
为什么你的截图没有视频画面的？

**Comment by b92303008** [comment]
> 贴下视频地址？

https://www.netflix.com/watch/70109445?trackId=14170286&tctx=2%2C0%2C36e3858d-5c59-47dc-918c-317c99d07522-27560640%2Cf20c9efa-1e97-4677-9e9d-3c71714f308c_14303422X3XX1627456699354%2C%2C

https://www.netflix.com/watch/80194756?trackId=14170286&tctx=2%2C2%2C36e3858d-5c59-47dc-918c-317c99d07522-27560640%2Cf20c9efa-1e97-4677-9e9d-3c71714f308c_14303422X3XX1627456699354%2C%2C

**Comment by b92303008** [comment]
> 为什么你的截图没有视频画面的？

應該是DRM，怕被盜錄吧，最近剛開始的，只要嘗試截圖畫面就黑了。

**Comment by muzuiget** [comment]
这个问题仍然还存在吗？

**Comment by muzuiget** [comment]
似乎是个别用户问题，你确定排除了其它扩展的原因？
