### ISSUE TITLE
重复字幕

### ISSUE THREAD

**Issue by SweetLoli** [muzuiget/dualsub-support#305]
![20210725075003](https://user-images.githubusercontent.com/15523475/126883529-851863bc-813b-4111-bc15-b5940fbde2cc.jpg)
https://www.youtube.com/watch?v=zBkVCpbNnkU
这个视频在简单模式和标准模式下，都会出现重复的英文字幕。一开始以为是翻译模式的问题，不过增强和普通都有这个问题。
自动选择写的是这个：
`[en][][][1]`
`[zh-hant, zh][][][2]`

**Comment by muzuiget** [comment]
和自动选择无关，它的字幕文件的确把一句话重复了三次。

![Screenshot_20210725_162634](https://user-images.githubusercontent.com/330812/126892769-18758c63-39a8-4683-a9e9-c07cc243cf54.png)

只是 `pPenId` 属性不同， 所以它是通过重复字幕文本使用不同样式来曲线实现一些字幕特效。

![Screenshot_20210725_163115](https://user-images.githubusercontent.com/330812/126892908-32b1e45b-1d2a-4482-b084-5a8159e5d877.png)

实际上 YouTube 的机器翻译也是重复字幕文本干扰了。

![Screenshot_20210725_165359](https://user-images.githubusercontent.com/330812/126893460-7a262e6f-e6a2-4c6f-87d4-6a2fdf40f20e.png)

Dualsub 默认对重叠的时间轴会合并文本处理，所以就这样的情况，比如有些电影，对白和 BGM 的歌词重叠，也可能人工打轴错误，但是偶然一两条可以接受的，反也不影响观看。

就像 PDF 转文本一样，PDF 里面的文字已经精确定位和带有特殊样式，你很难对其二次处理。所以我是不太想处理这“种特效字幕”了，用 Dualsub 就是为了学习外语，而不是专门渲染特效字幕。

虽然可以专门针对这个特例做一些处理，但是我还是觉得这是特效字幕的问题，很难完美解决，而且“简单模式”下因为要和保持和机器翻译对齐时间轴，不能增加也不能删除，根本解决不了。

最好就是通知字幕作者，特效和非特效字幕都提供，YouTube 是支持一个语言上传多个版本字幕的。

**Comment by muzuiget** [comment]
我后来重新想了一下， 这个问题还是得解决，因为决定按流量收费了。

对 YouTube 字幕，开始时间、结束时间、正文文本都完全一样的话，只保留一条时间轴就好了。

**Comment by SweetLoli** [comment]
原来这背后的原因这么复杂，大佬辛苦了orz

**Comment by muzuiget** [comment]
v1.65.3 已发布。

**Comment by SweetLoli** [comment]
现在没有重复字幕的问题了，感谢作者修复~

PS：以前每次打开有超多种字幕语言的视频时，会把整台电脑都卡住好一会儿，然后资源管理器会卡到自动重启（低配电脑）。这个新版本似乎也修复了这个问题，现在我打开这类视频，只要小卡顿几下就能加载好，而不会完全卡死了，体验好太多了！

**Comment by muzuiget** [comment]
字幕语言数量多少影响不了多少性能，你的错觉而已。

YouTube 本来就很卡，这是因为 Google 强推 VP9 编码格式，而很多电脑都不支持 VP9 硬件解码，所以就觉得卡。用其它扩展强制切换到 H264 编码就顺畅很多，你可以搜一下。

**Comment by SweetLoli** [comment]
确实是错觉，刚说完没几分钟，打开个视频就卡崩资源管理器了，这么说可能是和系统资源占用有关吧😂
因为1440P就会开始明显掉帧，所以我一直都用H264看1080P；播放视频不卡，就是开着Dualsub点开YTB视频的时候，有时候会让电脑卡死一会儿，然后才开始播放。

**Comment by muzuiget** [comment]
但我觉得 Dualsub 计算量比起 YouTube 网页本身，可以说是微不足道。你试过禁用 Dualsub 然后重新观察？

**Comment by muzuiget** [comment]
这帖子先关了，卡顿现象如果确实是 Dualsub 的原因，请另开新帖讨论。
