### ISSUE TITLE
收费用户如何下载youtube字幕

### ISSUE THREAD

**Issue by carli0215** [muzuiget/dualsub-support#307]
https://dualsub-exporter.netlify.app/网站关闭后，收费用户如何下载youtube字幕人工校对编辑

**Comment by muzuiget** [comment]
扩展里不会有字幕下载的功能了，不想做和有任何版权风险的功能，尤其是在收费之后。

你只能用其它工具下载字幕，例如 [youtube-dl](https://github.com/ytdl-org/youtube-dl)，而且字幕翻译网站多如牛毛。
