### ISSUE TITLE
Subtitle on Udemy error no quota

### ISSUE THREAD

**Issue by ducsiu** [muzuiget/dualsub-support#309]
<img width="693" alt="Ảnh chụp Màn hình 2021-08-02 lúc 22 16 22" src="https://user-images.githubusercontent.com/58317985/127884520-c949f623-5686-439b-83b1-4e06e5e205e0.png">
Hi Developer,

I'm watching courses on Udemy but subtitlte show "error no quota". 
Please help me. 
Thank you so much.

**Comment by muzuiget** [comment]
Open the url you will get the description.
