### ISSUE TITLE
中国大陆境外用户付款问题

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#310]
收费测试搞了差不多半个月，正式收费卡在最后一关就是付款问题。

因为我本人是中国大陆人，收取人民币是理想当然的，但是中国大陆个人开发者收款是永远的痛，即使现在 2021 年，也没有很好的解决方法。

## 境内付款

以用户角度来说，当然喜欢“一手交钱，一手交货”。要自动发货，需要支付平台的付款通知接口，然而在中国大陆，申请这种接口是需要企业资质的。注册企业要跑各种手续，还有额外的运营成本，为了一个小众软件专门搞这些根本不值得。

有一些第三方公司提供无需企业资质的接口，明显是通过二次交易来实现的，所以基于安全原因，我不会考虑这种方法，我宁愿自己写挂机程序自己实现。

所以退而其次，手工发货。支付宝和微信都提供“个人收钱码”功能，也就是付款人手机扫个二维码，输入金额，加个备注，钱直接就转到收款人账号上，也没有手续费。很多街边小店收款账号都是老板的个人账号，而不是对公账号，这样做有效降低店铺账面营业额，好处你懂的。

所以对于小额付款，用“个人收钱码”直接转账，即使没有中间人担保，因为其方便快捷的，隐私保障也比较好，已经被很多人接受了。所以我也使用这个方法，这是目前起来最简单的，顶多发货就是慢点而已。

## 境外付款

这就麻烦多了，一开始我是考虑用 PayPal 的，因为只有 PayPal 支持个人收款，但是一通研究下来，跟收钱码这种方法比起来，就是一个弱智设计，充满各种恶心的地方。

要个人收款，需要开通 PayPal.Me，而 PayPal.Me 会强制公开你的真实姓名和邮箱地址，一个有真实姓名的邮箱地址对钓鱼者来说多么诱人，这是嫌垃圾邮件收得不够多？至少支付宝就做得挺好，交易双方的都不会知道对方的支付宝账号和真实姓名（会用星号屏蔽一部分），所以交易双方不会有联系方式，也不会被对方骚扰，交易完成后各走各路。

根据[这篇文章](https://www.chenfeiblog.com/paypal/)，还有两处恶心得难以接受。

PayPal 上的钱也不一定是你的钱。

> 作为paypal用户要始终记住，paypal是倾向于保护买家利益的。买家可以举出无数个理由要回之前付给你的钱，其中使用最多的理由是“未经授权的付款”。

如果你及时提现吧，还有高额的手续费层层割肉。

> 取消快捷人民币，似乎也是受政策限制。电汇提现到国内银行方式，提现每笔35美元高额手续费，外加可能10-20美元的中间行费用，会让很多中小卖家心里隐隐作痛。每提现一次，不管金额多少，都得付出至少约230元人民币的提现手续费。提的多，平摊下来，提现成本还能接受，提的少了的话，就很不划算了。最后，别忘了，进来的是美元，还得办理结汇。

还有各种乱七八糟的中国大陆特供限制。

所以美元不好赚，这么麻烦，老子不奉陪了，老子就只收人民币。

**所以对于中国大陆境外的用户，自己想办法怎么使用支付宝吧。**

就是只花一点点兑换人民币手续费而已，对双方都有好处。

## 总结

不是我想放弃境外用户，而是有心无力，这一通折腾估计连时间成本都赚不回来。

~为了减少影响， 暂时对“翻译为非中文语言”免费（不会扣除流量，所有用户都是）。但是避免人家说我就针对中文收费，如果一个月内没有其它解决方法，也会取消这个免费条件，也可能提前取消。~

所以目前最大影响港澳台用户，没办法，繁体中文也是中文，所以不能对“翻译为繁体中文”免费。不过我相信有一部分人已经有大陆支付宝的，或者有大陆朋友代付。

如果你其它门路，可以跟帖讨论，或者通过电子邮件[联系我](https://www.dualsub.xyz/zh/docs/contact)。

**Comment by zhuliangyu** [comment]
尝试用支付宝给您付款, 但是显示 "对方收钱码为境内收钱码, 仅能在境内使用"
我人在境外, 使用中国的银行账户. 
暂时不知道如何给您付款?

**Comment by muzuiget** [comment]
我不知道有这个限制，你这是大陆版的支付宝吗？

**Comment by muzuiget** [comment]
还是不清楚，怎么我感觉人民币转人民币应该没限制的。

**Comment by zhuliangyu** [comment]
我还是没找到无法给您转账的原因.
是否能通过为微信给您转红包方式付款?  @muzuiget

**Comment by muzuiget** [comment]
微信红包也转不了的吧，不是一样的限制吗？

**Comment by muzuiget** [comment]
给我发[邮件](https://www.dualsub.xyz/zh/docs/contact)，我在邮件告诉你我的微信。

**Comment by asasas234** [comment]
@muzuiget 我付款了，麻烦看下邮箱。订单号发邮件了
