### ISSUE TITLE
能否增加更长使用期限的套餐？

### ISSUE THREAD

**Issue by kbps1411** [muzuiget/dualsub-support#313]
现在套餐才30天就到期，有点太早了，而且这样一个小插件我觉得不应该让用户花精力去关注余额，到期时间之类的琐事。
为何不出一个高流量的不限期套餐？贵一点也没问题

**Comment by muzuiget** [comment]
现在其实也是没限制，只是有这个设定，你可以当成“不小于 30 天“来理解。这是以防万一我两个星期后突然又需要改计费系统了，至少有个兼容期限，有计划淘汰旧账号。当计费系统我觉得够稳定了，自然会提高的。

**Comment by feipinxiang** [comment]
我7月27号申请了一个，今天显示
剩余额度 | 无
过期时间 | 无

**Comment by ficapy** [comment]
充值了十块钱体验了一下，十万字符，没想到看了个两个小时的视频就没了........

**Comment by muzuiget** [comment]
@ficapy 你可以把你的账号发给我，我看下日志。

**Comment by ficapy** [comment]
@muzuiget acb79b93-f1b5-4897-b097-08ad3e2b081d

**Comment by muzuiget** [comment]
100k 字符本来就是不多了，根本用不了到 30 天。

**Comment by muzuiget** [comment]
看上去就很正常，平均每分钟 1k，也就是 1 毛钱。

**Comment by kbps1411** [comment]
买了100K的套餐，零零碎碎用了5天就花掉了92k。。。还没开始看长篇呢。。
这样算下来，正常用一个月可能需要100块钱了

**Comment by muzuiget** [comment]
你这属于重度用户了，你换个角度想，每天也就是 2 元，现在两元能买什么，一瓶迷你版可口可乐，而且一口气就能喝完那种。

本来上游翻译 API 就死贵，我也想便宜点。

**Comment by muzuiget** [comment]
现在最大问题就是一般用户无法直观理解“字符数”到底能用多久，我得想个办法让用户购买前感受一下，虽然已经自带了个统计功能，明显没有会注意。
