### ISSUE TITLE
关于商品定价

### ISSUE THREAD

**Issue by SpaceCZ** [muzuiget/dualsub-support#314]
您好，在应用试用及测试期间并不了解这个应用，于是使用时就直接入手付费版了。
我认为商品定价是否有些过高？100k 的字节量经我购买后测试整体使用时间大概不会超过 150 分钟

**Comment by muzuiget** [comment]
你好，请你阅读一下[如何计算流量](https://www.dualsub.xyz/zh/docs/paid-features/how-is-traffic-calculated)，流量和视频时间无关，取决于字幕的文本字数有多少。在服务器翻译了文本就会计算流量，而不管这些文字对应多长视频，或者你有没有观看过，比如你翻译了但是不完整看视频，就存在浪费。

定价本来就是一个很困难的事，一开始可以赔本赚吆喝，但最终还是至少要保本。我不清楚你什么时候开始用 Dualsub，至少 Dualsub 赔本赚吆喝免费了很长一段时间，起码半年以上。

定价可能看情况变动，但现在的定价起码得维持一段时间，这样才对已经买过的用户公平。

**Comment by SpaceCZ** [comment]
好的，关于流量计算我有看过，时间是我再看一个视频翻译字幕时大概计算的
