### ISSUE TITLE
开发设想：网页版播放器

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#315]
Dualsub 目前代码足够稳定了，以后改动会谨慎一点，这里分享我一些想法，打算重用 Dualsub 的基础设施开发一些工具。

现在用户可以用 Dualsub 来自定义网页视频的字幕，也可以加载本地字幕，那么本地视频呢？一般来说本地视频只能用桌面播放器播放，桌面播放器的字幕功能做不到像网页那样动态交互，例如双语字幕功能，需要通过把两个字幕文件合并成一个文件来实现，所以一般只能由字幕组这些专业用户来做。当然，有一些桌面播放器可以写插件扩充字幕功能，一般都要用 C/C++ 来写，开发难度太高了。

所以最好反过来，用浏览器播放本地视频。现在 Chrome 支持直接打开扩展名为 `.mp4` 的文件来播放，但是不支持 `.mkv`，会直接显示下载对话框。而实际上，Chrome 是可以播放 mkv 的，只要 mkv 里的视频的编码被 Chrome 支持即可，绝大部分 mkv 都是用 h264 编码，就是主流视频网站所用的编码，当然被 Chrome 支持。简单做法就是把扩展名改成 `.webm` 再用 Chrome 打开即可。

理论上说，其实 Chrome 没有正式支持 mkv 格式，但支持 webm 格式，只是 webm 源自 mkv 格式，因此 Chrome 可以播放一部分 mkv。所以我们只需要写一个网页，当打开一个 mkv 文件时，告诉 Chrome 不要显示下载对话框，而是尝试直接播放。

所以我打算搞一个 `player.dualsub.xyz` 网站，一个很简单的播放器页面，用户可以把本地视频文件拖进去播放，然后让 Dualsub 去支持这个网站，就像 `www.youtube.com` 一样，只不过视频和字幕都是你自己提供的。

如果用 Electron 封装一下，就是一个桌面播放器了，只不过是基于浏览器技术。

**Comment by eAtlantis000** [comment]
请问是否有可能开发网页双语插件，类似彩云小译？
以及是否可以开发出APP使手机以及iPad通过复制视频或视频所在网页地址在APP中显示双语字幕，哪怕暂时仅开发可用于油管的简单模式也是香的
令代码盲如我冒昧提出开发者是否可以尝试steam游戏双语显示的开发，基于官方本身拥有简体中文与英文的情况下进行显示

**Comment by muzuiget** [comment]
> 请问是否有可能开发网页双语插件，类似彩云小译？

双语效果最简单只需要几行代码，见我在小众软件发的[这个帖子](https://meta.appinn.net/t/topic/22432/2?u=muzuiget)。但是要做成一个成熟的扩展，还需要很多工作。

>  以及是否可以开发出APP使手机以及iPad通过复制视频或视频所在网页地址在APP中显示双语字幕，哪怕暂时仅开发可用于油管的简单模式也是香的

手机 App 开发成本更加高了，现在 iOS 的 Safari 支持扩展，直接在网页上处理更好。

除非是用标准 HTML `<video>` 和 `<track>` 标签实现的视频，即视频和字幕都是一个单一文件，才有这个可能。但是 Dualsub 所支持的 20 多个网站，都不是这样，它们的视频是“动态合成”的，即“各种分辨率的画面文件”、“各种配音的音频文件”，“各种语言的字幕文件”，合成一个临时小视频来播放，没有统一的做法，也就不可能做得通用，只能一个个去分析来适配，改版也不会告诉你改了什么，又得重新分析一次。

>  令代码盲如我冒昧提出开发者是否可以尝试steam游戏双语显示的开发，基于官方本身拥有简体中文与英文的情况下进行显示

更加不可能做到通用了，要么打补丁才行，要么 OCR 识别。

补丁据我所知有，[生化危机8](https://www.nexusmods.com/residentevilvillage/mods/82) 和 [最终幻想7](https://www.nexusmods.com/finalfantasy7remake/mods/57)。

OCR 识别也只对 GalGame 适合，可以看 [YUKI](https://github.com/project-yuki/YUKI) 和 [MisakaTranslator](https://github.com/hanmin0822/MisakaTranslator)。

**Comment by muzuiget** [comment]
`player.dualsub.xyz` 基本功能已经可用了，拖曳视频文件和字幕文件进网页，用 Dualsub v1.79.0+ 就能看到拖曳进去的字幕了。
