### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by qinhanlei** [muzuiget/dualsub-support#316]
dualsub 真是棒！

以下两个建议：
1. 标准模式，希望字幕能够如 `简单模式/官方自带字幕` 一般自动浮动
2. 希望能方便的一键 `关闭/打开` 当前模式字幕；最好简单和标准模式作为一个单选，目前的交互稍有混淆感

btw: 关于付费，个人常用的另一个 chrome 插件 [划词翻译](https://chrome.google.com/webstore/detail/%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91/ikhdkkncnoglghljlkmcimlnlhkeamad) 做得很好（不过也只针对国内用户），可做参考

**Comment by muzuiget** [comment]
### 底部边缘位置问题

设置里只定义了个全局偏移量，然后所有网站用插件形式来特别处理小屏/宽屏/全屏等情况，让用户自定义。所以你可以进入设置页面的“插件“标签页，选择“YouTube 自动缩放”（安装时自动生成的，如果删掉就重置一下）。

编辑代码：

```
.ytd-page-manager .dualsub-renderer {
    margin-bottom: -50px;
}
.ytd-page-manager[theater] .dualsub-renderer {
    margin-bottom: -40px;
}
.ytd-page-manager[fullscreen] .dualsub-renderer {
    margin-bottom: 0;
}
/* 追加以下代码：进度条隐藏时，减少 30px 高度 */
.ytd-page-manager .ytp-autohide .dualsub-renderer {
    margin-bottom: -80px;
}
.ytd-page-manager[theater] .ytp-autohide .dualsub-renderer {
    margin-bottom: -70px;
}
.ytd-page-manager[fullscreen] .ytp-autohide .dualsub-renderer {
    margin-bottom: -30px;
}
```

这里 6 个规则对应 6 种布局情况，可自己调整 ` margin-bottom` 里的像素值。

### 模式单选问题

其实有意让两种模式同时工作的，就是为了对比两种模式的机器翻译质量，用来吸引用户付费使用 Dualsub 的自建翻译服务。

### 收费模式问题

这个扩展我也考察过了，这个扩展的买断，是客户端买断，而现在 Dualsub 是客户端免费的。所以要使用它的服务端功能，它一样要额外付费 https://github.com/lmk123/crx-selection-translate/discussions/993

所以服务端功能无法买断，只要运营服务器，作者就要会有支出，服务器也有被关闭的一天，无法承诺你能永远用下去。所以服务端功能只适合订阅制，按时间或者使用量付费。

**Comment by qinhanlei** [comment]
@muzuiget 

底部边缘位置问题解决了，感谢！

我赞同服务端功能收费的，`划词翻译` 插件我购买了会员也买了积分；希望 Dualsub 可以参考其自动化会员及收费的方式，目前还是不太方便😅。

**Comment by muzuiget** [comment]
可以看下 https://github.com/muzuiget/dualsub-support/issues/310，除非有足够付费用户，否则不想浪费精力去注册公司。
