### ISSUE TITLE
需要同时在家和公司使用

### ISSUE THREAD

**Issue by Hawkingsss** [muzuiget/dualsub-support#317]
您好 ，有个需求， 我需要同时在家和公司使用，好像这个购买的码只支持一台电脑 在别的电脑上使用就无效  有没办法转移或者支持两个设备？

**Comment by muzuiget** [comment]
可以同时使用的，官网已经说了：

> 账号用法类似超市的不记名购物卡，用完即弃，没有挂失、也没有充值。
>
> 你可能通过邮箱接收账号，但邮箱只用作交易的联系方式，开发者不会假定邮箱拥有者会使用这个账号。同一个也账号可以给不同的人或设备同时使用，使用者自行保证账号安全。

没有绑定邮箱浏览器，谁知道这个码谁就能用，因为就是按流量付费，谁用都一样。

**Comment by Hawkingsss** [comment]
嗯 解决了！
