### ISSUE TITLE
可以支持手机浏览器吗？具体内容见正文

### ISSUE THREAD

**Issue by lgy330335** [muzuiget/dualsub-support#32]
可以为手机浏览器支持吗？有很多手机浏览器都可以安装谷歌插件的，我随便举例两个，比如yandex和 kiwi手机浏览器，都可以安装谷歌插件的

**Comment by muzuiget** [comment]
有这个需求吗？YouTube 有手机 App 的。如果在浏览器上看，得重新适应布局。

**Comment by lgy330335** [comment]
必须有啊


---原始邮件---
发件人: &quot;muzuiget&quot;<notifications@github.com&gt;
发送时间: 2019年12月3日(周二) 下午3:06
收件人: &quot;muzuiget/dualsub-supports&quot;<dualsub-supports@noreply.github.com&gt;;
抄送: &quot;Author&quot;<author@noreply.github.com&gt;;&quot;lgy330335&quot;<1550391007@qq.com&gt;;
主题: Re: [muzuiget/dualsub-supports] 可以支持手机浏览器吗？具体内容见正文 (#32)



有这个需求吗？YouTube 有手机 App 的。如果在浏览器上看，得重新适应布局。
 
&mdash;

**Comment by tiancool** [comment]
有需求的，现在很多人用 iPad 看视频，没有字幕不方便。最好能支持 iOS, 感谢

**Comment by muzuiget** [comment]
尝试了一下，手机页面完全就是不同的网站，各种按钮都默认隐藏起来的，逆向出播放器接口太麻烦了，短时间不支持了。

强制让浏览器使用桌面版 UserAgent 浏览可以凑合下吧？

**Comment by lgy330335** [comment]
> 尝试了一下，手机页面完全就是不同的网站，各种按钮都默认隐藏起来的，逆向出播放器接口太麻烦了，短时间不支持了。
> 
> 强制让浏览器使用桌面版 UserAgent 浏览可以凑合下吧？

启用桌面版发现显示不全啊！用YouTube网站自己提供的网页桌面版，倒是可以完整显示，但是脚本完全不起效果，测试浏览器yandex和kiwi。

**Comment by tomtomdev** [comment]
我也是有这个需求。
Kiwi browser 打开电脑端Youtube 网页基本没问题，可以使用。但是安卓手机屏幕过小，不方便，容易误触。安卓平板应该无压力。
不知道开发大大会哪些技术。有三个构想：
1，适配Youtube手机端网页，使插件加载到kiwi等手机浏览器时，依旧能用。
2，自己开发个安卓应用，类似于kiwi这种基于chromium的，通过双语字幕这个功能，来切入语言学习社区这个领域。
3，独立开发个应用，可以像播放歌词一样，显示在最上层，用户打开youtube app 或者 youtube vanced的时候，自动识别播放的视频，然后从youtube服务器抓取字幕和机器翻译字幕。可以参考musixmatch抓取spotify歌曲信息。

当然，如果大大觉得，没有精力开发，或者成本太大，后期无法盈利，那就当我在扯淡吧。毕竟大大已经付出了那么多，创造了这个神奇的插件了。

**Comment by tomtomdev** [comment]
另外，官方的firefox 移动端app，如果强制打开桌面版Youtube页面，也是可以支持dualsub的。移动端Youtube网页一样是不支持dualsub。

**Comment by muzuiget** [comment]
@tomtomdev 哈哈哈，感谢你的建议，其实你说的部分功能我已经在做了。

另外我也写了个给 [Teleprompter](https://chrome.google.com/webstore/detail/teleprompter/cdpldaeldapgedhekjmcclhcbieipkol)，这是在尝试自行实现字幕渲染层，以后准备替换掉 YouTube 自带的渲染，这样省去无聊又麻烦的逆向工程，并且可以添加更多功能。

那么问题来了，花费大量精力和金钱(字幕服务器费用)，如何盈利，现在 Dualsub 有 1w+ 个用户了，有多少愿意付费呢？你愿意接受付费增值服务吗？

**Comment by lgy330335** [comment]
> 尝试了一下，手机页面完全就是不同的网站，各种按钮都默认隐藏起来的，逆向出播放器接口太麻烦了，短时间不支持了。
> 
> 强制让浏览器使用桌面版 UserAgent 浏览可以凑合下吧？

YouTube网页版提供有三个版本，1，手机浏览器版。2，网页内自身提供的桌面版。3，强制让浏览器使用桌面版 UserAgent。前两个插件都不生效，第三个可以生效，但是让视频横屏后全屏显示时是不全的，你可以测试下第三个的具体情况。另外可以考虑适当捐赠。测试了小米9的可装插件浏览器

**Comment by lgy330335** [comment]
> 我也是有这个需求。
> Kiwi browser 打开电脑端Youtube 网页基本没问题，可以使用dualsub。但是安卓手机屏幕过小，不方便，容易误触。安卓平板应该无压力。
> 不知道开发大大会哪些技术。有三个构想：
> 1，适配Youtube手机端网页，使插件加载到kiwi等手机浏览器时，依旧能用。
> 2，自己开发个安卓应用，类似于kiwi这种基于chromium的，通过双语字幕这个功能，来切入语言学习社区这个领域。
> 3，独立开发个应用，可以像播放歌词一样，显示在最上层，用户打开youtube app 或者 youtube vanced的时候，自动识别播放的视频，然后从youtube服务器抓取字幕和机器翻译字幕。可以参考musixmatch抓取spotify歌曲信息。
> 
> 当然，如果大大觉得，没有精力开发，或者成本太大，后期无法盈利，那就当我在扯淡吧。毕竟大大已经付出了那么多，创造了这个神奇的插件了。
> 感谢大大！

Kiwi browser 打开电脑端Youtube 网页可以使用dualsub？，你确定？我看问题大的很，你好好测试下，都显示不全好不好？别说字幕了，视频都显示不全

**Comment by tomtomdev** [comment]
> @tomtomdev 哈哈哈，感谢你的建议，其实你说的部分功能我已经在做了。
> 
> 另外我也写了个给 [Teleprompter](https://chrome.google.com/webstore/detail/teleprompter/cdpldaeldapgedhekjmcclhcbieipkol)，这是在尝试自行实现字幕渲染层，以后准备替换掉 YouTube 自带的渲染，这样省去无聊又麻烦的逆向工程，并且可以添加更多功能。
> 
> 那么问题来了，花费大量精力和金钱(字幕服务器费用)，如何盈利，现在 Dualsub 有 1w+ 个用户了，有多少愿意付费呢？你愿意接受付费增值服务吗？

我就买了Musixmatch 的一年subscription。

第一，建议后期只做app，插件毕竟是依附别人浏览器的。Musixmatch 也是做插件起家的，现在停做插件，只做app了。
第二，建议主攻海外市场。国内除了小部分用户，大部分用户基本用不到dualsub，因为不可说原因。他们主要用每日英语听力，每日法语听力这类的把油管视频搬运回国，然后加字幕，而不是直连的软件。
第三，模式的话，可以参考HiNative 或者HelloTalk，不单单是提供字幕，还提供一个语言学习交流平台，让用户分享所学语言的一些有趣频道或视频，也可以让用户分享字幕，给别人纠正或者指点语法，用法之类的。

**Comment by tomtomdev** [comment]
> > 我也是有这个需求。
> > Kiwi browser 打开电脑端Youtube 网页基本没问题，可以使用dualsub。但是安卓手机屏幕过小，不方便，容易误触。安卓平板应该无压力。
> > 不知道开发大大会哪些技术。有三个构想：
> > 1，适配Youtube手机端网页，使插件加载到kiwi等手机浏览器时，依旧能用。
> > 2，自己开发个安卓应用，类似于kiwi这种基于chromium的，通过双语字幕这个功能，来切入语言学习社区这个领域。
> > 3，独立开发个应用，可以像播放歌词一样，显示在最上层，用户打开youtube app 或者 youtube vanced的时候，自动识别播放的视频，然后从youtube服务器抓取字幕和机器翻译字幕。可以参考musixmatch抓取spotify歌曲信息。
> > 当然，如果大大觉得，没有精力开发，或者成本太大，后期无法盈利，那就当我在扯淡吧。毕竟大大已经付出了那么多，创造了这个神奇的插件了。
> > 感谢大大！
> 
> Kiwi browser 打开电脑端Youtube 网页可以使用dualsub，可以是可以，但是显示不全，而且问题很大，连视频都显示不全，别说字幕了！注：我说的是在全屏状态下！

小米9 se和pixel 2测试 kiwi browser 和Firefox， 都可以。不过，kiwi打开Youtube 电脑网页，再打开全屏时，在横屏状态下无法显示双语字幕，要在竖屏把字幕拖到中间，然后在横屏时才能显示全。
Firefox浏览器则没有上述问题。 不过火狐浏览器安装插件时要打开电脑端插件网页，而不是android版插件网页

**Comment by lgy330335** [comment]
@tomtomdev 你所说的拖，都不能显示全的，视频全了，字幕看不见，字幕全了，视频就显示不全，还有手机上看视频几乎没人选择竖屏看吧

**Comment by lgy330335** [comment]
> > > 我也是有这个需求。
> > > Kiwi browser 打开电脑端Youtube 网页基本没问题，可以使用dualsub。但是安卓手机屏幕过小，不方便，容易误触。安卓平板应该无压力。
> > > 不知道开发大大会哪些技术。有三个构想：
> > > 1，适配Youtube手机端网页，使插件加载到kiwi等手机浏览器时，依旧能用。
> > > 2，自己开发个安卓应用，类似于kiwi这种基于chromium的，通过双语字幕这个功能，来切入语言学习社区这个领域。
> > > 3，独立开发个应用，可以像播放歌词一样，显示在最上层，用户打开youtube app 或者 youtube vanced的时候，自动识别播放的视频，然后从youtube服务器抓取字幕和机器翻译字幕。可以参考musixmatch抓取spotify歌曲信息。
> > > 当然，如果大大觉得，没有精力开发，或者成本太大，后期无法盈利，那就当我在扯淡吧。毕竟大大已经付出了那么多，创造了这个神奇的插件了。
> > > 感谢大大！
> > 
> > 
> > Kiwi browser 打开电脑端Youtube 网页可以使用dualsub，可以是可以，但是显示不全，而且问题很大，连视频都显示不全，别说字幕了！注：我说的是在全屏状态下！
> 
> 小米9 se和pixel 2测试 kiwi browser 和Firefox， 都可以。不过，kiwi打开Youtube 电脑网页，再打开全屏时，在横屏状态下无法显示双语字幕。可能是小米9se机身太扁长了，kiwi浏览器全屏时没做好优化。
> 
> 要在竖屏时把字幕拖到视频中间，然后在横屏时才能显示双语字幕。或者，在全屏状态下，往下拖，就能看到字幕，然后把字幕拖到中间。
> 
> Firefox浏览器则没有上述问题。 不过火狐浏览器安装插件时要打开电脑端插件网页，而不是android版插件网页

@tomtomdev 你所说的拖，都不能显示全的，视频全了，字幕看不见，字幕全了，视频就显示不全，还有手机上看视频几乎没人选择竖屏看吧，还有不只小米9se 应该都这样吧，我的小米9和荣耀v10测试都是这样显示不全，而且测试的不止kiwi浏览器还有yandex浏览器都是这样，Firefox 手机浏览器我还没测试

**Comment by muzuiget** [comment]
不打算接受捐赠，我也根本不缺这点钱，接受捐赠反而有种“吃人嘴软，拿人手短”的感觉。还不如正经收费，当然是按月订阅模式最好，一过服务期大家两清，反而没压力。

**Comment by muzuiget** [comment]
目前 YouTube 网页版至少有 3 个布局，新桌面版，旧桌面版，移动版。而 Dualsub 只支持新桌面版。

用手机浏览器访问是移动版，也可以用 `app=desktop` 强制浏览旧桌面版，除非能改 UserAgent，好像不能直接访问新桌面版。
