### ISSUE TITLE
中文分析还是走流量啊？

### ISSUE THREAD

**Issue by SerendipityWYB** [muzuiget/dualsub-support#320]
长期对“中文分析”和“日语分析”接口免流量，但我还是在走流量啊，刚付完钱没几天流量走完了不能用了，

**Comment by muzuiget** [comment]
不可能，把你的账号发送[我的邮箱](https://www.dualsub.xyz/zh/docs/contact)看一下。

**Comment by muzuiget** [comment]
请看 #321。
