### ISSUE TITLE
收费模式改为包月模式

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#321]
虽然我曾经多次说过不会有无限流量包月套餐，好吧我现在自打脸了，现在改为包月模式。

## 原因

原先的”按流量付费“模式，显然绝大部分用户对流量没有概念，流量消耗的速度高于预期，然后向我抱怨，多次解释也身心俱疲。估计关于流量的文档写了也没有人看，看了也不一定理解。现在看按流量是不明智的，所以还是按时间付费好了。

## 更改方案

所以改成订阅制，按月付费，一月按 30 天计算，多加 1 天作为手动发货延迟补偿。

| 套餐   | 有效时间 | 价格  |
| ----   | -------- | ----  |
| 月套餐 | 30 天    | 60 元 |

也就是相当于每天 2 元钱，一瓶水的价格，彼此双方不再为流量而纠结。

**无限流量是基于单一用户在正常和合理使用的情况下，不再需要关心流量，不表示完全没有任何限制。用户可以在属于自己的不同设备轮流上使用，但不能把账号公开或分享给别人。**

**服务器会依然会检测滥用行为，并按严重程度作相应处理，比如限制请求或者封禁。这种举措是为了对付职业羊毛党，所以普通用户正常使用不需担心。**

## 补偿方案

**服务器已完成升级，旧套餐账号作废处理，请使用新套餐账号。**

在 2021-08-12 00:00:00 +0800 前购买的旧套餐账号的用户，无论旧套餐账号是否用完了流量，你可以换购新套餐或者全额退款。

### 换购新套餐

之前所有订单都作为已付款金额，按 2 元一天的价格换算为新账号。

发送邮件到 `dualsubstudio+alipay@gmail.com`，标题为 `换购新套餐`，邮件里说明你的所有支付宝订单号。

### 全额退款

如果你不满意此次定价改动，你可以获取全额退款。

发送邮件到 `dualsubstudio+alipay@gmail.com`，标题为 `申请退款`，邮件里说明你的所有支付宝订单号，以及收钱码截图（因为支付宝不允许通过原订单退款了）。

**Comment by Kzero01R** [comment]
现在的价格是低收费，还是正常价格？

**Comment by wangxin6** [comment]
大佬是好人

**Comment by muzuiget** [comment]
@Kzero01R 正常价格。

@wangxin6 我不能保证服务器一年后还能按照此价格，所以没有按年，也没有买断，没有家庭餐，只要你用起来像一个人用就行。

**Comment by Aircloud2021** [comment]
请问如何购买呢，我好像没找到你的收款账号

**Comment by incitere** [comment]
@muzuiget  看youtube如果经常换路线，希望不会被封
 
> @wangxin6 我不能保证服务器一年后还能按照此价格，所以没有按年，也没有买断，没有家庭餐，只要你用起来像一个人用就行。

**Comment by muzuiget** [comment]
@incitere IP 没有关系的，一般看请求频率。

**Comment by suheandzl** [comment]
我个人还是希望能有一个按流量计费的选择 平常看带字幕需翻译的视频不多 也许之前的方案就足够我一个月的使用

**Comment by muzuiget** [comment]
@suheandzl 短时间不会考虑了。

**Comment by xinli6** [comment]
感觉价格还是高了，一般人也看不了多少视频，虽然是无限流量，但实际用不了多少的。

**Comment by muzuiget** [comment]
@xinli6 开始收费都不够一个月，定价是否合理，先观察一段时间。

**Comment by neweva** [comment]
早就應該 訂閱模式 只是現在的訂閱模式稍顯麻煩 希望能改進

**Comment by muzuiget** [comment]
@neweva 自动发货需要支付宝的付款通知 API，但是在中国大陆不注册公司是拿不到这种 API 的。除非有足够连续包月的用户让我值得去搞个小公司来运营，所以目前只能先以私人转账方式来交易。

**Comment by neweva** [comment]
@muzuiget 等下忙完手頭上的事情 就去給您充值 請問能接受我充1年嗎

**Comment by muzuiget** [comment]
@neweva 请不要，最多一个月。我不保证这个定价能一年不变，服务器也不一定能稳当运行一年，所以按月付费就好，船小好调头，方便我应变意外。

**Comment by muzuiget** [comment]
删除了 10 元 3 天的日套餐，现在只有 60 元 30 天的月套餐。

但是”补偿方案“的用户仍然可以以每天 2 元的价格换算，不需要补足月套餐金额。

**Comment by muzuiget** [comment]
手动发货延迟补偿时间增加到 1 天。

**Comment by kongran-111** [comment]
好家伙 我一个月值看个几次 你要收我60  什么意思

**Comment by muzuiget** [comment]
一个月只看几次的话，凑合用“简单模式”的翻译就好了。
