### ISSUE TITLE
希望增加Top margin 设置选项.

### ISSUE THREAD

**Issue by firogh** [muzuiget/dualsub-support#322]
Hi, 
因为有的视频, 原生带字幕在视频的bottom. 
所以希望, 可以把dualsub的字幕调整到上面, 现有的bottom margin, 如果全屏后字幕在屏幕中间, 需要手动调.
Thanx, Firo

**Comment by muzuiget** [comment]
用一段 CSS 代码即可实现，在设置页面的“插件“里，添加一个样式类型的插件，代码如下：

```
.dualsub-renderer {
    top: 100px;
    bottom: auto;
}
```

下方勾选你要启用的网站。
