### ISSUE TITLE
哔哩哔哩字幕翻译失效

### ISSUE THREAD

**Issue by Meeerlin** [muzuiget/dualsub-support#323]
是需要付费才能正常使用吗，情况如图
![image](https://user-images.githubusercontent.com/36768680/129384066-f0c8ff55-2d4b-4a8d-930c-f298e77a5c4b.png)

**Comment by muzuiget** [comment]
如果是已知错误会以 `https://www.dualsub.xyz/error/` 网址显示。

**Comment by MustForgiveHer** [comment]
> 如果是已知错误会以 `https://www.dualsub.xyz/error/` 网址显示。

没有提示错误，它是没有进行翻译，而是直接输出原英文字幕，从而像图片那样俩字幕全是英文的，这个是插件出了问题吗，还是不适配哔哩哔哩了？

**Comment by MustForgiveHer** [comment]
看了一会，是failed to fetch，看来是需要付费了

**Comment by MustForgiveHer** [comment]
感谢，查出问题来了，我的网访问api.dualsub.xyz加载不出来，用流量没有问题，是我的网络的问题
