### ISSUE TITLE
翻译错误:SyntaxError: Unexpected token I in JSON at position 0

### ISSUE THREAD

**Issue by SinfoniaRO** [muzuiget/dualsub-support#324]
![QQ图片20210815112542](https://user-images.githubusercontent.com/88956299/129466116-c387c6cd-eb40-4dc0-bd1d-94d8e39fe301.png)

**Comment by SinfoniaRO** [comment]
好像是微软的问题，切成谷歌翻译正常了

**Comment by muzuiget** [comment]
我测试了一下，微软也是正常，如果你确定能 100% 重现，请贴下视频地址。

**Comment by muzuiget** [comment]
我测试了一下，微软也是正常，如果你确定能 100% 重现，请贴下视频地址。
