### ISSUE TITLE
关于哔哩哔哩港澳台专区的建议

### ISSUE THREAD

**Issue by 123456qewret** [muzuiget/dualsub-support#325]
首先感谢作者的开发与维护，dualsub是一款非常好用的字幕插件。
现在网页端bilibili港澳台专区的动画下，dualsub无法识别它的字幕，自带的cc字幕有个大黑底很丑，观感较差，希望后续dualsub可以支持，感谢！
播放器版本3.04
无法识别的动画示例：https://www.bilibili.com/bangumi/play/ep414593
截图：
![image](https://user-images.githubusercontent.com/57819273/129474936-1c0c82b3-e1d6-425a-976c-e13a4fdcd312.png)
另外不知道能不能对您的开发提供帮助，之前在用的字幕下载脚本近期解决了一个类似的问题，如果有需要的话您可以看一下。
https://github.com/indefined/UserScripts/issues/68
再次感谢您的付出，祝您生活愉快。

**Comment by muzuiget** [comment]
我都不知道港澳台专供动画竟然是 CC 字幕，我晚点研究下。

**Comment by 123456qewret** [comment]
> 我都不知道港澳台专供动画竟然是 CC 字幕，我晚点研究下。

感谢！期待下一个版本。

**Comment by muzuiget** [comment]
v1.65.4 已发布。

如果要自动缩放字体，需要在扩展设置的“插件”里重置一下，这样会重新生成字体缩放样式。

**Comment by 123456qewret** [comment]
已经试过了新版插件，可以正常显示了，自动缩放在重置之后也可以用了。非常感谢您采纳我的建议！

**Comment by CloudyEagle** [comment]
![image](https://user-images.githubusercontent.com/58777085/163624673-7ad735e7-f7d0-48b1-9f23-91c821076031.png)
所以我现在港澳台只能下载，不能挂载怎么用脚本解决，
因为我想下载港澳台的CC在幕后，再本地简繁转换后挂载回去

**Comment by muzuiget** [comment]
你直接用 Dualsub 的机器翻译功能不就行吗？翻译到中文是免费的。
