### ISSUE TITLE
按照字幕快进快退

### ISSUE THREAD

**Issue by ficapy** [muzuiget/dualsub-support#326]
请问能否通过自定义脚本，达到按字幕快进快退的效果，比如快退到本条字幕开始的时间点，再按一次快捷键快退到上条字幕开始

**Comment by muzuiget** [comment]
所有网站的话，不行。

如果是 YouTube，可以打开自带“解说词”面板，这样可以点击跳转。也可以脚本读取这个信息来实现，但是其它网站就不行。
