### ISSUE TITLE
建议:请对收费模式和定价 做一个市场调查，然后再调整商业化运营策略。

### ISSUE THREAD

**Issue by jesuser** [muzuiget/dualsub-support#327]
如题 一个友善的建议。

**Comment by muzuiget** [comment]
不知道你指的“市场调查”是哪种，如果是指出钱找人来搞那种，那就免了，我更相信自己的服务器访问日志做出来的统计。

实际上开始收费前，已经做过一次[免费发放账号测试](https://github.com/muzuiget/dualsub-support/issues/297)，连免费账号都不会申请的人，多半也不会是潜在的付费用户。

[已经改过一次收费模式和定价了](https://github.com/muzuiget/dualsub-support/issues/321)，按时间效果确实比按流量好，断时间内不会再改了，起码足够一个月才做改动决定。

**Comment by jesuser** [comment]
你可以参考一下 国内和国际互联网公司的月度会员费，以及用户能够接受的费用，Dualsub服务费溢价过高，甚至高于互联网信息服务费的市场价2倍。

**Comment by muzuiget** [comment]
不同软件之间无法比较，再说大厂有大厂的玩法，比如广告、股价等等，让一个独立开发者按大厂的标准收费，太难了。

**Comment by pcone-mm** [comment]
太贵了呜呜
