### ISSUE TITLE
Netflix更新播放界面，dualsub无法读取字幕

### ISSUE THREAD

**Issue by LucasZhao22** [muzuiget/dualsub-support#328]
如题
![image](https://user-images.githubusercontent.com/49909340/130317519-ba1503bc-5e35-4ce6-9a9e-b6d8cb246e6c.png)

**Comment by muzuiget** [comment]
按 F12 弹出开发者控制台，看看收否有错误输出。

**Comment by LucasZhao22** [comment]
> 按 F12 弹出开发者控制台，看看收否有错误输出。

![image](https://user-images.githubusercontent.com/49909340/130319614-9cd35063-aa62-46d9-85e3-e43c916e16f8.png)

**Comment by muzuiget** [comment]
控制台有中文输出，你这是有在用其它 Netflix 扩展吗？有没有试过禁用排除下冲突？

**Comment by LucasZhao22** [comment]
> 控制台有中文输出，你这是有在用其它 Netflix 扩展吗？有没有试过禁用排除下冲突？

关闭所有其他扩展后，仍读取不到字幕，不是冲突问题，此时控制台是空白的，没有输出
![image](https://user-images.githubusercontent.com/49909340/130422449-7f2e9cb3-0335-4492-8a05-05b1c18d8543.png)

**Comment by muzuiget** [comment]
我没有 Netflix 账号了，你是否愿意提供账号以供测试。如果愿意，通过[电邮联系我](https://www.dualsub.xyz/zh/docs/contact)。

**Comment by LucasZhao22** [comment]
> 我没有 Netflix 账号了，你是否愿意提供账号以供测试。如果愿意，通过[电邮联系我](https://www.dualsub.xyz/zh/docs/contact)。

可以提供，我给您发送到您的个人邮箱

**Comment by LucasZhao22** [comment]
不好意思，还有一个小小的请求，edge扩展商店可以麻烦也更新一下嘛

**Comment by muzuiget** [comment]
Edge 商店审核一次最少要 7 天，即使新版本提交上去，也不能马上更新出去的，所以只能用 Chrome/Firefox。

ZigZagHumor ***@***.***> 于2021年8月23日周一 下午10:40写道：
