### ISSUE TITLE
使用自动选择后能否手动开关字幕

### ISSUE THREAD

**Issue by animaio** [muzuiget/dualsub-support#332]
有些繁体简体内嵌字幕的视频不需要翻译，但是开启自动选择功能后会自动使用字幕，能否增加个临时禁用开关。

**Comment by muzuiget** [comment]
可以试下快捷键方式 https://github.com/muzuiget/dualsub-support/issues/288

**Comment by animaio** [comment]
> 可以试下快捷键方式 #288

好的马上试试，谢谢作者哈！

**Comment by muzuiget** [comment]
自动选择接下来会有一波大改。

打算把代码编辑框移动到“插件”里面，即“自动选择”作为插件的一种类型，这就能像样式那样，用户可以预先定义多套自动选择方案，然后在不同网站上启用，或者临时切换。

**Comment by animaio** [comment]
> 自动选择接下来会有一波大改。
> 
> 打算把代码编辑框移动到“插件”里面，即“自动选择”作为插件的一种类型，这就能像样式那样，用户可以预先定义多套自动选择方案，然后在不同网站上启用，或者临时切换。

哦哦可以的，希望简单模式也能用自动选择！（̶能̶白̶嫖̶

**Comment by muzuiget** [comment]
可以的，分成两种类型就行。
