### ISSUE TITLE
能否在标准模式使用youtube翻译数据

### ISSUE THREAD

**Issue by iamcxds** [muzuiget/dualsub-support#333]
现在似乎非付费用户只能通过简单模式加载youtube翻译字幕，但是简单模式的显示效果不如标准模式。
能否让标准模式下也可以选择使用youtube的翻译数据，而不依赖服务端。

**Comment by muzuiget** [comment]
不能，两种模式的处理字幕流程完全不同，“标准模式”的机器翻译真的是对任意文本进行翻译，而“简单模式”的机器翻译只是用来选择另一个字幕文件而已。

你可以用第三方工具下载 YouTube 的机器翻译字幕，例如 [downsub](https://downsub.com/)，然后用[加载外部字幕文件](https://www.dualsub.xyz/zh/docs/load-external-subtitle-files)的方式来显示，这样你就明白两种模式的区别。

“简单模式”就是将两个字幕文件合并城一个字幕文件，“欺骗”YouTube 的原生播放器，所以显示效果也是原生的。

实际上你仍然可以通过 CSS 来控制显示效果。在扩展设置页面的”插件“，默认就是生成一个"YouTube 简单模式“样式插件，以实现不同行不同字体大小，你也可以改动这些代码符合你需求。

**Comment by iamcxds** [comment]
那自动选择还可以在简单模式应用吗

**Comment by muzuiget** [comment]
自动选择近期会改，见 https://github.com/muzuiget/dualsub-support/issues/332#issuecomment-911811185
