### ISSUE TITLE
请问能够下载已经优化过的字幕吗？

### ISSUE THREAD

**Issue by chenyihao009** [muzuiget/dualsub-support#334]
最好是Sr格式的，如果付费功能里能支持我也愿意支持

**Comment by chenyihao009** [comment]
srt格式，打错了

**Comment by muzuiget** [comment]
不能， 即使付费也不能，见 https://github.com/muzuiget/dualsub-support/issues/253#issuecomment-828055531

**Comment by chenyihao009** [comment]
那我现在从youtube上下载的字幕太散装了，就像你案例里那样，应该怎么办才好？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月3日(星期五) 下午2:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [muzuiget/dualsub-support] 请问能够下载已经优化过的字幕吗？ (#334)





 
不能， 即使付费也不能，见 #253 (comment)
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by muzuiget** [comment]
你只能录屏，然后完整播放一次视频。

实际上一开始时按字符数计费，我还可以做搞个独立网站对 YouTube 做这种功能，但现在改成包月了，因为很容易被刷流量，我就不愿意了。要么就当成两个不同的产品分开收费，导出功能按字符数计费，但又容易被喷一鱼两吃。

归根到底，就是潜在用户量实在太少了，少到不值得去做，时间成本都回不了。况且类似的工具没一千也有八百，可代替方案实在太多。

**Comment by chenyihao009** [comment]
就是youtube显示｛此翻译请求被拒绝，需要付费账号｝
是的我发了图片




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年10月8日(星期五) 下午3:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [muzuiget/dualsub-support] 请问能够下载已经优化过的字幕吗？ (#334)





 
你是贴了图片吗？我看不到。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenyihao009** [comment]
请问能开发票吗。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年10月8日(星期五) 下午3:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [muzuiget/dualsub-support] 请问能够下载已经优化过的字幕吗？ (#334)





 
对，见文档 https://www.dualsub.xyz/zh/docs/paid-features/overview
 
但是即使付费，还是没有导出 srt 功能。
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by muzuiget** [comment]
不能，我没有开公司，纯个人交易。

**Comment by muzuiget** [comment]
请你发到购买页面里面留的那个邮箱地址，你刚刚是通过邮件回复到 GitHub 的，是公开的。
