### ISSUE TITLE
调整一下定价

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#335]
收费已经超过一个月了，统计了一下日志，收集了一些资料，定价调整如下：

* 30 天的月套餐价格降 10 元，现价为 50 元。
* 取消 3 天的日套餐，现在只有月套餐了。
* 实行“价格保护”策略。

价格保护由计费系统自动执行，无需手动申请，在扩展里检查一下有效期即可。

对已购买用户影响
----------------

### 在 2021-09-05 12:00:00 +0800 前以 60 元购买的账号

因为价格保护，已自动延长 6 天有效期，公式 `60 / (50 / 30) = 36`，按新价格为 36 天，所以补偿 6 天有效期。

同时延迟发货补偿也增加到 1 天，所以实际可以 37 天。

因为“包月模式”开始到现在还不够 30 天，所以现有包月用户不需要马上续费。

### 在 2021-08-12 00:00:00 +0800 前以”按流量计费“的购买的账号

前情提要 https://github.com/muzuiget/dualsub-support/issues/321

现已只接受退款（因为我想系统里都是包月账号，方便后续调整价格）。

发送邮件到 `dualsubstudio+alipay@gmail.com`，标题为 `申请退款`，邮件里说明你的所有支付宝订单号，以及收钱码截图（因为支付宝不允许通过原订单退款了）。

所以即使你想买月套餐，也请先退款，然后再付款 50 元。

**Comment by lilyblessing** [comment]
现在这套餐对于油管看的不多的轻量用户有点太贵了..
我104天平均每天2k5的字符量，共计263,200
以前旧10元套餐那个字符量差不多刚好够用，可以出个低价限制字符量的套餐吗？

**Comment by muzuiget** [comment]
收费模式有人欢喜有人愁，但以开发者角度看，目前来说包月模式胜出。因为包月用户更可能重度用户，更可能持续付费，而且售后问题更少。

另外技术上原因，正如我之前所说，绝大部分人都不知道怎么计算流量的，文档也是写了也没人看的，还不如统计下每月平均流量当定价，换成包月。

**Comment by kongran-111** [comment]
我觉得 .. 30每月我立即买，甚至可以在便宜点  薄利多销吧  现在这个套餐搞得我都好久不看教学视频了（平时大部分看的是这个）

**Comment by muzuiget** [comment]
所以说 1 元 1 天是心理价位么？

**Comment by wangxin6** [comment]
包月就是流量少的补贴流量多的。作者根据上月日志 + 合理的收入计算下月包月定价 + 价格保护，很合理。

**Comment by muzuiget** [comment]
对的，对于单一用户，其实是使用流量少的天数补贴使用流量多的天数。所以也干脆取消短期套餐，毕竟短期套餐肯定平均每天用得流量多。

反正对于刚需用户，什么时候买都一样。现在就是慢慢调整价格吸引那些徘徊在心理价位的用户。

**Comment by TANANIS** [comment]
你好不好意思，想請問能否有更多的支付方式可供選擇呢?
例如paypal之類的?

**Comment by ShuaiMakMak** [comment]
月付30的话立刻订

**Comment by kevinma321** [comment]
在 2021-09-05 12:00:00 +0800 前以 60 元购买的账号
因为价格，已自动延长 6 天有效，公式60 / (50 / 30) = 36，按新为 36 天，证明 6 天有效。

同时延迟证明也增加到 1 天，所以实际上可以 37 天。

因为“包月模式”开始还原生态30天，所以现有包月用户无需立即续费。
----------------------------------------------------------------------------------------------------------------------------------------------
我的是9月4日22点40多付的60元，之前查到有效期大概是10月11日左右，可是今天上午就突然不能使用了，而且查询有效期的按钮，点了，什么也查不到了？怎么会突然过期呢？邮件写了很多封了，也没有回复，问题也没有解决，都快一天了，请帮我尽快解决问题。

**Comment by muzuiget** [comment]
楼上的问题已经解决，是用户暂时连不上服务器，而又把“统计”面板的“当前时间”当成有效期，计费系统本身没有问题。

**Comment by xuwhao** [comment]
I also think $10/month is too much.   Whether it is possible to consider some kind of preferential education policy for students. Dualsub is a nice work,  and the largest number of potential paying customers should be students, especially cs students who are willing to pay for the softwares.
