### ISSUE TITLE
Fixing the punctuation marks direction in the RTL languages

### ISSUE THREAD

**Issue by Essam3152** [muzuiget/dualsub-support#337]
Hi, in Netflix the punctuation marks in the RTL languages (Arabic) are not displayed in the correct direction, it looks like this

![11](https://user-images.githubusercontent.com/87686356/132486274-8907e566-4b87-4ca0-a79f-649706808ede.png)

when it should look like this

![22](https://user-images.githubusercontent.com/87686356/132486345-b4ce7b10-74c7-4c9e-a399-1d37ad5f7f53.png)

Fixing this problem could be done by adding

`"&rlm;":"‫"`

there is a hidden Unicode control character between "" (202B   RIGHT-TO-LEFT EMBEDDING)

https://unicode.scarfboy.com/?s=%22%26rlm%3B%22%3A%22%E2%80%AB%22

the same hidden Unicode control character that is used in Subtitle Edit to fix the punctuation marks direction in the RTL languages.

![333](https://user-images.githubusercontent.com/87686356/132488159-6d6d6652-add8-443b-8fbd-651a2ffcfe88.png)

I tested it by myself and it worked just fine.

**Comment by muzuiget** [comment]
I can't copy and parse your code to my code editor.

It better to use `\uXXXX` to escape the Unicode character, so can this work?

```
'&lrm;': '\u202b',
```

Here is I test in console:

![Screenshot_20210908_183519](https://user-images.githubusercontent.com/330812/132494701-ba7153b9-acc7-4894-bce4-e625febc5b0d.png)

**Comment by muzuiget** [comment]
Please also read this issue https://github.com/muzuiget/dualsub-support/issues/129

**Comment by Essam3152** [comment]
Thank you, this worked.

`'&lrm;': '\u202b',`

for more information about this problem see here.

https://github.com/rsimmons/subadub/commit/c585fda90c8c5cb742f4fcaac693bd066f25b55a

**Comment by muzuiget** [comment]
After reading the wiki https://en.wikipedia.org/wiki/Right-to-left_mark, I think we should use `\u200f`. Current code is just remove the `&rlm;`.

So the change should be:

```
-    '&lrm;': '',
+    '&lrm;': '\u200e',
+    '&rlm;': '\u202f',
```

**Comment by Essam3152** [comment]
This is a subtitle file you could use for testing.

[Spider-Man.2.2004.zip](https://github.com/muzuiget/dualsub-support/files/7128408/Spider-Man.2.2004.zip)

**Comment by Essam3152** [comment]
This is how inputstream.adaptive fixed this problem

https://github.com/xbmc/inputstream.adaptive/commit/0c3f167259454d628ca883358ef359618d770909

**Comment by muzuiget** [comment]
It is difficult for me to recognize Arabic characters.

**Comment by Essam3152** [comment]
The full stop must be to the left, that is all what you need.

**Comment by muzuiget** [comment]
The XBMC code show that we should use `\u200e` and `\u200f`. as the wiki says:

> In Unicode, the RLM character is encoded at U+200F RIGHT-TO-LEFT MARK (HTML &#8207; · &rlm;). In UTF-8 it is E2 80 8F. Usage is prescribed in the Unicode Bidi (bidirectional) Algorithm.[1]

**Comment by Essam3152** [comment]
It did not work, I tried it now.

![33](https://user-images.githubusercontent.com/87686356/132500945-1a591efa-bf92-4a31-86aa-6e92db35de6b.png)

`l={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"',"&#39;":"'","&lrm;":"","&rlm;":"\u200f"}`

**Comment by muzuiget** [comment]
As the issue https://github.com/muzuiget/dualsub-support/issues/129 says, you should add the the CSS `direction: rtl;` to the HTML node.

**Comment by Essam3152** [comment]
I know this problem very well, and the fix that is done in Subadub and  inputstream.adaptive was my idea, I deal with the subtitles a lot, please take my word in this problem.

**Comment by Essam3152** [comment]
This was the fix that is done by the developer of inputstream.adaptive and it did not work

https://github.com/xbmc/inputstream.adaptive/commit/d713b9557f5d0088a17ff0bca7092f7291445430

this is the one that worked

https://github.com/xbmc/inputstream.adaptive/commit/126101883b4541ebca93925d803d8de03b69adba

Until Netflix made some changes in the subtitles and we had to find a new fix.

**Comment by muzuiget** [comment]
Note: https://github.com/muzuiget/dualsub-support/issues/337#issuecomment-915121227 I have a typo, it should be `'&rlm;': '\u202b',`.

**Comment by muzuiget** [comment]
Alright,  replace `&rlm;` to `\u202b`.

How about `'&lrm;`? replace it with empty string or `\u202a`?

**Comment by Essam3152** [comment]
For me I can not see the difference.

**Comment by muzuiget** [comment]
For consistency, I choose `\u202a`.

```
-    '&lrm;': '',
+    '&lrm;': '\u202a',
+    '&rlm;': '\u202b',
```

**Comment by muzuiget** [comment]
v1.68.0 released.

**Comment by Essam3152** [comment]
Thank you so much, It works perfectly.
