### ISSUE TITLE
edge更新

### ISSUE THREAD

**Issue by Timelord612** [muzuiget/dualsub-support#338]
请问一下edge 商店里面的Dualsub还停留在1.65版本。最近会更新吗？
要有就是Netflix的翻译是算收费服务吗?

**Comment by muzuiget** [comment]
Edge 漫长的审核时间，除非有严重 bug，没必要就不更新了，见 #269。其实 Edge 浏览器也可以安装 Chrome 商店的版本。

只有依赖 Dualsub 自己的服务器才会收费服务，即使用“标准模式”的“机器翻译”菜单（第二列菜单）。

网站自己提供的人工翻译字幕是不收费的，因为完全在你的浏览器上本地处理。

**Comment by Timelord612** [comment]
请问如何在edge上更新Chrome版本的Dualsub呢？

**Comment by muzuiget** [comment]
用 Edge 直接打开 [Chrome 商店地址](https://chrome.google.com/webstore/detail/dualsub/gnlibmlfpencglodjpgnalbdebfhpmfp)不就能直接安装了吗？

**Comment by Timelord612** [comment]
好的明白了，抱歉啊没有这方面的经验，问了一个这么白目的问题。现在知道了。谢谢
