### ISSUE TITLE
B站播放视频时出现字幕语言显示关闭的现象，您看下是哪的问题？

### ISSUE THREAD

**Issue by muyisherry** [muzuiget/dualsub-support#339]
而且谷歌和edge装完插件后结果都是这样，应该能排除其他插件干扰的问题吧。

**Comment by muyisherry** [comment]
我刚开始试着用github，不太熟练，是像我这样反馈吗？

**Comment by muyisherry** [comment]
<img width="415" alt="屏幕截图 2021-09-18 230240" src="https://user-images.githubusercontent.com/67221999/133893281-22930ee6-8e3a-442c-975c-d794d4e9cc5d.png">
 控制台这个样子，

**Comment by muyisherry** [comment]
<img width="945" alt="屏幕截图 2021-09-18 224822" src="https://user-images.githubusercontent.com/67221999/133893297-2c630e18-1084-47c9-8358-28b448f83543.png">
 界面这个样子，

**Comment by muyisherry** [comment]
<img width="523" alt="屏幕截图 2021-09-18 230524" src="https://user-images.githubusercontent.com/67221999/133893348-c592b212-6719-4e0f-bd64-5a3d30cdbad0.png">
界面 这个样子，

**Comment by muzuiget** [comment]
你不如把视频地址贴上来。

**Comment by muyisherry** [comment]
https://www.bilibili.com/video/BV1xt411N7QS?from=search&seid=11228700071258689158&spm_id_from=333.337.0.0
好的。但是我遇到问题就是整个B站都不显示字幕了。但是像wetv就没问题。
![Uploading 屏幕截图 2021-09-19 165608.png…]()

**Comment by muzuiget** [comment]
你这个视频本来就是无字幕的，需要上传者自己添加了"CC 字幕“才行，即软字幕。

比如这个视频 https://www.bilibili.com/video/BV1Gf4y1y7wc

**Comment by muyisherry** [comment]
老铁，还是不行啊
<img width="973" alt="屏幕截图 2021-09-21 153933" src="https://user-images.githubusercontent.com/67221999/134131156-eca580b2-f4e0-45e9-9ab1-29b5b450061d.png">

**Comment by muyisherry** [comment]
老铁你再看看

**Comment by muzuiget** [comment]
我以为我回复了。

你是不是遇上 B 站的新版布局？或者在浏览器的扩展详情页，检查一下是否有 `www.bilibli.com` 权限。

**Comment by muyisherry** [comment]
权限页面是这个吧   好像没问题   新版布局这问题 我不知道在哪看   怎么解决
<img width="704" alt="屏幕截图 2021-09-23 212959" src="https://user-images.githubusercontent.com/67221999/134515968-06dcca03-20a8-487c-957b-51da7d009761.png">
我把开发者页面也贴上来   不知道这个error能说明啥吗
<img width="1085" alt="屏幕截图 2021-09-23 213249" src="https://user-images.githubusercontent.com/67221999/134516432-e3be6cdb-f42d-4a56-8242-ec88e7fb2710.png">
<img width="1067" alt="屏幕截图 2021-09-23 213313" src="https://user-images.githubusercontent.com/67221999/134516515-82f44c2e-c622-4d6f-8a63-eada366adb4a.png">

**Comment by muzuiget** [comment]
那个错误，看上去是你在用其它 B 站油猴脚本造成的，禁用一下相关脚本再试。

**Comment by muzuiget** [comment]
缺少后续反馈，关了。
