### ISSUE TITLE
Subtitle delay and 'auto-enable subtitle'

### ISSUE THREAD

**Issue by andradadad** [muzuiget/dualsub-support#34]
1. Many subtitles, specially those who come from tvshows, have huge delays that could be fixed by a shortcut to forward/backward the subtitles. I tried to look even for third-party addons and couldn't find, so I believe this would be a huge improvement to your addon, since subtitles must be adjusted very frequently.
Controls have been used on this addon to adjust speed, and I believe it could help you on coding:
https://github.com/fx4waldi/playbackSpeed

2. I always have to press on subtitles, and the addon could easily enable them by default.

**Comment by muzuiget** [comment]
I didn't get your point. Do you want to adjust the time between subtitle and video? But your link is a playback speed control exntension, YouTube player already support this feature.

**Comment by andradadad** [comment]
1. Delayed subtitles in relation to the video. +1000ms by some shortcut, or like a panel in playbackspeed -1000ms or +4000...

**Comment by muzuiget** [comment]
Can you provide a test video url?

**Comment by andradadad** [comment]
https://youtu.be/k-inBwpOTCg?t=113
After 2 minutes, it just go way abroad than the dialog. So a rewind button or shortcut to take it a few seconds back would be great.

**Comment by andradadad** [comment]
https://www.youtube.com/watch?v=TToGsLQBKmA
Another example of a very delayed subtitle that could only be fixed in dualsub with some feature to increase or decrease the subtitle position in the video.

**Comment by muzuiget** [comment]
Interesting, why all the subtitle content is uppercase?

**Comment by andradadad** [comment]
I've seen you changed the uppercase in dualsub, could you also do something about pausing/spacebar moving the subtitles up, and after few seconds of resume, subtitles move slightly down.
The ideal is a fixed position pausing/resuming.

**Comment by muzuiget** [comment]
You can use CSS as below:

```
.ytp-caption-window-bottom {
    margin-bottom: 50px !important;
}
```

**Comment by andradadad** [comment]
Preferred language selection isn't saving the input on the newest version. Although if you select individually, the language choices are saved to the single video.
Also, set "automatic subtitles' auto-enable.

For the CSS, I'm using a text-size:
.captions-text {
    font-size: 36px !important;
}

Which conflicts with this code to prevent spacebar moving.

**Comment by muzuiget** [comment]
> Preferred language selection isn't saving the input on the newest version. Although if you select individually, the language choices are saved to the single video.
Did you clear the browser history? The config save to YouTube localStorage object.

> Which conflicts with this code to prevent spacebar moving.
See https://dualsub.netlify.com/setting?id=example-set-the-font-size-to-some-value

**Comment by andradadad** [comment]
Can you make self-uploaded subtitles to dualsub?

**Comment by muzuiget** [comment]
Currently, you can download the video and the .ass file, then play them on desktop video player.

**Comment by andradadad** [comment]
Uploadable, not downloadable. I want my subtitles on the youtube's default player.

**Comment by muzuiget** [comment]
For these kind of features, you can use other exntension.
