### ISSUE TITLE
希望可以支持视频网站vimeo和教育网站Khan Academy

### ISSUE THREAD

**Issue by eAtlantis000** [muzuiget/dualsub-support#340]

**Comment by muzuiget** [comment]
vimeo 技术上目测应该可以支持，但是它感觉太封闭了，登录还要搞验证码，不明白有那些特色视频有字幕的。

Khan Academy 这个网站，它的视频就是嵌入 YouTube 的，所以没必要特别支持了，用新标签页打开到 YouTube 看就好了。

**Comment by muzuiget** [comment]
v1.71.0 已发布，添加对 vimeo 的支持。

vimeo 仅支持 https://vimeo.com/470020599 这种地址，有些第三方引用地址是 https://player.vimeo.com/video/470020599 需要自己手动改一下，因为扩展没有请求存取 `player.vimeo.com` 的权限。
