### ISSUE TITLE
請問關於付款方式

### ISSUE THREAD

**Issue by TANANIS** [muzuiget/dualsub-support#341]
您好不好意思
想請問關於付款方案能否有更多選擇
例如paypal或者其他平台之類的
在台灣的使用者也很想要付費支持
但是支付寶的實名制方案目前我自己測試是無法使用的
希望能有更多付款方法
感謝!

**Comment by muzuiget** [comment]
本来有 PayPal 的，但是一收款就被风控了，要提交各种资料等解锁，麻烦得很，见 https://github.com/muzuiget/dualsub-support/issues/310

其实我是可以接受 [Steam 礼品卡](https://store.steampowered.com/digitalgiftcards/?l=schinese)的，聊胜于无了。
