### ISSUE TITLE
Please Support Apple TV+

### ISSUE THREAD

**Issue by vizmoe** [muzuiget/dualsub-support#343]
Website: https://tv.apple.com/

**Comment by muzuiget** [comment]
There is very difficultly for me to support  Apple TV.

Apple TV is not available on China Mainland, that mean if I test it, I need access it with a US proxy, and an US region Apple ID.

And I heard Apple ID has strict and unclear "risk control", that mean if Apple found if a Apple ID has login in difference region IP or device, Apple may ban the Apple ID, this scare me.

**Comment by jhhuang96** [comment]
@muzuiget Any plan on support Apple TV+? As I know, Apple TV+ is now claiming 3 months free trial in US/HK and other regions. And it is very easy to register a foreign App Store account. I also agree with @vizmoe about risk control. I suggest author can have a try. BTW, Apple TV+ have won the award in Oscars!

**Comment by muzuiget** [comment]
I need someone borrow me a Apple ID acount which can use in https://tv.apple.com/

I can't register a US Apple ID account myself because of registration verification.

**Comment by jhhuang96** [comment]
@muzuiget  I think the easiest way to experience Apple TV+ is to buy a shared account in Taobao.
