### ISSUE TITLE
Doesn't work in firefox nightly edition

### ISSUE THREAD

**Issue by livrth** [muzuiget/dualsub-support#344]
For firefox nightly edition 94.0a1 (2021-09-18) (64-bit) in Linux system, it only shows a `Quick Settings` button, there aren't any mode I can choose, it looks so wired and can't work for any website. the screenshot is there:

![image](https://user-images.githubusercontent.com/45538642/134918028-452f9cdb-1a44-4ee3-b52f-0064ce3f7092.png)

Hope you can fix it, thanks!

**Comment by muzuiget** [comment]
Got it, I will check out later.

**Comment by muzuiget** [comment]
Thanks for reporting, this bug fixed. The latest version `v1.70.1` should works on Firefox 92/93/94.

**Comment by livrth** [comment]
Thanks!
