### ISSUE TITLE
希望可以支持discoveryplus.com

### ISSUE THREAD

**Issue by promobob** [muzuiget/dualsub-support#348]
请问可否支持www.discoveryplus.com探索频道? 他的纪实节目品质很高, 谢谢!

**Comment by muzuiget** [comment]
见 #284，除非这段时间它改版了，提供独立字幕文件了，否则支持不了。

**Comment by promobob** [comment]
谢谢!

**Comment by muzuiget** [comment]
如果你想让我重新测试一下， 需要借我一下账号，可以发送到我的邮箱。
