### ISSUE TITLE
Dualsubs shows only Close (0) in Netflix

### ISSUE THREAD

**Issue by boathouse2112** [muzuiget/dualsub-support#349]
Hello,

Recently, Dualsub has begun showing only Close(0) on Netflix, for shows that have multiple subtitles. 

![screenshot](https://imgur.com/a/6jebYUI)

Subtitles work normally in Youtube.

Running in Firefox 93 on Mac M1

**Comment by muzuiget** [comment]
Maybe Netflix testing new design for your account.

Open https://www.netflix.com/DoNotTest to disable the testing feature.

**Comment by boathouse2112** [comment]
Ah, I set testing to "off", and it's working now! Thanks.
