### ISSUE TITLE
希望支持在线学习网站 https://courses.baeldung.com/ 谢谢

### ISSUE THREAD

**Issue by wayrt7** [muzuiget/dualsub-support#350]
希望支持在线学习网站 https://courses.baeldung.com/ 谢谢

**Comment by muzuiget** [comment]
研究了一下，支持价值不大，不打算支持了。

1. 太冷门的，只有 50 个课程，相当于一个 YouTube 个人频道而已。

2. 网站样式代码写的太宽松，会扰乱 Dualsub 自己的字幕布局，当然花点时间可以还原回来。

3. 根本原因，它的字幕做得毫无诚意，根本就是机器识别出来的字幕，然后人工校对一下拼写和加上标点。

![Screenshot_20211120_054914](https://user-images.githubusercontent.com/330812/142696272-ae113105-05ec-4de3-980f-32def066eae3.png)

这种我称为“伪人工字幕”，即在一条字幕中间存在句号，而又不是以标点结尾（也就是一句话拆开了两条字幕显示），会极大影响翻译质量，因为会干扰断句处理，这样原文译文就很难对应起来。这甚至不如 YouTube 的自动字幕，至少机器识别出来的字幕带有每个单词的精确时间，这样可以方便二次处理重新断句。

**Comment by wayrt7** [comment]
好的，还是感谢抽出时间研究这个 issue
