### ISSUE TITLE
HBO MAX无法显示字幕

### ISSUE THREAD

**Issue by AisonSu** [muzuiget/dualsub-support#351]
可以识别到字幕，但是选择之后无法显示出来

**Comment by muzuiget** [comment]
我现在没账号了，是否愿意借用一会来测试？

**Comment by AisonSu** [comment]
已发送给您

**Comment by muzuiget** [comment]
v1.76.7 已发布，但也是支持部分视频，因为有些视频不是单一的字幕文件，而是分片字幕文件，通常是 3 秒一个字幕文件，所以一个视频可能有上个字幕文件，技术上看就是类似“在线直播”的方式，难以对字幕文本二次处理。
