### ISSUE TITLE
disney+無法顯示字幕

### ISSUE THREAD

**Issue by ttanyasu831** [muzuiget/dualsub-support#352]
看到其他介紹好像都可以，但目前我的edge瀏覽器打不開字幕，已經把原始字幕關閉了，但還是無法使用，想請問是有甚麼前置的設定嗎?

**Comment by muzuiget** [comment]
你点击工具栏按钮会显示什么？

**Comment by ttanyasu831** [comment]
您好，感謝回覆
我的設定是這樣，但一樣沒有產生字幕

muzuiget ***@***.***> 於 2021年11月28日 週日 下午5:38寫道：

**Comment by muzuiget** [comment]
你贴了图片吗？没看到。

贴一下视频地址。

**Comment by ttanyasu831** [comment]
我剛剛關掉了一些插件後，好像就好了，也許是一些衝突導致的。

すすめ! ***@***.***> 於 2021年11月28日 週日 下午6:21寫道：
