### ISSUE TITLE
使用 Deepl 翻译显示 500

### ISSUE THREAD

**Issue by zkunn** [muzuiget/dualsub-support#353]

**Comment by muzuiget** [comment]
晚点再看看，但也有可能不修了，直接删掉这个引擎。

DeepL 其实没吹得那么神，翻译又慢又会漏译和多译。

**Comment by muzuiget** [comment]
我知道，所以我加上了“实验性”的字样，只是试水一下而已。

如果真的决定删除 DeepL，退款也是可以的（按时间比例退款），毕竟投入和收益不平衡，没必要折腾了。

**Comment by muzuiget** [comment]
抱歉，太麻烦了不修了，见 #354。
