### ISSUE TITLE
删除了对 DeepL 翻译引擎的支持

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#354]
在 2021-09-08 时发布了 v1.67.0，添加了 DeepL 翻译引擎支持，但设置选项中带有 `实验性` 的后缀。

到现在 2021-12-02，仍然无法保证稳定提供这个功能，所以在 v1.76.5 已经删除了对 DeepL 翻译引擎支持。

**对于付费用户**

如果你出于使用 DeepL 目的而付费，我可以对退款给你，退款金额按照失效时间在 API Key 有效期的比例换算。

通过更新日志，大概在 <code>2021-11-30 12:00:00 +0800</code> 这个时间失效。

你可以通过通过[邮件](https://www.dualsub.xyz/zh/docs/contact)申请退款。

* 在 <code>2021-12-07 00:00:00 +0800</code> **之前**申请，退款时间按照 <code>2021-11-30 00:00:00 +0800</code> 换算。
* 在 <code>2021-12-07 00:00:00 +0800</code> **之后**申请，退款时间按照申请邮件时间换算。

**Comment by Fallenpetal** [comment]
为啥我感觉DeepL翻译的比Google好？

**Comment by muzuiget** [comment]
现在大部分用户都升级到 v1.76.5 了。
