### ISSUE TITLE
api code500

### ISSUE THREAD

**Issue by Fallenpetal** [muzuiget/dualsub-support#355]
what's wrong?

**Comment by Fallenpetal** [comment]
![O~VVFOXV@Z9Z7F`40HCLP3J](https://user-images.githubusercontent.com/93207655/144706832-2be8a271-4b18-4cd8-a1dc-b939f8dd64ab.png)
![9{CYSXJ@LB5LF0TH`HWZXDW](https://user-images.githubusercontent.com/93207655/144706852-b423600b-adaf-4367-986c-060ee8b1ab0c.png)
怎么回事？这几天都这样，希望能解决一下，毕竟相当于这几天都浪费了

**Comment by Fallenpetal** [comment]
![V%R{56864}}_JN(E@ES$B7A](https://user-images.githubusercontent.com/93207655/144706890-5a289bbf-2792-4e97-8466-8cfd5de8df06.png)

**Comment by Fallenpetal** [comment]
不好意思没看到，由于引擎是用的DeepL，换成Google就好了

**Comment by muzuiget** [comment]
如果你及时更新到最新版本，会自动恢复回使用 Google 引擎的。

因为无法判断是否专门用 DeepL，所有账号都补了 5 天时间。

**Comment by Fallenpetal** [comment]
好的，我改成Google之后就好了，感谢回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "muzuiget/dualsub-support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月4日(星期六) 晚上7:23
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [muzuiget/dualsub-support] api code500 (Issue #355)





 
如果你及时更新到最新版本，会自动恢复回使用 Google 引擎的。
 
因为无法判断是否专门用 DeepL，所有账号都补了 5 天时间。
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
