### ISSUE TITLE
点击扩展图标，弹出的菜单无法被选择

### ISSUE THREAD

**Issue by inoton** [muzuiget/dualsub-support#356]
# 软件
```
OS: Fedora Linux 34
DE: GNOME 41.1
Windowing System: Wayland
Mozilla Firefox 94.0.2
Dualsub 1.76.5
```
# 问题
点击 `Dualsub` 扩展图标，弹出的菜单无法被选择。  
”字幕语言“、“主题样式”等无法弹出下拉菜单。

**Comment by inoton** [comment]
### 补充一张图片
![Screenshot from 2021-12-06 13-21-06](https://user-images.githubusercontent.com/54309560/144793552-21ce3491-51b1-4b93-9418-b66339796169.png)

**Comment by muzuiget** [comment]
这个问题我修复不了，我也是用 Linux，不过是 Fedora 和 KDE，点击菜单也是偶然有点问题的，就是菜单选项那个框会跑到屏幕别的位置上去的，重新点一下又会恢复正常。

这下拉菜单就是用 HTML 的原生 `<select>` 标签实现的，既然已经是原生的东西，没有什么能做的了。

其实 Firefox 在 Linux 下，它自身的搜索栏也是一直有这种问题的，莫名其妙的定位和窗口大小错误，移动一下窗口再点一下又好了。

一度怀疑是不是 Linux 的窗口管理的的一些特效设置问题，但是没找到头绪。

**Comment by muzuiget** [comment]
我看你是用 Wayland，感觉这种问题还是挺正常的。毕竟我的是 X11 都有这种问题。

**Comment by inoton** [comment]
> 我看你是用 Wayland，感觉这种问题还是挺正常的。毕竟我的是 X11 都有这种问题。

看起来不是 wayland 的锅，升级到 火狐 v95 以后问题解决了。

**Comment by muzuiget** [comment]
我的 Fedora 还未推送更新。

再观察下咯，有可能是幻觉，之前 Firefox 94 也是说会[修复图形问题](https://www.phoronix.com/scan.php?page=news_item&px=Firefox-94-EGL-Linux-Usage)的。

现在弹出页面在 Firefox 94 其实还有 bug 的，比如切换标签页时，滚动条会莫名其妙闪现一下，但是明明已经用 CSS 定义了最小高度，不应该出现滚动条的。

**Comment by inoton** [comment]
> 

嗯，bug 是有的。
这个扩展的问题从昨天到今天确认过 4 次以上（其中还重置过一次 ~/.mozilla .
次次能用。
