### ISSUE TITLE
Please support https://www.khanacademy.org/

### ISSUE THREAD

**Issue by oqqA** [muzuiget/dualsub-support#359]
url: https://www.khanacademy.org/

need registration

2 types of player are used, default and youtube

**Comment by muzuiget** [comment]
If the video player just an embed YouTube player, I recommend to open it in a new YouTube tab.

**Comment by oqqA** [comment]
I do that, but it's tedious :(

**Comment by muzuiget** [comment]
Supporting embedded players is very difficult, involving complicated page permissions and communication issues.

**Comment by oqqA** [comment]
I assumed this. But please at least check the possibility, there may be a similar solution in already supported sites.

The site is related to the study of mathematics, it is the best one that I have ever found, especially related to higher mathematics, I hope you at least take a look.. If not, then not, ok

**Comment by muzuiget** [comment]
Won't fix, see #414
