### ISSUE TITLE
希望能够添加暂停时显示当前字幕翻译的功能

### ISSUE THREAD

**Issue by ore3a** [muzuiget/dualsub-support#360]
目前插件是直接开启/关闭实时翻译功能。
作为一个半吊子英语学习者，看视频的时候，大部分词汇其实能懂，仅有部分句子里的词汇或者特殊句子有时不太能理解，对中文字幕的需求，其实只需要暂停时当前字幕翻译而已。但是这个自己暂停后手动去查工作量很大，直接全程双语翻译又会不由自主地只看中文字幕而忽视英文字幕（有一些语速飞起的视频更是），完全起不到预期的拓展目的。所以希望能添加平时开启英文字幕，然后仅暂停时会显示当前句子的翻译的功能。

**Comment by muzuiget** [comment]
可以用扩展的内部”插件“功能实现。

最简单是添加一个样式：

```
.dualsub-renderer .subtitle-2 {
    filter: blur(10px);
}
.dualsub-renderer:hover .subtitle-2 {
    filter: none;
}
```

勾选要启用的网站，然后“鼠标动作”设置为“文本选择”。

效果就是第二行字幕变模糊，当你移动鼠标上去时，就变回清晰。

**Comment by ore3a** [comment]
可行而且效果不错，感谢作者XD
