### ISSUE TITLE
2021-12-24 服务器故障

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#361]
升级服务器出现问题，大概半小时恢复。

**Comment by Ryuya1218** [comment]
目前youtube會顯示TypeError: Failed to fetch

**Comment by muzuiget** [comment]
服务器已经恢复了，可能是你的网络问题，直接访问 https://api.dualsub.xyz/ 试试，如果是 200 OK 的话，多半是扩展没有权限。

如果你是用 Edge 的话，需要手动把 `https://api.dualsub.xyz/*` 添加进扩展权限。

**Comment by Ryuya1218** [comment]
是200 OK沒錯，另外重新測試了一下，移除重新安裝後就可以了，感謝
