### ISSUE TITLE
希望能推出按量或按使用时间之类的付费套餐

### ISSUE THREAD

**Issue by defRoroNoa** [muzuiget/dualsub-support#362]
学生，使用频率中等而且很随机，希望能推出按量或按使用时间之类收费的套餐。

**Comment by muzuiget** [comment]
一开始就是按量收费的，然而发现一些人认为自己用量其实不高，总怀疑程序在“偷跑”，哪怕文档写得清清楚楚，但没人会看的，而是发邮件质问，互相产生不快。

为了一些用户节省几块钱，而让我需要花更多时间应付这些情况，比如修改计费系统和客户端程序，这样运营成本很高。

现在这个模式已经收费几个月了，显然是比按量收费更合理。
