### ISSUE TITLE
下载原文字幕

### ISSUE THREAD

**Issue by yilu1015** [muzuiget/dualsub-support#363]
有没有可能导出原文字幕，以便学习新词？

**Comment by muzuiget** [comment]
你可以在“快速设置"里把”鼠标动作“切换为“文本选择”，配合其它 Chrome 划词翻译扩展使用。

要下载原始文件，可以用 Chrome 开发者工具找出来，在”网络“面板搜 `.vtt` 之类的关键词即可。
