### ISSUE TITLE
如何在bilibili使用dualsub?

### ISSUE THREAD

**Issue by Fallenpetal** [muzuiget/dualsub-support#365]
![20220114161918](https://user-images.githubusercontent.com/93207655/149474754-2dc3ffc0-4f97-4a5e-b825-c108b1de6d84.png)
如图，在某个视频的页面并没有显示可翻译之处

**Comment by muzuiget** [comment]
你截图中的那个视频，我测试一下，可是正常的。

![Screenshot_20220115_043331](https://user-images.githubusercontent.com/330812/149581492-3da030c2-b0fe-47a6-91fc-8d580cb09d5c.png)

确保你更新到最新的浏览器以及 Dualsub，然后重置扩展设置为默认值。

**Comment by muzuiget** [comment]
截图中那个视频的字幕，我称之为“伪人工字幕“，本质转换自机器识别字幕，反而删掉了 YouTube 的机器识别字幕中的”字词的时间轴“，这意味着无法更具每个单词的出现时间重新断句，造成翻译效果很差。

所以有两个建议：

1. 直接在 YouTube 上看。
2. 把翻译模式设置为”普通“。

**Comment by muzuiget** [comment]
所以问题自己修复了？

**Comment by Fallenpetal** [comment]
感谢回复!我在Youtube上找到了相关视频 ，已放弃在Bilibili上看了，可以说已解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "muzuiget/dualsub-support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月16日(星期天) 凌晨5:35
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [muzuiget/dualsub-support] 如何在bilibili使用dualsub? (Issue #365)





 
所以问题自己修复了？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by muzuiget** [comment]
好的。
