### ISSUE TITLE
Hot star.com error please help

### ISSUE THREAD

**Issue by beachedlolli** [muzuiget/dualsub-support#366]
it used to work perfectly fine until few weeks ago the subtitle bar shows 0 languages 
how can i make the dual subs back :(

![F1435491-A8F5-4904-80A2-641EE4934246](https://user-images.githubusercontent.com/97769228/149600718-2dcb6336-c201-4786-b6f3-0a9afe5548b3.jpeg)

**Comment by beachedlolli** [comment]
to be specific it’s hotstar.com/th/….
it really used to work perfectly few weeks ago

**Comment by beachedlolli** [comment]
please reply please help

**Comment by muzuiget** [comment]
Got it, I will check it later.

**Comment by beachedlolli** [comment]
thank you so much appreciate the effort

**Comment by muzuiget** [comment]
v1.78.1 has been released, try to see if it has fixed the issue.

**Comment by beachedlolli** [comment]
yes it is working and i am so thankful to you

**Comment by beachedlolli** [comment]
service is top notch and my problems been fixed
