### ISSUE TITLE
没有控制两种字幕之间距离的选项吗？

### ISSUE THREAD

**Issue by uuu12333** [muzuiget/dualsub-support#367]
![屏幕截图 2022-01-20 204954](https://user-images.githubusercontent.com/33220975/150341775-e459a209-85a6-440d-ba68-0da9b1df972c.png)
上下两行字幕贴的太近了！！！

**Comment by muzuiget** [comment]
其实这个问题有点麻烦的，即时在 Dualsub 相同的配置下，不同网站和系统也可能使用不同字体，某些字体本来就设计的比较“饱满”，看上去空白毕竟比较小，像你这种情况，小字体加描边，进一步减少字体间的空白。

不过 Dualsub 始终都使用 HTML 来渲染，对这种特殊情况，能轻易用一点自定义 CSS 来解决的，你可以用在扩展设置的“插件”页面，新加一个“样式”类型，应用一些 CSS 代码。

有几个方案给你选择：

**强制增加间距**

```
.dualsub-renderer .subtitles {
    gap: 8px;
}
```

强制在两种语言之间设置为 `8px` 像素(默认是 `4px`)。

**添加字幕行高**

```
.dualsub-renderer .subtitle-2 .contents {
    line-height: 1.5;
}
```

设置第二个字幕为 `1.5` 单位行高(默认是 `1`)，行高效果好处是对于字幕太长时，自动换行造成的“软换行”也有效。

当然你可以两者同时使用：
```
.dualsub-renderer .subtitles {
    gap: 8px;
}
.dualsub-renderer .subtitle-2 .contents {
    line-height: 1.5;
}
```

**Comment by uuu12333** [comment]
> 其实这个问题有点麻烦的，即时在 Dualsub 相同的配置下，不同网站和系统也可能使用不同字体，某些字体本来就设计的比较“饱满”，看上去空白毕竟比较小，像你这种情况，小字体加描边，进一步减少字体间的空白。
> 
> 不过 Dualsub 始终都使用 HTML 来渲染，对这种特殊情况，能轻易用一点自定义 CSS 来解决的，你可以用在扩展设置的“插件”页面，新加一个“样式”类型，应用一些 CSS 代码。
> 
> 有几个方案给你选择：
> 
> **强制增加间距**
> 
> ```
> .dualsub-renderer .subtitles {
>     gap: 8px;
> }
> ```
> 
> 强制在两种语言之间设置为 `8px` 像素(默认是 `4px`)。
> 
> **添加字幕行高**
> 
> ```
> .dualsub-renderer .subtitle-2 .contents {
>     line-height: 1.5;
> }
> ```
> 
> 设置第二个字幕为 `1.5` 单位行高(默认是 `1`)，行高效果好处是对于字幕太长时，自动换行造成的“软换行”也有效。
> 
> 当然你可以两者同时使用：
> 
> ```
> .dualsub-renderer .subtitles {
>     gap: 8px;
> }
> .dualsub-renderer .subtitle-2 .contents {
>     line-height: 1.5;
> }
> ```

**Comment by uuu12333** [comment]
哦~好的~非常感谢。不过如果以后作者有充裕的时间、精力和兴趣的时候，还是希望能够添加上此功能~

**Comment by muzuiget** [comment]
通过添加 CSS 代码应用自定义样式就是解决方法，即使提供一个数值调整 UI 控件，本质也是内部生成这些 CSS 代码而已。
