### ISSUE TITLE
希望可以添加一个调节字幕时间轴的功能

### ISSUE THREAD

**Issue by haildceu1** [muzuiget/dualsub-support#368]
流媒体片源和字幕对应版本有相差时间，而且每个片都不一样，尤其是HBO Max。希望作者能添加调节时间轴的功能，谢谢！

**Comment by muzuiget** [comment]
因为 HBO Max 的视频是“合成”的，通常它会在正片前加一段其它视频的预告，所以播放进度的时间轴和字幕文件有偏移，这个偏移值其实能在字幕元数据文件里获得，实际上 Dualsub 就是自动做了这个偏移。

我还是更想从根本上解决这个问题，即把这个值也应用到用户添加的自定义字幕中，而不是加一个控件让用户调，毕竟这么已经支持了这么多网站都不需要让用户调整这种东西。

**Comment by haildceu1** [comment]
对不起现在才看到，期待作者早日达成目标，谢谢！

在 2022年1月28日星期五，muzuiget ***@***.***> 写道：

**Comment by ly4096x** [comment]
有时候外部字幕时间轴和原片不是完全匹配，本来就有点错位，还是希望能加一个控件来调时间轴偏移，这样可以适配更多的使用场景。虽然外部字幕可以通过编辑时间轴来调整偏移，但是这样得来回调很多次才能调到最佳，毕竟不如播放的时候直接调整偏移来得方便。而且有时候视频放着放着字幕时间轴偏移量还会变，也需要重新调整。如果能支持手动调整就最好了，谢谢！

**Comment by muzuiget** [comment]
还是不打算支持这种功能。
