### ISSUE TITLE
B站获取字幕列表失败

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#369]
似乎B站在测试什么，在 Windows 下偶然会获取不了字幕列表，而在 Linux 下却没问题。调试了一下，似乎是“播放策略”选择为 HEVC 的问题，因为两个系统的默认值不同。

临时解决方法，点击播放器的齿轮图标，在设置里将“播放策略” 选择 为 AVC 或 AV1，然后刷新页面。

![Screenshot_20220128_074854](https://user-images.githubusercontent.com/330812/151462261-3c855a70-5ee3-47cf-b0c4-5ee4726a2f82.png)

推荐 AVC，毕竟 AVC 就是 H264，Chrome 支持硬件解码，其余两个都不支持。

**Comment by IndifferentArea** [comment]
您好，请问字幕无法拖拽是正常现象吗

**Comment by muzuiget** [comment]
正常，原来是有拖曳的，后来删除了，因为无法保证在所有情况下可用（不同浏览器、页面布局、设备分辨率等等），所以改成自动定位了。

只有在“快速设置”里有一个“底部边距”选项来设置相对偏移（高一些/低一些）。

不过，用户想拖曳多半是为了避免遮挡原生播放器上的一些 UI 元素（例如进度条/预览缩略图），写点用户脚本和用户样式自己针对性处理下就好了，你可以此 Issues 系统搜下 `拖` ，已经有一些讨论。

**Comment by IndifferentArea** [comment]
好的谢谢！

>
