### ISSUE TITLE
有中文字幕的状态下，怎么优先只使用中文字幕？

### ISSUE THREAD

**Issue by LittleFlorence** [muzuiget/dualsub-support#37]
![图片](https://user-images.githubusercontent.com/17644631/71524827-32634600-290a-11ea-8992-6c26d9b291ab.png)
目前的语言设置是这样的，但是有中英文字幕的中文视频就会出现两个中文字幕，第二个字幕就是英文字幕翻译成的中文字幕，这种情况我只想要显示中文字幕，该如何设置呢？这种优先逻辑我搞不明白。

**Comment by muzuiget** [comment]
我更新了下文档，你看看现在是否更好理解？

https://dualsub.netlify.com/zh-cn/setting

**Comment by LittleFlorence** [comment]
> 我更新了下文档，你看看现在是否更好理解？
> 
> https://dualsub.netlify.com/zh-cn/setting

谢谢您。我现在把中文字幕放到优先选择语言的第一行了，虽然没试过实际效果，但感觉上通顺些了。
