### ISSUE TITLE
HBO MAX 不能用

### ISSUE THREAD

**Issue by svcarlos** [muzuiget/dualsub-support#370]
我测试了HBO MAX好几个视频，都无法用插件，个别能用，字幕语言那栏没有选顶
另外有些字幕英文全是大写的，可否加个改成首字母大小其余写小的功能

**Comment by muzuiget** [comment]
因为 HBO Max 之前改版了 #351，某些视频就是没有单一的字幕文件，类似直播那样对视频文件分片了。

**Comment by muzuiget** [comment]
英文大小写，可以添加自定义样式来修改，假设对第二个字幕应用：

```
.dualsub-renderer .subtitle-2 {
    text-transform: lowercase;
}
.dualsub-renderer .subtitle-2 .contents:first-child .text:first-letter {
    text-transform: uppercase;
}
```

因为 Chrome 不支持原生描边，所以首字母大写会造成错误，如果觉得碍眼，可以删掉第二段代码，或者用“背景”基本样式。

彻底的解决方法是通过服务器跑自然语言处理工具来修正，就像添加汉字拼音一样，直接把文本改写。

**Comment by svcarlos** [comment]
方法可行，但确实会出现错位。可以用服务器加个这种功能吗

**Comment by muzuiget** [comment]
NLP 应该类似拼写检查之类的功能，有时间打算加上。
