### ISSUE TITLE
[Improvement]简单模式下的字幕渲染等几个功能都不可用

### ISSUE THREAD

**Issue by scutxd** [muzuiget/dualsub-support#374]
这几个功能在标准模式下可用，但是在简单模式或者快速设置中不生效。
由于部分视频底部可能是白色的，因此会影响的字幕的阅读性，即使不准备支持过多的定制特性，能否保持youtube中原生的背景以提升阅读性。

**Comment by muzuiget** [comment]
不明白，现在简单模式就是原生背景的了，这些东西都是在 YouTube 字幕菜单中修改的。

扩展就加了几行 CSS：

1. 把第二行字体小一号
2. 对齐两行黑色背景（如果启用了背景不透明）

你可以扩展设置页面“插件”里取消，或者进一步修改。

**Comment by scutxd** [comment]
抱歉，是我的另外一个扩展和这个冲突了，现在已解决，非常感谢你的回复。另外，原来还有个插件的位置可以自定义风格，非常感谢！
