### ISSUE TITLE
請求支援BBC iPlayer

### ISSUE THREAD

**Issue by chuchipang** [muzuiget/dualsub-support#375]
開發者你好！

網站地址： https://www.bbc.co.uk/iplayer

網站包括BBC直播的電視台和點播的電視節目，兩者均有字幕。

影片是可註冊、登入賬戶後免費觀看：本人願意提供網站賬戶以供測試。
網站只供英國國內觀衆收看：本人願意提供VPN賬戶以供測試。

謝謝！

**Comment by muzuiget** [comment]
你好

只需要账号即可，代理问题我可以自行解决，个人邮箱 `muzuiget@gmail.com`。

不过 BBC 的线上媒体服务我稍微看过了下，根据维基百科，毕竟 BBC 旗下还有个叫 BritBox 的品牌，所以 iPlayer 有可能其实是一种“直播”信号，而没有完整的单一字幕文件。

**Comment by chuchipang** [comment]
明白的，測試賬戶已經傳送至你的電郵了，謝謝！

**Comment by muzuiget** [comment]
已发布 v1.79.0

**Comment by chuchipang** [comment]
謝謝！

**Comment by chuchipang** [comment]
開發者muzuiget你好！

承上和email的討論，

我發現有節目部分集數無法顯示Dualsub字幕，以下爲其中一例：

[https://www.bbc.co.uk/iplayer/episode/b01q03nv/miranda-series-3-4-je-regret-nothing?seriesId=p00w4b78](url)

在Windows的Chrome和Edge、Mac的Chrome中測試過，問題依舊。

播放器界面如下：

<img width="962" alt="螢幕截圖 2022-04-25 下午4 52 22" src="https://user-images.githubusercontent.com/9114494/165055067-191b49dc-a5f2-4b3f-b1ac-c5aaba8a35d1.png">

原生字幕功能正常。

商店版和測試版Dualsub界面都試過，問題依舊。

該節目其他集數的Dualsub字幕要是顯示不了，多按數次「重新載入」鍵總能成功載入字幕，唯獨此例子重新載入多次仍未能看到Dualsub字幕。

謝謝！

**Comment by muzuiget** [comment]
因为这个视频的 TTML 格式字幕不够标准，字幕解析错误。

问题不大，做了一些容错就搞定了。

**Comment by muzuiget** [comment]
Dualsub v1.80.2 已发布。

**Comment by chuchipang** [comment]
> 因为这个视频的 TTML 格式字幕不够标准，字幕解析错误。
> 
> 问题不大，做了一些容错就搞定了。

謝謝！

**Comment by muzuiget** [comment]
那个视频是 TTML 解析错误。

Dualsub v1.82.2 已发布，更新试下。

**Comment by chuchipang** [comment]
謝謝！字幕看到了！

**Comment by chuchipang** [comment]
開發者muzuiget你好！

我發現影片會有部分字幕無法在Dualsub中顯示。在Mac和Windows電腦上皆會有這個問題。問題亦見於該節目的若干集數。

其中一次見於影片的1分53秒開始，無法顯示Dualsub字幕，原生字幕顯示正常。

1分52秒
![螢幕截圖 2022-07-17 下午6 10 17](https://user-images.githubusercontent.com/9114494/179393572-2d1ec754-0a80-4af0-8961-2e760759e2dc.png)

1分53秒，無法顯示Dualsub字幕
![螢幕截圖 2022-07-17 下午6 10 55](https://user-images.githubusercontent.com/9114494/179393624-e0b81c02-1c10-47b9-a4c9-15d2c75833ff.png)

2分02秒，回復正常。
![螢幕截圖 2022-07-17 下午6 12 36](https://user-images.githubusercontent.com/9114494/179393665-c0bdd233-038d-49e3-905a-21478e0bf46e.png)

影片： https://www.bbc.co.uk/iplayer/episode/b007cjrb/the-vicar-of-dibley-christmas-specials-2006-2-the-vicar-in-white



謝謝！

**Comment by muzuiget** [comment]
BBC 使用 TTML 字幕格式，它的时间格式五花八门。

在 v1.85.3 修复了。

**Comment by chuchipang** [comment]
謝謝！
