### ISSUE TITLE
youtube字幕问题

### ISSUE THREAD

**Issue by Kzero01R** [muzuiget/dualsub-support#377]
一开始会将视频全部英文字幕显示出来，之后的只有中文字幕，也就是没了双字幕

順帶一提這是簡單模式

**Comment by Kzero01R** [comment]
![image](https://user-images.githubusercontent.com/66917054/157717146-88f5f26d-b67c-48d1-b645-3f0b39372c07.png)

**Comment by muzuiget** [comment]
我找了个视频测试一下，没有重现，那贴一下你的出问题视频的地址。

**Comment by muzuiget** [comment]
还是正常，你所说的两个问题都没出现。

![Screenshot_20220311_015046](https://user-images.githubusercontent.com/330812/157724626-17bc7f4e-d820-4de7-9712-c15abc9cd7a0.png)

**Comment by Kzero01R** [comment]
![image](https://user-images.githubusercontent.com/66917054/157732884-c45b1c24-ed61-4c13-843d-0af6fce2cbab.png)

我已经删除+重新下载了一次还是这样，不过如图好像是英文字幕和中文字幕重叠了

**Comment by muzuiget** [comment]
你试试禁用其它 YouTube 相关扩展和脚本看看。
