### ISSUE TITLE
外部字幕文件设置里面，希望增加“字幕偏移”时间设定

### ISSUE THREAD

**Issue by xibaluo** [muzuiget/dualsub-support#378]
需求背景是：
很多从字幕网站上下载下来的文件，由于没有包括视频网站片头的时间，导致字幕和视频不同步。
故期望，外部字幕文件设置里面，希望增加字幕加载时间的设置，可以设置将字幕按提前或延迟设置的时间进行加载。
类似于kodi 字幕功能里面的“字幕偏移”功能
![image](https://user-images.githubusercontent.com/71700074/157783162-b8e0c016-3baf-4cc8-bc9f-490553cbc87e.png)

再次感谢！

**Comment by muzuiget** [comment]
不会又是 HBO Max 吧？见 #368。
