### ISSUE TITLE
Updated WeTV video player / URL scheme possibly prevents Dualsub from loading subtitle data.

### ISSUE THREAD

**Issue by frinic** [muzuiget/dualsub-support#379]
I ran into this issue a few days ago. The WeTV video player appearance, controls and subtitle menu seems different from before. 
Since the video player has changed, I am unable to display any subtitles with Dualsub. The "Subtitle Language" column in standard mode always shows zero subtitles available. The "Machine Translation" column shows available translations, but if I choose one of them nothing is displayed.  

Also, the URL scheme maybe for the videos maybe has changed from before, but I am not sure, since I didn't pay much attention to that. 

I tested this with WeTV in Google Chrome, Microsoft Edge and Mozilla Firefox. I tried to uninstall / re-install Dualsub, reload the video page several times and also disable / re-enable Dualsub. but I had no luck. I also tested while being logged in and logged out of WeTV (wetv.vip) and with several videos.

I hope this isn't an issue on my side, but every other page seems to work just fine.

![wetv-full-chrome-1x](https://user-images.githubusercontent.com/90572537/158028323-f8e63d95-bc16-46ce-8ac7-02905c690e93.jpg)
 
![wetv-full-chrome-2](https://user-images.githubusercontent.com/90572537/158028631-3b416bbf-33a0-4cee-abbe-babafe571ab1.jpg)

**Comment by muzuiget** [comment]
> The WeTV video player appearance, controls and subtitle menu seems different from before.

Nothing wrong on your side, WeTV has changed it's code, so Dualsub need to re-adapt it's changes.

**Comment by muzuiget** [comment]
I have released v1.79.2, you can try to check if the issue is fixed.

**Comment by muzuiget** [comment]
Currently only released on Chrome Store.

**Comment by frinic** [comment]
I tested a  few videos and so far it seems to be working again. 
Thank you for your quick reply and the quick fix. 

![wetv-full-chrome-3x](https://user-images.githubusercontent.com/90572537/158033410-f027239e-96f7-42cc-99a0-022e0eb10bfc.jpg)
