### ISSUE TITLE
simple yet powerful feature

### ISSUE THREAD

**Issue by aaman-git** [muzuiget/dualsub-support#38]
Hello Sir, Firstly, thank you for your beautiful extension. 

Can you simply add and on/off key for the second subtitle. I don't want to depend fully second translation to know the context. only when needed. So ideally while watching the video in full screen I want to be able to switch on/off the second subtitle.

Thank you again

**Comment by muzuiget** [comment]
Current problem is YouTube builtin subtitle-render not support dynamic changing on the fly by code, so switching on/off need to regenerate a whole subtitle code on server. 

The prefer way to implement this feature is implement subtitle-render our self, but I am not promise when it is done.
