### ISSUE TITLE
无法搜到hbo max 字幕

### ISSUE THREAD

**Issue by ShuhengLi** [muzuiget/dualsub-support#381]
现版本无法搜索到hbo max 字幕
在standart选项只能找到 “English[example]"

**Comment by muzuiget** [comment]
因为 HBO Max 之前改版了 https://github.com/muzuiget/dualsub-support/issues/351，某些视频就是没有单一的字幕文件，类似直播那样对视频文件分片了。

**Comment by ShuhengLi** [comment]
所以对于新的视频就无法进行该插件进行实时翻译了 只能对老的存在字幕文件的影片进行翻译 我可以这样理解吗？

**Comment by muzuiget** [comment]
不是新旧视频的问题，是我自己都找不出规律，甚至 HBO 自制剧都是有些有单一字幕，有些却用分片字幕。

所以有些人会自行找外挂字幕，让 Dualsub 加载显示。当然还有个 HBO 还有个恶心的地方，正片视频前会在追加了一段不定长推广片头，导致和外挂字幕的时间不完全匹配，需要手动做偏移。

**Comment by ShuhengLi** [comment]
我自己试了5，6个新的电影和电视剧 都没能成功 好的多谢你的解答 希望这个plugin越做越好

**Comment by muzuiget** [comment]
#351 之前还是全部有单一字幕的，改版后就变成现在这样了。

分片字幕确实很难搞，因为技术上就像“直播视频”一样，不能提前得知道后几分钟的字幕内容，就无法高效翻译。YouTube 的直播视频一样，YouTube 也是没有原生翻译的。电视台背景的似乎都有这个毛病，比如 Discovery #284，明明是点播，技术上看起来确实“直播”。

所以目前还是用外挂字幕方式凑合用。
