### ISSUE TITLE
希望能够支持funimation

### ISSUE THREAD

**Issue by Seulxy** [muzuiget/dualsub-support#382]
你好开发者，这是官网：https://www.funimation.com/

不需要登录即可观看，VPN设在加拿大，美国等地即可观看，如果开发者需要我愿意提供VPN以供测试。

谢谢~

**Comment by Seulxy** [comment]
啊，翻找到在去年开发者提到过支持funimation太麻烦的事情，不好意思，问了多余的事情……

**Comment by muzuiget** [comment]
看了下，这个网站改版了，可以再研究一下。

**Comment by Seulxy** [comment]
> 看了下，这个网站改版了，可以再研究一下。

好的好的，期待期待！
