### ISSUE TITLE
希望能支持 treehouse 字幕翻译

### ISSUE THREAD

**Issue by c810610** [muzuiget/dualsub-support#383]
希望能提供该网站的字幕翻译
以下页面可供测试
https://teamtreehouse.com/techdegree
非常感谢

**Comment by muzuiget** [comment]
这个测试视频是一个宣传视频，不够代表性。需要的是“专门”视频页面，而不是仅仅是播放器，因为页面布局也是需要特殊处理的。

而且也无法注册测试账号，因为需要信用卡。所以除非你能提供账号，否则就无法测试了。

**Comment by muzuiget** [comment]
目前没有人借用账号，无法支持。
