### ISSUE TITLE
希望能够支持 mubi

### ISSUE THREAD

**Issue by WILLOWCJ** [muzuiget/dualsub-support#384]
主要是不喜欢mubi的字幕样式 然后就是mubi没有中文字幕
希望能支持 衷心感谢

https://mubi.com/

**Comment by muzuiget** [comment]
注册是能注册了，但是所有视频都是付费的。所以除非你能提供账号，否则就无法测试了。

**Comment by muzuiget** [comment]
目前没有人借用账号，无法支持。
