### ISSUE TITLE
Dualsub support HBO GO

### ISSUE THREAD

**Issue by jhhuang96** [muzuiget/dualsub-support#388]
In Asia, we can't watch HBO Max but we could watch HBO GO. So would author support HBO GO for dual sub? Thanks!

**Comment by jhhuang96** [comment]
By the way, HBO GO already owns Chinese and English subtitles.

**Comment by muzuiget** [comment]
HBO GO requires a paid account, if you are willing to share it for a while for my testing, please send it to my email `muzuiget@gmail.com`.

**Comment by jhhuang96** [comment]
For HBO GO's policy, users must use local network to watch HBO GO which follows your country of account and payment info of subscription. So I am not sure do you have philippines IP network env?

**Comment by muzuiget** [comment]
According to [HBO Go Wikipedia](https://en.wikipedia.org/wiki/HBO_Go#External_links), HBO Go operates under a different domain name in the Asian region.

![Screenshot_20220402_003651](https://user-images.githubusercontent.com/330812/161305754-8cbf2caf-2791-4934-8c59-7f4ab81caca9.png)

I don't have Philippines IP. I only have Hong Kong IP, so I only can test on https://www.hbogoasia.hk/.

If only the domain name is different and the codebase of the website is the same, then in theory the adaptation code can be reused, but I am not sure.

**Comment by muzuiget** [comment]
No paid account for testing
