### ISSUE TITLE
字幕语言无法选择，字幕不显示

### ISSUE THREAD

**Issue by z-komorebi** [muzuiget/dualsub-support#392]
标准模式下的字幕语言只有关闭，没有其他选择，字幕不显示，使用的网站是哔哩哔哩

**Comment by z-komorebi** [comment]
> 标准模式下的字幕语言只有关闭，没有其他选择，字幕不显示，使用的网站是哔哩哔哩
! [text ] ( /user/desktop/2022-04-14 183856.png)

**Comment by muzuiget** [comment]
你看看是不是这个问题 #369
