### ISSUE TITLE
Edge 上的 Prime Video 无法获取字幕

### ISSUE THREAD

**Issue by lflcan** [muzuiget/dualsub-support#393]
在 Edge 上，插件无法获取到 Prime Video 的字幕，字幕语言始终显示为0
![屏幕截图 2022-04-15 175338](https://user-images.githubusercontent.com/13313772/163556952-964b8778-099e-4ec1-9b42-df45fc3b4a1d.png)

而在 Chrome 上，插件可正常使用
![屏幕截图 2022-04-15 175234](https://user-images.githubusercontent.com/13313772/163556984-9573159b-a131-4b34-b2aa-256ce1425af5.png)

**Comment by muzuiget** [comment]
奇怪，理论上两个浏览器效果应该一样。能否也测试下 Firefox？

**Comment by lflcan** [comment]
Firefox 也是正常的，就只有 Edge 不行
![屏幕截图 2022-04-18 000637](https://user-images.githubusercontent.com/13313772/163722874-89c434de-ca33-4396-8f7a-89fdfaddc7d1.png)

**Comment by ancelotpinto** [comment]
I had the same issue, turning off hardware acceleration on edge seemed to work for me.

**Comment by muzuiget** [comment]
这样的话，我怀疑是系统安装了“HEVC 扩展”，所以 Edge 支持了 HEVC 硬件解码，于是网站使用了另一套播放器代码。

因为 Chrome 和 Firefox 铁定不会支持 HEVC 的了，所以没问题。

能否在系统控制面板里的“添加/删除”或者“应用管理”里检查一下，是不是安装“HEVC 扩展”。

**Comment by lflcan** [comment]
> 这样的话，我怀疑是系统安装了“HEVC 扩展”，所以 Edge 支持了 HEVC 硬件解码，于是网站使用了另一套播放器代码。
> 
> 因为 Chrome 和 Firefox 铁定不会支持 HEVC 的了，所以没问题。
> 
> 能否在系统控制面板里的“添加/删除”或者“应用管理”里检查一下，是不是安装“HEVC 扩展”。

看了一下，确实有hevc扩展

**Comment by muzuiget** [comment]
这个 HEVC 扩展是从 Microsoft Store 购买的吗？

**Comment by lflcan** [comment]
> 这个 HEVC 扩展是从 Microsoft Store 购买的吗？

不是，是那个免费的“来自设备制造商的 HEVC 扩展”

**Comment by muzuiget** [comment]
我开发在 Linux，重现这个问题还是挺麻烦的，我也不愿意给冤枉钱给微软（钱事少，面子事大），毕竟装了也未必是 HEVC 原因。

这个问题不太严重，暂时不管了。

除非有人能测试出确切原因，让我能在 Linux 重现调试。

**Comment by lflcan** [comment]
> 我开发在 Linux，重现这个问题还是挺麻烦的，我也不愿意给冤枉钱给微软（钱事少，面子事大），毕竟装了也未必是 HEVC 原因。
> 
> 这个问题不太严重，暂时不管了。
> 
> 除非有人能测试出确切原因，让我能在 Linux 重现调试。

好的吧😭

**Comment by muzuiget** [comment]
我记得 Prime 也是很鸡贼不提供用户自选分辨率和视频编码的，而是替用户自动选择。

所以你是觉得在 Edge 上，目测画质比 Chrome 好？不然两个浏览器不应该有区别。

**Comment by lflcan** [comment]
> 我记得 Prime 也是很鸡贼不提供用户自选分辨率和视频编码的，而是替用户自动选择。
> 
> 所以你是觉得在 Edge 上，目测画质比 Chrome 好？不然两个浏览器不应该有区别。

其实画质上也没太大差别啦～ 
但个人感觉Edge比Chrome所需要的缓冲时间更短一点🤔

**Comment by muzuiget** [comment]
试下这个版本 https://github.com/muzuiget/dualsub-support/issues/404#issuecomment-1112206773

**Comment by muzuiget** [comment]
试下这个版本 https://github.com/muzuiget/dualsub-support/issues/404#issuecomment-1112206773

**Comment by Benlee1129** [comment]
我用手機及dualsub 1.80.01 的Amazon加載版觀看www.amazon.com 的 Freevee (免費的prime video)時，大部分視頻會被要求至Prime video app 觀看（會開起Google store連結），但是我是用切換成手機的桌面版觀看。此時，Dualsub 也出現這種找不到字幕檔的情形，請問能解決嗎？

**Comment by muzuiget** [comment]
现阶段不管手机上的情况了，有些网站手机版根本就是另一套代码，没那么多精力一一测试兼容。

不管手机是不是使用桌面模式，网站总能判断实际的运行的设备，从而改变代码的运行方式。

现在只保证 m.youtube.com 能在手机上使用。

**Comment by Benlee1129** [comment]
我提的情形跟你說的狀況剛好反過來，我在手機版使用Amazon 時，dualsub 完美運行。
但轉換為桌面版時，就出現討論中讀不到字幕檔的情形。

muzuiget ***@***.***> 於 2022年5月2日 週一 16:34 寫道：

**Comment by muzuiget** [comment]
有时间的话，用 #411 再测试一下 Edge 这个问题。

**Comment by lflcan** [comment]
OK，完全可用了

**Comment by muzuiget** [comment]
Dualsub v1.81.1 已发布。
