### ISSUE TITLE
请求功能[设置导入/导出]和[设置云同步]功能

### ISSUE THREAD

**Issue by suheandzl** [muzuiget/dualsub-support#394]
在重新配置浏览器或者更换浏览器时 设置需要重新手动设置 比较不方便

如果可以的话请加入这两个功能 谢谢大佬

**Comment by muzuiget** [comment]
WebExtension API 自带云同步功能，也就是把 `chrome.storage.local` 和 `chrome.storage.sync`，浏览器自己处理同步问题，但是 `chrome.storage.sync` 有性能和容量限制，也带来一些奇怪问题，同步冲突问题，所以没有使用。

最简单还是自己实现，把扩展设置导出成一个 JSON 文本文件，让用户自己手动同步，所有浏览器都通用。

原来的“样式”、“插件"、”文件“是有单独导出/导入功能的，后来删掉了，因为原来是打算改成”导出/导入整个扩展设置数据”，然而一直懒得实现。
