### ISSUE TITLE
Support request https://www.dr.dk/drtv/ 丹麥國家電視台

### ISSUE THREAD

**Issue by Benlee1129** [muzuiget/dualsub-support#396]
DR TV 是丹麥國家電視台的線上頻道，所有影集都帶有字幕，而且免費。北歐的人文風情，是值得加入支持的線上資源。

**Comment by muzuiget** [comment]
这个网站内容相当无聊，代码陈旧，不打算支持了。

**Comment by Benlee1129** [comment]
Muzuiget,

這個網站已經update好一段時間，現在內容豐富，頁面也作的很好。
小說系列都是原創作品，電影也拍得很好。
請重新考慮支持。
小說系列影集的連結：
https://www.dr.dk/drtv/kategori/fiktionsserier/nyeste

Ben

muzuiget ***@***.***> 於 2022年5月24日 週二 12:31 寫道：
