### ISSUE TITLE
Support request https://iview.abc.net.au/ Australia 國家電視台

### ISSUE THREAD

**Issue by Benlee1129** [muzuiget/dualsub-support#397]
ABC iview是Australia 國家電視台的線上頻道，完全免費且有自製和英、美的大量視頻。

**Comment by muzuiget** [comment]
测试版 [dualsub-v1.81.1.zip](https://github.com/muzuiget/dualsub-support/files/8669804/dualsub-v1.81.1.zip)

**Comment by Benlee1129** [comment]
Thanks, it works.

**Comment by Benlee1129** [comment]
iview 的直播頻道都是帶有字幕的，不過dualsub 沒有偵組到。

**Comment by muzuiget** [comment]
你这个 500 问题暂时没有头绪，现在只有你报告有这种情况。

**Comment by Benlee1129** [comment]
約為前1/10的段落，比如59分鐘的影片，在5分多鐘前都會呈現 {500}，而沒有出現翻譯。

可能跟你預設的免費試用時間長有關。

muzuiget ***@***.***> 於 2022年5月12日 週四 13:13 寫道：

**Comment by muzuiget** [comment]
你应该贴出你的运行环境，浏览器版本，视频地址，以及出问题的时间。

出问题时，可换一下翻译别的语言，比如日语或者简/繁中文，是否同样的问题，好让我缩小 bug 的范围。

**Comment by Benlee1129** [comment]
使用的是Android 手機版的 Kiwi-browser 101.0.4951.40。
在iview中任一視頻，約在前1/10段落都有出現錯誤。
已經轉換過其他語言，日文等，結果仍是出現一樣錯誤。
這版本有發佈上Chrome add-on平台了嗎？平台上版本似乎尚不支援Abc iview。

**Comment by muzuiget** [comment]
Dualsub v1.81.2 已发布。

**Comment by muzuiget** [comment]
@Benlee1129 这是另外一个问题了，请开新帖讨论，目前所有网站只保证桌面版浏览器上兼容。
