### ISSUE TITLE
建议加入有道云智能翻译的api接口

### ISSUE THREAD

**Issue by larryjobs** [muzuiget/dualsub-support#398]
有道云的接口是按照使用量进行付费，更合理。有时候机器翻译用的不多，很多网站现在都有提供中文字幕。看到月租基本望而却步。像hulu，youtube（少量视频），hbo max有其他插件代替。

**Comment by muzuiget** [comment]
实际上你[可以使用加载外部字幕文件](https://www.dualsub.xyz/zh/docs/load-external-subtitle-files)功能。

我不想为自己不感兴趣的功能花时间，以开发者和付费的用户角度看，就是花钱买时间。现在的收费模式就是有意过滤掉一部分用户。
