### ISSUE TITLE
建议支持 discovery plus

### ISSUE THREAD

**Issue by larryjobs** [muzuiget/dualsub-support#399]
discovery plus，与国家地理频道，bbc同为纪录片巨头
如果有中文字幕的支持，应该会吸引不少的用户

**Comment by muzuiget** [comment]
见 #284，除非这段时间它改版了，提供独立字幕文件了，否则支持不了。

**Comment by larryjobs** [comment]
https://www.discoveryplus.com/ph。现在是支持cc字幕。我看的是dr pimple popper和my feet are killing me。

**Comment by muzuiget** [comment]
没有付费账号供测试。
