### ISSUE TITLE
字幕不显示

### ISSUE THREAD

**Issue by halu1999** [muzuiget/dualsub-support#40]
第一行的字母可以打开，但是会有重叠。当第二行的字幕打开后，所有字幕消失了，怎么刷新都没用，只有关掉第二行的字幕才能使用。望大佬修复一下下

**Comment by halu1999** [comment]
@muzuiget

**Comment by ayugioh2003** [comment]
same issue +1

**Comment by shuwai** [comment]
同样问题+1

**Comment by muzuiget** [comment]
是 YouTube 改了字幕格式，把 XML 换成 JSON 了，又得重新逆向了，估计要花上一些时间。

**Comment by muzuiget** [comment]
@halu1999 只选一行字幕就是不通过 Dualsub 服务器处理的，就是 YouTube 原来的字幕，所以能显示。

所以“重叠”是什么意思？能给个视频地址？

**Comment by halu1999** [comment]
> @ halu1999只选一行字幕就是不通过Dualsub服务器处理的，就是YouTube原来的字幕，所以能显示。
> 
> 所以“重叠”是什么意思？能给个视频地址？

重叠问题后来就好了，估计是YouTube自己的问题

**Comment by muzuiget** [comment]
似乎 YouTube 是灰度更新了，今天我测试又变回了 XML 了，需要一个 100% 使用 JSON 格式的视频来测试才行。

**Comment by muzuiget** [comment]
https://www.reddit.com/r/VirtualYoutubers/comments/es4yc7/youtube_seems_to_have_decided_that_subtitlers/

那几天 YouTube 确实在测试新字幕格式，然后被人骂了，然后回滚了。

现在好像部分视频默认使用新格式了，蛋疼。

**Comment by muzuiget** [comment]
已经做了基本兼容。
