### ISSUE TITLE
bugs report _ BBC iPlayer with Kiwi-browser Android 

### ISSUE THREAD

**Issue by Benlee1129** [muzuiget/dualsub-support#400]
As I know, Kiwi-browser support chrome add_on in use on Android phones. 
When I used this browser with dualsub add-on to watch BBC iPlayer films, it was not working like charms. Because the translation was covered by the full screen displays, no substittles had been shown.
I think it meets the rendering layer of dualsub covered by the full screen layer, but I don't recognize the status.

**Comment by Benlee1129** [comment]
> As I know, Kiwi-browser support chrome add_on in use on Android phones. When I used this browser with dualsub add-on to watch BBC iPlayer films, it was not working charm. Because the translation was covered by the full screen displays, no substittles had been shown. I think it meets the rendering layer of dualsub covered by full screen, but I don't recognize the status.

**Comment by muzuiget** [comment]
全屏问题见 #407。
