### ISSUE TITLE
Please support https://www.nicovideo.jp/

### ISSUE THREAD

**Issue by zikaku** [muzuiget/dualsub-support#403]

**Comment by Benlee1129** [comment]
You also can try ABEMA that is a good Japanese platform for shows and videos.

**Comment by Benlee1129** [comment]
You also can try ABEMA that is a good Japanese platform for shows and videos.

**Comment by muzuiget** [comment]
Please provide a test video url which has soft/text subtitle.

**Comment by zikaku** [comment]
https://www.nicovideo.jp/watch/so37633964
[Jujutsu-Kaisen-01.enUS_.zip](https://github.com/muzuiget/dualsub-support/files/8596470/Jujutsu-Kaisen-01.enUS_.zip)
Best regards

**Comment by muzuiget** [comment]
See https://github.com/muzuiget/dualsub-support/issues/459
