### ISSUE TITLE
Amazon prime video can't be translated by Dualsub 

### ISSUE THREAD

**Issue by Benlee1129** [muzuiget/dualsub-support#404]
我第一次嘗試使用 Amazon prime video，但無法像在使用其他平台一樣的方式使用Dualsub，想請教是否我疏忽了什麼呢？
因為Dualsub完全支援不到Amazon prime video內建的字幕檔。

先前，我有推薦可支援iMDB TV，它是Amazon prime video 平台的廣告版，與prime video 同一播放器，所以Dualsub有支援Amazon prime video ，就能支援iMDB TV。

**Comment by muzuiget** [comment]
这可能两个原因，可能是已知问题 #393。

另外原因就是我故意没在 `amazon.*` 域名上启用，现在仅在地址 `https://www.primevideo.com/` 上启用。所以要在 `amazon.*` 之类的地址上使用 Dualsub，需要手动修改一下扩展，修改一下 `manifest.json` 文件，把 `https://www.amazon.com/*`  地址加进去，然后以开发者模式运行，具体讨论见 #357。

因为这个 `amazon.com` 域名很多人都是当成一个购物网站，有很多个人敏感信息，例如地址、信用卡等等。一个视频类扩展申请购物网站会让人怀疑（安装是强制接受），所以干脆不添加了，让用户自己添加。

要真正启用这类域名，需要升级到 Manifest V3 标准才行，见 https://github.com/w3c/webextensions/issues/119。

**Comment by Benlee1129** [comment]
我已經把擴展 ”修改一下 manifest.json 文件，把 https://www.amazon.com/*
 地址加进去，然后以开发者模式运行”，也在擴充功能面頁按過更新。不過，仍然不見www.amazon.com有被加入至列表中。

請問，我是哪裡沒有注意到呢？


muzuiget ***@***.***> 於 2022年4月26日 週二 上午8:11寫道：

**Comment by muzuiget** [comment]
按下 Dualsub 的工具栏图标，弹出的页面是怎么样的，截一下图。

**Comment by Benlee1129** [comment]
沒有偵到的字幕檔。
似乎 json 檔沒被存取

muzuiget ***@***.***> 於 2022年4月26日 週二 上午11:04寫道：

**Comment by muzuiget** [comment]
一图胜千言。

**Comment by Benlee1129** [comment]
我該怎麼作呢？

muzuiget ***@***.***> 於 2022年4月26日 週二 11:44 寫道：

**Comment by muzuiget** [comment]
打开 `amazon.com` 的视频页面，然后截一下这个图。

![Screenshot_20220426_133551](https://user-images.githubusercontent.com/330812/165228996-f27353bd-ea3b-46bf-91fd-432280bf109f.png)

**Comment by Benlee1129** [comment]
跟前回一樣，沒有存取到字幕檔。

muzuiget ***@***.***> 於 2022年4月26日 週二 13:36 寫道：

**Comment by Benlee1129** [comment]
我在擴展的“網站存取權”處，沒有新增加入的amazon.com/*。

json 檔是否沒有被讀取呢？

Lee Ben ***@***.***> 於 2022年4月26日 週二 13:53 寫道：

**Comment by muzuiget** [comment]
要不然你改错了，

![Screenshot_20220426_141208](https://user-images.githubusercontent.com/330812/165233655-6a16f570-7e7b-4c9c-aefe-0fa9d649c3d2.png)

注意末尾的逗号。

改了后，要点击那个 reload 按钮重新加载。

**Comment by muzuiget** [comment]
![Screenshot_20220426_141451](https://user-images.githubusercontent.com/330812/165233989-b5980810-3d34-4f73-959e-a16c69d2d1ac.png)

如果有错误，也点开一下看看。

`"manifest_version": 2,` 这个错误可以忽略。

**Comment by Benlee1129** [comment]
你沒有直接加入amazon.com，要使用者自行加入，可能真的有困難。

我也不知道哪裡出錯了，json的更改都有留意到，也重載了。
我附上json檔案，你看看有錯嗎？

Lee Ben ***@***.***> 於 2022年4月26日 週二 下午2:45寫道：

**Comment by Benlee1129** [comment]
您好，

這個問題我無法解決，你能否寫一段 腳本script 讓我加入，我想這樣可能會較容易。

Lee Ben ***@***.***> 於 2022年4月26日 週二 15:24 寫道：

**Comment by muzuiget** [comment]
有那么难吗？直接改好的 [dualsub-v1.80.1.zip](https://github.com/muzuiget/dualsub-support/files/8570299/dualsub-v1.80.1.zip)

**Comment by Benlee1129** [comment]
是不難，但是瀏覽器（Kiwi-browser)嚥不下。

我也試過你上回給我的zip來改json，改是改了，一放回瀏覽器，就報錯了，而且Dualsub還無法使用。




muzuiget ***@***.***> 於 2022年4月27日 週三 16:27 寫道：

**Comment by Benlee1129** [comment]
可以用了， imdb tv 可以觀看了，讚！

我比較在chrome addon store 下載，跟這zip的差異是，「允許存取檔案網址」一項可以勾選。

在chrome store 沒有這項，所以改了json檔，也加入不了，是嗎？

muzuiget ***@***.***> 於 2022年4月27日 週三 16:32 寫道：

**Comment by muzuiget** [comment]
那个选项无关紧要，那个选项意思是授权扩展访问地址 `file://` 的网页而已。

如果你比较商店版，就是 `manifest.json` 多了一行而已。

```
"https://www.primevideo.com/*",
"https://www.amazon.com/*", <-- 就加了这行
"https://www.raiplay.it/*",
```

肯定是你改错了，或者打包回 zip 时错误，把**文件夹**压缩了，应该是把**文件夹内的文件**压缩。

**Comment by Benlee1129** [comment]
這樣的調整後，似乎在同步上就出了問題了。

我比對原字幕是同步的，但Dualsub就有先有後了，尤其是廣告播出時。

但在hulu並沒有這樣的同步問題，即使播廣告後也是一樣同步。

muzuiget ***@***.***> 於 2022年4月27日 週三 16:57 寫道：

**Comment by Benlee1129** [comment]
IMBd TV 是免費的平台，你可以自己試試問題在哪嗎？

Lee Ben ***@***.***> 於 2022年4月27日 週三 17:37 寫道：

**Comment by Benlee1129** [comment]
進一步回報，
Amazon prime 只有某些節目有字幕跟Dualsub同步出現問題，判斷不是全面的，
我想問題不是你能解決的。

Lee Ben ***@***.***> 於 2022年4月27日 週三 下午5:37寫道：

**Comment by muzuiget** [comment]
我没有美区 Amazon 账号，无法测试。

你看不同步的视频，是不是有 10 秒钟偏移？现有的代码的就是对某些视频做了 10 秒钟偏移。

**Comment by Benlee1129** [comment]
美區的Amazon 可以任意申請，用kindle book註冊的也可以，沒有限制。

確實會有提前的偏移，但有一奇怪的事，是使用「網頁版就正常」，手機版才有偏移，是因為手機版設計提前10秒偏移嗎？

muzuiget ***@***.***> 於 2022年4月28日 週四 10:29 寫道：

**Comment by muzuiget** [comment]
试下这个测试版 [dualsub-v1.80.1.zip](https://github.com/muzuiget/dualsub-support/files/8583126/dualsub-v1.80.1.zip)

这个版本同时修复 ARTE 和 Rai Play 的问题。

**Comment by Benlee1129** [comment]
Raiply都沒有問題了，arte.de 在全屏下，直屏可以看到字幕，橫屏時字幕會被蓋住。

**Comment by muzuiget** [comment]
arte 问题在 #406 讨论，最好附上截图。

**Comment by muzuiget** [comment]
`amazon.com` 专门发个测试版，见 ##411

**Comment by Benlee1129** [comment]
我加入amazon.com/*在json檔後，改連接到 peacock 時，就讀不到字幕檔了，錯誤訊息如附件的截圖。
改前 peacock都是正常可以用。

Lee Ben ***@***.***> 於 2022年4月26日 週二 下午3:07寫道：

**Comment by Benlee1129** [comment]
沒有出現你所提的manifest_version error.

我是更改路徑 ~/Library/Application Support/Google/Chrome/Profile
1/Extensions/gnlibmlfpencglodjpgnalbdebfhpmfp/1.80.0_0/manifest.json

接著替換掉 https://player.dualsub.xyz/* 為 https://www.amazon.com/*
（只改內容文字），存檔後，按重載後，再刷新chrome頁面，此時https://player.dualsub.xyz/* 仍然存在。
換句話說，就是我並沒有完成更改 json檔。

muzuiget ***@***.***> 於 2022年4月26日 週二 下午2:16寫道：

**Comment by Benlee1129** [comment]
如同BBC一樣，可能需要加個FS控制器。
這在2.5版只要我自己打勾就行，但現在太複雜了。還是恢複原來的樣式選單功能為佳。

Ben

**Comment by Benlee1129** [comment]
Muzuiget,

最有價值的網站BBC 無法顯示字幕，請維護。

Ben

**Comment by Benlee1129** [comment]
我剛換了VPN就可以了。
不是Dualsub 的問題，抱歉。

Ben

Lee Ben ***@***.***> 於 2023年1月18日 週三 10:19 寫道：

> Muzuiget,
>
> 最有價值的網站BBC 無法顯示字幕，請維護。
>
> Ben
>
