### ISSUE TITLE
修复 arte.tv

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#406]

**Comment by Benlee1129** [comment]
手機橫屏時，arte 的字幕都被蓋住。
![Img_2022_04_28_22_34_32](https://user-images.githubusercontent.com/103996456/165875206-1252d879-4012-4719-850f-9a9e4d9e79e2.jpeg)

**Comment by muzuiget** [comment]
是不是使用桌面模式？

**Comment by Benlee1129** [comment]
桌面模式反而沒有問題，是正常的。
手機的app版本，才有字幕被蓋住的問題。

**Comment by muzuiget** [comment]
我测试了，我的手机上，即使用手机模式都是正常的，只是默认字体有点大，毕竟还没有特别适配手机情况。

网站的手机页面可能完全是不同的代码，所以我暂时不打算花太多时间在手机上了，目前只考虑特别处理 `m.youtube.com`。

**Comment by Benlee1129** [comment]
桌面模式反而沒有問題，是app版模式才有蓋字幕的問題。

muzuiget ***@***.***> 於 2022年4月29日 週五 11:16 寫道：
