### ISSUE TITLE
支持 https://www.britbox.co.uk/

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#409]
来自邮件的请求。

**Comment by muzuiget** [comment]
测试版 [dualsub-v1.80.2.zip](https://github.com/muzuiget/dualsub-support/files/8598205/dualsub-v1.80.2.zip)

这个版本的字幕列表侦测方法不够完美，需要先手动激活一下网站的原生字幕功能（然后可以关掉），迟点再研究一下更好的侦测方法。

**Comment by Benlee1129** [comment]
Muzuiget,
Much thanks. 
Britbox uk is a treasure of British TV culture, including BBC, ITV, Channel 4 and 5 episodes.

**Comment by muzuiget** [comment]
第二个测试版 [dualsub-v1.80.2.zip](https://github.com/muzuiget/dualsub-support/files/8608354/dualsub-v1.80.2.zip)

不需要手动激活一下网站的原生字幕功能了，同时添加 ITV 的支持，如果没问题就可以发布到 Chrome 商店了。

**Comment by Benlee1129** [comment]
好的，我來試試。

muzuiget ***@***.***> 於 2022年5月3日 週二 13:19 寫道：

**Comment by Benlee1129** [comment]
整體表現的非常的好，近於完美。

Lee Ben ***@***.***> 於 2022年5月3日 週二 13:20 寫道：

**Comment by Benlee1129** [comment]
Gee thanks, muzuiget. You have technical expertise.

muzuiget ***@***.***> 於 2022年5月3日 週二 21:11 寫道：

**Comment by muzuiget** [comment]
Dualsub v1.81.0 已发布
