### ISSUE TITLE
可否添加Coursera和Edx支持?

### ISSUE THREAD

**Issue by Hanson7300** [muzuiget/dualsub-support#41]
Coursera 和Edx 上的课程大部分都有英文字幕,只有部分有中文字幕,如果能支持的话就太好了~

**Comment by muzuiget** [comment]
具体地址？

**Comment by Hanson7300** [comment]
主页:  https://www.coursera.org/    https://www.edx.org/
https://www.coursera.org/lecture/python-functions-files-dictionaries/introduction-to-the-specialization-dnw2F 是coursera上面一门python课的试看视频,选择 免费注册-旁听 即可
https://www.edx.org/course/calculus-1a-differentiation 同样选择旁听

**Comment by muzuiget** [comment]
没有额外精力，这功能不做了。
