### ISSUE TITLE
NETFLIX 字幕問題

### ISSUE THREAD

**Issue by MagicFox29** [muzuiget/dualsub-support#410]
我用EDGE看NETFLIX的時候，只要用硬體加速開4K結果雙字幕都無法使用，但關掉硬體加速又可以正常使用但就只有1080P
![image](https://user-images.githubusercontent.com/104728478/166155757-54f864fa-01a3-44e3-891b-c6f5d26996e2.png)
其他瀏覽器也沒辦法4K
請問雙字幕的功能目前4K沒辦法使用嗎?謝謝

**Comment by muzuiget** [comment]
可能是 Netflix 在 4K 下使用了不同代码，Prime Video 也是这样的 #393。

**Comment by muzuiget** [comment]
请更新到 v1.85.0 再测试一下，根据 #433 的信息，请关掉其它可能冲突的扩展。
