### ISSUE TITLE
Amazon 视频测试版

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#411]
Amazon 的视频有几个商标名，例如 Prime Video、IMDB TV、Freevee，甚至在不同地区以不同域名运行，例如 `primevideo.com`、`amazon.com`。

但似乎都是用同一套网站代码，所以理论上也可以用同一套适配代码，但是我无法一一测试了。

这里专门放个测试版，用户可以自行以 Chrome 的开发者模式安装和使用。

### 和商店版的区别

仅在以下网址启用：

```
"https://www.amazon.ae/*",
"https://www.amazon.ca/*",
"https://www.amazon.cn/*",
"https://www.amazon.co.jp/*",
"https://www.amazon.co.uk/*",
"https://www.amazon.com.au/*",
"https://www.amazon.com.br/*",
"https://www.amazon.com.mx/*",
"https://www.amazon.com.tr/*",
"https://www.amazon.com/*",
"https://www.amazon.de/*",
"https://www.amazon.eg/*",
"https://www.amazon.es/*",
"https://www.amazon.fr/*",
"https://www.amazon.in/*",
"https://www.amazon.it/*",
"https://www.amazon.nl/*",
"https://www.amazon.pl/*",
"https://www.amazon.sa/*",
"https://www.amazon.se/*",
"https://www.amazon.sg/*",
"https://www.primevideo.com/*"
```

你可以同时和商店版安装到浏览器里，但是不要同时启用，而是仅启用其中一个。

如果需要两个版本同时启用，则至少要取消其中一个的 `"https://www.primevideo.com/*"` 权限，否则会冲突。

### 文件列表

不定时更新，请使用总使用最新版：

* [dualsub-v1.81.0.zip](https://github.com/muzuiget/dualsub-support/files/8618467/dualsub-v1.81.0.zip)

**Comment by Benlee1129** [comment]
Yes, it works.

**Comment by muzuiget** [comment]
此帖关闭，后续更新见 #418。
