### ISSUE TITLE
hbomax部分视频无法翻译中文

### ISSUE THREAD

**Issue by larryjobs** [muzuiget/dualsub-support#417]
使用的是dualsub付费版本，发现有部分hbomax的剧集无法出现中文字幕（在字幕语言在一个格，获取不到cc字幕）。例如curb your enthusiasm第一季第一集，young sheldon（四季，随机挑了几集都不行），这两个剧都有带cc字幕。也有能支持的，像batman和westworld可以支持。看下po主有空麻烦关注下和解答下。谢谢哈！

**Comment by muzuiget** [comment]
这是已知问题 #351，需要网站提供独立的字幕文件，而不是分片字幕文件，所以短时间内无法解决了。

如果翻译 HBO Max 对你特别重要的话，我只能给你退款。

**Comment by larryjobs** [comment]
> 这是已知问题 #351，需要网站提供独立的字幕文件，而不是分片字幕文件，所以短时间内无法解决了。
> 
> 如果翻译 HBO Max 对你特别重要的话，我只能给你退款。

谢谢解答，没事。影响不大，看得也不多

**Comment by muzuiget** [comment]
好的，现在也没法得 HBO Max 的字幕文件规律，无论是外购还是原创的都有可能出现分片字幕，看上去似乎就是随机的。
