### ISSUE TITLE
{ An API Key is required, https://www.dualsub.xyz/buy} 

### ISSUE THREAD

**Issue by minanagehsalalma** [muzuiget/dualsub-support#419]
For real man ! 

![image](https://user-images.githubusercontent.com/20546638/168497425-91e81868-2b91-4dc6-9af6-f47f5842d64f.png)
A monthly subscription for a web extension !! like wtf ! 

You are even using google translate for Translation Engine

so why would that be a paid thing ?
![image](https://user-images.githubusercontent.com/20546638/168497483-50ae26a1-fe09-42ca-b0c5-05d92e8d9d8d.png)

sad thing i really like the Machine Translation
i started depending on it :( 

And i have no time to reverse engineer it , which wouldn't be hard

**Comment by muzuiget** [comment]
It looks like you know programming, why not develop one yourself, it's definitely free.
