### ISSUE TITLE
fix the format of setting，设置需固定

### ISSUE THREAD

**Issue by Jasonqin2020** [muzuiget/dualsub-support#42]
fix the format of setting，设置需固定，打开新网页时，翻译语种及设定，宜跟上次视频网页一致，勿需反复更改设定。

**Comment by muzuiget** [comment]
现在就是这样，难道不是吗？前提是新视频有对应的语言字幕。

**Comment by Jasonqin2020** [comment]
现在不是的，播放第二个视频时，得重新设置显示中文还是英文或者都显示，开关和视频本身字幕开关也有冲突。建议插件增加默认设置按钮，及可自定义的风格1，风格2按钮，这样每人根据其自身情况可以快速调用或调整。另外我发现 显示中文字幕时，中文拼音也附带显示了，拼音可以去掉吧？------------------ 原始邮件 ------------------
发件人: "muzuiget"<notifications@github.com>
发送时间: 2020年2月4日(星期二) 凌晨1:10
收件人: "muzuiget/dualsub-support"<dualsub-support@noreply.github.com>;
抄送: "Jasonqin2020"<275552714@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [muzuiget/dualsub-support] fix the format of setting，设置需固定 (#42)



现在就是这样，难道不是吗？前提是新视频有对应的语言字幕。
 
&mdash;

**Comment by muzuiget** [comment]
> 现在不是的，播放第二个视频时，得重新设置显示中文还是英文或者都显示

你可以使用”优先选择语言“这个功能，在设置面板里。

> 开关和视频本身字幕开关也有冲突

如果工具栏两行字幕都是”关闭“的话，也就是扩展不会起作用，YouTube 播放器原来怎么处理就怎么处理(比如它默认语言是根据你界面语言自动决定的)

> 建议插件增加默认设置按钮，及可自定义的风格1，风格2按钮，这样每人根据其自身情况可以快速调用或调整。

现在设置已经够复杂了，看几分钟视频花几秒调整下字幕可以接受的。

> 另外我发现 显示中文字幕时，中文拼音也附带显示了，拼音可以去掉吧？

你开启了”语言工具“，你要在第三个下拉框选择关闭。或者干脆在设置面板里关闭。

你可以看下文档 https://dualsub.netlify.com/
