### ISSUE TITLE
Support request https://gem.cbc.ca/ 加拿大國家電視台

### ISSUE THREAD

**Issue by Benlee1129** [muzuiget/dualsub-support#420]
加拿大國家電視台有大量自製和英美日的免費的視頻，皆有字幕，請加入Dualsub支持。

**Comment by muzuiget** [comment]
这个网站没有提供独立字幕，没有办法支持了。

**Comment by Benlee1129** [comment]
我不瞭解，我觀察每個視頻都有字幕，是怎麼回事呢？

muzuiget ***@***.***> 於 2022年5月17日 週二 20:09 寫道：

**Comment by Benlee1129** [comment]
它的最前一段是廣告，你要等廣告播放完，才會進入正式節目，都有字幕，或用adguard 可以把廣告完成屏蔽。

Lee Ben ***@***.***> 於 2022年5月17日 週二 20:10 寫道：

**Comment by muzuiget** [comment]
假设一个 60 分钟的视频：

* **独立字幕**就是一个字幕文件，里面有 60 分钟的字幕内容。
* **分片字幕**就是 3600 个字幕文件，每个字幕文件包含 1 秒钟字幕内容。

分片字幕本质就像你用手机的实时字幕，你没法提前得知道后面几句话的内容，翻译质量差到不能看。

**Comment by Benlee1129** [comment]
瞭解，所以它使用的是分片字幕。

muzuiget ***@***.***> 於 2022年5月17日 週二 20:24 寫道：
