### ISSUE TITLE
Netflix no subtitle

### ISSUE THREAD

**Issue by dorawei** [muzuiget/dualsub-support#422]
好像更新之後netflix就不能正常顯示字幕了… chrome瀏覽器
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'downloadUrls')
    at c (content.js:1:98736)
    at content.js:1:99007
    at content.js:1:99166
    at l.createManifest (content.js:1:99430)
    at l.onManifest (content.js:1:15236)
    at onMessage (content.js:1:15182)

**Comment by muzuiget** [comment]
看下是否为 #410 的原因。

**Comment by muzuiget** [comment]
先访问 https://www.netflix.com/DoNotTest 关掉测试计划。

**Comment by dorawei** [comment]
> 先访问 https://www.netflix.com/DoNotTest 关掉测试计划。

關掉可以了，謝謝！
