### ISSUE TITLE
618了，打个折吧

### ISSUE THREAD

**Issue by stamnug** [muzuiget/dualsub-support#424]
打个5折吧，不打折来个半月套餐也行。

**Comment by muzuiget** [comment]
不搞这些套路。曾经两次调整价格，都以最低的单价赠送相应的天数给已购买用户，也即是什么时候买价格都是最低的了。

**Comment by stamnug** [comment]
┑(￣Д ￣)┍  现在套餐还是很不友好。其实，价格越贵，用户越不舍得浪费流量，巴不得每天24小时都在用。价格便宜下来，反而流量未必会用多少。就像现在的话费流量，每个月给几十G，多数人反而1G都用不了。

每天时间就那么多，若不是花钱买的流量，又有几个人真的会每天坚持花好几个小时看视频呢。

**Comment by stamnug** [comment]
价格低了，人均流量必然会下降，用户必然会增加。 整体流量和收入我不敢断言，但比值应该不会有太大变动。 用户上去对未来发展多是一件美事。个人建议。。。

**Comment by muzuiget** [comment]
你把问题想得太简单了。

其实我也可以这么收费：客户端设计成使用第三方 API 服务器，但我仍然可以对客户端收费 50 元一个月。当然有人会说，作者不需要付出额外成本了，为什么还要收费（或者价格太高），这不合理。

但是以作者角度看，我付出了劳动，就是希望获得报酬。

那么如何衡量收费模式或者价格是否合理呢？老掉牙的问题了，无非就是**市场**，或者说**供需关系**。按照你的说法，如果这是合理的，那么市场一定有很多能够代替 Dualsub 的软件，竞争关系把价格拖下来。

**Comment by stamnug** [comment]
没有什么合理不合理。 我只是反馈一下个人意见。一个月我用不了，50块钱太贵了，我不会买。25块钱半个月可以用一下。
至于如何根据反馈意见进行决策我是无权左右的。

**Comment by muzuiget** [comment]
你觉得贵这也很正常，但是现在这个定价还是有人愿意付费，那就由市场来决定好了。

你看我为什么只愿意最多卖两个月，就是为了随时调整定价。

**Comment by Benlee1129** [comment]
若一次訂一年，算500元，等於收費10個月，如何呢？這是常用於友善長期客戶的訂閱方式，很合理的商業模式，並不影響訂價策略。

**Comment by muzuiget** [comment]
现在定价 90 元两个月，10 个月也就 450 元，你怎么算的。

**Comment by muzuiget** [comment]
我亲自做客服，但不想讨论收费定价问题。不会因为个别用户讨价还价就算便宜点，这样的话还哪会有人愿意原价购买。
