### ISSUE TITLE
Dualsub装了不能用

### ISSUE THREAD

**Issue by Jiaojiao2005** [muzuiget/dualsub-support#427]
你好， 请问为什么装了插件不能用呢？ Subtitle language那一栏没有能选择的语言，显示是“0”。  我装了家里的几台电脑， 都是一样， 不能翻译， 为什么呢？

**Comment by Jiaojiao2005** [comment]
加一句， 是在YouTube上用不了。

**Comment by muzuiget** [comment]
要视频自己本身提供字幕才行，例如

* <https://www.youtube.com/watch?v=LaLvVc1sS20>
* <https://www.bilibili.com/video/BV1Gf4y1y7wc?p=21>

**Comment by Jiaojiao2005** [comment]
那如果显示“无法显示字幕”就没有希望了吗？ 有什么其他办法吗？蛮多想看的都“无法显示字幕”。。。

**Comment by muzuiget** [comment]
Dualsub 只支持在[特定网站](https://www.dualsub.xyz/zh/docs/supported-websites)，特定视频上显示双语字幕，即视频本身提供文本格式的字幕，这样才能二次处理（比如翻译）。

如果你在找任意视频的翻译软件，那不是 Dualsub 能做到。

扩展商店上已经有很多通过“录音”方式的扩展，但这种扩展不能有效解决延迟问题，体验很不好，因为录音识别有延迟，翻译也有延迟。

**Comment by Jiaojiao2005** [comment]
谢谢了， 这么耐心及时的回复！ ：）好明白了
