### ISSUE TITLE
您好，请问是否可以下载标准模式的字幕？

### ISSUE THREAD

**Issue by zhlz22** [muzuiget/dualsub-support#429]
您好，请问是否可以下载标准模式的字幕？付费后可以吗？或者利用其他工具？

**Comment by zhlz22** [comment]
看了您以前的介绍，和对其他用户的回复。还是希望能加入一个针对YouTube计数导出的功能，我觉得肯定是有很多愿意给这个功能付费群体的。也不会被喷一鱼两吃什么的，可以包年或者半年的用户才有这个功能之类的。因为youtube上确实有很多专业领域的优质资料，但时间久了有的会被发布者删，所以好的内容我还有下载留存的习惯，如果能同时下载您这个字幕就十分完美了。

**Comment by muzuiget** [comment]
我是想干脆专门弄一个字幕工具网站，让用户自己上传字幕文件，然后重用 Dualsub  的一些设计和代码来做双语合并、机器翻译。

这样好处就是：

* 我不需要（也不应该）关心原文字幕是什么视频的字幕。
* 可以按翻译字符数计费，翻译前就可以让用户确认会花费多少。

但是又想想这种网站或者现在没一千也有八百了，毕竟现在人人都搞自媒体，随便一些视频剪辑软件都内置这种功能。

所以除非是认同 Dualsub 的一些字幕设计和算法的人才会来用，但是这种人又有多少呢？

**Comment by zhlz22** [comment]
我觉得会很多，我测试了很多视频识别语音翻译的软件，翻译效果都很差，像您优化的断句法全网我都没找到第二个，一些学术内容的视频翻译起来效果都很通顺，这种是其他软件不能比的。我觉得您说的这个字幕网站是很好的，这种计量的可能会比订阅的收入更可观。

因为确实好用，时间久了就传播起来了，就像deepl翻译一样，也没有人宣传，用的人多了，好用的东西就自然传播了，然后就有消费群体了。包括您的这个插件我也是看其他的youtuber推荐才知道的，等您的网站翻译出来，这些字幕就会在网上传播，大家就会好奇这么好的翻译效果是什么软件实现的，然后就引流了；目前无法分享的可能机制就相对封闭，很难有更多人知道这样好的翻译。真心希望您能实现出来。

**Comment by muzuiget** [comment]
就是因为太多面向创作者的字幕工具，大多数都是为了批量制作各种低创内容，发到视频网站赚钱赚流量，我才不想掺和进去，安安静静做个面对观看者的工具就好。

如果你只是为了日后离线官网，完全可以把 YouTube 的视频和原文字幕文件备份下来，然后用 https://player.dualsub.xyz/ 来播放，效果是一样的。
