### ISSUE TITLE
最新版本不能下载字幕了

### ISSUE THREAD

**Issue by carli0215** [muzuiget/dualsub-support#43]
在chrome 应用商店中下载了最新版本的扩展，发现现在没有下载字幕功能了

**Comment by muzuiget** [comment]
点击设置面板里”关于“页面的“更多工具”。

**Comment by carli0215** [comment]
是通过https://dualsub-exporter.netlify.com/来下载字幕吗？今天试了好几个小时，一直在转圈,不知道是怎么回事
测试的网址：https://www.youtube.com/watch?v=DlmZYkNQI_s
![image](https://user-images.githubusercontent.com/30374441/73781889-09b55280-47cc-11ea-8d4d-5a5cf15dc011.png)


![image](https://user-images.githubusercontent.com/30374441/73781803-de326800-47cb-11ea-9255-2730bf31a375.png)

**Comment by muzuiget** [comment]
昨天内存告急，所以限制了一下字幕大小，但是这个导出器前端还没有做错误显示处理。

我调整了下大小限制，现在应该可以了。

**Comment by carli0215** [comment]
谢谢你的快速回复，也可能是我将上传的视频公开范围设置成了私享导致下载不了字幕，我将公开范围更改为公开后就可以正常下载了
后面有计划在字幕下载网站https://dualsub-exporter.netlify.com/
中多增加几个选项吗？例如：
1.可以有选择将每次下载字幕的的第一字幕语言和第二字幕语言固定，不用每次下载都得设置一下，英文>中文       英文
2.字幕的样式风格，自己设置好后可以选择保存几个快速样式风格，方便快速选择

**Comment by muzuiget** [comment]
导出器目前用的人太少，没有改进的动力。

ASS 的样式，可以用任何 ASS 字幕编辑器修改，或者用记事本改也行，无非就是替换掉最前面那几行样式定义。
