### ISSUE TITLE
Please support https://www.mewatch.sg/ 新加坡電視台

### ISSUE THREAD

**Issue by Benlee1129** [muzuiget/dualsub-support#430]
新加坡國家投資公司淡馬錫投資的電視頻道，內有東南亞、南亞語系的各種頻道，以華語跟英語節目為大宗。都有英語字幕，是一個相當好的免費平台。可以自由的申請帳號。

**Comment by muzuiget** [comment]
见 https://github.com/muzuiget/dualsub-support/issues/459
