### ISSUE TITLE
10play.com.au 有像 bbc.co.uk 的全屏問題

### ISSUE THREAD

**Issue by Benlee1129** [muzuiget/dualsub-support#432]
同 bbc.co.uk，把插件中全屏按鈕FS的10play打勾就可以了。

**Comment by muzuiget** [comment]
这个网站似乎加了更严格的 IP 限制，我使用的几个 VPS 澳洲代理都无法绕过限制，无法正常播放视频，广告倒是可以。

我不会再浪费时间和这些限制多多的网站斗智斗勇，这个网站不会再有任何修复，直到它改版自动失效。
