### ISSUE TITLE
Netflix 無字幕 已關閉測試計畫

### ISSUE THREAD

**Issue by tommy102282** [muzuiget/dualsub-support#433]
Netflix 6/15晚上開始無法使用，字幕數量都是0，Chorme瀏覽器
已嘗試访问 https://www.netflix.com/DoNotTest 关掉测试计划
關閉後一樣字幕數量為0

F12有錯誤訊息
content.js:30 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'downloadUrls')
    at wy (content.js:30:16531)
    at vy (content.js:30:16700)
    at Fa (content.js:30:16879)
    at le.createManifest (content.js:30:17248)
    at le.onManifest (content.js:26:10732)
    at onMessage (content.js:26:10680)
開發人員工具無法載入來源對應：無法剖析 https://www.netflix.com/service-worker.js.map 的內容：Unexpected token < in JSON at position 0

**Comment by muzuiget** [comment]
Dualsub v1.84.1 已发布，临时修复了这个问题。

现在 Netflix 的字幕菜单分成了两组，顶部的是首选语言，底部的是候选语言，候选语言初次加载是没有字幕地址的，所以 Dualsub 的菜单就不显示了。

如果需要 Dualsub 显示候选语言，需要使用 Netflix 的字幕菜单显示一下，触发字幕地址加载，这样才能在 Dualsub 菜单里显示出来。

**Comment by tommy102282** [comment]
> Dualsub v1.84.1 已发布，临时修复了这个问题。

請問如何更新為v1.84.1版?
謝謝

**Comment by muzuiget** [comment]
Chrome 审核太慢了，等不及可以用 Firefox 的 XPI 文件。

**Comment by muzuiget** [comment]
Chrome 商店已通过审核。

**Comment by SpriteColaFanta** [comment]
> Dualsub v1.84.1 已发布，临时修复了这个问题。
> 
> 现在 Netflix 的字幕菜单分成了两组，顶部的是首选语言，底部的是候选语言，候选语言初次加载是没有字幕地址的，所以 Dualsub 的菜单就不显示了。
> 
> 如果需要 Dualsub 显示候选语言，需要使用 Netflix 的字幕菜单显示一下，触发字幕地址加载，这样才能在 Dualsub 菜单里显示出来。

你好，1.85版本下又出现了无字幕的问题

**Comment by muzuiget** [comment]
这是 [dualsub-v1.84.1.zip](https://github.com/muzuiget/dualsub-support/files/8956677/dualsub-v1.84.1.zip) 版本，用开发者模式测试一下。

如果 v1.84.1 正常，而 v1.85.0，那么贴一下视频地址。

**Comment by SpriteColaFanta** [comment]
> 这是 [dualsub-v1.84.1.zip](https://github.com/muzuiget/dualsub-support/files/8956677/dualsub-v1.84.1.zip) 版本，用开发者模式测试一下。
> 
> 如果 v1.84.1 正常，而 v1.85.0，那么贴一下视频地址。

1.84.1下正常，观看的视频是：https://www.netflix.com/watch/81253106?trackId=14170286&tctx=1%2C1%2Ca1974282-7c28-46ea-9e77-57f96e54c948-544975758%2CGPS_39C670AD2AA7D7D4196FEACEC73DA1-B9F225DDE3A711-FA2C318CAD_p_1655891499875%2CGPS_39C670AD2AA7D7D4196FEACEC73DA1_p_1655891267319%2C%2C%2C%2C

**Comment by muzuiget** [comment]
v1.85.0 也是正常的。

![Screenshot_20220622_190317](https://user-images.githubusercontent.com/330812/175014731-ef9f3a4a-c534-44e9-b82e-62beeb640ead.png)

见我第二个回复

> 现在 Netflix 的字幕菜单分成了两组，顶部的是首选语言，底部的是候选语言，候选语言初次加载是没有字幕地址的，所以 Dualsub 的菜单就不显示了。
>
> 如果需要 Dualsub 显示候选语言，需要使用 Netflix 的字幕菜单显示一下，触发字幕地址加载，这样才能在 Dualsub 菜单里显示出来。

所以你试下手动激活下原生字幕菜单，会重新请求一个新的字幕列表。

**Comment by SpriteColaFanta** [comment]
> v1.85.0 也是正常的。
> 
> ![Screenshot_20220622_190317](https://user-images.githubusercontent.com/330812/175014731-ef9f3a4a-c534-44e9-b82e-62beeb640ead.png)
> 
> 见我第二个回复
> 
> > 现在 Netflix 的字幕菜单分成了两组，顶部的是首选语言，底部的是候选语言，候选语言初次加载是没有字幕地址的，所以 Dualsub 的菜单就不显示了。
> > 如果需要 Dualsub 显示候选语言，需要使用 Netflix 的字幕菜单显示一下，触发字幕地址加载，这样才能在 Dualsub 菜单里显示出来。
> 
> 所以你试下手动激活下原生字幕菜单，会重新请求一个新的字幕列表。

谢谢，发现问题了，是跟这个拓展冲突了：https://github.com/lkmvip/netflix-4K-DDplus ，这个拓展的字幕列表还是以前的版本

**Comment by SpriteColaFanta** [comment]
> 所以关掉那个扩展就可以了？不知道 #410 是否也是这个原因。

对的

**Comment by muzuiget** [comment]
发布了 v1.85.1，重新兼容 netflix-1080p 这个扩展，理论上 netflix-4K-DDplus 也应该兼容了。

有意思的是这种扩展，它们替换了整个 netflix 播放器代码，让播放器恢复回改版前的行为，也就是所有字幕语言都会被 Dualsub 显示出来。

如果等不及 Chrome 审核，可以开发者模式这个 zip 文件。

[dualsub-v1.85.1.zip](https://github.com/muzuiget/dualsub-support/files/9042002/dualsub-v1.85.1.zip)
