### ISSUE TITLE
HBO MAX 不能用了?

### ISSUE THREAD

**Issue by Retsu0907** [muzuiget/dualsub-support#436]
https://play.hbomax.com/
偵測不到字幕

其他網站(hulu,paramountplus,youtube)使用正常

是需要額外設置?還是暫時掉了?

**Comment by muzuiget** [comment]
已知问题，部分视频就是侦测不出来 https://github.com/muzuiget/dualsub-support/issues/351

除非对底层代码做较大改动，否则段时间不能修复了。

**Comment by muzuiget** [comment]
按 #439 所说处理。
