### ISSUE TITLE
youtube字幕背景大小问题

### ISSUE THREAD

**Issue by FmoX** [muzuiget/dualsub-support#438]
检索之后有过相同问题https://github.com/muzuiget/dualsub-support/issues/83
但是新版本没有内间距的调节选项https://github.com/muzuiget/dualsub-support/issues/83#issuecomment-629200701

**Comment by muzuiget** [comment]
看下 https://github.com/muzuiget/dualsub-support/issues/367#issuecomment-1018448018

**Comment by FmoX** [comment]
我理解错了 我像讲的是背景的宽高 不是两个字幕的间距 我想在标准模式调整成YouTube原生字幕的背景大小

**Comment by FmoX** [comment]
![image](https://user-images.githubusercontent.com/96420805/181661002-6b5d64d3-a2f7-4b36-8741-999f2bbeabb5.png)
