### ISSUE TITLE
HBO Max 失效问题

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#439]
最近又有人报告 HBO Max 失效问题，这次可能真的是所有视频完全失效，而不是[使用分片字幕](https://github.com/muzuiget/dualsub-support/issues/351)的视频失效。

HBO Max 几次频繁改版都搞得越来越难以兼容，我只能遗憾放弃正式支持 HBO Max 了。

这表示在商店版 Dualsub 暂时不会支持 HBO Max 了，后续更新会删除申明需要 `https://play.hbomax.com/*` 的权限。

如果有人还愿意借用账号给我抢救一下，那就专门做个分支版本，[就像 Amazon 那样](https://github.com/muzuiget/dualsub-support/issues/418)，让用户以开发者模式加载使用。

这个分支版本就只考虑兼容 HBO Max，这样可以大胆改掉底层代码，以便重新支持使用分片字幕的视频。

**Comment by muzuiget** [comment]
v1.85.4 已删除 `https://play.hbomax.com/` 的支持。

**Comment by Seulxy** [comment]
您好，我愿意借用HBO的账号，请问还需要吗？

**Comment by muzuiget** [comment]
我最近暂时没时间处理这个问题，你可以先借给我账号，但是需知道逆向工程还是要看运气的，所以这个问题不知道需要花多少时间，未必能在你愿意借出账号的时间内解决问题。

**Comment by Seulxy** [comment]
> 我最近暂时没时间处理这个问题，你可以先借给我账号，但是需知道逆向工程还是要看运气的，所以这个问题不知道需要花多少时间，未必能在你愿意借出账号的时间内解决问题。

已经发到你的邮箱muzuiget+dualsub@gmail.com了~

**Comment by muzuiget** [comment]
见 https://github.com/muzuiget/dualsub-support/issues/459
