### ISSUE TITLE
使用duelsub,选择“英语（自动生成）”，反而youtube原始字幕都不显示了

### ISSUE THREAD

**Issue by forrest917** [muzuiget/dualsub-support#44]
使用duelsub,选择“英语（自动生成）”，反而youtube原始字幕都不显示了，更没有翻译了。只有选择“关闭”，youtube原始字幕才显示。请大佬修复一下啊！谢谢。

**Comment by muzuiget** [comment]
麻烦发个视频地址测试下。

**Comment by forrest917** [comment]
https://www.youtube.com/watch?v=N1-bCj4InD0&t=254s
也有可能是youtube的问题，我安装其他翻译扩展，效果也一样不能翻译。

**Comment by muzuiget** [comment]
我刚才试一下是可以喔，是不是你的网络问题？你可以点击两次播放器的字幕图标强制重新请求一次。

**Comment by surrla** [comment]
> 麻烦发个视频地址测试下。

我的也是，求解决

**Comment by surrla** [comment]
我的也是，弄不出来，还会遮挡原来字幕

**Comment by surrla** [comment]
都需要什么去设置呀，弄了一下午没弄好

**Comment by forrest917** [comment]
今天上班用单位电脑（i5-8400），是正常可用了。家里的电脑（r5-1600）还是不行。
系统都是win10的。不知什么情况。

**Comment by muzuiget** [comment]
和操作系统无关，你要把 `*.appspot.com` 也加入代理服务器。

**Comment by forrest917** [comment]
恩。是的。改成全局模式就可以显示了。

**Comment by surrla** [comment]
我的设置成全局也不行，怎么把那个加入代理



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: forrest917 <notifications@github.com&gt;
发送时间: 2020年2月11日 19:22
收件人: muzuiget/dualsub-support <dualsub-support@noreply.github.com&gt;
抄送: surrla <554612245@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[muzuiget/dualsub-support] 使用duelsub,选择“英语（自动生成）”，反而youtube原始字幕都不显示了 (#44)




恩。是的。改成全局模式就可以显示了。

**Comment by surrla** [comment]
还是不行




发自我的iPhone


------------------ 原始邮件 ------------------
发件人: forrest917 <notifications@github.com&gt;
发送时间: 2020年2月11日 19:22
收件人: muzuiget/dualsub-support <dualsub-support@noreply.github.com&gt;
抄送: surrla <554612245@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[muzuiget/dualsub-support] 使用duelsub,选择“英语（自动生成）”，反而youtube原始字幕都不显示了 (#44)




恩。是的。改成全局模式就可以显示了。

**Comment by muzuiget** [comment]
@surrla 用浏览器直接打开 https://dualsub-app.appspot.com/ 看看能否访问，如果不行，说明没有加入代理。

**Comment by surrla** [comment]
打开只显示“Dualsub Server”两个单词




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"muzuiget"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月13日(星期四) 凌晨1:26
收件人:&nbsp;"muzuiget/dualsub-support"<dualsub-support@noreply.github.com&gt;;
抄送:&nbsp;"王小亮"<554612245@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [muzuiget/dualsub-support] 使用duelsub,选择“英语（自动生成）”，反而youtube原始字幕都不显示了 (#44)




@surrla 用浏览器直接打开 https://dualsub-app.appspot.com/ 看看能否访问，如果不行，说明没有加入代理。

**Comment by muzuiget** [comment]
那就说明代理没问题，感觉你的问题描述不清楚。

你看过官方文档了吗？

https://dualsub.netlify.com/zh-cn/introduce

**Comment by surrla** [comment]
看了。自动生成的是英文，想转化为中文，没反应，还把youtobe自带的英文弄没了。我这字幕图标一直显示的是C而不是CC




发自我的iPhone


------------------ 原始邮件 ------------------
发件人: muzuiget <notifications@github.com&gt;
发送时间: 2020年2月13日 04:34
收件人: muzuiget/dualsub-support <dualsub-support@noreply.github.com&gt;
抄送: surrla <554612245@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[muzuiget/dualsub-support] 使用duelsub,选择“英语（自动生成）”，反而youtube原始字幕都不显示了 (#44)




那就说明代理没问题，感觉你的问题描述不清楚。
 
你看过官方文档了吗？
 
https://dualsub.netlify.com/zh-cn/introduce

**Comment by muzuiget** [comment]
你贴一下视频地址。

**Comment by muzuiget** [comment]
https://www.v2ex.com/t/644094 可以确定重叠不是扩展的问题，是 YouTube 自己的问题。

**Comment by surrla** [comment]
https://www.youtube.com/watch?v=yIo4cPxwT-E不是遮挡，是开了你这个插件字幕不显示




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"muzuiget"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月13日(星期四) 晚上8:18
收件人:&nbsp;"muzuiget/dualsub-support"<dualsub-support@noreply.github.com&gt;;
抄送:&nbsp;"王小亮"<554612245@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [muzuiget/dualsub-support] 使用duelsub,选择“英语（自动生成）”，反而youtube原始字幕都不显示了 (#44)




https://www.v2ex.com/t/644094 可以确定重叠不是扩展的问题，是 YouTube 自己的问题。

**Comment by Solon21** [comment]
我关掉插件字幕可以正常显示，一开插件字幕就不见了，所有视频都是这样。前几天还可以正常使用

**Comment by muzuiget** [comment]
你是否更新到最新版本？

**Comment by muzuiget** [comment]
缺少反馈，关闭词问题。
