### ISSUE TITLE
平假名和分词线不工作问题

### ISSUE THREAD

**Issue by FmoX** [muzuiget/dualsub-support#440]
![8E0I$6%YG2K_V@K`VGOW@D8](https://user-images.githubusercontent.com/96420805/181513010-a69b2078-c489-4d16-9319-e7aa7db01fb5.png)

**Comment by muzuiget** [comment]
确保能正常链接 <https://api.dualsub.xyz/>。

确定所使用的“语言样式”，“语言工具”中选择了“日语分析”。

![Screenshot_20220728_222033](https://user-images.githubusercontent.com/330812/181540652-197baf09-a830-483c-9e0a-d6ea6aec9d20.png)

**Comment by FmoX** [comment]
200 OK 是这样设置的 就是重置也没解决

**Comment by FmoX** [comment]
虽然是这么设置的 但是没有变化 不过尝试重装之后可以解决了
