### ISSUE TITLE
youtube字幕背景宽高问题

### ISSUE THREAD

**Issue by FmoX** [muzuiget/dualsub-support#441]
![image](https://user-images.githubusercontent.com/96420805/181904331-2a81e60c-0c71-454e-b7de-2756951870bb.png)
标准模式怎么调整像YouTube的原生字幕一样的背景宽高

**Comment by muzuiget** [comment]
在“快速设置”里选择“基本样式”为 `背景` 时，默认设置下已经有一点内间距的，不会像你截图中那么贴的。

如果你仍然想自己调，可以添加一个用户样式：

![Screenshot_20220730_174357](https://user-images.githubusercontent.com/330812/181904881-846c731f-edf0-434c-a45f-5d5b778d0241.png)

代码：

```
.dualsub-renderer .subtitles {
    padding: 16px 16px;
}
```

然后刷新网页。

默认是  `padding: 8px 16px;`，即上下 `8px` ，左右 `16px` ，应用样式后四个方向都是 `16px`。

**Comment by muzuiget** [comment]
这是默认设置下的效果。

![Screenshot_20220730_175509](https://user-images.githubusercontent.com/330812/181905204-11b83582-d110-48bc-990b-1be6aa329523.png)

上面是标准模式，下面是简单模式。

**Comment by FmoX** [comment]
> 这是默认设置下的效果。
> 
> ![Screenshot_20220730_175509](https://user-images.githubusercontent.com/330812/181905204-11b83582-d110-48bc-990b-1be6aa329523.png)
> 
> 上面是标准模式，下面是简单模式。

我知道默认设置下已经有一点内间距  但是基本样式为背景的话那么双字幕的背景就会合并一个了 而且覆盖组件设置
![image](https://user-images.githubusercontent.com/96420805/181908840-432ee7c5-c1dd-4787-9573-1718942af0d9.png)
双字幕公用的背景遮挡有点影响 所以说可以调整其中一个字幕的背景就好了

**Comment by muzuiget** [comment]
需要把基础样式切到除“背景”之外，避免添加默认背景，然后用 `.subtitle-1` 自己添加背景并增加内间距：

```
.dualsub-renderer .subtitle-1 {
    background: rgb(0 0 0 / 75%);
    padding: 16px;
}
```

**Comment by muzuiget** [comment]
这是另一个效果，如果你不想左右两边空白背景和第二字幕对齐的话：

```
.dualsub-renderer .subtitle-1 .dialogue {
    background: rgb(0 0 0 / 75%);
    padding: 16px;
    width: fit-content;
    margin: auto;
}
```

![Screenshot_20220730_213542](https://user-images.githubusercontent.com/330812/181916803-2c3ddc27-fdfd-40da-85fd-289b1de98153.png)

**Comment by Andy19L** [comment]
Oh Plz Don't. I usually use different sizes in both two language subtitles via the "style" function. It gave me more motivation to learn languages.
