### ISSUE TITLE
请支持Curiosity Stream

### ISSUE THREAD

**Issue by brucezhiyue** [muzuiget/dualsub-support#442]
请支持Curiosity Stream

**Comment by Peijidak** [comment]
https://www.dualsub.xyz/zh/docs/supported-websites

> 如果你请求支持新的网站，请你同时提供以下信息：
> 
> 网站地址：具体指出网站地址。
> 测试视频：包含有多语言字幕的视频地址。
> 对于只提供收费视频的网站，开发者可能会询问你是否愿意提供账号以供测试。
