### ISSUE TITLE
有没有可能做一个ios/macos safari版本的扩展  以一个合理的的价格 上架app store

### ISSUE THREAD

**Issue by jiangxiaoxu** [muzuiget/dualsub-support#445]
有没有可能做一个ios/macos safari版本的扩展  以一个合理的的价格 上架app store

**Comment by muzuiget** [comment]
其实早已经支持 Safari 了，只是我不愿意上架 App Store 而已，见 #268。因为上架需要交苹果保护费 700 元一年。

如果要收费回本苹果保护费，那么如何定价呢，订阅制还是买断制？而且我现在另外有[收费服务](https://www.dualsub.xyz/zh/docs/paid-features/overview)，会不会让人觉得我一鱼两吃？

除始之外，Dualsub “支持 iOS 的 Safari”不等于“支持视频网站的移动版”，仅保证支持 YouTube 移动版，即 `https://m.youtube.com` 这个网址，其余网站可能要开启桌面模式使用，使用体验很不好。

就是，能在 iOS 运行，还是不能保证有用户体验地运行。

现在只能用户自己下载 XCode，然后自己打包 Chrome 的 crx 文件来安装。

我觉得最好的解决方案就是 https://browser.kagi.com/ 这个自行实现 WebExtension API 的浏览器，就像 Android 的 kiwi 那样，开源免费，可以直接加载扩展的 crx 文件。不过似乎还有一些 bug。

**Comment by muzuiget** [comment]
我不喜欢买断制，绝大部分用户眼中的买断制就是开发者卖身制，要求开发者终生更新维护。我可不想今天赚了某个用户十块钱，十年后还得对用户有求必应做客服支持。

再说买断 Dualsub 客户端是没有意义的，因为在其它浏览器里本来就是免费的，现在只是苹果这只臭鸡不让你自由安装到你的 Safari 里而已，一定要走 App Store 那一套流程再敲一笔。所以很多本来在 Chrome/Firefox 免费的扩展都没兴趣上架 App Store。

其实我更想是用户买的是 **App Store 服务**本身，而不是开发者的软件。这样用户有两个选择：

1. 花上 50GB 硬盘空间，以及 3 小时下载 XCode，自己注册苹果开发者账号安装到手机里，然后每 7 天重装一次。
2. 每个月花费 1 RMB 购买 App Store 对这个软件的安装和更新服务。

这么比较下来，相信绝大部分人都觉得第二个方案都是超值的，用户花钱是买自己的时间，而不是开发者的软件。可惜苹果不提供这种服务。

目前来说，我还是寄望于 Orion 浏览器，毕竟 Dualsub 所需要的 WebExtension API 其实很简单。

**Comment by muzuiget** [comment]
如果你还是愿意花钱买时间的话，最好就是买一台二手 Android 手机用，比如我花了不到 600 元买一台二手 Pixel 3XL，我就不想再折腾 iOS 了。

**Comment by muzuiget** [comment]
因为这些脚本只是很简单地合并时间轴，然后会有冲突的地方留给播放器处理，冲突的地方是指时间轴/显示位置互相重叠，我在 Dualsub 可是设计一套系统来解决这个问题，生成的干净无冲突的字幕格式给播放器显示，这可不是几十行油猴代码能解决的。

**Comment by muzuiget** [comment]
不是定价问题，而是一旦收费就各种麻烦了。

其实我是不信任苹果那套付费方案，随便搜下工具类应用，比如”翻译“，”字幕“之类的，然后挑一个排名前面的应用，查看最新评论，绝大部分评论都是抱怨无缘无故扣费的。

**Comment by muzuiget** [comment]
你说的我都知道，如果使用这些收费方案，那说明我要特别针对苹果来增加和改写大部分代码，但这本来就是一个通用的浏览器扩展，还得给苹果写专门代码真是不爽了。

如果是 macOS，可以用 Chrome，而且 Chrome 104 开始支持 HEVC 硬件解码，所以没必要用 Safari 了。所以现在问题就是在 iPadOS/iOS 上使用而已，还是等 Orion 好了。

**Comment by muzuiget** [comment]
我现在只有一台 2013 的 MacBook Air，升级到 Big Sur，装了 XCode 勉强用来打包测试一下，编写 ObjectC/Switf 卡得一逼无法用。
