### ISSUE TITLE
funimation字幕失效问题

### ISSUE THREAD

**Issue by Seulxy** [muzuiget/dualsub-support#446]
https://www.funimation.com/shows/toilet-bound-hanako-kun/
你好开发者，不知道为啥，经常会检测不到字幕，来来回回打开几次后，偶尔才能有一次成功的……

**Comment by muzuiget** [comment]
估计改版了。

**Comment by muzuiget** [comment]
我测试还是正常的。

![Screenshot_20220829_032039](https://user-images.githubusercontent.com/330812/187136877-2990fc68-73d3-403c-894f-4924aa184bbf.png)
