### ISSUE TITLE
Amazon.com 讀取不到字幕檔

### ISSUE THREAD

**Issue by Benlee1129** [muzuiget/dualsub-support#447]
我一直使用1.81版的Dualsub 採專家模式讀取Amazon.com 字幕，但今天試了多部影集，讀到的字幕檔都是0。

**Comment by Benlee1129** [comment]
英國 amazon.co.uk 仍然可以讀取字幕檔，不過檢查了1.81版的API key 顯示400，key 是在可用時間。
昨日提及不能讀取的是美國的Amazon.com。

**Comment by muzuiget** [comment]
amazon.com 我测试过还是正常的，[测试视频](https://www.amazon.com/Sprung-Season-1-Official-Trailer/dp/B0B18GVDTZ/ref=FREEVEE_ACQ_CRO_OTH_MLP_05Q_SPRU)。

**Comment by muzuiget** [comment]
服务器去掉了旧版本 v1.81 接口，你要使用较新版本。

你要根据最新版本改一个，见 #418

**Comment by muzuiget** [comment]
你清空 amazon.com 的浏览数据，第一次打开时，在右下角会看到这个信息吗？

![Screenshot_20220829_032643](https://user-images.githubusercontent.com/330812/187138736-16327637-8f2e-494c-b50c-9bd63cc4f918.png)

**Comment by Benlee1129** [comment]
用1.85.2版修改後，正常可用。
謝謝

muzuiget ***@***.***> 於 2022年8月29日 週一 14:36 寫道：

**Comment by Benlee1129** [comment]
沒有這個問題，我使用的kiwi 瀏覽器可以使用最高品質的影集。

muzuiget ***@***.***> 於 2022年8月29日 週一 14:41 寫道：

**Comment by muzuiget** [comment]
那个画质提示，只在 Windows 下会出现，或者改成 Windows 的 UserAgent 就会出现。

其实 Amazon 有两种播放器的，Linux 和 Windows 使用不同播放器。

**Comment by Benlee1129** [comment]
我是使用手機版的Kiwi，為Linux平台。
沒有出現提示，就是你說的原因。

muzuiget ***@***.***> 於 2022年8月29日 週一 16:10 寫道：

**Comment by muzuiget** [comment]
所以你你用 v1.86.0 后，amazon.com 视频也正常了？

**Comment by Benlee1129** [comment]
我是用1.85.2改的，正常。

muzuiget ***@***.***> 於 2022年8月29日 週一 16:15 寫道：
