### ISSUE TITLE
Condition that fulfills for every Latin alphabet word?

### ISSUE THREAD

**Issue by TheChilliPL** [muzuiget/dualsub-support#448]
Hello, I'm trying to hide the rōmaji transcription in the existing subtitles that have both the original Japanese text as well as the romanization after it.
I'm not sure how it could be done, it seems like in the conditions list there is a Romaji textbox, but it doesn't seem to be documented in any way, nor is it used in any existing component condition style. How do these textboxes work?

**Comment by muzuiget** [comment]
Currently no such features like this, the only way is download the subtitle files, and replace the romaji in a text editor, then [load it as external subtitle](https://www.dualsub.xyz/docs/load-external-subtitle-files) file in Dualsub.

You can use Chrome DevTools to get the subtitle file.
