### ISSUE TITLE
亚马逊

### ISSUE THREAD

**Issue by just4fun1101** [muzuiget/dualsub-support#449]
你好，prime video好像失效了，读取不了字幕

**Comment by muzuiget** [comment]
应该类似 #447。

试下 amazon.com [这个视频](https://www.amazon.com/Sprung-Season-1-Official-Trailer/dp/B0B18GVDTZ/ref=FREEVEE_ACQ_CRO_OTH_MLP_05Q_SPRU)是否正常。
