### ISSUE TITLE
dualsub failed to fetch for bilibili website

### ISSUE THREAD

**Issue by vonxxe** [muzuiget/dualsub-support#452]
hiya, I was using dualsub today (02/09/2022) when suddenly this popped up on a bilibili VOD I was watching. The MTL wasnt working but the chinese learning one was. Is there an error or something of that sort?

(the subtitles I was using were auto-subtitles from the site itself btw)

![unknown (14)](https://user-images.githubusercontent.com/112676013/188051287-5954c4da-2cfb-4757-bd02-a26402064075.png)

**Comment by muzuiget** [comment]
Make sure the extension has persmission to access `https://api.dualsub.xyz/*`

![Screenshot_20220902_112338](https://user-images.githubusercontent.com/330812/188053036-72505e06-41b6-4544-a68b-611740d65294.png)
