### ISSUE TITLE
API-key输入后网络连不上

### ISSUE THREAD

**Issue by liz727** [muzuiget/dualsub-support#456]
API-key输入之后网络一直连不上，但是视频网页和谷歌都能打开，我电脑本身上网没问题

![image](https://user-images.githubusercontent.com/79632825/193448082-001e7554-16c1-4715-9e46-63396dbb7f7e.png)

**Comment by muzuiget** [comment]
先在浏览器新标签页打开 <https://api.dualsub.xyz/>，如果显示 200 OK，表示你的网络是正常的。

那么可能就是浏览器扩展权限问题了，进入浏览器扩展管理页，确保 Dualsub 有 `api.dualsub.xyz` 这个域名的权限。

一般来说，初始安装时默认会允许所声明的网站权限，除非用户安装后又手动取消，也可能使用其它“扩展管理”类的扩展自动取消。

**Comment by liz727** [comment]
谷歌的拓展，权限看起来是自动允许的
![image](https://user-images.githubusercontent.com/79632825/193449485-fc118a17-ce88-4688-ad66-30cae302c692.png)

dualsub拓展使用必须要翻墙吗？
我发现不开vpn，连接不上网络（200 OK）。不过视频页面，dualsub能提取出原字幕，就是翻译不了。

开了VPN之后，网络显示200 OK，但是视频页面根本打不开dualsub
![image](https://user-images.githubusercontent.com/79632825/193449638-43b44666-2eb3-41d7-b317-00aaf1bab0c7.png)

这个是视频地址：https://www.ardmediathek.de/video/tatort/waldlust/wdr/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTUwYmJhNDExLTkwZGEtNGIyMy04ZmQzLTgyZGI0YzA2ZmU2OQ

**Comment by muzuiget** [comment]
访问 https://api.dualsub.xyz/ 不需要翻墙，实际上这个地址已经用了 Cloudflare 做了 CDN 加速了，直接打不开就可能也可能是 ISP 的原因。当你也可以加代理访问。

你这个视频我测试是正常，原因也是你截图里列出的 3 点。

或者你可以先卸载扩展，完全关闭浏览器，再重启浏览器，重新安装扩展。
