### ISSUE TITLE
請求支援 Now Player

### ISSUE THREAD

**Issue by Peijidak** [muzuiget/dualsub-support#457]
開發者muzuiget你好！

網站地址： https://nowplayer.now.com/

網站是香港的收費串流影片網站，與viu.tv同屬一間公司。本人願意提供網站賬戶以供測試。

網站只供香港觀衆收看。如有需要，本人願意提供VPN賬戶以供測試。

謝謝！

**Comment by muzuiget** [comment]
见 https://github.com/muzuiget/dualsub-support/issues/459
