### ISSUE TITLE
请求支持新网站汇总

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#459]
在完成 [Manifest V3 升级](https://github.com/muzuiget/dualsub-support/issues/458) 之前不打算支持新网站了，因为现有网站都有可能因为升级而挂掉。

这里列出长时间没处理的 Issues：

- [ ] [#457](https://github.com/muzuiget/dualsub-support/issues/457) https://nowplayer.now.com/ 
- [ ] [#455](https://github.com/muzuiget/dualsub-support/issues/455) https://www.discoveryplus.com/
- [ ] [#451](https://github.com/muzuiget/dualsub-support/issues/451) https://www.vlive.tv/
- [ ] [#450](https://github.com/muzuiget/dualsub-support/issues/450) https://www.tv5mondeplus.com/
- [ ] [#444](https://github.com/muzuiget/dualsub-support/issues/444) https://learning.oreilly.com/
- [ ] [#439](https://github.com/muzuiget/dualsub-support/issues/439) https://play.hbomax.com/
- [ ] [#434](https://github.com/muzuiget/dualsub-support/issues/434) https://pluto.tv/
- [ ] [#431](https://github.com/muzuiget/dualsub-support/issues/431) https://mobile.france.tv/
- [ ] [#430](https://github.com/muzuiget/dualsub-support/issues/430) https://www.mewatch.sg/
- [ ] [#403](https://github.com/muzuiget/dualsub-support/issues/403) https://www.nicovideo.jp/
- [ ] [#465](https://github.com/muzuiget/dualsub-support/issues/465) https://www.starplus.com/
- [ ] [#490](https://github.com/muzuiget/dualsub-support/issues/490) https://tv.apple.com/
- [ ] [#527](https://github.com/muzuiget/dualsub-support/issues/527) https://www.crehana.com/
- [ ] [#537](https://github.com/muzuiget/dualsub-support/issues/537) https://www.hbogoasia.tw/
- [ ] 来自邮件 https://player.vimeo.com/
- [ ] 来自邮件 https://www.khanacademy.org/
- [ ] 来自邮件 https://www.crunchyroll.com/
- [ ] 来自邮件 https://www.sbs.com.au/
- [ ] 来自邮件 https://www.blutv.com/
- [ ] 来自邮件 https://www.wowtv.de/
- [ ] 来自邮件 http://www.gohitv.com/

_这个列表仅仅做个备忘，不表示优先支持和保证支持。_

另外有些人是发邮件请求的，我找起来太麻烦了，所以我当忘记了。所以请你们重新发一次，或者这里跟帖，我添加到这个列表中。

**Comment by muzuiget** [comment]
他这个扩展示加载本地字幕文件的，Dualsub 旧版本都能做到，只不过最近为了升级 Manifest V3 删除了。

HBO Max 最大问题就是因为用了分片字幕，因为底层代码一开始没有考虑到这个问题，现在**不能有效率处理**，所以只好先删除了，见 #439。

**Comment by 1604295917** [comment]
[vimeo](https://vimeo.com/)可能因为升级而挂掉了
字幕地址:https://player.vimeo.com/texttrack/*.vtt?token=*
根据js文件看是12月13日更新了。

**Comment by PochienTsai** [comment]
請求支持下列網站
https://codewithmosh.com/ 
下面是該網站免費試看的影片
https://codewithmosh.com/p/the-ultimate-html-css-part1

**Comment by touchmii** [comment]
请求支持下列网站
https://tubitv.com/
下面是免登录可观看的影片
https://tubitv.com/movies/100009033/deadly-midwife

**Comment by muzuiget** [comment]
关闭此帖，原因见 https://github.com/muzuiget/dualsub-support/issues/553
