### ISSUE TITLE
很好用 希望加一个一键开关插件的按钮谢谢

### ISSUE THREAD

**Issue by lichenxxx** [muzuiget/dualsub-support#46]
很好用 希望加一个一键开关插件的按钮谢谢

**Comment by muzuiget** [comment]
一键开关？意思是一键把两个下拉框切换到为“关闭”？

**Comment by Jesselee0322** [comment]
比如我想要双语字幕，第一行英文-英文，第二行英文-中文，设置好了以后，下次能够固定这个设置，直接就是这两种语言，打开一键开关就是我第一次那种设置，省的每次设置都很麻烦

**Comment by muzuiget** [comment]
不是已经有了吗？难道你不知道点击工具栏那个图标可以打开设置？

**Comment by muzuiget** [comment]
文档[优先选择语言](https://dualsub.netlify.com/zh-cn/setting?id=%e4%bc%98%e5%85%88%e9%80%89%e6%8b%a9%e8%af%ad%e8%a8%80)。

**Comment by lichenxxx** [comment]
> 一键开关？意思是一键把两个下拉框切换到为“关闭”？

首先感谢回复。
就是目前按照你的文档设置了英文和中文一起，但是某些时候直接想看原版的(就是不使用这个插件)，能否在哪个DS按钮下面加入一个一键关闭插件(使插件不生效)的按钮。
不知道有没有表达清楚，谢谢！

**Comment by muzuiget** [comment]
看几分钟选两次“关闭”不麻烦吧，这样各种状态多了，反而把界面和选择搞复杂。
