### ISSUE TITLE
删除“插件”功能，转移到 WildMonkey 扩展

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#460]
因为要升级到 [Manifest V3](https://github.com/muzuiget/dualsub-support/issues/458) 标准，所以删除 v1.86.5 中的“插件”功能。

**如果你没有使用或改动过“插件”标签页中的任何设置，无须理会这个改动。**

## 删除原因

这里的”插件“其实就是一个编辑大段配置文本的地方，几种配置类型：

* 样式
* 脚本
* 菜单自动选择（标准模式）
* 菜单自动选择（简单模式）

### 菜单自动选择

我觉得这个功能应该没多少人用了，甚至我自己都不用。实际上默认的做法应该很好了：优先选择和前一个视频的相同字幕语言菜单，所以干脆删除了。

### 样式和脚本

这两个统称”用户脚本“，例如油猴脚本也算是一种用户脚本。Manifest V3 标准不允许”执行远程代码“，但是定义有点模糊，用户自己从网上复制并粘贴运行的代码算不算“远程代码”？

不过 Google 又打算允许了这种情况了，见 [Userscript managers support](https://developer.chrome.com/docs/extensions/mv3/known-issues/#userscript-managers-support) 不过现在连设计文档都没有。

我觉得现在 Dualsub 这个功能也应该很少人用了，所以也干脆删掉了。

## 迁移方法

实际上我早建了个 [WildMonkey](https://github.com/muzuiget/monkey-support/blob/master/README.zh.md)，就是把 Dualsub 的用户脚本功能提取出来，方便在任何网站上使用：

* [Chrome](https://chrome.google.com/webstore/detail/wildmonkey/jlffehhlfkdbdheffcaekpmkhfphmhpg) 
* [Edge](https://microsoftedge.microsoft.com/addons/detail/wildmonkey/pmcpgdoagobpecaodmpjnhdigdicapad)

设置界面几乎一样，区别在于把执行网站从单选框改成表达式。

例如在 Dualsub 中勾选了 `https://www.youtube.com/` 单选框，则在 WildMonkey 使用表达式 `https://www.youtube.com/*`，也就是末尾加 `*`。

**Comment by Peijidak** [comment]
打開YouTube，發現Dualsub無法自動顯示字幕，點進去才得悉「菜單自動選擇（標準模式）」功能要沒了，很遺憾。

請問這個功能可以透過WildMonkey實現嗎？

我的「菜單自動選擇（標準模式）」功能設置是：

**字幕#1**
```
en-gb, en-uk, en, en*, en-us
```
_換言之：英文（英國）> 英文_


**字幕#2**
```
yue, zh-hk, zh-hant, zh-tw
或
從 zh-hans, zh-cn 翻譯爲 zh-hant
或
從 en-gb, en-uk, en, en*, en-us 翻譯爲 zh-hant
```
_換言之：粵語 > 中文（香港） > 中文（繁體） > 中文（臺灣） > 中文（簡翻繁） > 中文（英翻繁）_


我沒有這方面的背景，當初看文檔也花了好些時候理解。不過設置好後，這個功能確實是省了我許多力氣點來點去。

雖然我上面是這樣說，但是也只是一個個體使用者的使用體驗，也理解和明白開發者在開發新版本時需要作出功能上的刪減。

順祝開發者業務蒸蒸日上！

**Comment by muzuiget** [comment]
现在 WildMonkey 不能替代，你只能用开发者模式使用 v1.86.5 版本。

这功能现在看来过度设计了，专门设计了个配置代码格式，也不好理解，所以我也相信没什么人用。

既然一样难理解，还不如直接用 JavaScript 处理，所以我考虑以后再回来的话，会给 Dualsub 设计一些 JavaScript 接口，然后让 WildMonkey 跑 JavaScript 来调用。

**Comment by Peijidak** [comment]
謝謝回覆！
