### ISSUE TITLE
Not working on Disney+

### ISSUE THREAD

**Issue by kbsarrow** [muzuiget/dualsub-support#467]
It seems that 'dualsub' is not working on Disney+

**Comment by khaeunie** [comment]
Same problem here. "Dualsub" is not working on Dİsney+ since yesterday. I use this extention only for Disney+. I hope the problem can be solved as soon as possible.

**Comment by fragarray** [comment]
+1

**Comment by muzuiget** [comment]
Hi guys.

* Update to Chrome 107 and Dualsub 2.4.0.
* Check your Disney+ account setings to disable "new design layout preivew" feature (if any).

Then test it again, if it still does'nt work, please post your Disney+ region and some testing video urls.

**Comment by fragarray** [comment]
> Hi guys.
> 
> * Update to Chrome 107 and Dualsub 2.4.0.
> * Check your Disney+ account setings to disable "new design layout preivew" feature (if any).
> 
> Then test it again, if it still does'nt work, please post your Disney+ region and some testing video urls.

Hi, after update chrome and extension nothing change.
In can't find "new design layout preivew" feature.
My region is Italy.

**Comment by muzuiget** [comment]
Dualsub still works on US region, maybe they deploys the new design layout on some regions only.

**Comment by muzuiget** [comment]
You can use a US proxy to workaournd this until Dualsub fix this issue.

**Comment by khaeunie** [comment]
Even though I use VPN and locate it to United States, still works on Netflix but doesn't work on Disney+.

![image](https://user-images.githubusercontent.com/119002092/204119127-ba7d61e9-3db0-40f4-9eb7-a5a6b662946b.png)

![image](https://user-images.githubusercontent.com/119002092/204119211-8aac6415-48c0-4182-aa83-060425a24374.png)

**Comment by muzuiget** [comment]
So Disney+ is doing A/B testing, the website code is diffrrence on difference accounts/regions/browsers.

**Comment by Fred00231** [comment]
Hi, after update chrome and extension nothing change.
I can't find "new design layout preivew" feature.
My region is Taiwan.

**Comment by muzuiget** [comment]
Netflix has a user settings called https://www.netflix.com/DoNotTest, it allows users to quit the testing new website layout, it looks like Disney+ doesn't a setting like that.

And I notice if you change the profile UI language to non-English, it won't redirect you to a new url:

* English

```
https://www.disneyplus.com/video/06ca06ee-00ef-48af-bc90-850a35c543b4
```

* non-English

```
https://www.disneyplus.com/ko-kr/video/06ca06ee-00ef-48af-bc90-850a35c543b4
```

So you have any luck to change the profile language?

**Comment by muzuiget** [comment]
If it doesn't works, it is painful that I can't reproduce the issue on my computer.

So I will build a debug version Dualsub, which add some debug messages to the DevTools console, to help me find out where the issue happen.

**Comment by khaeunie** [comment]
I changed my profile language. It's English now. But still Dualsub is not working. And I'm sorry for troubling and bothering you..
![image](https://user-images.githubusercontent.com/119002092/204613650-290f82bc-44a3-4388-b637-d36197433ec1.png)
![image](https://user-images.githubusercontent.com/119002092/204614503-c5927f08-feed-4f0b-8133-438413b56924.png)

**Comment by khaeunie** [comment]
There are also comments under the extension on chrome web store. I hope this problem can be solved soon. Thank you for your hard work.

**Comment by khaeunie** [comment]
There are also comments under the Dualsub extension on chrome web store. I hope this problem can be solved soon. Thank you for your hard work.

**Comment by ksiwososj** [comment]
It's still not working. When will it be available?

**Comment by XJTLUer19** [comment]
My disney+ subtitle was not working since last night in UK, hoping for fixing QAQ

**Comment by a0071234c** [comment]
> If it doesn't works, it is painful that I can't reproduce the issue on my computer.
> 
> So I will build a debug version Dualsub, which add some debug messages to the DevTools console, to help me find out where the issue happen.

If your Disney+ account's region is US, 'dualsub' will still work. But if your Disney+ account's region is Singapore, it won't work, maybe accounts in other countries are the same. So far, that's all I know. I hope this information can helps you.

**Comment by a0071234c** [comment]
> If it doesn't works, it is painful that I can't reproduce the issue on my computer.
> 
> So I will build a debug version Dualsub, which add some debug messages to the DevTools console, to help me find out where the issue happen.

现在的情况是：美国注册的Disney+账号，哪怕转过区了，插件也是可以用的，但是新加坡直接注册的Disney+账号就不能用，可能其它国家注册的也不行吧。希望这条信息能给你提供帮助。

**Comment by muzuiget** [comment]
![Screenshot_20221205_100657](https://user-images.githubusercontent.com/330812/205534002-b9895bac-917a-4b27-a22e-41f3d3fff1a2.png)

I test again, my account still works.

**Comment by muzuiget** [comment]
I use a Seoul proxy and test again, it still works. I got the message "It look like you area travelling" on logging in.

So this issue is related to the account, not the IP region.

**Comment by muzuiget** [comment]
The fastest solution is somebody can borrow me an account that can reproduce the issue on my computer.

If there is a volunteer, please sent the account to my email `muzuiget@gmail.com`, you can reset the password later.

**Comment by XJTLUer19** [comment]
> The fastest solution is somebody can borrow me an account that can reproduce the issue on my computer.
> 
> If there is a volunteer, please sent the account to my email `muzuiget@gmail.com`, you can reset the password later.

我已邮件发您，辛苦您了

**Comment by muzuiget** [comment]
I have recevied 3 accounts currently, I will test them later.

**Comment by muzuiget** [comment]
I test it hours ago, and I found my account also not works, maybe Disney+ has pushed the changes to all accounts. I can reproduce and fix the bug with my account.

I have released the v2.5.0 to Chrome Store, please try it.

**Comment by Fred00231** [comment]
It's working now.
My account is register in Taiwan.
thank you for your help!

**Comment by lazyguy328** [comment]
It works now on Disney+ but has not worked on Netflix since this morning.

**Comment by lazyguy328** [comment]
![螢幕擷取畫面_20221206_191814](https://user-images.githubusercontent.com/81511431/205897720-f051d214-3868-4e00-bf37-8b6da6879195.png)

**Comment by lazyguy328** [comment]
sure, the Disney+ should be of no problem now

**Comment by ksiwososj** [comment]
I'm using vpn from USA to Canada, but it doesn't work like this.
![20221207_140149](https://user-images.githubusercontent.com/119629808/206272611-bfd67738-5a7e-4360-9d8a-28225983d696.jpg)

**Comment by muzuiget** [comment]
@ksiwososj You can create another post if you are using `api.dualsub.xyz` service.

**Comment by ksiwososj** [comment]
Now, It's working. Thank you.

**Comment by ksiwososj** [comment]
Suddenly, it's not working.. shit..
