### ISSUE TITLE
字幕无法显示，插件支持的网站部分视频的cc字幕无法解析。

### ISSUE THREAD

**Issue by liz727** [muzuiget/dualsub-support#468]
网络检查无误，我刚也测试了同一个网站的其他视频，字幕可以正常翻译。
但是下面这个视频，根本看不到翻译字幕栏。
https://www.ardmediathek.de/video/tatort/blut/hr-fernsehen/Y3JpZDovL2hyLW9ubGluZS8xODU2NTk
这个视频确定是有cc字幕的，而且dualsub的谷歌插件显示也提取到了，但是字幕栏根本没有显示。。。
[
![cca876a13359bea51b2add1dc85d64e](https://user-images.githubusercontent.com/79632825/204101918-36313597-beb3-4422-970e-7d707a558ad9.png)
](url)
请问这是什么问题，要怎么解决？

**Comment by muzuiget** [comment]
它的字幕时间轴有点迷醉，最前的一个不是从零开始。

![Screenshot_20221127_021211](https://user-images.githubusercontent.com/330812/204103251-a79fb00e-bf3b-4504-b9c2-ff20f399e847.png)

之前发现它的字幕在这种情况下，需要对后面的时间轴做个偏移才能对得上视频时间。

但现在好像又不需要做偏移了，我改了，重新打包一个版本

[dualsub-v2.4.0.zip](https://github.com/muzuiget/dualsub-support/files/10096793/dualsub-v2.4.0.zip)

你可以用开发者模式加载测试下，原来商店版正常的视频，也请看看是不是一样正常。

**Comment by liz727** [comment]
现在可以正常看了，谢谢
其它视频也可以看的

**Comment by muzuiget** [comment]
v2.4.1 已发布，修复了这个问题。

**Comment by liz727** [comment]
您好，又有一个视频出现了同样的问题。网络正常的情况下cc字幕没翻译出来（已经用了最新版本的 Dualsub）
不知道是否又是字幕时间轴的问题。
https://www.ardmediathek.de/video/tatort/fuenf-minuten-himmel/br-fernsehen/Y3JpZDovL2JyLmRlL3ZpZGVvLzRkOTZjNGU3LTk1OWUtNDdjNC1iMThmLWNjZmZmZGFkOWI3Mg
















在 2022-11-28 21:19:25，"muzuiget" ***@***.***> 写道：

v2.4.1 已发布，修复了这个问题。

**Comment by liz727** [comment]
您好，又有一个视频出现了同样的问题。网络正常的情况下cc字幕没翻译出来（已经用了最新版本的 Dualsub）
不知道是否又是字幕时间轴的问题。


https://www.ardmediathek.de/video/tatort/fuenf-minuten-himmel/br-fernsehen/Y3JpZDovL2JyLmRlL3ZpZGVvLzRkOTZjNGU3LTk1OWUtNDdjNC1iMThmLWNjZmZmZGFkOWI3Mg
















在 2022-11-28 21:19:25，"muzuiget" ***@***.***> 写道：

v2.4.1 已发布，修复了这个问题。

**Comment by muzuiget** [comment]
这个视频地址返回错误了。

![Screenshot_20221205_100122](https://user-images.githubusercontent.com/330812/205533282-229bda11-e5c7-4a61-9fd5-43497c81845b.png)
