### ISSUE TITLE
删除扩展设置页面中的“样式”标签页

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#469]
在最新的 Dualsub v2.5.0 版本我删除了“样式”标签页。

## 原因

为了升级到 Manifest V3，被逼重写了不少代码，所以顺势审视了现有的设计和代码，发现很多地方都值得重写。现在浏览器足够强大，各家浏览器行为差异也在减少，很多陈旧的代码都可以抛弃。

所以我重写了底层 UI 组件的代码，扩展设置页也跟着重写了，虽然它整体看起来没什么变动。除了那个“样式”标签页我不太想重写，因为它太复杂了。

我设计了一个 UI 编辑器，希望避免用户写 CSS 代码，也可以灵活调整样式。但这个编辑器本质就是**一个 CSS 代码生成器**，基本上和 CSS 的概念一一对应的。

![Screenshot_20221207_094745](https://user-images.githubusercontent.com/330812/206071181-c0e40f7f-a0bc-48dc-b728-69791f334fd6.png)

过去我沉迷发明这种看上去“强大”的东西，现在看来真无必要，密密麻麻的 UI 组件看上去未必让人觉得易用，现在觉得直接填代码反而更加简洁。而且 GUI 无法表示很多用代码能实现的功能。题外话：所以我不看好现在那些号称**无代码**的工具。

而且我敢说 99% 用户都是只用那个调整字体大小的功能，所以我索性全删了。

## 未来的想法

默认样式做到自适应环境开箱即用，仅仅给那些几个常见样式做 UI 组件。

至于想精确控制样式的用户，用 [Wildmonkey](https://chrome.google.com/webstore/detail/wildmonkey/jlffehhlfkdbdheffcaekpmkhfphmhpg) 来应用 CSS 代码就行了，可以自己用 DevTools 来调试。

至于那些不会 CSS 又不想花时间学习的用户，你发个帖子问一下就好，就像 #441 一样，我贴一段示例代码，然后用户自己改改其中的几个数字。这通常就花了我几分钟时间，好过我常年累月维护一些不知道有没有人用的代码。

## 关于 Wildmonkey

本质就是从 Dualsub 原来的”插件“标签页分离出来的功能。

**Dualsub 修改网站的 HTML，其它扩展也可以修改 Dualsub 的 HTML，这是很正常的用法。**

**Comment by XXpE3** [comment]
吓我一跳，看着看着没颜色了，笑死

**Comment by peterhsun13** [comment]
請問字體顏色怎麼改呢 試了幾個寫法都沒有套用上

**Comment by muzuiget** [comment]
字体颜色和大小可以看 #472 中的示例。

如果想学习 CSS，MDN 的教程就很好了，[看这一篇](https://developer.mozilla.org/zh-CN/docs/Learn/CSS/First_steps/What_is_CSS)就够了。

**Comment by isLundy** [comment]
> ![S__24879107](https://user-images.githubusercontent.com/71948248/205967625-6efff1a2-662e-4f76-8d48-37e3d1c0d5c3.jpg) 世界上唯一一個可以把字幕放到這麼大的, 這樣追劇眼睛很舒服

牛 👍（好大）

**Comment by xqdoo00o** [comment]
可以留个自定义css输入框么，不想装别的插件额

**Comment by muzuiget** [comment]
WildMonkey 也就 100K 不到，没必要纠结。

如果你已经在使用其它油猴扩展，也可以直接用这些扩展添加 CSS。
