### ISSUE TITLE
一个额外的关于谷歌翻译的问题

### ISSUE THREAD

**Issue by SpoonerCake** [muzuiget/dualsub-support#47]
您好，我在看dualsub的设置时发现可以可以设置机器翻译这个选项以减小条目数量，这非常的方便！我在用谷歌翻译插件一直很困扰，在有些双语网页不能正确识别，每次都要下拉100多个才能看到英语。我在网上找了很多也没能找到解决办法，请问作者，能否通过代码，或者您能否开发类似的插件来解决这个问题呢？谢谢！

**Comment by muzuiget** [comment]
你是指谷歌官方的 Chrome 扩展吗？

**Comment by SpoonerCake** [comment]
感谢，问题已解决。方法是把源网页语言设为未知，这样在双语界面也可以翻译了~
