### ISSUE TITLE
v1.86.5 on Firefox does not display subtitles on Netflix

### ISSUE THREAD

**Issue by dongsibo** [muzuiget/dualsub-support#470]
Recently, Dualsub 1.86.5 has not been displaying subtitles on Netflix with Firefox 107.0.1. "Close (0)" is the only option under "Subtitle Languages" for titles with multiple subtitle options on Netflix. I have tried opting out of test participation in https://www.netflix.com/DoNotTest to fix this issue but to no avail.

**Comment by lazyguy328** [comment]
same problem of Netflix on Chrome

**Comment by muzuiget** [comment]
Does it work in Dualsub v2.5.0 on Chrome?

**Comment by lazyguy328** [comment]
No

**Comment by lazyguy328** [comment]
![螢幕擷取畫面_20221206_191814](https://user-images.githubusercontent.com/81511431/205944086-364cc209-f8cc-4d0a-bfe1-7fb2d34efb50.png)

**Comment by muzuiget** [comment]
Anyone can borrow me a Netflix account just for fixing bug? It's not easy to buy an account on Taobao today, lot of buyer links are broken.
