### ISSUE TITLE
网飞字幕无法使用

### ISSUE THREAD

**Issue by supeep** [muzuiget/dualsub-support#471]
![image](https://user-images.githubusercontent.com/88100064/206159133-deb7571e-679e-46b4-a69f-c084c674dcee.png)

**Comment by w2dcoke** [comment]
遇到了同样的问题

**Comment by muzuiget** [comment]
我没有账号了，所以我需要一个热心人士借个账号测试，好运的话半小时就搞定。

过去我会在淘宝奸商里买一个临时的，但是现在的形势不好买了，店都搜不到了。而且奸商的账号也不好，卖得贵就算了，实际上会超卖，而且账号有些隐藏属性（比如注册地区不同）不能重现问题。

所以最好还是让出问题的用户借出一下账号，这么多用户，只有一个人愿意就够了。

如果愿意借出账号，请发送到 `muzuiget@gmail.com`。

**Comment by champsing** [comment]
是要借哪一個帳號?GutHub嗎?還是Netflix的?

**Comment by muzuiget** [comment]
当然是 Netflix 的。

**Comment by muzuiget** [comment]
Dualsub v2.5.1 已发布。

**Comment by Shizuka0330** [comment]
感謝更新Chrome的版本
請問Edge能否也提供更新?
Chrome會鎖Netflix畫質平常還是習慣在Edge看...
謝謝!

**Comment by champsing** [comment]
> 

Chrome 擴充套件商店可以直接新增到Edge喔! 因為內核都是Chromium，所以可以互通

**Comment by Shizuka0330** [comment]
> > 感謝更新Chrome的版本 請問Edge能否也提供更新? Chrome會鎖Netflix畫質平常還是習慣在Edge看... 謝謝!
> 
> Chrome 擴充套件商店可以直接新增到Edge喔! 因為內核都是Chromium，所以可以互通

原來如此!! 感謝告知!!



> Edge 商店也提交了，只是它审核很慢，大约要 2-3 天，期间不可取消审核提交新版本。
> 
> 所以紧急更新只能安装 Chrome 商店的版本。

了解，辛苦了，一直以來感謝您開發，真的是用到現在最穩定的雙字幕系統> <
