### ISSUE TITLE
网飞开了1080插件后就不能显示字幕了

### ISSUE THREAD

**Issue by MrZhang000** [muzuiget/dualsub-support#473]
![image](https://user-images.githubusercontent.com/120107518/206454721-52b95d44-cfa2-4074-b0a2-c927927fafe5.png)

**Comment by MrZhang000** [comment]
是的，我昨天用都还是可以的，那请问怎么用以前的版本，没找到😂

**Comment by muzuiget** [comment]
用这个 [dualsub-v2.5.0.zip](https://github.com/muzuiget/dualsub-support/files/10186215/dualsub-v2.5.0.zip)

或者 Edge 商店那个版本，因为 v2.5.1 还在等审核。

**Comment by MrZhang000** [comment]
果然2.5.0可以，感谢感谢

**Comment by muzuiget** [comment]
Dualsub v2.5.2 已发布，修复了这个问题。

**Comment by MrZhang000** [comment]
好的，辛苦了
