### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by fragarray** [muzuiget/dualsub-support#475]
As i undestand whit google translate, you decide to remove completely the setting page from your extension.
Shurely you have your own reasons for doing that, can i ask you at least to implement some more default styles?
Most important, in my opinion, is the coulor of the subtitles. 

For those who use not-asian alphabeth, it's really confusing and difficult to read quickily the proper language. 

p.s.
There is some way to make a simbolic money donation for your job? 
You really can't know how useful is your extension for bi-national couple as mine!

**Comment by muzuiget** [comment]
The settings for styles will  be re-designed in the furture versions.

Currently two workarounds:

1. Install [WildMonkey](https://chrome.google.com/webstore/detail/wildmonkey/jlffehhlfkdbdheffcaekpmkhfphmhpg)

Add a CSS code, like this:

![Screenshot_20221211_011254](https://user-images.githubusercontent.com/330812/206866989-df4d00d5-c2ef-4f62-8903-5c0b0c6f6a2e.png)

```
.dualsub-renderer .dialogue {
    color: #ffa500;
}
```

2. Stay in an old version

If you still want the GUI way, you can use the developer mode to load an old version Dualsub.

Get the [history verisons here](https://addons.mozilla.org/en-US/firefox/addon/dualsub/versions/).

You can use Firefox, or unzip the .xpi to a directory to load it into Chrome.

**Comment by fragarray** [comment]
> .dualsub-renderer .dialogue {
>     color: #ffa500;
> }

Using WildMonkey i can change the style of all subs not one by one, using older version don't work for disney+.

Maybe i did not undestand the way to do what i need?

What about the donation? Please, take my money! XD

**Comment by muzuiget** [comment]
You can use another CSS rule to override, like this:

```
.dualsub-renderer .dialogue {
    color: #fff;
}

.dualsub-renderer .subtitle-2 .dialogue {
    color: #ffa500;
}
```

The v1.86.6 should works in Disney+, have you try it?

I don't accept the "donation" for feature request.
