### ISSUE TITLE
为什么现在youtobe的自动翻译不能用了呢

### ISSUE THREAD

**Issue by simple12345yuu** [muzuiget/dualsub-support#476]
一个英文视频有自动字幕，但是把它选择自动翻译 简体中文 就没有字幕了，这个是什么原因呢
![IMG_4919](https://user-images.githubusercontent.com/120291082/206884895-1760acdf-5d92-43f7-b06f-e0fe7715bcf3.JPG)

**Comment by muzuiget** [comment]
检查一下是不是 #426 的原因。

如果不是，那么它的原始字幕本身有点问题，你可以发一下地址让我测试下。

**Comment by simple12345yuu** [comment]
https://www.youtube.com/watch?v=eJEc-McnliI&ab_channel=BBCNews 我看的是这个新闻

**Comment by simple12345yuu** [comment]
我觉得会不会是节点原因呢，我在ipad 网页 youtobe 好像也没有自动翻译字幕，但是我换了个节点，一样不能自动翻译，会不会是youtobe的本身问题

**Comment by muzuiget** [comment]
是 YouTube 自己的译文字幕问题，时间轴完全错位了。

![Screenshot_20221211_120917](https://user-images.githubusercontent.com/330812/206885937-e82dec5e-11cc-4a0b-92ad-fe98025bba2c.png)

它的时间轴对齐算法有问题，因为它即使是机翻字幕，还是很执着使用以词为单位的时间轴格式，即中文还是会像英文那样，一个个词崩出来那种。

这个问题我无法修复了，因为两个字幕文件的时间轴必须相同。

**Comment by simple12345yuu** [comment]
这个后面youtobe自己会修复吗，前段时间还是用好好的，我就觉得应该不是我设备的问题，我换了好几个设备，都是一样的情况

**Comment by muzuiget** [comment]
这是 YouTube 自己的服务器问题，只能等他们自己解决。

**Comment by simple12345yuu** [comment]
这个可以向他们反馈这个问题吗

**Comment by muzuiget** [comment]
事实上 YouTube 一直都有这种小问题，偶然发生在个别视频上，不见的他们会愿意修复。

**Comment by simple12345yuu** [comment]
刚刚反馈了。不知道他们会不会给我回复

**Comment by Kzero01R** [comment]
刚刚看了这个问题，好像是所有自动产生英文字幕的视频都会有这个问题，应该很快会修复

**Comment by wfxtrading** [comment]
我也遇到同樣問題

**Comment by simple12345yuu** [comment]
对啊，昨天突然发现不能用了

**Comment by wfxtrading** [comment]
看了這麼多廣告，翻譯還壞掉，不知道什麼時候才修好

**Comment by muzuiget** [comment]
还真是，所有视频的自动生成的字幕的机翻字幕，时间轴都是错的。

只能等 YouTube 自己修复了。

**Comment by simple12345yuu** [comment]
真的无语了，不知道什么时候修好

**Comment by muzuiget** [comment]
YouTube 官方论坛的讨论

https://support.google.com/youtube/thread/191694651/spanish-subtitles-not-working

**Comment by simple12345yuu** [comment]
好多人都这么说了

**Comment by muzuiget** [comment]
译文倒是有的，只是时间轴全错了。

![Screenshot_20221212_000845](https://user-images.githubusercontent.com/330812/206915047-11125acb-fcae-4057-a4b9-448023231c6e.png)

我试下能不能找到时间轴错位的规律，然后推算回正确的时间轴。

不过测试了几个视频，时间轴错位得毫无规律，所以还是不行。

**Comment by simple12345yuu** [comment]
这个他们什么时候才能修好呢

**Comment by muzuiget** [comment]
不知道，你看上面官方论坛的帖子，bug 最早出现在 5 天前。

**Comment by simple12345yuu** [comment]
是的，你们的翻译是al翻的还是机翻的，有些说实话还是不够准确

**Comment by muzuiget** [comment]
对我来说，机翻只是一个辅助速读的手段，见到生词省下暂停去查字典的时间，在不需要精读的情况下，现在的机翻质量算是够用的了。

**Comment by JiuJingMianQiu** [comment]
我也，四天前还看的好好的，突然就没有翻译字幕了，而且问了很多人大家都看不到中文字幕。。。

**Comment by muzuiget** [comment]
YouTube 已经修复了这个问题。

**Comment by simple12345yuu** [comment]
嗯嗯，对啊，修复了
