### ISSUE TITLE
如何把字幕底边距降低呢，我的字幕太靠上了，看着不适应。

### ISSUE THREAD

**Issue by wang8456** [muzuiget/dualsub-support#477]
如何把字幕底边距降低呢，我的字幕太靠上了，看着不适应。

**Comment by wang8456** [comment]
已解决
.dualsub-renderer {
    bottom: 50px;
}

**Comment by muzuiget** [comment]
快速设置里不是有的调整吗？

**Comment by wang8456** [comment]
> 

昨天没看见，当时直接用Wildmonkey，就没把注意力放在Dualsub上。所以没看见。

**Comment by wang8456** [comment]
> 昨天没看见，当时直接用Wildmonkey，就没把注意力放在Dualsub上。所以没看见。
