### ISSUE TITLE
能否支持手动添加字幕啊

### ISSUE THREAD

**Issue by xBLACKICEx** [muzuiget/dualsub-support#479]
能不能支持从 open subtitile 插件 读取字幕 或者支持手动添加字幕并进行翻译？

主要就是我能获取一些日语字幕文件让后我想配合dualsub 显示日语假名

**Comment by muzuiget** [comment]
这个功能本来有的，但是升级到 Manifest V3 后删除了 #461。

两个方法：

1. 使用 Manifest V2 旧版，所以用 Firefox 就行了。或者用下载 [xpi](https://addons.mozilla.org/en-US/firefox/addon/dualsub/versions/) 文件，当 zip 解压后用 Chrome 开发者模式加载使用。

2. 使用 <https://player.dualsub.xyz>，把视频文件和字幕拖进去就行了，原理见 #315。

**Comment by xBLACKICEx** [comment]
我用的就是firefox版的但是没有找到类似上传字幕的按钮啊？能给个截图或gif吗谢谢。

**Comment by muzuiget** [comment]
在扩展的设置页面，“文件”标签页，勾选“网站”的单选框，对应的网站的“字幕语言”就多出了一个菜单条目。

**Comment by xBLACKICEx** [comment]
谢谢，找到了不过还是希望吧这个功能搬到简单设置里去，就像open subtitile扩展那样。
