### ISSUE TITLE
开启插件字幕显示不出来了

### ISSUE THREAD

**Issue by Solon21** [muzuiget/dualsub-support#48]
前几天插件还可以正常使用，14号开始就无法显示字幕
我试着在关闭插件的情况下开启字幕，字幕正常显示。也能正常访问 https://dualsub-app.appspot.com/ 

是不是youtube更新了字幕的接口？

**Comment by Solon21** [comment]
不是个别视频无法显示，所有视频都是这种情况

**Comment by muzuiget** [comment]
我试了一下，现在还可以。

YouTube 上个月确实在更新字幕格式和接口，但是扩展已经做了基本兼容，除非又有新的改动。因为 YouTube 是灰度更新的，也就是只有部分人看到新格式，我看不到新格式也就做不了兼容。

所以目前建议你可以换下浏览器，比如 Firefox，或者试下清空 Cookie 来碰下运气是否让你回到旧格式。
