### ISSUE TITLE
dualsub 是否支持字幕选中？

### ISSUE THREAD

**Issue by xBLACKICEx** [muzuiget/dualsub-support#480]
dualsub 是否支持字幕选中（复制，划词）？，比如在语言学习模式下，如果遇到不明白单词或句子时候可以直接借助其他扩展实现划词翻译.

目前我自己我无法选中字幕。

**Comment by muzuiget** [comment]
理论上和其它划词扩展搭配使用，在工具栏页面的“快速设置”，将“鼠标动作”改成“选择文本”即可。

**Comment by xBLACKICEx** [comment]
谢谢啊，找到了
