### ISSUE TITLE
How to enable/disable furigana/segment for "Japanese Analysis" on Chrome

### ISSUE THREAD

**Issue by pabadacfuc** [muzuiget/dualsub-support#481]
Hi, I don't know how to toggle these features after the "style" page has been removed. Do I have to input some command onto Wildmonkey? Thanks a lot! Really like your extension for learning through videos :)

**Comment by muzuiget** [comment]
Do you want to hide the segment underline?

**Comment by pabadacfuc** [comment]
Both the furigana and segment line. Sometimes I would like to hide either one of them for different videos or purposes.

**Comment by pabadacfuc** [comment]
e.g. sometimes I would like to have segment only, sometimes furigana only

**Comment by muzuiget** [comment]
You can change the 3rd column menu to "Close".

**Comment by muzuiget** [comment]
To hide the furigana, you can add a style:

![Screenshot_20230106_144344](https://user-images.githubusercontent.com/330812/210945554-9a599db8-3579-4b86-a92b-a96c1cfa3eb7.png)

```
.dualsub-renderer .hiragana {
    display: none !important;
}
```

To hide the segment underline, create another style:

```
.dualsub-renderer .dividers {
    display: none !important;
}
```

**Comment by pabadacfuc** [comment]
Work like a charm! Though it seems to require page refreshing each time for the style to apply. Hope the style toggle options will be back in future updates. Thanks again! :)

**Comment by muzuiget** [comment]
Or you can add a "Page Script" like this:

![Screenshot_20230106_150331](https://user-images.githubusercontent.com/330812/210948318-e57f9555-501f-42f1-8b8f-c8458e333f67.png)

```
const styleText = `
body.hide-furigana .dualsub-renderer .hiragana {
    display: none !important;
}
body.hide-segments .dualsub-renderer .dividers {
    display: none !important;
}
`;

const style = document.createElement('style');
style.textContent = styleText;
document.head.appendChild(style);

document.addEventListener('keyup', (event) => {
    if (event.key === 'q') {
        document.body.classList.toggle('hide-furigana');
        return;
    }
    if (event.key === 'w') {
        document.body.classList.toggle('hide-segments');
        return;
    }
});
```

This snippet let you press <kbd>q</kbd> to toggle the furigana, and  <kbd>w</kbd> to toggle the segment underline.

**Comment by pabadacfuc** [comment]
Got it, Perfecto! It's so much more convenient now with the script. Thanks heaps!
