### ISSUE TITLE
Exclude auto-generated subtitle option?

### ISSUE THREAD

**Issue by penicillium** [muzuiget/dualsub-support#482]
Is there a possibility to exclude language option?
I want to exclude `Auto-Generated` subtitles.

**Comment by muzuiget** [comment]
The `auto-generated` menuitem doesn't take too much displaying space, why do you want to hide it?

**Comment by penicillium** [comment]
Sorry, I don't mean the menu item specifically the space is not the issue.
For example I set my subtitle to `English` 
The current behavior is if there are no `English` subtitles, it will display `English (auto-generated)` subtitle by default.
But I don't want to see `English (auto-generated)` subtitles, I would rather see no subtitles.

**Comment by penicillium** [comment]
Oh ok, I see, thank you for the reply.
