### ISSUE TITLE
youtube简单模式不可用

### ISSUE THREAD

**Issue by jamespatriot** [muzuiget/dualsub-support#483]
标准模式 能正常显示英文字幕，
简单模式下，设置字幕语言无效。

firefox 108.0.1 (64 位)

**Comment by muzuiget** [comment]
我测试了下，仍然正常，或者你先排除下可能还冲突的扩展或者脚本。

**Comment by jamespatriot** [comment]
换了109.0b6 (64-bit) developer 版本就正常了。

**Comment by muzuiget** [comment]
我在 108.0.1 也是正常的。
