### ISSUE TITLE
增加下拉選單樣式，該怎麼作?

### ISSUE THREAD

**Issue by Benlee1129** [muzuiget/dualsub-support#487]
在下拉選單中已經定義了字幕１和字幕２，若要自定義可選的樣式該怎麼新增？
在wildmonkey 中可用CSS 控制 .dualsub-renderer .subtitle-1，若我想要自定義一個 .subtitle-3 給特定網站使用，要在wildmonkey中新增哪些內容。

**Comment by muzuiget** [comment]
`.subtitle-3` 是指第三个字幕，扩展设置里的“字幕数量”设置为 `3`  时。

你再建一个样式分开写就是了。

![Screenshot_20230202_214648](https://user-images.githubusercontent.com/330812/216341818-466e2229-1e86-4769-8efc-bbab7d89a584.png)

![Screenshot_20230202_214702](https://user-images.githubusercontent.com/330812/216341860-06396ea3-77b9-44bd-9bac-6eb8d8112c5b.png)
