### ISSUE TITLE
在YouTube頁面上調整標準模式的「底部邊距」，怎麼做？

### ISSUE THREAD

**Issue by Benlee1129** [muzuiget/dualsub-support#488]
Dualsub 標準模式下的字幕在YouTube 頁面上沒有呈現，原來是因為底部邊距差距70px，因此我在wildmonkey設置：

.dualsub-renderer .dialogue {
  padding-bottom: 70px;
}

.dualsub-renderer .subtitle-1 {
 font-size: 140%;
    color: #fff;
}

.dualsub-renderer .subtitle-2 {
font-size: 70%;
    color: #ffa500;
}
不幸的是字幕1跟字幕2的間距也差距70px，因此我想如何設置可以將字幕2抬高70px，且字幕1跟字幕2間保持在同一對話框中，並維持1.0行高差距呢？

**Comment by muzuiget** [comment]
底部边距不是可以在“快速设置“里改吗？

行高问题看 https://github.com/muzuiget/dualsub-support/issues/367

**Comment by Benlee1129** [comment]
是的，我知道底部邊距可以在快速設置改，但改後是全域設置，會影響其他網站的設置。我只想要改YouTube
的底部邊距，但卻是將字幕一跟字幕二都抬高了70px。

muzuiget ***@***.***> 於 2023年2月7日 週二 15:04 寫道：

**Comment by Benlee1129** [comment]
我改好了，我這樣寫就可以了。謝謝！
![Screenshot_20230207-152748](https://user-images.githubusercontent.com/103996456/217178528-01f5290f-9a0c-4ad1-b774-0e2964b135c3.png)

.dualsub-renderer .subtitles {
 gap: 8px;
 align:center;
 margin-bottom:70px;
}

.dualsub-renderer .subtitle-1 .contents {
 font-size: 1.3em;
 line-height:1.2;
}

.dualsub-renderer .subtitle-2 {
font-size: 1em;
}
