### ISSUE TITLE
Amazon无法读取字幕

### ISSUE THREAD

**Issue by Seulxy** [muzuiget/dualsub-support#489]
检索发现新版好像可以直接使用，请问作者是还没更新完毕还是我应该额外设置点什么？

**Comment by muzuiget** [comment]
所以现在行还是不行？

还是这个问题 https://github.com/muzuiget/dualsub-support/issues/418

**Comment by Seulxy** [comment]
> 所以现在行还是不行？
> 
> 还是这个问题 #418

最新下载的商店版还是不能直接在 amazon.* 下使用，我就是想知道是不是后续会支持，不用自己再更新了

**Comment by muzuiget** [comment]
#418 说了，因为我不想申请 `amazon.*` 域名的权限，解决方法是 Manifest V3 的[可选权限](https://github.com/muzuiget/dualsub-support/issues/458)做法，现阶段没时间改而已。

开发者模式加载扩展启动时就是会弹出那个警告的，你可以把商店版都安装上，只启用其中一个就行。比如你看完 amazon 就禁用开发者版本，启用商店版。把 `chrome://extensions/` 添加进书签栏直达扩展管理页就好。

**Comment by Seulxy** [comment]
> #418 说了，因为我不想申请 `amazon.*` 域名的权限，解决方法是 Manifest V3 的[可选权限](https://github.com/muzuiget/dualsub-support/issues/458)做法，现阶段没时间改而已。
> 
> 开发者模式加载扩展启动时就是会弹出那个警告的，你可以把商店版都安装上，只启用其中一个就行。比如你看完 amazon 就禁用开发者版本，启用商店版。把 `chrome://extensions/` 添加进书签栏直达扩展管理页就好。

好的谢谢……我还想再多嘴问一下字体的样式，如果我想把第二字幕调在视频上方我应该在编辑器里输入啥？不好意思，在教程文档里没有找到

**Comment by muzuiget** [comment]
用 Wildmonkey 自定义一个样式，原因见  #469。

![Screenshot_20230211_221138](https://user-images.githubusercontent.com/330812/218262589-2cc764ee-b44d-4782-abfe-307ec3eab790.png)

这个样式表示第二字幕把第一字幕往上“顶”起 500 个像素，你可以自己改一下这个数字。

**Comment by Seulxy** [comment]
> 用 Wildmonkey 自定义一个样式，原因见 #469。
> 
> ![Screenshot_20230211_221138](https://user-images.githubusercontent.com/330812/218262589-2cc764ee-b44d-4782-abfe-307ec3eab790.png)
> 
> 这个样式表示第二字幕把第一字幕往上“顶”起 500 个像素，你可以自己改一下这个数字。

输入了
.dualsub-renderer .subtitle-2 {
    padding-top: 2000px；
}
但是啥反应也没有……

**Comment by Seulxy** [comment]
> 用 Wildmonkey 自定义一个样式，原因见 #469。
> 
> ![Screenshot_20230211_221138](https://user-images.githubusercontent.com/330812/218262589-2cc764ee-b44d-4782-abfe-307ec3eab790.png)
> 
> 这个样式表示第二字幕把第一字幕往上“顶”起 500 个像素，你可以自己改一下这个数字。

成功啦，谢谢！
