### ISSUE TITLE
好评！不过，建议固定个性化设置，省的每次想看字幕都要重新打开

### ISSUE THREAD

**Issue by Jesselee0322** [muzuiget/dualsub-support#49]
比如我想要双语字幕，第一行英文-英文，第二行英文-中文，设置好了以后，下次能够固定这个设置，直接就是这两种语言，打开一键开关就是我第一次那种设置，省的每次设置都很麻烦
最后，感谢大神的制作！

**Comment by muzuiget** [comment]
看下文档[优先选择语言](https://dualsub.netlify.com/zh-cn/setting?id=%e4%bc%98%e5%85%88%e9%80%89%e6%8b%a9%e8%af%ad%e8%a8%80)。
