### ISSUE TITLE
为何客户端也收费？

### ISSUE THREAD

**Issue by lenchen13** [muzuiget/dualsub-support#492]
“客户端：即你从浏览器商店安装的浏览器扩展程序。客户端依然保持功能免费，也不区分收费版和免费版。”
但为什么我从Chrome浏览器商店安装了浏览器扩展程序，却告知我需要APLkey。

**Comment by muzuiget** [comment]
“标准模式”下的机器翻译是使用自建服务器的，所以 API Key 提交给服务器的，用来证明是你付费用户。

**Comment by lenchen13** [comment]
那客户端仅仅指的是简单模式吗

**Comment by muzuiget** [comment]
在你电脑上运行的代码就叫“客户端”，所以整个扩展就是客户端。

现在只有““标准模式下的机器翻译”需要发送原文到服务器来翻译，标准模式在其它网站都能用，例如 Netflix。

**Comment by lenchen13** [comment]
意思是客户端免费的只是简单模式，所以只有yuotube能用。标准模式虽然是客户端也不是免费的。谢谢

**Comment by muzuiget** [comment]
标准模式其它功能也是免费的，YouTube 也能用。比如你单纯只是想显示两个人工字幕，不需要机器翻译，用标准模式渲染出来的字幕会有描边效果。

简单模式才是专为 YouTube 另外搞出来的，因为 YouTube 自带一份译文，不需要依赖第三方服务器。

**Comment by lenchen13** [comment]
了解了，除了yuotube是免费的，其他的网站即使是客户端都需要收费。

**Comment by muzuiget** [comment]
你试一试 B 站这个视频就明白了。

https://www.bilibili.com/video/BV1Gf4y1y7wc

**Comment by lenchen13** [comment]
我想翻译的是ardmediathek.de这个网站，看来这个网站需要机器翻译恰好是需要收费的。

**Comment by muzuiget** [comment]
对的。
