### ISSUE TITLE
购买流程有些麻烦！

### ISSUE THREAD

**Issue by isLundy** [muzuiget/dualsub-support#493]
非常支持您的收费～

一.购买流程有点麻烦。在我购买后需要向您发送订单号，但是不知道是否可以立即收到回复key？我想立刻使用。有没有便捷的交易页面，在我付款后可以立刻收到api key。

二.收费过于昂贵。非常感谢您的开发，但是作为国内使用的人来讲，大部分人都是合租的Netflix或Disney Plus，每月的费用最高也不过25 RMB。现在大部分的使用情况基本是使用双字幕，在少数情况下会用到机器翻译，不知道可否将您制定的每月50 RMB的费用降低一下？

再次感谢您～

**Comment by muzuiget** [comment]
1. 要自动发货得去注册个公司，不想浪费时间去搞。
2. 不想讨价还价，一切都是经济学规律。
