### ISSUE TITLE
请求支持增加 GPT3.5 翻译引擎

### ISSUE THREAD

**Issue by Equity0** [muzuiget/dualsub-support#495]

**Comment by muzuiget** [comment]
最大问题在于我想买都买不到，挑信用卡挑代理服务器，试用额度无了都充不了钱。

**Comment by yi0322** [comment]
> 最大问题在于我想买都买不到，挑信用卡挑代理服务器，试用额度无了都充不了钱。

我昨天看到一篇[ChatGPT Plus 国内用户信用卡绑定](https://my.oschina.net/vangie/blog/7867595)，不知道对你是否有帮助

**Comment by muzuiget** [comment]
看过了，太折腾了。

**Comment by asasas234** [comment]
这个我觉得还有1个问题是，chatgpt翻译速度很慢，并且调的过快会有限流的问题，不太适合这种实时翻译插件

**Comment by muzuiget** [comment]
不是这样的，Dualsub 不是一次请求就翻译显示在屏幕上那段文本，而是一次请求翻译一大段。所以才要挨个网站做逆向工程，专门写适配把整个字幕文本提取出来。

这样做才能做到无延迟，和画面声音完全同步，而且带有翻译上下文。

一般视频开始都有一些进场音乐，几秒后才出现第一条字幕，这个空档已经把这段时间附近的字幕都翻译好了。

**Comment by FmoX** [comment]
> 最大问题在于我想买都买不到，挑信用卡挑代理服务器，试用额度无了都充不了钱。

让用户自己提供api

**Comment by muzuiget** [comment]
问题在于如果连我都觉得搞个 API 非常麻烦，那么做出这种功能有多少普通用户能用呢，愿意折腾可能也就那么几个人。

或者可能已经会有类似的工具了。

**Comment by muzuiget** [comment]
暂时不考虑了，GPT 那个翻译速度不适合在线观看，我希望 3 秒内就能看到结果。
