### ISSUE TITLE
Subtitles for bilibili not working..?

### ISSUE THREAD

**Issue by vonxxe** [muzuiget/dualsub-support#496]
Hiya sorry to bother but dualsub keeps on not picking up the subtitles on bilibili (the original cn website, not the bstation international one)..? I've turned on the subtitles for the bilibili video & saw it working a bit but dualsub keeps not picking up that there're subtitles for the video. "subtitle language: closed (0)" keeps on popping up even though there are subtitles on the actual vid itself :(

Is there a way to fix this? or is my laptop just buggy rn..? Sorry for the weird english, I'm not a native & its kinda late in the night rn so my brain isn't functioning properly lol
![image](https://user-images.githubusercontent.com/112676013/222945881-dd6d67a8-b14f-4e1d-8753-cc6f6567c51d.png)
![image](https://user-images.githubusercontent.com/112676013/222945915-cf3c5387-5b0f-4bd2-b0a5-de8d02fc712a.png)

**Comment by vonxxe** [comment]
Also adding to this:
I've used dualsub for the site a few times and the MTL + subtitles thing works just fine before but its been like a month or two since I've used it
Was there a new update or smth along those lines that I wasn't aware of that I need to like download/get for it to function normally again?

**Comment by muzuiget** [comment]
B站现在似乎抽风了，所有视频都消失了。

**Comment by muzuiget** [comment]
或者你试下把B站的布局新版和旧版切换一下。

**Comment by muzuiget** [comment]
This is fixed in v2.6.2, before v2.6.2, the AI type subtitles are not be detected.
