### ISSUE TITLE
Failed to Fetch

### ISSUE THREAD

**Issue by JohnFrankz** [muzuiget/dualsub-support#497]
Youtube 观看视频的时候翻译报错：https://www.dualsub.xyz/error/failed-to-fetch 
访问 https://api.dualsub.xyz/ 显示 200 OK

**Comment by muzuiget** [comment]
进入浏览器扩展管理页，确保 Dualsub 有  http://api.dualsub.xyz/ 这个域名的权限。

一般来说，初始安装时默认会允许全部网站权限，除非用户安装又手动取消，也可能使用其它“扩展管理”类的扩展自动取消。

**Comment by JohnFrankz** [comment]
> 进入浏览器扩展管理页，确保 Dualsub 有 [http://api.dualsub.xyz](http://api.dualsub.xyz/) 这个域名的权限。
> 
> 一般来说，初始安装时默认会允许全部网站权限，除非用户安装又手动取消，也可能使用其它“扩展管理”类的扩展自动取消。

拥有这个权限，
![image](https://user-images.githubusercontent.com/86246881/223154617-7fda5027-6e21-44de-94ff-0dec2cd454de.png)

**Comment by muzuiget** [comment]
在扩展设置页“网络”，点击“检查”按钮，看看是否正常。

**Comment by JohnFrankz** [comment]
> 在扩展设置页“网络”，点击“检查”按钮，看看是否正常。

检查后，状态显示： 200 OK
![image](https://user-images.githubusercontent.com/86246881/223308595-2b413c91-2abf-47c0-bd32-dc0d884d6894.png)

**Comment by muzuiget** [comment]
版本是 2.6.0 吗？

试下按 F12 弹出 DevTools，然后切换到 Network 标签页，输入 `domain:api.dualsub.xyz`，然后在 Dualsub 触发一下翻译。

正常应该是这样：

![Screenshot_20230307_110603](https://user-images.githubusercontent.com/330812/223310166-e28b2d70-4c0c-4484-9887-4f1e56264b32.png)

**Comment by JohnFrankz** [comment]
> domain:api.dualsub.xyz

问题应该是出现在这里
![image](https://user-images.githubusercontent.com/86246881/223315394-3de403a0-2818-4373-a0e1-0fe167fe7f47.png)

访问 `https://api.dualsub.xyz/service` 显示的是：`405 Method Not Allowed`
![image](https://user-images.githubusercontent.com/86246881/223315452-dbfd864f-1be3-4307-83b0-6a2d199b7d18.png)

**Comment by muzuiget** [comment]
2.6.0 不通过 Service Worker 发送请求了，改在页面里直接发送，所以应该被你的广告过滤扩展屏蔽掉了。 

不知道命中了那个广告规则。

**Comment by JohnFrankz** [comment]
> 2.6.0 不通过 Service Worker 发送请求了，改在页面里直接发送，所以应该被你的广告过滤扩展屏蔽掉了。
> 
> 不知道命中了那个广告规则。

确实是被拓展`ublock origin`屏蔽了，关闭这个拓展后正常。被其中的`[RU AdList](chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=https%3A%2F%2Feasylist-downloads.adblockplus.org%2Fadvblock.txt)` 规则列表屏蔽了。
![image](https://user-images.githubusercontent.com/86246881/223317217-5fd3ee01-20b6-4b82-a19f-cd3b2218d7e3.png)

过滤规则为
``
||xyz^$xhr,3p,from=~anidub.com|~anidub.vip|~anidubonline.com|~animedia.pro|~animeheaven.ru|~animevibe.wtf|~app.element.io|~assistir-filme.biz|~auth.magic.link|~avtomaty-i-bonusy.com|~baza.bz|~bdnewszh.com|~capshd.xyz|~cdnmovies.be|~cdnmovies.cc|~cdnmovies.nl|~coomeet.com|~crackstreams.com|~crackstreams.ga|~csgoreports.com|~emblix.cc|~espnfree.xyz|~estream.to|~europixhd.io|~films.hds-stream.com|~flowcdn.nl|~fyshare.info|~getvi.tv|~github.io|~gsmware.com|~hanime.tv|~hentaiz.org|~herokuapp.com|~infoua.biz|~jokehd.com|~jokerswidget.com|~jokerswidget.org|~kinoguru.be|~kinoguru.me|~live-nhl.stream|~live94today.com|~lookbase.xyz|~lyra.finance|~mail.google.com|~mangahere.fit|~map-a-date.cc|~mas-stream2021.xyz|~matchat.online|~mikeamigorein.xyz|~miranimbus.ru|~my.mail.ru|~nccg.ru|~newdmn.icu|~odysee.com|~onmovies.se|~playjoke.xyz|~playm4u.xyz|~playmuvi.com|~roadhub.ru|~roblox.com|~sextop.net|~soccer365.ru|~soonwalk.net|~sportsbay.org|~streetbee.io|~streetbee.ru|~telerium.club|~telerium.live|~uacycling.info|~uploadedpremiumlink.net|~vercel.app|~vk-apps.com|~vk.com|~vmeste.tv|~web.app|~webflow.io
``

**Comment by muzuiget** [comment]
看上去这个规则把 `.xyz` 这个顶级域名都屏蔽掉了。我也在用 ublock origin，不过用的规则没有这条。

之前的版本，是通过扩展自己的 Service Worker 发送，所以不会被其它扩展屏蔽。
