### ISSUE TITLE
关于设置栏的建议

### ISSUE THREAD

**Issue by wongFanx** [muzuiget/dualsub-support#50]
![image](https://user-images.githubusercontent.com/14831158/75134596-c0e12180-5719-11ea-9e57-2d10b06eb0c6.png)
设置的这一块有点难看, 是否可以移到其他地方或者隐藏起来呢? 不太想破坏页面的原有布局

**Comment by muzuiget** [comment]
你可以用自定义样式，鼠标移动到工具栏所在的附近才显示：

```
#info .dualsub {
    display: none;
}
#info:hover .dualsub {
    display: block;
}
```

**Comment by wongFanx** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    很好用! 谢谢
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                601433457
                            
                    
                        
                            
                                    601433457@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2020年02月24日 21:56，muzuiget<notifications@github.com> 写道： 


你可以用自定义样式，鼠标移动到工具栏所在的附近才显示：

#info .dualsub {

    display: none;

}

#info:hover .dualsub {

    display: block;

}





—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
