### ISSUE TITLE
Different color / position for every subtitle

### ISSUE THREAD

**Issue by feedingaliencat** [muzuiget/dualsub-support#500]
Hello, thank you for your work, this browser extension is very appreciated.
As an user, I'd often like to change the subtitles style, to better distinguish between them while reading. In example, with a CSS rule I tried to make one of the subs yellow while leaving the other one white and I found it more readable.
The software already provides the possibility to change the style by choosing one of the option, but I couldn't find an option for changing the text color or to put one of the subtitles on top of the video and the other on bottom, which also would be nice.

**Comment by muzuiget** [comment]
Dualsub used to provides a complex GUI editor for adding styles, but be removed in recently versions, #469.

Now it is recommend to use [Wildmonkey](https://chrome.google.com/webstore/detail/wildmonkey/jlffehhlfkdbdheffcaekpmkhfphmhpg) to apply the CSS code directly, Or any userscripts mananger extensions.

Here is an example:

![Screenshot_20230313_102520](https://user-images.githubusercontent.com/330812/224594350-27a9afd2-fa50-4925-9703-35e6a155b76d.png)

```
.dualsub-renderer .subtitle-1 .dialogue {
    color: lightblue;
}

.dualsub-renderer .subtitle-2 .dialogue {
    color: orange;
}
```

If you known CSS, you can inspect the `.dualsub-renderer` DOM node in the DevTools.
