### ISSUE TITLE
hbo max

### ISSUE THREAD

**Issue by a1634112** [muzuiget/dualsub-support#506]
请求支持 hbo max中文字幕

**Comment by muzuiget** [comment]
曾经支持过，[你搜一下相关帖子](https://github.com/muzuiget/dualsub-support/search?q=hbo&type=issues)，好折腾。

除非它现在又改版了，提供单一的字幕文件，否则不想支持了。

**Comment by a1634112** [comment]
您好，邮件已收到，谢谢！
