### ISSUE TITLE
修复 www.zdf.de

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#508]
www.zdf.de 似乎改版了，这里发个修复版，可以 Chrome 开发者模式测试。

[dualsub-v2.7.0.zip](https://github.com/muzuiget/dualsub-support/files/11205838/dualsub-v2.7.0.zip)

只支持**播放页**的播放器，例如：

<https://www.zdf.de/dokumentation/terra-x/kielings-wilde-welt-der-baerenmann-doku-100.html>

不支持**索引页**的播放器，例如：

<https://www.zdf.de/dokumentation/terra-x/kielings-wilde-welt-118.html>

![Screenshot_20230412_075533](https://user-images.githubusercontent.com/330812/231314786-ebd4ab39-f6fb-404a-a161-c46094dca41d.png)

点击右边侧边栏里的链接进入**播放页**。

**Comment by Benlee1129** [comment]
修正後可以使用了。
你所說：点击右边侧边栏里的链接进入播放页。
《提醒》就是點那個小箭頭，就能正確進入播放頁。

**Comment by muzuiget** [comment]
v2.7.1 已发布。
