### ISSUE TITLE
建议在新edge浏览器上架该应用

### ISSUE THREAD

**Issue by DefetC** [muzuiget/dualsub-support#51]
新edge浏览器是chromium内核，可以直接用chrome商店的插件。可能是把chrome插件直接往edge商店上传就行了。

最后非常感谢作者做出这么优秀的作品。

**Comment by muzuiget** [comment]
可以，迟点研究一下。

**Comment by muzuiget** [comment]
Edge 商店硬是要我提供个“隐私声明”文本，又不知道怎么写好。

**Comment by DefetC** [comment]
我也不太清楚。。。。。 字面意思也许就是写个不会侵犯用户隐私的声明？如果是这样的话，感觉可以先大体意思随便简单写写，上传审核试一波。

**Comment by muzuiget** [comment]
https://microsoftedge.microsoft.com/addons/detail/fnhdkmahdiplfgjplnlokjfigbjcoopp

已通过审核。
