### ISSUE TITLE
如何做才能表現原字幕的配色？

### ISSUE THREAD

**Issue by Benlee1129** [muzuiget/dualsub-support#510]
BBC iPlayer的播放器中的字幕有文字配色，以區分不同角色的對話，這樣非常的好。請問Dualsub 可以保有原來字幕的配色嗎？

**Comment by muzuiget** [comment]
不能，因为只提取了各种字幕格式（WebVTT，TTML，ASS）里面的纯文本内容，对于颜色、字体、位置数据都是忽略的。

其实你可以译文字幕用 Dulasub 渲染，原文字幕则用网站自带的渲染。
