### ISSUE TITLE
PayPal payment issue (贝宝付款问题)

### ISSUE THREAD

**Issue by dem1995** [muzuiget/dualsub-support#513]
When I try to pay on PayPal with dualsubstudio+paypal@gmail.com., I get the issue "Please enter a valid email address, name or mobile number (i.e. name@domain.com, a name or 10 digit number only)."
当我尝试使用 dualsubstudio+paypal@gmail.com. 在 PayPal 上付款时，出现问题“请输入有效的电子邮件地址、姓名或手机号码（即 name@domain.com，仅限姓名或 10 位数字）

I only speak English and am using Google Translate, so sorry if the automatic translation is poor
我只会说英语，正在使用谷歌翻译，如果自动翻译不好，我深表歉意

**Comment by muzuiget** [comment]
Hi, I also don't know the cause of the problem, but I'm sure the account email address is valid.

Can you dobule-check the special characters like `+` 和 `@`?

**Comment by dem1995** [comment]
I will double-check both of those when I try again next time! I will let you know whatever the outcome is when I do that.
