### ISSUE TITLE
在Chrome 內無法搜尋到Dualsub 

### ISSUE THREAD

**Issue by Benlee1129** [muzuiget/dualsub-support#515]
今天要下載，搜尋不到。

**Comment by muzuiget** [comment]
正常喔。

![Screenshot_20230425_145918](https://user-images.githubusercontent.com/330812/234198600-25e8788b-205e-4722-bf66-aa15c051101a.png)

**Comment by Benlee1129** [comment]
真的是，怪了。
我是用kiwi_ browser 。

**Comment by Benlee1129** [comment]
我的是112版。
請你email 給我.zip，我先用上。
wildmonkey 也一樣搜尋不到。

**Comment by muzuiget** [comment]
[dualsub-v2.7.2.zip](https://github.com/muzuiget/dualsub-support/files/11319767/dualsub-v2.7.2.zip)

**Comment by Benlee1129** [comment]
你可以寄“wildmonkey”的插件給我嗎？
我還是無法在Chrome 市場中找到。
可能是Chrome 市場限制kiwi_browser 安裝。

muzuiget ***@***.***> 於 2023年4月25日 週二 15:17 寫道：

**Comment by muzuiget** [comment]
[wildmonkey-v0.13.4.zip](https://github.com/muzuiget/dualsub-support/files/11343102/wildmonkey-v0.13.4.zip)

**Comment by muzuiget** [comment]
或者试下 Edge 商店

https://microsoftedge.microsoft.com/addons/search?developer=Dualsub%20Studio

**Comment by Benlee1129** [comment]
在edge商店可以下載，謝謝！

muzuiget ***@***.***> 於 2023年4月27日 週四 19:52 寫道：
