### ISSUE TITLE
无法获取 Coursera 字幕以进行翻译

### ISSUE THREAD

**Issue by JohnFrankz** [muzuiget/dualsub-support#519]
你好，我使用Dualsub(版本 2.7.3)，在观看 Coursera 上的课程时遇到了一个问题。最近我发现，插件无法获取 Coursera 的字幕，导致无法进行翻译。

具体来说，当我在 Coursera 播放视频时，该插件正常工作，可以将其他视频平台 (Youtube) 的字幕翻译为我想要的语言。然而，在 Coursera 上，插件无法检测到字幕，也就无法进行翻译。我尝试了不同的课程和视频，问题都是一样的。具体如下所示：
![image](https://github.com/muzuiget/dualsub-support/assets/86246881/ba346871-bb63-4560-82a3-3181b2f00163)

我希望您能帮助解决这个问题，因为字幕翻译对于我来说非常重要。如果可能的话，请检查插件是否需要更新以适应 Coursera 平台的更改 (我发现 coursera 平台的样式好像有一些改变）。如果需要任何其他信息或测试，请告诉我，我会尽力配合。

谢谢您的努力和出色的插件！期待您的回复。

**Comment by muzuiget** [comment]
请发一下有问题的视频地址，最好是免费的课程视频。

**Comment by muzuiget** [comment]
试下这个测试版：

[dualsub-v2.7.3.zip](https://github.com/muzuiget/dualsub-support/files/11494043/dualsub-v2.7.3.zip)

**Comment by JohnFrankz** [comment]
使用测试版后一切正常， 非常感激你的帮助

**Comment by muzuiget** [comment]
已发布 v2.7.4
