### ISSUE TITLE
油猴脚本上不能直接附上下载.srt字幕和翻译字幕的按钮吗？

### ISSUE THREAD

**Issue by pendave** [muzuiget/dualsub-support#52]
这个油猴脚本只能通过下拉菜单调整在线视频里CC字幕的显示。但是不能直接有按钮下载所需字幕。能加上这样的下载按钮吗，只求srt格式的就好了！

类似油猴脚本参见
Youtube Subtitle Downloader v20
https://greasyfork.org/en/scripts/5368-youtube-subtitle-downloader-v20

希望你们这个能直接下翻译好的中文字幕等功能啊！

**Comment by muzuiget** [comment]
已经有了 https://dualsub.netlify.com/zh-cn/more-tools

**Comment by pendave** [comment]
没有！
没有.srt格式的字幕，不想要.ass格式的

而且不像跳转到那个网页去下载，只想在youtube视频页直接下载！

**Comment by muzuiget** [comment]
用其它字幕工具转换一下就好。
