### ISSUE TITLE
在Disney Hotstar 无法显示字幕

### ISSUE THREAD

**Issue by rugratz80** [muzuiget/dualsub-support#520]
Dualsub 能正常读取得字幕语言列表。
Dualsub 标准模式和简单模式都不能用。
YouTube 自带的原生字幕功能能用。
没有使用代理服务器

**Comment by rugratz80** [comment]
Hotstar里的所有视频都无法使用Dual Sub，只能使用Hotstar本身的字幕。另外好像是自从界面换了就开始无法显示了。

**Comment by muzuiget** [comment]
封锁主流云服务提供商的 IP，我试用 Google 和 Vultr 作为代理，都返回 475 错误。

我不打算和它们斗智斗勇了，我会删除这个网站的支持，所以不修复了。
