### ISSUE TITLE
[2.7.4][問題]優化Youtube翻譯（增強模式）有時會發生翻譯不完全的狀況

### ISSUE THREAD

**Issue by CrazyLayKer** [muzuiget/dualsub-support#522]
對於自動產生的字幕或是人工字幕都曾經遇到過。
狀況是，有少部分字幕的原文會正常切換，但增強模式下，翻譯字幕顯示合併後的句子，但翻譯不完全或沒有翻譯。

以下案例使用英文(自動生成)翻譯成中文(繁體)，分別使用增強模式(上)與普通模式(下)的結果：
https://youtu.be/dpJUc_BpChw?t=110
![image](https://github.com/muzuiget/dualsub-support/assets/71445791/4635f19b-b20c-40d7-8213-0a0580b915e3)
![image](https://github.com/muzuiget/dualsub-support/assets/71445791/711f8e38-b05f-42d0-93e9-ea3d16b38739)
![image](https://github.com/muzuiget/dualsub-support/assets/71445791/1f2f907b-93ff-4d39-b24b-c8bce5fa6546)
![image](https://github.com/muzuiget/dualsub-support/assets/71445791/3e73deee-16ba-4850-9510-db3d634d092a)
![image](https://github.com/muzuiget/dualsub-support/assets/71445791/f3777e60-e815-4771-bfbc-2694ad69d50e)
![image](https://github.com/muzuiget/dualsub-support/assets/71445791/2b0a6dc0-78ed-43ab-9126-d5ae77f28361)

**Comment by CrazyLayKer** [comment]
發現翻譯引擎改用微軟就會正常翻譯
![image](https://github.com/muzuiget/dualsub-support/assets/71445791/aa9d2913-2e00-4540-9483-f0253768d182)
![image](https://github.com/muzuiget/dualsub-support/assets/71445791/f0d43493-7313-49be-97ec-554b62000b16)
這段在原片中是在細數介面項目，自動生成的字幕中並沒有根據中斷添加逗號，應該會遇到增強模式的短版，也就是合併翻譯導致不通順，但字幕中沒有翻譯完全，將原文直接輸入到Google翻譯，是有翻譯出來的。
![image](https://github.com/muzuiget/dualsub-support/assets/71445791/a5ddf649-361c-4aa6-896e-ef8e163d365a)

**Comment by muzuiget** [comment]
是 Google 翻译自己的问题，有时候就是会漏翻的，只是几率很少。

![Screenshot_20230522_085746](https://github.com/muzuiget/dualsub-support/assets/330812/d3560537-1e28-47e0-a29d-8593c82829ce)

区别就在最后那个点号。
