### ISSUE TITLE
[2.7.4][建議]增強翻譯與普通翻譯的快速切換；原版字幕按鈕啟動簡單模式時覆蓋標準模式

### ISSUE THREAD

**Issue by CrazyLayKer** [muzuiget/dualsub-support#523]
由於增強翻譯不適合歌詞等基於詞彙或短句標點不佳的字幕，所以有時需要改成使用普通翻譯，但翻譯模式設定為自動，我還是常常遇到這類型的字幕被合併後翻譯，很影響使用體驗，尤其是觀看長片時實在受不了就要自己去設定改成普通翻譯，或是改用簡單模式，但簡單模式的翻譯又和標準模式普通翻譯不太相同。

我能想到有兩個解決方案：
1.在擴充功能的快速設置中添加增強／普通翻譯模式的切換選項
2.在設定中添加選項，讓使用者決定點擊原版字幕按鈕啟動簡單模式後，是否要停用標準模式的字幕（但簡單模式下的翻譯和標準模式普通翻譯的結果不同，這是個問題）

以下案例為同時啟動標準模式與簡單模式，標準模式在上圖為增強翻譯、下圖為普通翻譯
https://youtu.be/u7wAJTGl2gc?t=260
![{57E49338-7362-4738-96B2-E6620C32078B}](https://github.com/muzuiget/dualsub-support/assets/71445791/1d3aba1b-b24d-48dd-a621-854b45f98609)
![{9C29F9AC-DFE8-4ABB-9395-D3608BDCF2BA}](https://github.com/muzuiget/dualsub-support/assets/71445791/3f9e2df9-b782-4ed3-966a-7120f31c4156)

**Comment by muzuiget** [comment]
我看了这个字幕，造成增强模式翻译质量差的原因，确实在于没有标点。

![Screenshot_20230522_094833](https://github.com/muzuiget/dualsub-support/assets/330812/82e4d677-0ad8-4ecc-8675-b78852b49c98)

如果加上标点就很好，例如末尾加上句号。

我是希望这种 _非说话类型_ 的字幕能用特殊括号包起来，例如：

* `[背景音乐]`
* `♪ 这是歌词 ♪`

这样独立成句翻译。

对于这个字幕，还是有个模式能判断的，例如序号 1 和 2 其实间隔了 7 秒，即使没有标点，基本上当成两句话处理了，这是一个断句策略。但是对于歌词还是很难，因为歌词本来间隔就是短。
