### ISSUE TITLE
请问翻译Netflix的影片也是需要API的么

### ISSUE THREAD

**Issue by doubleanandyang** [muzuiget/dualsub-support#524]
我翻译了疾速追杀的英译汉，显示我需要API
![Xnip2023-05-24_00-37-55](https://github.com/muzuiget/dualsub-support/assets/67193933/fd841b81-2ceb-4742-af9c-ec0a87268522)
 （我试了下别的影片/剧 好像是可以的）还是说每部影片或剧都能翻译一定时间 一定时间以后就需要API了？

**Comment by muzuiget** [comment]
对的。

不过这种片子，等官方出中文就好了。
