### ISSUE TITLE
请求支持新网站（Support for new website）

### ISSUE THREAD

**Issue by javenhmh** [muzuiget/dualsub-support#525]
URL
https://www.deeplearning.ai/short-courses/

Enroll for Free (Free for a limited time)

Example:
https://learn.deeplearning.ai/chatgpt-prompt-eng/lesson/1/introduction

**Comment by javenhmh** [comment]
![image](https://github.com/muzuiget/dualsub-support/assets/12635249/9c5b811d-bcdb-42d3-aa03-cdab684c70a8)

**Comment by muzuiget** [comment]
这个网站只有 4 个课程，还是只有最早那个 ChatGPT Prompt Engineering for Developers 有字幕，还是断句很烂的字幕，怀疑是语音识别出来的，仅仅做了文本校对，没有重新打轴。。

所以现阶段不值得支持。

**Comment by muzuiget** [comment]
这点视频数量直接预生成字幕完事了 https://github.com/muzuiget/ai-subtitles
