### ISSUE TITLE
在切换两种不同语言时出现错误

### ISSUE THREAD

**Issue by DesertAc** [muzuiget/dualsub-support#53]
Error: Subtitle content includes whitespace character only

**Comment by muzuiget** [comment]
这个不算错误，说明字幕内容真的只包含空白字符。你可以用“打开解说词”查看一下。

**Comment by DesertAc** [comment]
> 这个不算错误，说明字幕内容真的只包含空白字符。你可以用“打开解说词”查看一下。

我核验了解说词，字幕并不是空白字符，大部分视频会出现错误，也有的视频能正常显示两种字幕。
![Image](https://user-images.githubusercontent.com/43565419/77806546-fcc42980-70bf-11ea-9246-4fb08af6f647.png)

**Comment by muzuiget** [comment]
发个视频地址测试下。

**Comment by DesertAc** [comment]
> 发个视频地址测试下。

任意拥有多语言视频都可能出现这个问题。您可以去看看。

**Comment by muzuiget** [comment]
试了几个视频都重现不了。

**Comment by muzuiget** [comment]
缺少反馈，先关掉了。
