### ISSUE TITLE
YouTube这几天开始不能显示翻译后的语言，只有英文单字幕

### ISSUE THREAD

**Issue by 5uy4n9** [muzuiget/dualsub-support#530]
YouTube 这几天开始不能显示翻译后的语言，只有英文单字幕
浏览器 Firefox 115.0.2 (64-bit)

**Comment by muzuiget** [comment]
是 YouTube 自己的问题，好像不能翻译自动字幕了，返回结果都是换行符。

![Screenshot_20230722_165040](https://github.com/muzuiget/dualsub-support/assets/330812/1f829324-66b0-4d35-b914-495492e1ec5d)

你可以禁用扩展，然后用 YouTube 原生的字幕菜单尝试下翻译。

**Comment by muzuiget** [comment]
搜了下 Twitter，就是 YouTube 自己的故障。

![Screenshot_20230722_165844](https://github.com/muzuiget/dualsub-support/assets/330812/2a0b914f-b292-4131-82d1-67f509f8e395)

**Comment by dolosking** [comment]
i meet the same problem

**Comment by muzuiget** [comment]
现在YouTube 修复了问题。
