### ISSUE TITLE
建议新增朗读字幕的功能

### ISSUE THREAD

**Issue by marlowma** [muzuiget/dualsub-support#533]
感觉增强后的翻译确实更精确一些，但是美中不足的就是没有字幕朗读的功能，特别是在看技术操作相关的视频时感受很深，一边看屏幕的操作细节，一边还要停下来看字幕，如果能一边听中文朗读一边看视频操作细节，那就会省去好多时间。这一点可以参考一下“YouTube字幕语音和翻译器”这个扩展插件（链接：“[https://chrome.google.com/webstore/detail/youtube-subtitles-speaker/gmimaknkjommijabfploclcikgjacpdn]）它不但可以同步朗读字幕，而且一旦遇到翻译后字幕过长导致朗读时间超过原视频播放时间，它会通过自动调慢原视频来自动适应语音朗读，也就是自动调慢视频进度等待当前这一段话朗读完，再播下面的视频和字幕及朗读。这一点非常人性化，但是他们的翻译来自youtube自带的翻译器，翻译的不如你们增强后的效果，所以真希望你们能参考一下他们的长处，取长补短。

**Comment by muzuiget** [comment]
不打算做这种功能，我不理解这种需求，译文本来不一定能和原文一一对应上的（无论时间长度和语序），甚至还有译错的地方，最终还是要眼睛看对比原文脑内修正。

我不知道这个扩展的实现原理，如果只是朗读上屏的那条字幕，总是可以在 DOM 里查找 `.dualsub-renderer` 这个节点来获取字幕文本。
