### ISSUE TITLE
如何增加自定义的主体样式

### ISSUE THREAD

**Issue by syheliel** [muzuiget/dualsub-support#534]
教程中没有找到新增样式的信息，在下拉菜单中也没有
![image](https://github.com/muzuiget/dualsub-support/assets/45957390/d6cb687a-9553-403a-ad65-3ac6e9fa8854)

**Comment by muzuiget** [comment]
删掉了，或者说，没有把这个设置 GUI 移植到 Manifest V3，现在是建议用 Wildmonkey 来直接加 CSS。

具体见 #469。
