### ISSUE TITLE
中文字幕与英文字幕闪烁问题

### ISSUE THREAD

**Issue by Meng-Nan-MZ** [muzuiget/dualsub-support#535]
使用网站：https://www.youtube.com/watch?v=Y5Hg4MvUXc4&t=993s

之前使用插件时从未出现该问题，但是今天打开网站选择标准翻译模式（英文-->中文，第一字幕），会出现翻译好的中文突然闪烁切换为英文，随后又从英文闪烁切换回来，反反复复无休止矣。长时间观看，看的眼睛都冒星星了。

请问这个问题该如何解决呢？只有我一个人遇到这个问题吗？

**Comment by muzuiget** [comment]
我本地的开发分支改了一大堆代码，昨天测试好好的，今天一行代码未改，结果也出现这个问题，调了大半天都不知道出错在哪里。

应该是 YouTube 改了什么，我切换回稳定分支再调试下。

**Comment by muzuiget** [comment]
你这个视频确实会闪烁。

你也试下这个视频 https://www.youtube.com/watch?v=LaLvVc1sS20 翻译“自动字幕”会不会闪烁？

**Comment by Meng-Nan-MZ** [comment]
> 你这个视频确实会闪烁。
> 
> 你也试下这个视频 https://www.youtube.com/watch?v=LaLvVc1sS20 翻译“自动字幕”会不会闪烁？

Youtube自带的英翻中的字幕不会闪烁，会以短句的形式慢慢呈现出来。

**Comment by muzuiget** [comment]
我说 Dualsub 的标准模式，简单模式应该也不会的。

**Comment by Meng-Nan-MZ** [comment]
> 你这个视频确实会闪烁。
> 
> 你也试下这个视频 https://www.youtube.com/watch?v=LaLvVc1sS20 翻译“自动字幕”会不会闪烁？

如果你指的是Dualsub选项中的标准模式，字幕语言这里我只有一个选项 English（auto-generated）。

**Comment by Meng-Nan-MZ** [comment]
完蛋了，我切换为简单模式后，现在字幕直接整没有了，Nothing！啊哈哈哈哈哈

**Comment by muzuiget** [comment]
频繁触发请求字幕会被限流的 #426

**Comment by Meng-Nan-MZ** [comment]
那字幕闪烁这个问题是我自身的原因吗？

**Comment by muzuiget** [comment]
不是，我正在找原因，我都觉得非常诡异，这部分代码好久没改过了。

**Comment by muzuiget** [comment]
找到原因了，检测视频数据变动代码，间隔会收到无意义的数据。

![Screenshot_20230730_221447](https://github.com/muzuiget/dualsub-support/assets/330812/abee258e-a2d9-4d8b-bf8e-cc87e03e639c)

正常应该是这样

![Screenshot_20230730_222000](https://github.com/muzuiget/dualsub-support/assets/330812/346fc23e-2f91-4a44-9d4f-bedb36c2505a)

不知道是不是广告的视频信息，所以扩展其实是在“广告视频“和“正常视频”之间反复切换。

**Comment by muzuiget** [comment]
准备发版本修复。

**Comment by muzuiget** [comment]
已提交 2.7.8 到 Chrome 商店等待审核。

等不及可以用这个 zip 

[dualsub-v2.7.8.zip](https://github.com/muzuiget/dualsub-support/files/12209465/dualsub-v2.7.8.zip)

**Comment by Meng-Nan-MZ** [comment]
辛苦！不着急，这门课太难，我还在温习离散数学呢，等你明天发布的新版本。

**Comment by Meng-Nan-MZ** [comment]
使用新版本，没有出现闪烁问题，该Issue关闭。

**Comment by Meng-Nan-MZ** [comment]
使用新版本，没有出现闪烁问题，该ISUUE关闭。
