### ISSUE TITLE
未来会增加chatgpt校正和翻译选项功能吗

### ISSUE THREAD

**Issue by eatcosmos** [muzuiget/dualsub-support#536]
一般用 https://aiproxy.io/ 的3.5接口，感觉费用可以接收。可以由用户自己提供apiurl和apikey，代替远程的谷歌机器翻译。
而且chatgpt也许可以校正一些youtube语音识别错误的问题。

**Comment by muzuiget** [comment]
不会做了，做得多不如做得精。

还不如让用户自己本地跑个服务器，自己去接入其他翻译引擎，省得还要我去接入。

其实很简单，下载 Dualsub 的 .crx 文件解压，修改 `manifest.json`，把 `host_permissions` 中的 `https://api.dualsub.xyz/*` 改成别的地址。

比如本机的 `http://127.0.0.1:8000/*` ，然后这个服务器实现一个类似 [JSON-RPC](https://zh.wikipedia.org/zh-cn/JSON-RPC) 的接口。

例如翻译：

![Screenshot_20230804_143056](https://github.com/muzuiget/dualsub-support/assets/330812/5d4c613b-516b-4430-86e8-a3961d756217)

返回结果：

![Screenshot_20230804_143106](https://github.com/muzuiget/dualsub-support/assets/330812/76d7de18-a2a5-4622-a058-3c882eb62b3a)

这样连 Key 都不用发到我的服务器。
