### ISSUE TITLE
关于标准模式下无法读取到“英语（自动生成）”的问题

### ISSUE THREAD

**Issue by m1a2sep** [muzuiget/dualsub-support#539]
从昨天开始我发现只要是YouTube自动生成的英语字幕都无法被标准模式读取到，显示“关闭（0）”，但是在简单模式下就可以读取到，并且可以正常显示，如果视频本身有原生英语字幕，那么标准模式就可以读取到，请问是怎么回事，谢谢

**Comment by muzuiget** [comment]
因为隐藏了，见 #538。不过理论上应该还看到 `Englisht (auto-generated) +` 这个菜单条目才对。

**Comment by m1a2sep** [comment]
> 因为隐藏了，见 #538。不过理论上应该还看到 `Englisht (auto-generated) +` 这个菜单条目才对。

好的谢谢，已经解决了
