### ISSUE TITLE
Netflix字幕問題

### ISSUE THREAD

**Issue by lazyguy328** [muzuiget/dualsub-support#540]
您好！
不知道是不是因為18號更新了，今天21號在Netflix上使用dualsub的時候出現了一個問題。
字幕在設定完成後，看了大概二十分鐘就自動消失了。
看下一集也會有同樣情況出現，所以要不斷設定字幕。每次打開新影集也要設定一次。
可能Disney+平台那些也有同樣情況出現。
因為以前的版本不會，所以不知道是不是新版本發生了什麼錯誤。
希望能夠解決此問題，感激！

**Comment by muzuiget** [comment]
应该和 https://github.com/muzuiget/dualsub-support/issues/538#issuecomment-1684866003 这个改动有关。

Netflix/Disney+ 会提前预读下一集的字幕数据，以为切视频了所以重置了字幕，这是 bug。

消失后重新选一下菜单应该会重新出现。

**Comment by lazyguy328** [comment]
原來如此。
請問有修復方法嗎？
因為每看一集都要重設一次字幕有點不方便。

**Comment by muzuiget** [comment]
晚点修复。

**Comment by muzuiget** [comment]
已提交 v2.8.8 等待审核。

**Comment by muzuiget** [comment]
刚刚过审了。

**Comment by lazyguy328** [comment]
剛試過，現在可以正常使用了。感激！
