### ISSUE TITLE
解决 No Audio File

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#542]
测试视频 https://www.youtube.com/watch?v=gQdflOUZQvA

调试方法：

1. 刷新一次页面，确保是当前标签页第一个打开的视频。
2. 按 F12 弹出 DevTools。
3. 在 Console 里运行：

```
ytInitialPlayerResponse.streamingData.adaptiveFormats
```

4. 展开最后一个 `mimeType: audio/` 的结果，截图。

![Screenshot_20230822_160209](https://github.com/muzuiget/dualsub-support/assets/330812/45ad5d2f-0e97-4f11-80e7-381d1921cc2b)

**Comment by zweix123** [comment]
部分截图如下

![image](https://github.com/muzuiget/dualsub-support/assets/74446314/59d79828-6f0a-49d5-a890-8c805d2ad650)

**Comment by muzuiget** [comment]
你要点开 `15:` 那个位置。

**Comment by zweix123** [comment]
部分截图如下：  
![image](https://github.com/muzuiget/dualsub-support/assets/74446314/ccf0682a-0f64-4728-ad5c-40b66fae9b4b)

**Comment by zweix123** [comment]
其他视频正常

**Comment by muzuiget** [comment]
就只有这个视频不正常？同一个频道的其它视频呢？都是要选择 `English (auto-generated) +` 这个菜单条目。

**Comment by zweix123** [comment]
哦！抱歉，其他视频也是不行的，比如您提供的视频，可以正常使用，但是选择的是“英语”，如果选择”英语 (auto-generated) +“会出现同样的错误。

**Comment by muzuiget** [comment]
试下另一个代码：

```
document.querySelector('#movie_player')?.getPlayerResponse().streamingData.adaptiveFormats
```

![Screenshot_20230822_163106](https://github.com/muzuiget/dualsub-support/assets/330812/2a5c3cc1-c007-4374-8e93-7ecd658a37d1)

**Comment by zweix123** [comment]
似乎之后最后的url不同

![image](https://github.com/muzuiget/dualsub-support/assets/74446314/0aceef4a-50c8-4607-8442-acee121f5bd1)

**Comment by zweix123** [comment]
也会有类似的报错

![image](https://github.com/muzuiget/dualsub-support/assets/74446314/e1251696-24cc-417a-a4a7-e87085266ad5)

左上角的数字会持续增长

**Comment by muzuiget** [comment]
这些警告是 YouTube 自己的代码，我也是这样的，无视就好。

看视频的音频数据好像都正常。

**Comment by muzuiget** [comment]
暂时想不出原因，要不你升级到最新 Chrome/Dualsub，并且关掉其它作用在 `youtube.com` 上的扩展再试下。

实在不行就用回 YouTube 的识别结果。

**Comment by zweix123** [comment]
按照您的方法处理了，最新Chrome，重新下载Dualsub，禁用其他所有扩展，仍然不行。

看来我和这个无缘了。

感谢您的时间。

**Comment by NingJay** [comment]
同样的问题出现在自我投稿的视频, 网页结构的变化影响了audio file的识别(在退出账号登录后就能识别到了). 能够理解不在https://player.dualsub.xyz/上部署whisper的存储原因. 但希望尽快适配一下不同结构的网页(以自我投稿视频入手修复这个bug).

**Comment by muzuiget** [comment]
和页面结构无关的，扩展会用

```
document.querySelector('#movie_player')?.getPlayerResponse().streamingData.adaptiveFormats
```

获得音频地址，所以在手动在 DevTools 运行和检查一下（类似前面帖子的截图）。

https://player.dualsub.xyz/ 是另一个问题了的，之所以在 YouTube 里几秒钟能识别好，因为扩展只是是发送音频地址到 Dualsub 服务器的，然后 Dualsub 服务器去 YouTube 服务器去下载音频文件，云服务器之间传输远比和家庭网络的速度快。

如果在 https://player.dualsub.xyz/  上实现 Whisper，只能上传整个视频文件，当然这不现实，速度又慢又要服务器储存空间。除非做成桌面应用能调用 ffmpeg 分离出音频，这样可以减少上传数据量。

**Comment by NingJay** [comment]
> 重现打开这个 issue。
> 
> 目前有三个人报告这个问题，都是我能正常识别出字幕。

 手动打开url可以跳转到语音, 但插件似乎无法正确获取

**Comment by muzuiget** [comment]
发布了 v2.10.1，再测试下。

**Comment by NingJay** [comment]
> 发布了 v2.10.1，再测试下。

测试已解决

**Comment by muzuiget** [comment]
其实 v2.10.1 还未通过审核。

**Comment by chenyihao009** [comment]
感觉还是有点问题，我用chrome看我自己上传的视频，权限为未公开，会出现 no audio file，但是我复制视频链接，到edge浏览器打开就可以了

**Comment by muzuiget** [comment]
视频权限要是“公开”（Public）或“不公开列出”（Unlisted），这样服务器才能匿名下载，如果是“私享”（Private），肯定不行，这种要登录。

具体见 <https://support.google.com/youtube/answer/157177?sjid=10908427626019299942-NA>

**Comment by chenyihao009** [comment]
还是不行啊，无论怎么调整视频权限，在chrome上就是 no audio file，但是其他人的视频就没有问题

**Comment by muzuiget** [comment]
试下 v2.10.1，Chrome 商店 3 天了都未通过审核。

[dualsub-v2.10.1.zip](https://github.com/muzuiget/dualsub-support/files/12843085/dualsub-v2.10.1.zip)

**Comment by chenyihao009** [comment]
再次测试，只要edge浏览器登陆自己的账号，刚才还可以的视频也变成了no audio file

**Comment by chenyihao009** [comment]
还是不行，算了，我先用两个浏览器凑合着用

**Comment by chenyihao009** [comment]
其他人的视频都行，就是自己上传的视频自己看不行，但我退出账号就又可以了，这点上两个浏览器都一样

**Comment by muzuiget** [comment]
这么玄学。

**Comment by chenyihao009** [comment]
蟹蟹，希望能早日解决



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月13日(周五) 晚上6:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [muzuiget/dualsub-support] 解决 No Audio File (Issue #542)




 
我测试了，确实这样，看自己的视频就是 no audio file。
 
原因是看别人的视频，音频地址是 xxx.googlevideo.com/yyy.mp4，如果是看自己的视频，视频/音频地址的域名是 xxx.c.youtube.com/yyy.mp4，而后者这种地址是无法匿名下载的，无论可见权限设置为“Unlisted“还是”Public“。
 
所以只能避免看自己的上传的视频：上传视频后，退出登录或者切换别的账号来观看。
 
不想频繁登录/登出的话，最简单的方法就是两个浏览器，或者临时打开一个隐身模式窗口来观看。如果是手机，可以用 YouTube App 来上传，浏览器来观看。

**Comment by muzuiget** [comment]
现在就是解决不了，只能让用户手动操作绕过下。

**Comment by marlowma** [comment]
我也遇到了同样的问题，chrome浏览器，mac主机。显示“no audio file”
