### ISSUE TITLE
Not Compatible With Older Version of Google Chrome

### ISSUE THREAD

**Issue by Jo-JoJ** [muzuiget/dualsub-support#545]
Good day, 

Thank you so much for creating such a helpful extension! 

May I ask a question about the compatibility? Cause the current version doesn't support the older version of Google Chrome, just wondering if there's any future plan to make it compatible with the older version of Chrome. If it's possible, it would be really helpful, cause my laptop is not that new anymore, and Chrome won't be updated to a newer version, the current version is 103.0.5060.134. 

![DualSub](https://github.com/muzuiget/dualsub-support/assets/143205295/befe158f-077d-47c7-a052-927cb0ecc8b5)
 

Thank you so much! : )

**Comment by muzuiget** [comment]
No plan to support older version browsers, actually it only test on latest stable version browsers.

Google don't provide older version Chrome download, it forces everyone to update to latest versions.

**Comment by Jo-JoJ** [comment]
Thank you so much for your quick reply! 

My Chrome wouldn't update due to the computer system being unable to update anymore. But I figured out a workaround that uses the older version of the DualSub (Dualsub v1.87.1 which was found from Crx4Chrome) and manually added it to Chrome, it seems to work!

If someone else has a similar issue, they may try this way too I guess. 

Thanks again for creating and always updating this amazing extension!! : )

**Comment by muzuiget** [comment]
The older version 1.x is an Manifest V2 extension, you can download the latest 1.x version on Firefox archive

https://addons.mozilla.org/en-US/firefox/addon/dualsub/versions/

**Comment by Jo-JoJ** [comment]
Thank you so much for your help! : )
