### ISSUE TITLE
部分Disney+的原创视频字幕提前于画面

### ISSUE THREAD

**Issue by livy365** [muzuiget/dualsub-support#546]
Disney+上有部分视频为Disney+原创，播放新的一集时会播放Disney+的logo片头。由于dualsub始终按照没有片头的时间轴展示字幕，此种情况下字幕优先于画面。

**Comment by muzuiget** [comment]
已知问题 https://github.com/muzuiget/dualsub-support/issues/484#issuecomment-1444997048
