### ISSUE TITLE
Youtube字幕顯示的問題

### ISSUE THREAD

**Issue by kkl1919** [muzuiget/dualsub-support#548]
Youtube有的中文字幕，我在dualsub按中文字幕，顯示  { HTTP 500  } ，求解答
![image](https://github.com/muzuiget/dualsub-support/assets/120043926/182a3e00-7fea-4ebf-bce2-e2818bba5e85)

另外就是，最近幾天才出現的問題，就是在Youtube每次點開新的影片都要在右上角再按一次dualsub的字幕，就是每次點開新的影片字幕不會自動出現，以前不會這樣的，不知是否你們更新了什麼，求解答，感謝！！

還有一個問題，也是最近幾天出現的，就是Youtube英語的自動字幕顯示{ waiting for server response... }
![image](https://github.com/muzuiget/dualsub-support/assets/120043926/d9234005-24fa-4c86-994e-15db3354c0aa)
但也就只有這個選項，沒有那個沒有+號的

**Comment by muzuiget** [comment]
见 #538

**Comment by kkl1919** [comment]
看了，#538 針對我上面說的第三個問題，但我這裡只有+號的選項，為什麼呢？
還有求解答中文字幕用不了，還有dualsub字幕不會自動出現的這兩個問題，感謝

**Comment by kkl1919** [comment]
原來我提的第一個問題，我在Machine translation是選了中文的，如果不選擇就沒有問題了。但以前不是這樣的，因為我習慣了吧簡體中文翻成繁體中文，但現在就會顯示 { HTTP 500  } 了。
![image](https://github.com/muzuiget/dualsub-support/assets/120043926/030ab27f-ced5-4a3b-81bd-50e790426f8e)

**Comment by muzuiget** [comment]
1. `{ waiting for server response... }` 表示正在等待 Whisper 识别音频结果，这是正常的。

2. 不会自动选择菜单，这是有意改掉的 https://github.com/muzuiget/dualsub-support/issues/538#issuecomment-1684866003

3. HTTP 500，请给出视频地址和菜单选择设置，等我测试。

**Comment by kkl1919** [comment]
1  明白，另外就是有些時候識別不了，沒有顯示任何字幕， 例如影片中 1:40-2:40
https://www.youtube.com/watch?v=rl2Q9xH8e7M

2 好的了解

3 例如這個影片 https://www.youtube.com/watch?v=zQV42J1e5j4
以下是我顯示的畫面，顯示{ HTTP 500  }
![image](https://github.com/muzuiget/dualsub-support/assets/120043926/e0a09e48-982d-480f-a259-c0470e5918e9)

**Comment by muzuiget** [comment]
1. 这是 Whisper 的特性，偶然识别不出来，只好跳过一小段。

3. 这个是 bug，服务器接口改了，迟点修复。

**Comment by kkl1919** [comment]
謝謝你，還有提問，1就是我選擇不了沒有+號的 English(auto-generated)，是為什麼？


2 還有就是 剛剛遇到{ not support limited video }這樣一個情況 https://www.youtube.com/watch?v=PwRl5W-whTs
![image](https://github.com/muzuiget/dualsub-support/assets/120043926/b5ea5d92-0cd3-4996-a82f-3e2d19a219ca)

**Comment by muzuiget** [comment]
服务器已经修复了简繁中文转换。

1. #538 里有说了，你要用 DevTools 设置参数。

2. 这个视频就是加密了音频文件地址的，所以无法识别。至于原因，我只能猜测，视频被检测出用了一些版权音乐，这些视频打开详情几乎都有这种声明。

![Screenshot_20230828_232927](https://github.com/muzuiget/dualsub-support/assets/330812/e94396d0-d85d-44ac-b3e7-f63e38c1c8f4)
