### ISSUE TITLE
DOES NOT WORK IN Star+

### ISSUE THREAD

**Issue by orchidraco** [muzuiget/dualsub-support#549]
### No subtitle language option appears in the domain [https://www.starplus.com/](https://www.starplus.com/).

i.e. **"Close (0)"** appears no matter what video I try it with _(I've seen every tutorial there is to make good use of this expansion so I'm pretty sure this error is not due to me or my inexperience using this)_. Anyway, to check it out I tried it with both _YouTube and Netflix_ and it works great, **but I downloaded it in order to make use of the bilingual subtitles on Star+** and I'm sad that it doesn't work for me.

@muzuiget Could you take a look at it and fix it? Only if it's not too much trouble for you, thank you very much.

**Examples:**
![example 1](https://github.com/muzuiget/dualsub-support/assets/143757859/17c79a44-972c-4739-8eed-61e32d91fd21)
![example 2](https://github.com/muzuiget/dualsub-support/assets/143757859/d602315c-df12-40f5-9213-e54861f423c9)

**Comment by orchidraco** [comment]
I detected an error and you @muzuiget didn't even answer, at least to say that it is impossible for you to solve it. I don't really understand it, it's a real pity because I saw a good future for the development of this expansion.

**Comment by muzuiget** [comment]
Starplus has changed their website code, it makes Dualsub broken. I don't have time to deal with it recently.

Actually I decide to drop support for such sites:

* No free video for testing.
* Has restrictions according to the viewer's location or device.

**Comment by muzuiget** [comment]
Won't fix, see https://github.com/muzuiget/dualsub-support/issues/553
