### ISSUE TITLE
Dual sub panel hides youtube video's info on "views", "date"...

### ISSUE THREAD

**Issue by andradadad** [muzuiget/dualsub-support#55]
https://i.imgur.com/FlKPsQZ.png
It's irritating to not see that info.

**Comment by muzuiget** [comment]
Maybe your browser window width is too small, are you use it on Pad computer?

**Comment by andradadad** [comment]
1280x1024 Windows 7 pc
Doesn't matter if it's small, it shouldn't mess the screen like that. Not for all the many other users.

Use the source code of the page to organize it better, or adjust it to be draggable.

**Comment by muzuiget** [comment]
YouTube itself will hide "view" and "date" when the width is too small, it is hard to find a place for the toolbar, and most user today use 1080p monitor.

**Comment by andradadad** [comment]
You fixed it, and then removed it? It worked good.

**Comment by muzuiget** [comment]
Yes, I revert back, because most users don'nt like it.
