### ISSUE TITLE
Not displaying autogen subs on youtube

### ISSUE THREAD

**Issue by cl0udrecesses** [muzuiget/dualsub-support#551]
Since the latest updates, standard mode on youtube is not showing the option of autogenerated eng subs at all, while they present on youtube's native ccs. is it a youtube update that broke this or dualsub's?

**Comment by muzuiget** [comment]
Are you using Firefox verison?

**Comment by cl0udrecesses** [comment]
yeah

**Comment by muzuiget** [comment]
I am deprecating the old Manifest V2 version, the server-side features is hidden by default, the server will removes the API for Manifest V2 in the furture.

* Use the "Simple Mode" instead.
* USe the Chrome version (Manifest V3) instead.
