### ISSUE TITLE
你做得很好，但YouTube 不乏選擇

### ISSUE THREAD

**Issue by Benlee1129** [muzuiget/dualsub-support#556]
您好，

感覺到你已經將重心移往YouTube 內容，並且有雄心壯志。你能把YouTube 的字幕翻譯作好，我覺得很棒，也會支持。
不過，可供在YouTube 字幕翻譯的插件選擇太多了，而且YouTube的大量受眾使用的語言都是母語，並不需要使用字幕翻譯功能，而且YouTube自帶的字幕翻譯功能也能湊合著用。
使用dualsub的目的，一是雙語訓練需要，二是想要去探索各國的文化和娛樂內容，這在各國的國家電視台，如德國的ARD, ZDF，英國的BBC, ITV都有豐富的內容，但YouTube 卻是很缺乏。
再來，YouTube 的廣告一大堆，想認真看節目都覺得很累人。
我建議你堅持初始的想法和精神（初心），把YouTube 的字幕翻譯做得比別人完美，但這不是唯一的目的。
近年來，我一直有回覆意見給你，我也常看別人的問題。我發現，當你宣布Wisper專案的想法和把所有的留言都清除了之後，就再也沒有看到有人留言了。

**Comment by muzuiget** [comment]
根据服务器日志数据分析，现实就是付费用户都是为了翻译 YouTube 字幕，其余网站真是可以忽略不计。

我也就是 Netflix 和 Disney+ 勉强感兴趣看看，其它网站就算了，高投入低回报，没那么多精力。

**Comment by Benlee1129** [comment]
我是感到你把工作做的很好，而且也是非常有用的事。
我還是會付費支持你，增加其他網站的使用量。
你也確實把YouTube 的自動翻譯做的很好。

muzuiget ***@***.***> 於 2023年10月17日 週二 16:57 寫道：
