### ISSUE TITLE
观看过程中出现{no speech}问题

### ISSUE THREAD

**Issue by wulong2020** [muzuiget/dualsub-support#558]
https://www.youtube.com/watch?v=jLfdnr5PMq4&list=PL5IcOO7sZoK04boclR5LzHbSgUAUCmSOY&index=36

比如这个视频，手动选择“whisper”后，开始可以正常识别字幕，但时不时会出现"no speech",过一会又会自己恢复识别

下图是截图，第二行中文是我故意测试设置为“英语（自动识别）的，防止看一会就”whisper“就"no speech"
<img width="958" alt="Snipaste_2023-10-18_21-20-43" src="https://github.com/muzuiget/dualsub-support/assets/86549530/62fa56f0-2dd9-4caa-9572-5488dc0cb24d">

**Comment by muzuiget** [comment]
Dualsub 是边播放边识别的，每次识别 30-90 秒片段，现在只支持识别英文。

所以出现 `no speech` 表示整个片段识别不出任何有效英文。

1. 如果视频是中文或者纯音乐视频，这是正常，就是提示用户关掉 Whsiper 功能，避免浪费服务器资源。
2. 如果是英语视频，某个片段识别质量不佳，比如太大噪声，或者音乐占了大部分。
3. 服务器处理错误，比如从 YouTube 下载失败。

对于 2 和 3 的情况，可以刷新页面重试的。

刷新后你可以直接跳转之前出现错误的时间点开始识别，看下是否再出现。因为开始识别时间点不同， 切分的片段也不同，所以第 2 种情况可能不会出现。

**Comment by muzuiget** [comment]
截图种我看不到你的时间点，不然我可以测试下。

**Comment by muzuiget** [comment]
![Screenshot_20231021_123708](https://github.com/muzuiget/dualsub-support/assets/330812/b4155cd7-b292-4eb8-b677-afd64ff2d30d)

我是正常的，所以刷新重试就好。
