### ISSUE TITLE
控制栏出现在视频上方

### ISSUE THREAD

**Issue by SpoonerCake** [muzuiget/dualsub-support#56]
不知道是更新的问题还是什么情况，
![QQ截图20200407184424](https://user-images.githubusercontent.com/49234232/78660548-dc863d00-78ff-11ea-8416-4b579bb7d7f2.png)
我觉得这样的话很妨碍视频观看，即使它播放时会消失，请问能否恢复到原来的位置？

**Comment by muzuiget** [comment]
是更新了，原来的位置又有人嫌宽度太窄，遮盖观看次数和日期。

先发个版本观望下。

**Comment by xuyaocrazy** [comment]
能不能增加个选项，让用户自己选在哪里显示。
**我比较喜欢在下面的。**

**Comment by uzcool** [comment]
是的..出现在上面感觉有怪怪的..希望能加个选项..

**Comment by DefetC** [comment]
现在这样不太行。 不如放下面。 或者可以把控制栏合并到浏览器右上角的插件图标上？

**Comment by as921921** [comment]
希望有選項可以改變，快轉時也會顯示出來，很檔視線

**Comment by muzuiget** [comment]
发现 YouTube 自己在浏览器窗口太小时也是自动隐藏“观看次数”和“日期”的。

所以算了，恢复到原来的位置，放到哪里都觉得不顺眼。

上传了 v0.7.1，等待审核。
