### ISSUE TITLE
可以把字母字体放大么？ 感谢

### ISSUE THREAD

**Issue by cyx951211** [muzuiget/dualsub-support#560]

**Comment by muzuiget** [comment]
现在有点麻烦 https://github.com/muzuiget/dualsub-support/issues/469#issuecomment-1341745742

**Comment by cyx951211** [comment]
没事儿  可以等等 但是最好还是有。麻烦了。给个时间就好 十分感谢

**Comment by muzuiget** [comment]
现在做法是自适应字体大小，比如 32px 的字体，在 4K 显示器和手机上观感是不一样的，需要根据窗口大小，视频布局，点距比例等各种条件自动设置不同的像素。

所以目前最佳方法添加自定义 CSS ，你根据你的显示器和观感，自己设定一个绝对像素值，覆盖掉 Dualsub 默认的自适应像素值。

**Comment by cyx951211** [comment]
有操作路径不？ 我学习下？

**Comment by muzuiget** [comment]
就是这个帖子

https://github.com/muzuiget/dualsub-support/issues/472#issuecomment-1341727283
