### ISSUE TITLE
火狐浏览器貌似用不了了，都显示0，重新安装也不行

### ISSUE THREAD

**Issue by MML1118** [muzuiget/dualsub-support#561]
![iShot_2023-10-22_13 47 50](https://github.com/muzuiget/dualsub-support/assets/92147385/3ac1b20d-1d39-445a-a12e-9017ce45ca3a)

**Comment by muzuiget** [comment]
因为 Firefox 还是基于 Manifest V2 的旧版本，只对 YouTube 维护一下。

其余功能只能用最新的 Manifest V3 版本。
