### ISSUE TITLE
Twitch support 

### ISSUE THREAD

**Issue by BrokedTV** [muzuiget/dualsub-support#567]
Twitch support pls

**Comment by orchidraco** [comment]
@BrokedTV there is already a tool that proposes what you watn, and it can be used not only on twitch but also on other platforms: [speech translator](https://github.com/speech-translator-ext/speech-translator-readme) by kappaflow. as it is, you can also get it from [chrome web store](https://chromewebstore.google.com/detail/speech-translator/jodfjmaiakpnmeddgpeflpafebmlhppn).
