### ISSUE TITLE
多字幕为啥今天更新后去掉了

### ISSUE THREAD

**Issue by aristotll** [muzuiget/dualsub-support#569]
这个extension 比其他类似多sub 拓展多的一个很好的功能，为啥去掉了啊

**Comment by aristotll** [comment]
只能有两个了，以前可以增加

**Comment by muzuiget** [comment]
这个功能从 _全局设置选项_ 改成 _网站设置选项_，每个网站可以单独设置，这个功能不太重要，所以就先删掉 UI 了，需要用 DevTools 来修改。

在 https://www.youtube.com/ 按 F12 打开 DevTools，在 Console 里运行：

```
localStorage.setItem('dualsub-subtitle-count', '4');
```

![Screenshot_20231215_214245](https://github.com/muzuiget/dualsub-support/assets/330812/5fc71b2e-cd06-4780-a2f3-272927d5828a)

刷新一次页面就行。

现在“标准模式”下只能前两个字幕能使用 `api.dualsub.xyz` 的机器翻译服务。

**Comment by aristotll** [comment]
最新更新这个失效了，现在有其他方式吗 @muzuiget

**Comment by muzuiget** [comment]
这个参数已经删掉，最后支持的版本是 2.43.2。
