### ISSUE TITLE
如果可以加入下载双字幕的功能就更好了

### ISSUE THREAD

**Issue by yiyinyiyang** [muzuiget/dualsub-support#57]
很棒的插件
如果可以加入下载双字幕的功能就更好了
Dualsub Exporter 虽然能实现 但是 使用不方便 
希望 作者可以考虑下  
不论怎么样 这款插件已经很棒了 ！ 谢谢分享

**Comment by muzuiget** [comment]
你意思是在 YouTube 界面直接下载吗？
