### ISSUE TITLE
Chinese Learning Theme Style Option Missing on Firefox

### ISSUE THREAD

**Issue by bluestreak-vl** [muzuiget/dualsub-support#570]
Hello,

I've tried uninstall/reinstall, reset options, but the Chinese (and Japanese) learning themes are still not available on my Firefox. I tried on another PC with same result. Is this a paid feature? I don't see it mentioned as a paid feature on the website, so I am not sure...

![image](https://github.com/muzuiget/dualsub-support/assets/138949690/0d401625-0d2c-47d6-883c-f06e9348d81b)

I also tried changing the "First Subtitle" to match the Chinese Learning theme. Enabled the "Show Pinyin" option : no change. Next, I selected "Chinese Analysis" under "Language Toolkit" and then the option for the "First Subtitled" disappeared from the theme style list - So it seems to be something related to the "Chinese Analysis"?

Thanks

**Comment by bluestreak-vl** [comment]
Extension version available is 1.86.11, last updated Nov 24, 2023. 
https://addons.mozilla.org/en-US/firefox/addon/dualsub/

**Comment by muzuiget** [comment]
The Firefox version `v1.x` is outdated Manifest V2 extension, I have removed all the features which decency the remote  server, and keep only the basic YouTube dual subtitles features.

The "Chinese Learning" feature is not a paid feature, but currently you only can use the latest `v2.x` version on Chrome which is a Manifest V3 extension.

See the changelog: https://www.dualsub.xyz/guide/other/changelog.html#2.0.0

**Comment by bluestreak-vl** [comment]
Thank you for the quick response.

Sad to hear that the Firefox version is missing some of the nicer features but I understand its a lot of work. I will use Chrome in the future.

**Comment by pfn** [comment]
> The Firefox version `v1.x` is outdated Manifest V2 extension, I have removed all the features which decency the remote server, and keep only the basic YouTube dual subtitles features.
> 
> The "Chinese Learning" feature is not a paid feature, but currently you only can use the latest `v2.x` version on Chrome which is a Manifest V3 extension.
> 
> See the changelog: https://www.dualsub.xyz/guide/other/changelog.html#2.0.0

Does this mean that dualsub on chrome currently cannot use the pinyin (chinese learning) feature? I am not seeing it in chrome at the moment

**Comment by muzuiget** [comment]
Moved to **Styles** tab.

![Screenshot_20231230_060400](https://github.com/muzuiget/dualsub-support/assets/330812/3bc97ce7-a76c-4935-87bd-1b850fac0723)

**Comment by pfn** [comment]
Thank you!
