### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Rahjooyan** [muzuiget/dualsub-support#571]
1. Please support uploading SRT and VTT subtitles like Substital extension.
2. Please support this site:
https://youku.tv/
3. I tried free content from IQ.com but it didn't work and I can't choose Persian/Farsi language from menu.
Thanks.

**Comment by muzuiget** [comment]
> 1. Please support uploading SRT and VTT subtitles like Substital extension.

Actually this is a removed feature https://www.dualsub.xyz/guide/other/changelog.html#1.87.1

So it won't be add back.

> 2. Please support this site: https://youku.tv/

Maybe later.

> 3. I tried free content from IQ.com but it didn't work and I can't choose Persian/Farsi language from menu.
Thanks.

The website itself should provides Persian/Farsi language human translation, otherwise you only option is to use the machine translation.

**Comment by Rahjooyan** [comment]
"load local subtitle file" was good feature and I didn't find your extension. I requested it from websites and other owner's extensions but it wasn't useful. may you create another extension just to do this like  Substital extension? It will be good to use another subtitles or human translations. so users can try another sources or use languages that there isn't provided by websites.

**Comment by muzuiget** [comment]
Too few users need this functionality.

Subtitle files you get from other places are usually out of sync with the video. For example, the subtitle frame rate also differentiates between BDRip and WebRip versions.

ASS subtitles also add a lot of special effects codes that are difficult to parse.

If you have video files and subtitle files on your local computer, use https://player.dualsub.xyz/ to play them.

Drag video files and subtitle files into the web page, and the Dualsub menu will display the subtitle files you dragged in.

**Comment by muzuiget** [comment]
`v2.18.0` has supported for <https://www.youku.tv>.
