### ISSUE TITLE
Disney plus 字幕与声音不同步

### ISSUE THREAD

**Issue by isLundy** [muzuiget/dualsub-support#574]
观看Disney plus时字幕比声音块1-2s，很糟糕！！！！！！

**Comment by muzuiget** [comment]
见 https://github.com/muzuiget/dualsub-support/issues/484#issuecomment-1444997048

打算把这个问题在字幕菜单界面上加个文档链接。

**Comment by muzuiget** [comment]
解决方法：把进度条拖回最开始 `00:00` 一次。

**Comment by muzuiget** [comment]
在 v2.28.0，在字幕菜单页面添加了 #593 的链接。
