### ISSUE TITLE
No longer able to select font and styles

### ISSUE THREAD

**Issue by SonicAwareness** [muzuiget/dualsub-support#575]
I am unsure of the exact version change or date, but I am no longer able to select detailed font and CSS settings in dual sub for Firefox. Is this functionality returning later?

**Comment by muzuiget** [comment]
The Firefox version has been updated to Manifest V3, changelog: https://addons.mozilla.org/en-US/firefox/addon/dualsub/versions/

Currently the only way to custom the subtitle font is apply some CSS code, see https://github.com/muzuiget/dualsub-support/issues/500

Here is the CSS code for custom the font size:

```
.dualsub-renderer .subtitle-1 .dialogue {
    font-size: 36px;
}

.dualsub-renderer .subtitle-2 .dialogue {
    font-size: 32px;
}
```

I known writing code is not friendly for users, but currently Dualsub support many websites, difference layouts(video width, desktop and mobile devices), so it is better auto set the font size by environement.
