### ISSUE TITLE
Feature request: Create your own Preferred Language List

### ISSUE THREAD

**Issue by idanrm** [muzuiget/dualsub-support#578]
I think it would be great if you could edit the current list of preferred languages, i.e. each user creates their own preferred language list.

Thanks

**Comment by muzuiget** [comment]
The preferred languages is your browser preferred languages, you can add your languages in the browser setting page.

![Screenshot_20240201_185029](https://github.com/muzuiget/dualsub-support/assets/330812/38470e9a-02ff-43ae-855e-e12a1a77d719)

Doc: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/languages

**Comment by idanrm** [comment]
I understand, thank you. The preferred language list is indeed as configured in my browser, however Hebrew is configured in my browser but is missing in the extensions' preferred language list. What could be the issue, then?

Thanks

**Comment by muzuiget** [comment]
Switch the Dualsub setting option to `All Available Languages`, can you see the Hebrew menuitem?

**Comment by idanrm** [comment]
Yes, I can see it. I personally have no problem with continuing using the All Available Languages option, however maybe it's worrth looking into this bug.

**Comment by muzuiget** [comment]
![Screenshot_20240201_193246](https://github.com/muzuiget/dualsub-support/assets/330812/98495cc2-7e33-4e4c-9935-32303a41b715)

Hebrew has two language codes: `he` and `iw`.

I believe the issue arises because the browser uses `he`, while Dualsub uses `iw`, leading to `he` being treated as an unsupported language code and consequently filtered out.

**Comment by idanrm** [comment]
If so, then why does Dualsub uses 'iw' instead of 'he'?
As far as I can see, 'iw' is the old ISO-639 language abbreviation for Hebrew and 'he' is the new one.

**Comment by muzuiget** [comment]
The current language code list was "copied" from Google many years ago. If backward compatibility is not a concern now, we can consider switching to `he` in the next version.

**Comment by muzuiget** [comment]
This is fixed in `2.23.0`.
