### ISSUE TITLE
字幕出现不了

### ISSUE THREAD

**Issue by yyxs038** [muzuiget/dualsub-support#58]
![image](https://user-images.githubusercontent.com/32858003/79525164-ccefbc80-8094-11ea-9e9b-54384327ec8f.png)

请看一下报错

**Comment by muzuiget** [comment]
我试了一下还 OK 啊。你这是哪个版本的 Chrome？

**Comment by yyxs038** [comment]
![4 0`D0}L}NY9ET U 4271CR](https://user-images.githubusercontent.com/32858003/79624105-32ee4980-8152-11ea-834d-ff0217fe3fb3.png)

**Comment by muzuiget** [comment]
呃，你有把 https://dualsub-app.appspot.com/ 加进代理吗？直接访问一下看看。

**Comment by muzuiget** [comment]
缺少后续反馈
