### ISSUE TITLE
Viki.com subtitles disappearing

### ISSUE THREAD

**Issue by zvbt** [muzuiget/dualsub-support#580]
Sometimes, there is a subtitle that won't show up until you move the mouse, and it happens quite a bit while watching an episode.

**Comment by muzuiget** [comment]
I wasn't able to reproduce this issue. If it occurs in a specific video, please post the video link.

**Comment by zvbt** [comment]
I managed to solve my issue. I was using an extension (Stylus) to change the subtitle font, and since I disabled it, everything works fine as before. Sorry for the inconvenience.
