### ISSUE TITLE
Different Auto-Generated Language Detected on Native Mode vs Standard Mode

### ISSUE THREAD

**Issue by idanrm** [muzuiget/dualsub-support#582]
Hello,

For this video (and for any other video with auto-generated Arabic subtitles):
https://www.youtube.com/watch?v=ZNwGH28_PeU&ab_channel=HowtolearnArabicwithSahar

The Native Mode will show "Arabic (auto-generated)", while in the Standard Mode it will show only "English (auto-generated)".

Could you please look into it?

Thank you

**Comment by muzuiget** [comment]
As the **Help** panel shows:

> This mode features machine-generated subtitles (machine translation and speech recognition) provided by Dualsub servers.

Currently our servers only supports speech recognition for English.

**Comment by idanrm** [comment]
I see, thank you.
