### ISSUE TITLE
Restore support for starplus

### ISSUE THREAD

**Issue by fragarray** [muzuiget/dualsub-support#584]
Disney+ is actually supported, both sites have almost the same code, it's planned to add support once again?

**Comment by muzuiget** [comment]
There are two reasons for no longer supporting such websites:

* They restrict the regions that users can access, requiring a VPN to bypass this restriction.
* They do not have videos available for free testing, requiring payment.

I will not spend too much time on these kinds of websites.

**Comment by fragarray** [comment]
Could it be helpful to open an online fundraising campaign to purchase the necessary services to cover these needs?

**Comment by fragarray** [comment]
> Why not just use https://www.disneyplus.com/ directly?

Because in many regions, such as Latin America, Disney and Star subscriptions are on different websites.

**Comment by fragarray** [comment]
I can share my vpn account with you if you need.

**Comment by fragarray** [comment]
Now even Disney Plus has switched to the same interface as StarPlus, in fact the extension no longer works.

**Comment by muzuiget** [comment]
Close it as I said on 2nd comment.
