### ISSUE TITLE
Disneyplus update

### ISSUE THREAD

**Issue by fragarray** [muzuiget/dualsub-support#586]
The Disneyplus interface, at least in Latin America, has changed and the extension is no longer working.

**Comment by sigmacharding** [comment]
Same issue here. Working for YouTube but not D+. Using it from Hong Kong to watch Star Wars the bad batch. Tried turning D+ subs on and off and restarting browser but not luck so far.

**Comment by fragarray** [comment]
Interface upgraded in europe too.

**Comment by muzuiget** [comment]
Disney+ is still available according to our server logs (from machine translation requests).

Or you can try turning off experimental features in the Disney+ settings.

**Comment by fragarray** [comment]
> Disney+ is still available according to our server logs (from machine translation requests).
> 
> Or you can try turning off experimental features in the Disney+ settings.

I can't find the option to turn off experimental features, any help?

**Comment by sigmacharding** [comment]
It's working for me again now. I didn't click or change anything. It's just running like it normally does. Thanks all for the help. Not sure what was going on.

**Comment by fragarray** [comment]
> It's working for me again now. I didn't click or change anything. It's just running like it normally does. Thanks all for the help. Not sure what was going on.

Still nothing here. 😭

**Comment by 19971n0** [comment]
I had the same problem and tried adjusting Disney Plus's built-in subtitles and resetting it back to default, and Dualsub works again! Hope this helps :D

**Comment by muzuiget** [comment]
I need an account to test and fix this issue, if anyone would like to lend me an account please send it to `muzuiget@gmail.com`.

You can reset your account password after this problem is fixed.

**Comment by fragarray** [comment]
I tried to reset the subtitles settings from the Disney player but nothing changed. Unfortunately, my account is shared and I can’t change the password.

**Comment by muzuiget** [comment]
Dualsub 2.25.1 have been released on Chrome Web Store, please try this version to check the bug is fixed or not.

**Comment by fragarray** [comment]
> Dualsub 2.25.1 has been released on the Chrome Web Store. Please try this version to see if the bug has been fixed.

Perfect, well done!

One last thing, as I can see from the pages, Disney+ and Star+ share the same variables. I'm pretty sure your extension will work on Star+ too if you just enable that.

**Comment by muzuiget** [comment]
@fragarray You can share me your account for testing.

**Comment by fragarray** [comment]
> @fragarray You can share me your account for testing.

mine it's shared too. I'm sorry.
