### ISSUE TITLE
Official change.org petition.

### ISSUE THREAD

**Issue by fragarray** [muzuiget/dualsub-support#587]
Hi everyone, I would like to share this petition with you. It is about requesting streaming platforms to introduce the feature to display two subtitles simultaneously during content playback.

Feel free to vote, share and suggest changes.

This is the original petition text:

We, the undersigned, address streaming platforms to request the introduction of the feature to display two subtitles simultaneously during content playback.

In an increasingly interconnected and multicultural world, it is crucial to ensure access to audiovisual content inclusively for all linguistic and cultural communities. Currently, no streaming service offers the ability to display two subtitles simultaneously, a lack that significantly limits access to content for multilingual families and those looking to enhance their language skills.

This feature would not only be beneficial for multilingual families but also hold significant educational value. Allowing users to display two subtitles in different languages during content playback would promote language and cultural learning, offering a more enriching and inclusive experience for viewers worldwide.

We acknowledge that the introduction of multiple subtitles may pose technical challenges for streaming platforms, but we firmly believe that these difficulties are surmountable with commitment and adequate resources. Implementing this feature would represent a significant step towards a more inclusive and accessible streaming experience for all.

We therefore ask streaming platforms to consider this request and work towards the introduction of multiple subtitles as an option for users.

Thank you for your attention and your commitment to ensuring a more inclusive streaming experience for all.

[Petition](https://chng.it/8KxWXbfb2D)

**Comment by muzuiget** [comment]
Off topic.
