### ISSUE TITLE
please support https://play.max.com

### ISSUE THREAD

**Issue by orchidraco** [muzuiget/dualsub-support#589]
website URL: https://play.max.com

before making this request, I quickly made sure that I was not repeating previous requests, and I was surprised not to have found any other proposal in this regard. It really surprises me that the extension does not support this domain, since it is one of the most used platforms

**Comment by muzuiget** [comment]
After a Google search, HBO has rebranded their streaming service again.

Dualsub used to support HBO Max, but dropped support after the service started using sliced subtitle files. Dualsub only supports standalone subtitle files.
