### ISSUE TITLE
建议设置可隐藏

### ISSUE THREAD

**Issue by siupangcheng** [muzuiget/dualsub-support#59]
![image](https://user-images.githubusercontent.com/14009345/79591657-65288880-810b-11ea-8161-72b9d99dcfa8.png)
建议红框区域设置可隐藏，影响了原本的界面，感觉怪怪的。

**Comment by muzuiget** [comment]
你可以用自定义样式，鼠标移动到工具栏所在的附近才显示：

```
#info .dualsub {
    display: none;
}
#info:hover .dualsub {
    display: block;
}
```

**Comment by siupangcheng** [comment]
> 你可以用自定义样式，鼠标移动到工具栏所在的附近才显示：
> 
> ```
> #info .dualsub {
>     display: none;
> }
> #info:hover .dualsub {
>     display: block;
> }
> ```

**Comment by siupangcheng** [comment]
感谢。完美解决。
