### ISSUE TITLE
Text selection

### ISSUE THREAD

**Issue by minostauros** [muzuiget/dualsub-support#592]
It would be great if there is an option to make the subtitle texts selectable so they can be copied.
It will be useful with macOS lookup function to find a word on dictionaries or Google.

**Comment by minostauros** [comment]
Found it in the settings :)

**Comment by muzuiget** [comment]
Yes, this is why Dualsub does not need to implement the dictionary function itself. As long as the subtitles can be selected like ordinary text, users can use any dictionary software, whether it is another browser extension or a desktop application.
