### ISSUE TITLE
Disney+ 字幕不同步问题 | Disney+ subtitles out of sync issue

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#593]
## 中文

在 Disney+ 上，可能出现 Dualsub 字幕和声音不同步的问题。因为播放器会随机插入出品工作室片头，造成播放器时间和字幕时间不一致，大约有 3 秒钟偏移。

这个随机插入片头的行为，目前很难通过程序判断并自动解决，需要用户手动操作解决。

解决方法：**把进度条拖回到最开始 `00:00` 的位置一次**，然后字幕就同步了，也可以正常跳转别的时间。

因为这个片头是不能通过拖动进度条来重新播放的，所以播放器会和原始视频时间的 `00:00` 重新同步。

### 隐藏这个提示信息

如果你已经阅读了这个帖子，可以到 **设置 > 通用 > 隐藏提示信息**，勾选 **dualsub-support#593** 单选框。

## English

On Disney+, there may be an issue with Dualsub subtitles and sound being out of sync. Because the player randomly inserts the production studio bumpers, the player time and subtitle time are inconsistent, with an offset of about 3 seconds.

This behavior of randomly inserting bumpers is currently difficult to judge and automatically solve through programs, and requires manual operation by the user.

Solution: **Drag the progress bar back to the initial position `00:00` once**, then the subtitles will be synchronized, and you can also jump to other times normally.

Because these bumpers cannot be re-played by dragging the progress bar, the player will be re-synchronized with `00:00` of the original video time.

### Hide this alert message

If you have read this post, you can go to **Settings > General > Hide Alert Messages**, check the **dualsub-support#593** checkbox.

**Comment by linminhtoo** [comment]
thanks for this
