### ISSUE TITLE
2.29.0版本似乎無法配合wildmonkey 改字型大小

### ISSUE THREAD

**Issue by gnafrgb** [muzuiget/dualsub-support#594]
Firefox 上更新2.29.0版後
無法根據wildmonkey那邊的設定的改變字幕大小
但顏色、陰影那些樣式測試後似乎還是有效的
wildmoney是0.17.1版
確定已經有設定always allow on netflix

PS.
因為有兩個add-on連動
我不太確定要報告到哪一邊
估計是新的dualsub字幕樣式更動的問題
先放這

**Comment by muzuiget** [comment]
贴一下你现在用的 CSS 代码。

**Comment by gnafrgb** [comment]
目前是這樣

.dualsub-renderer .subtitle-1 {
  color: rgb(255, 255, 0);
  font-size: 40px;
  background-color: transparent;
  padding: 6px;
  text-shadow: 2px 2px 2px rgba(0,0,0,1), -2px -2px 2px rgba(0,0,0,1), 2px -2px 2px rgba(0,0,0,1), -2px 2px 2px rgba(0,0,0,1);
}

.dualsub-renderer .subtitle-2 {
  color: rgb(255,255,255);
  font-size: 20px;
  background-color: transparent;
  text-shadow: 2px 2px 1px rgba(0,0,0,1);
}

**Comment by gnafrgb** [comment]
測試後不用加`!important`即可正確改變大小
感謝!

**Comment by gnafrgb** [comment]
發現另外一個可能的Bug
dualsub似乎不會儲存使用者在樣式方面的設定
比如底部邊距
每次重開都會恢復成100
描邊、陰影那些也是會重新啟用

**Comment by muzuiget** [comment]
不是 bug，这些设置已经从**扩展全局设置**改成**网站局部设置**，也就是每个网站各自保存不同的值。

所以在浏览器执行删除网站数据，会把这些设置也删除掉，所以会恢复默认。

**Comment by gnafrgb** [comment]
原來是這樣
那在Firefox上有辦法更改設定讓它不要刪除嗎?

**Comment by muzuiget** [comment]
不能的。

**Comment by muzuiget** [comment]
**删除网站数据**就是把这些网站的储存的数据删除，而不管这些数据是由网站代码写入还是扩展代码写入。
