### ISSUE TITLE
arc瀏覽器語言選項被遮擋

### ISSUE THREAD

**Issue by AW8712** [muzuiget/dualsub-support#597]
<img width="511" alt="螢幕擷取畫面 2024-05-01 235413" src="https://github.com/muzuiget/dualsub-support/assets/112561781/199cf04e-0637-4117-904a-c40c3f474dbe">

**Comment by muzuiget** [comment]
下拉菜单只是很普通的一个原生 HTML 标签 `<select>`，浏览器自己正确处理，例如在 Android 会显示为一个弹出列表。

这种魔改的浏览器的 bug 应该浏览器自己解决。

**Comment by AW8712** [comment]
了解 謝謝作者回覆
