### ISSUE TITLE
Subtitles is freezing on bilibili videos [microsoft edge]

### ISSUE THREAD

**Issue by matheusmdcg** [muzuiget/dualsub-support#598]
In Microsoft Edge, version 124 (didn't tried on others browsers yet), the extension is not working correctly.

My settings are:
![image](https://github.com/muzuiget/dualsub-support/assets/38542862/391a663a-f62c-4421-95ce-0b40b2b24ce6)
I set to get the bilibili machine translation at the top. And below to english machine translation

Sometimes both subtitles freezes, as you can see in the image below the video's own subtitle and the bilibili subtitle are synchronized, while the extension Chinese subtitle and the English subtitle are not (and the English subtitle is also in Chinese - I don't know why)
![image](https://github.com/muzuiget/dualsub-support/assets/38542862/4311288c-d653-43f0-a775-bdfc54401d84)

In this other video, the video subtitle, the bilibili machine translation subtitle, and the english machine translation are all synchronized. Only the extension chinese machine translation is not.
![image](https://github.com/muzuiget/dualsub-support/assets/38542862/4815cd72-13d7-4d0b-b0f5-fc0325f7d328)

**Comment by muzuiget** [comment]
Can you provide the bilibili video urls?

**Comment by matheusmdcg** [comment]
> Can you provide the bilibili video urls?

Sorry, I didn't save the links. But this was happening with any videos.
Now I tested it again after the update of the extension, and the update of the edge browser and It's working perfectly. 感谢你！

**Comment by matheusmdcg** [comment]
Sorry, I didn't save the links. But this was happening with any videos.
Now I tested it again after the update of the extension, and the update of the edge browser and It's working perfectly. 
感谢你！

**Comment by muzuiget** [comment]
I actually haven't updated any code regarding this issue.

This may be a problem with your local browser, such as network problems, conflicts with other extensions, etc.
