### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by cravinglove** [muzuiget/dualsub-support#60]
提个小建议：开发者可以将该插件添加到coursera网站，这样能够方便很多学习coursera的课程的同学

**Comment by muzuiget** [comment]
这个网站真有那么多人用吗？

**Comment by cravinglove** [comment]
如果开发者有时间和精力的话可以试试哈，只是提个建议。
该网站是海外最大的mooc平台，由斯坦福大学教授建立。

**Comment by muzuiget** [comment]
研究了一下，还是不打算支持了，几个原因：

* 网站地图混乱，翻了半天都找不到几个免费能测试的视频。
* 并非以视频为中心，好象就一篇博客文章里插个视频，网页结构都不一致，给分析带来麻烦。
* 用双语的多半是为了学习外语，那么娱乐和日常性质的视频网站更适合，这种专业学习网不适合，估计也没多少用户。

因此不打算支持了。
