### ISSUE TITLE
用YouTube原生模式出现了http 429 too many requests

### ISSUE THREAD

**Issue by touchfishguy** [muzuiget/dualsub-support#600]
这是是什么原因
标准模式可以正常使用
但原生模式不行

**Comment by muzuiget** [comment]
YouTube 服务器返回的错误，老问题了 https://github.com/muzuiget/dualsub-support/issues/426

最近的改动只是判断出这个错误，并作为字幕内容显示出来而已。

这就是为什么每次切换视频会重置字幕菜单，就是避免太过频繁请求字幕，尤其在漫无目的刷视频时。

关闭再打开字幕则会重新请求字幕文件重试，如果依旧出现 429，考虑更换一下代理，因为这个 IP 已经被降权限流了。

**Comment by touchfishguy** [comment]
搞定了 换了个节点
