### ISSUE TITLE
UI broken

### ISSUE THREAD

**Issue by Domper45** [muzuiget/dualsub-support#601]
New update broke the UI it seems to work on open pages that the translator would not want to access but on the actual sites example: Viki/iqiyi the subtitle part is broken, if the settings part of the ui is open when the extension is clicked it opens but putting it in subtitles breaks it again.

Screenshots:
![Képernyőkép – 2024-05-27 17-07-17](https://github.com/muzuiget/dualsub-support/assets/170959619/b7e784f6-2f38-470f-b03e-44463dbee725)
![Képernyőkép – 2024-05-27 17-07-31](https://github.com/muzuiget/dualsub-support/assets/170959619/23546083-055d-479b-97e5-329484508bad)
![Képernyőkép – 2024-05-27 17-07-39](https://github.com/muzuiget/dualsub-support/assets/170959619/d0d2a725-3ce9-4ac2-b58e-65656988f31e)
![Képernyőkép – 2024-05-27 17-07-46](https://github.com/muzuiget/dualsub-support/assets/170959619/c53a17f9-daa2-4227-b61f-dfd41a857122)
![Képernyőkép – 2024-05-27 17-07-56](https://github.com/muzuiget/dualsub-support/assets/170959619/25b9dbaa-a424-4e0d-91bf-614ab83ee90d)
![Képernyőkép – 2024-05-27 17-08-06](https://github.com/muzuiget/dualsub-support/assets/170959619/b85115fa-65e7-4246-bd4f-f4f2debaf482)

**Comment by muzuiget** [comment]
This is fixed in 2.39.2, re-install or update Dualsub from Chrome Store.

**Comment by Domper45** [comment]
Thanks for the fix! Confirmed working!
