### ISSUE TITLE
Wildmonkey Code for the New Extension

### ISSUE THREAD

**Issue by fragarray** [muzuiget/dualsub-support#602]
One of the most useful functions of the extension has long been removed, and the only way to customize and differentiate the subtitles individually is through the Wildmonkey extension.

Here is an example of code to add, compatible with the new version of the extension:

Type: Page Style

Code:

.dualsub-renderer .dualsub-subtitle:nth-child(odd) { 
          font-size: 120%;
}

.dualsub-renderer .dualsub-subtitle:nth-child(even) { 
          font-size: 120%; 
          color: #FFAA00; 
}

**Comment by muzuiget** [comment]
This is not an issues?
