### ISSUE TITLE
iOS Orion 無法正常使用插件

### ISSUE THREAD

**Issue by fantasy1330** [muzuiget/dualsub-support#604]
照教學步驟安裝無法正常開啟
![1F97DA1B-FD34-49D1-8D60-7C43362FCB56](https://github.com/muzuiget/dualsub-support/assets/69185659/9df7b6c3-ad19-449b-b03c-e518b540317d)

**Comment by muzuiget** [comment]
试过重启 Orion 吗？确定是 Orion 和 Dualsub 都是最新版，看一下 #585。

**Comment by fantasy1330** [comment]
確定都是最新版
但我的iOS 版本是16.2
不知道有沒有可能是iOS 版本太久的問題

**Comment by muzuiget** [comment]
我测试可以在 iOS 16.7.8 上正常运行。

**Comment by fantasy1330** [comment]
更新到iOS17.5已可正常使用 
另外想請教如何全屏使用還是有字幕 感謝

**Comment by muzuiget** [comment]
我没有能升级到 iOS 17 的 iPhone，所以无法测试。

Safari 17.2 beta 就有更新日志说支持 Fullscreen API 的：

https://x.com/jensimmons/status/1717937227190460797

难道最新版本还不行？

**Comment by muzuiget** [comment]
https://developer.apple.com/documentation/safari-release-notes/safari-17_2-release-notes

最近几个正式版的更新日志都没有 Fullscreen API 的记录，看来是悄悄删掉了。

从[苹果开发者论坛](https://developer.apple.com/forums/thread/133248)的最后几个帖子看，估计 bug 太多又悄悄删掉这个功能了。

**Comment by fantasy1330** [comment]
好的感謝！
