### ISSUE TITLE
想了解一下繁體中文介面的原因, 以及現在不會再保留字幕的語言設定？

### ISSUE THREAD

**Issue by yhinz** [muzuiget/dualsub-support#606]
想了解一下繁體中文介面的原因, 以及現在不會再保留字幕的語言設定？ 因為以前不用每一條片都設置字幕的語言. 謝謝

**Comment by muzuiget** [comment]
> 想了解一下繁體中文介面的原因

不想维护繁体中文而已，对于结构化的文本可以通过程序转换，对于文档这些非结构化文本就很麻烦，所以删除掉。

> 以及現在不會再保留字幕的語言設定？ 因為以前不用每一條片都設置字幕的語言

这个改动已经很久了。

只有在 YouTube 上会重置，原因是 #426
