### ISSUE TITLE
可以增加下对可汗学院的支持吗，还有语言选项能否保存配置，每次切视频都要重选

### ISSUE THREAD

**Issue by screamff** [muzuiget/dualsub-support#609]
用的是edge浏览器

**Comment by screamff** [comment]
可汗学院地址：www.khanacademy.org

**Comment by muzuiget** [comment]
可汗学院的视频打开到 YouTube 独立标签页观看就好。

字幕菜单自动选择问题见 https://github.com/muzuiget/dualsub-support/issues/585#issuecomment-2094563454
