### ISSUE TITLE
想问下翻译成中文字幕的原理机制

### ISSUE THREAD

**Issue by pendave** [muzuiget/dualsub-support#61]
Hi，我自己喜欢在本地用 Python 脚本来翻译 .srt 字幕，效果就是时间轴不变，一段英文对应一段中文，就像 Subtitle Edit 翻译的那样。

看到你们翻译出来的字幕，是不是有什么规律？一长句中文对应2段英文时间轴，这种我要用 Python 实现的话，应该做哪些操作？

![image](https://user-images.githubusercontent.com/1331881/80815009-7c816e80-8bff-11ea-8b2e-93023196a67c.png)

**Comment by muzuiget** [comment]
那是 YouTube 自带的翻译，也就是调用 YouTube 的 API，把原文语言和翻译语言传递过去，YouTube 自己就返回翻译字幕文件。

你所说的这个效果，其实 YouTube 也是两个月前才实现的，之前一样也是一行原文一行翻译。
