### ISSUE TITLE
subtitle recognition broken

### ISSUE THREAD

**Issue by Domper45** [muzuiget/dualsub-support#613]
On all the websites I have checked subtitle recognition by the extension is broken therefore it wont translate.

![screen](https://github.com/user-attachments/assets/fa8c9cde-d0f6-4e43-a949-5e265a6eb486)

**Comment by chu-siang** [comment]
yeah, it's not working now.

**Comment by muzuiget** [comment]
There is a bug in 2.46.0, please update to 2.46.1. The version 2.46.1 has already passed the Chrome Store review.
