### ISSUE TITLE
如何购买API KEY

### ISSUE THREAD

**Issue by foolstack-omg** [muzuiget/dualsub-support#614]
如何购买API KEY

**Comment by muzuiget** [comment]
b4a303e8-d1a9-40d8-94e4-88a972417b13

0x0 ***@***.***> 于2024年8月21日周三 15:15写道：

**Comment by muzuiget** [comment]
正在改造计费系统，因为不想维护两套方案，暂时不开放购买，这段时间发送测试用的 key。

**Comment by muzuiget** [comment]
你发一封邮件到 `dualsubstudio@gmail.com` ，我给你发送一个 key。

**Comment by Danie1Lo** [comment]
> 你发一封邮件到 `dualsubstudio@gmail.com` ，我给你发送一个 key。

I sent you an Email,please Send me the Api Key.
