### ISSUE TITLE
BiliBili dual sub issue

### ISSUE THREAD

**Issue by jaosncijdsaa** [muzuiget/dualsub-support#615]
Hi i been using dual sub for a while usually for Iqiyi and youtube. I checked the web the exension should also work in bilibili but i tried everthing i doesnt work. Usually i just change the subtitile file to english and chinese and the sub pops out, it never shows on bili bili, also test the api key and everthing, is there any special reason? please enlighten me

<img width="1440" alt="Screenshot 2024-09-07 at 08 07 10" src="https://github.com/user-attachments/assets/88b67956-9c31-4995-8475-336e2e3ea710">

**Comment by muzuiget** [comment]
The video should has a text-base subtitle file, like this:

![Screenshot_20240914_151605](https://github.com/user-attachments/assets/1c8b40ca-42c9-4a41-9546-69ec5bbef9ec)
