### ISSUE TITLE
开启翻译失败：{ JSON.parse: unexpected end of data at line 1 column 1 of the JSON data }

### ISSUE THREAD

**Issue by jindongjie** [muzuiget/dualsub-support#616]
最近这段时间 Youtube 网站的字幕翻译失效了，开启后就是报错：{ JSON.parse: unexpected end of data at line 1 column 1 of the JSON data }

![图片](https://github.com/user-attachments/assets/892f770a-f3ca-4e9f-81a0-dedf7315d773)

**Comment by jindongjie** [comment]
浏览器版本： FireFox Developer Edition 131.0b6 插件是最新版的

**Comment by muzuiget** [comment]
这是原生模式？

https://github.com/muzuiget/dualsub-support/issues/585#issuecomment-2094563454

**Comment by jindongjie** [comment]
> 这是原生模式？
> 
> [#585 (comment)](https://github.com/muzuiget/dualsub-support/issues/585#issuecomment-2094563454)

两个模式都不行

**Comment by muzuiget** [comment]
两个模式都失败，说明下载不了原文字幕，就是 YouTube 限制你的 IP https://github.com/muzuiget/dualsub-support/issues/426

**Comment by jindongjie** [comment]
> 两个模式都失败，说明下载不了原文字幕，就是 YouTube 限制你的 IP #426

明白了，我用家里的网络就没问题
