### ISSUE TITLE
Hebrew Translation Empty

### ISSUE THREAD

**Issue by idanrm** [muzuiget/dualsub-support#618]
Hello,

When I choose Native Mode and select translation in Hebrew, the text in Hebrew does not show (it's as if I just selected one subtitle, the one that is not Hebrew, it is the only one that appears on the screen).

Could you please look into it?

Thanks,
Idan

**Comment by muzuiget** [comment]
You should also test other languages, and other videos, it's unlikely to be a problem with one language.

**Comment by idanrm** [comment]
I tested it with about 10 other languages, all of them work correctly. Only when I choose Hebrew, it does not show any subtitles (unless I choose one additional subtitle in a different language, then it shows only the different language).
I have tested it in many videos, all of them show the same without exception.

**Comment by muzuiget** [comment]
Can you post a video url, and the Dualsub menu screenshot?
