### ISSUE TITLE
Subtitle line break display issue on Netflix

### ISSUE THREAD

**Issue by Heterosis** [muzuiget/dualsub-support#619]
![image](https://github.com/user-attachments/assets/cfcf31c3-276a-4710-96e4-5d962dc77eeb)

回報目前在 Netflix 上會出現的一個問題，這種單句英文字幕中出現換行的情況下，由插件顯示出來的字幕會只出現原生字幕中的第一行文字。

Reporting an issue here. When a single-line English subtitle appears with a line break on Netflix, the extension only displays the first line of the original subtitle.

**Comment by muzuiget** [comment]
我猜想是因为带有位置信息的字幕，它们的时间轴重叠。你试下选择另一个英语字幕，不要带 `CC` 那种。
