### ISSUE TITLE
unusable of settings panel 1.0.0 Chrome store version 

### ISSUE THREAD

**Issue by cccvvv2012** [muzuiget/dualsub-support#62]
The latest version 1.0.0 on Chrome store has bad/unusable setting panel and cannot load/save sub settings as previously

**Comment by muzuiget** [comment]
You need to open setting from Chrome toolbar icon. New version setting not compatible with previous.

**Comment by cccvvv2012** [comment]
Could you please update setting related documents in offical site to show latest version change, actually I currently restored old version.

**Comment by muzuiget** [comment]
Document updated.
