### ISSUE TITLE
Disney+ subtitle not showing in full screen mode

### ISSUE THREAD

**Issue by jelly3360** [muzuiget/dualsub-support#620]
在Disney+上，字幕在非全螢幕模式時能正常顯示，但轉換到全螢幕模式時則不能顯示。
![WhatsApp Image 2024-09-30 at 12 43 28 AM](https://github.com/user-attachments/assets/99c264f8-5075-45b8-92d8-c9e7d20d4a34)
![WhatsApp Image 2024-09-30 at 12 43 45 AM](https://github.com/user-attachments/assets/99e9ad5f-23d4-42f0-8add-1be1d4471ad8)

**Comment by skylover007** [comment]
我也是同样的问题，在chrome和edge都一样，有解决方法吗？

**Comment by Girotio** [comment]
一样问题

**Comment by nogomin** [comment]
why? please fix ASAP

**Comment by littletete23** [comment]
same problem

**Comment by muzuiget** [comment]
理论上，按 <kbd>F11</kbd> 键那种全屏可以凑合一下。

如果要彻底修复这个问题，需要一个账号来测试。

[之前说过了](https://github.com/muzuiget/dualsub-support/issues/599)：

> 所以这两个网站作为免费功能提供，但是出问题不一定会及时修复，也不会保证每个版本的兼容性。

如果有人愿意短期共享一个账号来测试，请发送到邮箱 `muzuiget@gmail.com`。

**Comment by muzuiget** [comment]
版本 2.47.1 已发布。
