### ISSUE TITLE
Wildmonkey無法改變字幕樣式

### ISSUE THREAD

**Issue by 4popguys** [muzuiget/dualsub-support#624]
HI，最近發現Wildmonkey無法改變Netflix字幕樣式，是不是要付費版，還是我的 CSS錯了，謝謝。

.dualsub-renderer .dualsub-subtitle:nth-child(1) {
    font-size: 45px; -webkit-text-stroke-width: 0px; text-shadow: black 0.1em 0.1em 0.3em; font-weight: bold; font-family: Segoe UI;
}

.dualsub-renderer .dualsub-subtitle:nth-child(2)  {
    font-size: 25px; -webkit-text-stroke-width: 0px; text-shadow: black 0.1em 0.1em 0.3em; font-weight: bold; font-family: Segoe UI;
}

**Comment by muzuiget** [comment]
我格式化了你的 CSS 代码，看上去似乎格式正确。

```
.dualsub-renderer .dualsub-subtitle:nth-child(1) {
    font-size: 45px;
    -webkit-text-stroke-width: 0px;
    text-shadow: black 0.1em 0.1em 0.3em;
    font-weight: bold;
    font-family: Segoe UI;
}

.dualsub-renderer .dualsub-subtitle:nth-child(2) {
    font-size: 25px;
    -webkit-text-stroke-width: 0px;
    text-shadow: black 0.1em 0.1em 0.3em;
    font-weight: bold;
    font-family: Segoe UI;
}
```

不知道你在 Wildmonkey 的其它字段怎么填的，最好截一下图。

**Comment by 4popguys** [comment]
截圖如下

![image](https://github.com/user-attachments/assets/1856f5c4-926f-42d1-a931-2eb784af97f9)
![image](https://github.com/user-attachments/assets/8b6dca36-ef23-4282-a9ce-be7c83ed573f)

**Comment by muzuiget** [comment]
应该是这个原因 https://github.com/muzuiget/dualsub-support/issues/623
