### ISSUE TITLE
希望有命令能手动调试识别的字幕

### ISSUE THREAD

**Issue by NingJay** [muzuiget/dualsub-support#629]
我在YouTube上看视频时, 有时候会出现视频YouTube视频字幕识别的语种不一样的情况, 在之前的版本是默认可以识别英语. 但现在的判断逻辑是优先基于YouTube自动生成字幕选择识别. 在没有字幕的时候才加入英文选项, 我希望这类问题能够手动纠正就好了

示例视频:https://www.youtube.com/watch?v=EuA8Q_BYdQA&list=PL05umP7R6ij1a6KdEy8PVE9zoCv6SlHRS&index=2

这个视频应该为英语, 但YouTube将其识别为了德语导致了问题

**Comment by muzuiget** [comment]
在最新版相关功能已经删掉了。
