### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 1031918137** [muzuiget/dualsub-support#63]
打开后无法使用 看不到调整页面

**Comment by muzuiget** [comment]
什么是调整页面？

**Comment by 1031918137** [comment]
就是用不了  没有下面那个东西了  看不到语言的设置了

在 2020年5月9日星期六，muzuiget <notifications@github.com> 写道：

**Comment by muzuiget** [comment]
新版的在侧边栏呀，难道你用过什么扩展隐藏了吗？

**Comment by 1031918137** [comment]
好吧 我再试试


muzuiget <notifications@github.com> 于2020年5月9日周六 下午7:38写道：

**Comment by muzuiget** [comment]
这个问题解决了吗？
