### ISSUE TITLE
1

### ISSUE THREAD

**Issue by BruceVL** [muzuiget/dualsub-support#631]
英语（自动生成）+无法使用

**Comment by muzuiget** [comment]
已在 2.48.0 修复，等待商店审核。

**Comment by TharinWONG** [comment]
作者能提供手動安裝版本嗎。Ggogle 或 firefox

**Comment by muzuiget** [comment]
Chrome 一直都可以用 .xpi 文件，其实就是 .zip 文件。

https://addons.mozilla.org/en-US/firefox/addon/dualsub/versions/
