### ISSUE TITLE
Netflix 上选择第二字幕为 英语cc 时，英文字幕显示不全 

### ISSUE THREAD

**Issue by ElioxElio** [muzuiget/dualsub-support#632]
如果一个句子比较长，通常只显示前半段。总是如此。非常常见。 请帮忙看看这个问题，谢谢

**Comment by muzuiget** [comment]
见 https://github.com/muzuiget/dualsub-support/issues/619

**Comment by muzuiget** [comment]
2.49.0 版本不再支持 Netflix。

原因见 https://github.com/muzuiget/dualsub-support/issues/599
