### ISSUE TITLE
删除中文拼音和日语假名功能 | Remove Chinese Pinyin and Japanese Kana features. 

### ISSUE THREAD

**Issue by muzuiget** [muzuiget/dualsub-support#636]
这两个功能依赖我们的服务器，将在后续版本删除。

如果你有 API key，在 2.52.0 里仍然可以使用一段时间。**这不是变为收费功能，不要为此功能购买 API key**。

在大语言模型时代，这两个功能没有必要了，只需要在 **样式 > 文本选择** 设置为 **启用**，这样就可以配合任意词典工具使用（甚至可以是桌面工具），用鼠标选择一下文本，可以获得该字幕的更详细解释，不仅仅是注音。

---

These two features rely on our servers and will be discontinued in future versions.

If you have an API key, you can still use these features temporarily in version 2.52.0. **This is not a paid feature, so please do not purchase an API key for this purpose**.

In the era of large language models, these features are no longer necessary. Simply go to **Styles > Text Selectable** and set it to **Enable**. This allows you to use any dictionary tool (including desktop tools). By selecting text with your mouse, you can obtain a more detailed explanation of the subtitles, not just phonetic annotations.

**Comment by BennyWang1007** [comment]
Hi,
    As a Japanese learner, I found this feature incredibly helpful. Subtitles with hiragana annotations allow learners like me to instantly connect the pronunciation to the audio, significantly improving the learning experience.
    I understand the reasoning behind removing server-dependent features. However, this change does present a challenge since the source code is neither open-sourced nor modifiable, and also obfuscated.
    That said, I’ve come across some JavaScript-only libraries and solutions that can handle this kind of functionality locally. Perhaps, in the future, this feature could be reintroduced in a way that doesn’t rely on your servers, thus alleviating resource concerns while still supporting users who found it valuable.

Best regards,

**Comment by muzuiget** [comment]
The furigana dictionary is quite large, even after compression it is still several dozen MB, while Dualsub is less than 50KB, so it is inefficient to implement it locally in the browser.

At the same time, Dualsub no longer needs to handle phonetic related functions, which can simplify a lot of code.

**Comment by yhinz** [comment]
日語假名功能其實很有用, 歌詞那些不用每一次都去查翻譯, 當初使用這個插件的其中一個原因就是為了這個功能
