### ISSUE TITLE
新版的字体渲染样式太过单一

### ISSUE THREAD

**Issue by i6henl** [muzuiget/dualsub-support#68]
通用--字体渲染，字体原本是白色，描边效果不是很好，取消掉描边，在视频背景很亮的时候，字体就看不清楚了。

建议可以像主题样式里的组件样式设置那样设置字体渲染，希望可以设置字体颜色，描边和背景颜色、透明度什么的...

辛苦了，谢谢！！！

**Comment by muzuiget** [comment]
我是反而觉得默认描边挺好，如果你不喜欢，可以在设置里，“通用”，“基础样式”改成“无”，然后在“主题样式”里从头定义一个样式。

因为 Chrome 不支持原生描边，用了个曲线救国实现，“主题样式”里的“字体边缘效果”无法覆盖自带描边，所以提供一个选项。
