### ISSUE TITLE
新版本不知道如何设置

### ISSUE THREAD

**Issue by SpoonerCake** [muzuiget/dualsub-support#69]
之前的版本设置了上面英文下面中文的两行字幕，更新后暂时没找到这样设置的地方，好像很多地方都变了

**Comment by muzuiget** [comment]
Chrome 右上角工具栏图标。

**Comment by qin9125** [comment]
> Chrome右上角工具栏图标。

选项找到了，但是具体怎么设置呢？好像没作用。。。

**Comment by qin9125** [comment]
> Chrome右上角工具栏图标。

![image](https://user-images.githubusercontent.com/32502941/81473474-642dd700-9231-11ea-9be3-650326cc3b00.png)
设置呢？我找到的选项就是这样

**Comment by qin9125** [comment]
> Chrome右上角工具栏图标。

找不到设置鸭，就是这样的
![image](https://user-images.githubusercontent.com/32502941/81473535-bcfd6f80-9231-11ea-87b9-caddb586416b.png)

**Comment by SpoonerCake** [comment]
> Chrome 右上角工具栏图标。

这个我知道，就是设置里面没有可以添加两行代码的地方了，另外我发现一个bug，在网易云音乐的界面插件也会开启
![QQ截图20200509213207](https://user-images.githubusercontent.com/49234232/81475135-d526bc00-923c-11ea-804c-8121e28a5329.png)

**Comment by qin9125** [comment]
> > Chrome 右上角工具栏图标。
> 
> 这个我知道，就是设置里面没有可以添加两行代码的地方了，另外我发现一个bug，在网易云音乐的界面插件也会开启
> ![QQ截图20200509213207](https://user-images.githubusercontent.com/49234232/81475135-d526bc00-923c-11ea-804c-8121e28a5329.png)

插件怎么开启？为什么我的不起作用呢？求助

**Comment by SpoonerCake** [comment]
> Chrome 右上角工具栏图标。

请问现版本第二行优先选择字幕怎么开启
![QQ截图20200509220530](https://user-images.githubusercontent.com/49234232/81475867-4a948b80-9241-11ea-96f4-eead7b1a74fe.png)

**Comment by muzuiget** [comment]
文档可以先看 https://netsub.netlify.app/ 的，大同小异，https://dualsub.netlify.app/ 还是旧版的。

难道你们都看不到 YouTube 侧边栏的菜单吗？

![Screenshot_20200509_225522](https://user-images.githubusercontent.com/330812/81477071-3dc76600-9248-11ea-883c-8794111fcaea.png)

**Comment by muzuiget** [comment]
> > > Chrome 右上角工具栏图标。
> > 
> > 
> > 这个我知道，就是设置里面没有可以添加两行代码的地方了，另外我发现一个bug，在网易云音乐的界面插件也会开启
> > ![QQ截图20200509213207](https://user-images.githubusercontent.com/49234232/81475135-d526bc00-923c-11ea-804c-8121e28a5329.png)
> 
> 插件怎么开启？为什么我的不起作用呢？求助

网易云音乐哪个页面？因为网易云音乐总是固定在下方有个播放控制栏，所以扩展没限制在歌曲页面，这样在方便搜索页面也能显示。当然有些特殊地址要排除一下。
