### ISSUE TITLE
单个视频设置完之后没法推广到每个视频

### ISSUE THREAD

**Issue by zrwd01** [muzuiget/dualsub-support#70]
单个视频设置完之后没法推广到每个视频，每次都是关闭，需要手动更改。
![1212](https://user-images.githubusercontent.com/33946060/81468272-1012fa80-9211-11ea-942a-42181a291896.jpg)
![1313](https://user-images.githubusercontent.com/33946060/81468282-1bfebc80-9211-11ea-855e-10ec602b088b.jpg)

**Comment by muzuiget** [comment]
下一个版本会加进这个功能，主要是现在考虑通用性，支持了几个网站了。每个网站，甚至 YouTube 自己都一种语言都有好几个版本。

例如简体中文有，`zh-cn`, `zh-hans`, `zh`, `zh.cc` 几种组合，英文也是，例如 `en`, `en.cc`，多个版本要自动选择，现在甚至超过2个字幕，怎么自动选择比较好还没想清楚，你可以提出下意见。

**Comment by qin9125** [comment]
> 单个视频设置完之后没法推广到每个视频，每次都是关闭，需要手动更改。
> ![1212](https://user-images.githubusercontent.com/33946060/81468272-1012fa80-9211-11ea-942a-42181a291896.jpg)
> ![1313](https://user-images.githubusercontent.com/33946060/81468282-1bfebc80-9211-11ea-855e-10ec602b088b.jpg)

图片中的菜单你是怎么弄出来的，我没有。。。。真的是

**Comment by zrwd01** [comment]
> > 单个视频设置完之后没法推广到每个视频，每次都是关闭，需要手动更改。
> > ![1212](https://user-images.githubusercontent.com/33946060/81468272-1012fa80-9211-11ea-942a-42181a291896.jpg)
> > ![1313](https://user-images.githubusercontent.com/33946060/81468282-1bfebc80-9211-11ea-855e-10ec602b088b.jpg)
> 
> 图片中的菜单你是怎么弄出来的，我没有。。。。真的是

直接出现在视频右侧上放的位置

**Comment by zrwd01** [comment]
> 下一个版本会加进这个功能，主要是现在考虑通用性，支持了几个网站了。每个网站，甚至 YouTube 自己都一种语言都有好几个版本。
> 
> 例如简体中文有，`zh-cn`, `zh-hans`, `zh`, `zh.cc` 几种组合，英文也是，例如 `en`, `en.cc`，多个版本要自动选择，现在甚至超过2个字幕，怎么自动选择比较好还没想清楚，你可以提出下意见。

能不能做个判断语句，最优先的是某个自定义语言（例如）我现在这样就只显示第二语言栏里的中文，效果挺好的
![12](https://user-images.githubusercontent.com/33946060/81480834-d10b9600-925e-11ea-82d9-36c202783009.jpg)
![81468272-1012fa80-9211-11ea-942a-42181a291896](https://user-images.githubusercontent.com/33946060/81480847-dbc62b00-925e-11ea-8893-c18512a42d6d.jpg)

**Comment by zrwd01** [comment]
![122](https://user-images.githubusercontent.com/33946060/81480929-5000ce80-925f-11ea-82a4-d1a11df9969c.jpg)
这样甚至都不用youtube自己的字幕选项

**Comment by qin9125** [comment]
> ![122](https://user-images.githubusercontent.com/33946060/81480929-5000ce80-925f-11ea-82a4-d1a11df9969c.jpg)
> 这样甚至都不用youtube自己的字幕选项

怎么做到的只有三行选项？

**Comment by zrwd01** [comment]
> > ![122](https://user-images.githubusercontent.com/33946060/81480929-5000ce80-925f-11ea-82a4-d1a11df9969c.jpg)
> > 这样甚至都不用youtube自己的字幕选项
> 
> 怎么做到的只有三行选项？

![1](https://user-images.githubusercontent.com/33946060/81666198-4ef4ba80-9474-11ea-9176-955fe94fad1c.jpg)
字幕数量设为1

**Comment by muzuiget** [comment]
v1.3.0 已经支持记住上次选择。
