### ISSUE TITLE
新版本怎样设置？

### ISSUE THREAD

**Issue by qin9125** [muzuiget/dualsub-support#71]
您好，新版是从这里设置吗？毫无头绪，这里设置什么才起作用？
![image](https://user-images.githubusercontent.com/32502941/81473653-8116da00-9232-11ea-9822-5e7883746d97.png)

**Comment by muzuiget** [comment]
你要设置什么功能？语言菜单在 YouTube 视频页的侧边栏。

**Comment by qin9125** [comment]
> 你要设置什么功能？语言菜单在 YouTube 视频页的侧边栏。

有bug吧，第一次播放视频右上角并不显示工具翻译条目，要重新刷新一下播放页面才能出现，我说我找了半天设置，怎么没看到翻译选项，而且一旦关闭YouTube页面，重新打开再播放翻译条目依旧消失，必须重新刷新页面才能出现，这个体验不好，

**Comment by qin9125** [comment]
> 你要设置什么功能？语言菜单在 YouTube 视频页的侧边栏。

每次新打开YouTube这个必然消失，播放时工具栏必须重新刷新一遍才显示，你不关闭YouTube去播放其他不会消失工具栏，关闭重新打开就会消失，必须播放视频再刷新一遍才显示，
![image](https://user-images.githubusercontent.com/32502941/81488950-814ebe00-92a2-11ea-8b8e-3a22ba638aad.png)

**Comment by muzuiget** [comment]
本来就是自动显示的，你有装过什么 YouTube 之类的扩展吗？你可以开个隐身模式单独运行 Dualsub 试下。

**Comment by qin9125** [comment]
> 本来就是自动显示的，你有装过什么 YouTube 之类的扩展吗？你可以开个隐身模式单独运行 Dualsub 试下。

这是我装的插件，我关闭了跟YouTube的插件，依旧在播放视频界面不出现翻译条目，必须在刷新一遍，不知道咋回事，旧版的Dualsub以前不会这样
![image](https://user-images.githubusercontent.com/32502941/81496045-4753db00-92e7-11ea-957a-b6d65029f3b4.png)

**Comment by muzuiget** [comment]
不能先把其它扩展禁用再测吗？我怀疑是 Adblock，会不会因为放在侧边栏，被当成广告位隐藏掉呢？

**Comment by qin9125** [comment]
> 不能先把其它扩展禁用再测吗？我怀疑是 Adblock，会不会因为放在侧边栏，被当成广告位隐藏掉呢？

Adblock禁了，没用，如果当成广告，不可能第二遍刷新就可以显示了

**Comment by muzuiget** [comment]
难道是 MacOS 的问题吗？你的 Chrome 是什么版本？用最新版总是最兼容的。

**Comment by muzuiget** [comment]
我看你截图还有个 Magic Action For YouTube 呀，没禁用再测试？

或者你更新到 `v1.1.0`，在设置页面 -> 网站 -> YouTube，工具栏位置切换为“标题栏”，然后刷新看看。

**Comment by qin9125** [comment]
> 我看你截图还有个 Magic Action For YouTube 呀，没禁用再测试？
> 
> 或者你更新到 `v1.1.0`，在设置页面 -> 网站 -> YouTube，工具栏位置切换为“标题栏”，然后刷新看看。

我的macos Chrome版本是版本 81.0.4044.138（正式版本） （64 位） 已经更新1.1.0 设置为侧边栏时优先工具条位置还是显示到标题栏下面刷新一遍恢复正常，设置为标题栏一直正常了不用刷新，就是有点丑，太长了，你看看
![image](https://user-images.githubusercontent.com/32502941/81533770-5b581500-9399-11ea-8820-1ca181840dd5.png)
![image](https://user-images.githubusercontent.com/32502941/81533787-6448e680-9399-11ea-8ea6-cd77720adfdc.png)

**Comment by muzuiget** [comment]
侧边栏那个有点奇怪，我再想想原因。如果放到标题栏，你可以换成“堆叠”布局，就像 0.x 版本一样。

现在工具栏的组件为了所有支持网站通用所以做成这样，以后或者会给 YouTube 专门定制一个。

**Comment by qin9125** [comment]
> 侧边栏那个有点奇怪，我再想想原因。如果放到标题栏，你可以换成“堆叠”布局，就像 0.x 版本一样。
> 
> 现在工具栏的组件为了所有支持网站通用所以做成这样，以后或者会给 YouTube 专门定制一个。

奇怪的原因是因为广告拦截让它外观有变化，但是长度没变，标题栏堆叠也不是很美观，太宽了，不协调，谢谢你的插件
