### ISSUE TITLE
新版本无法设置”字幕可选中“

### ISSUE THREAD

**Issue by DesertAc** [muzuiget/dualsub-support#72]
“字幕样式”在小窗口下很大，并不会随窗口改变而改变。
个人觉得还是上一个版本好用。
Netflix 功能与其他扩展冲突，希望能提供可关闭的按钮。
谢谢！

**Comment by DesertAc** [comment]
如图，Netflix 字幕菜单自动无法关闭，影响观看视频。
![Image](https://user-images.githubusercontent.com/43565419/81489365-15228900-92a7-11ea-9b1b-9a478eec62f0.png)

**Comment by muzuiget** [comment]
“字幕可选中”可选中以后版本才加回来。

字体大小不随画面缩放，是有意这样做的，因为设置里用了各种属性都用了像素单位，缩放过后反而很奇怪。如果你多数在小窗口播放，可以定义一个新的主题样式。

可否告知和哪个 Netflix 扩展冲突？你可以用 Chrome 自带的扩展权限功能禁用，进入 Dualsub 扩展的详情页，把不想运行的网站权限关掉就行。

**Comment by DesertAc** [comment]
好的，谢谢。

原以为会与”NflxMultiSubs (Netflix Multi. Subtitles)“ 这个扩展冲突，从而导致它无法选择第二字幕，经禁用扩展测试发现，可能是该扩展自己的问题。

”字幕可选中“该功能很好用，期待作者能尽快更新!
辛苦了，谢谢！

**Comment by muzuiget** [comment]
在 v1.8.0 已实现，在 “设置” -> "快捷键“ -> "鼠标行为” 切换为 “文本选择” 即可，仍然可以按住 <kbd>Alt</kbd> 来移动字幕位置。
