### ISSUE TITLE
在手机浏览器上无法显示字幕菜单

### ISSUE THREAD

**Issue by huLter** [muzuiget/dualsub-support#73]
我在kiwi browser 上安装后，字幕菜单无法显示
不知道是YouTube针对小屏幕有特定的网页布局

**Comment by muzuiget** [comment]
一直没测试在手机浏览器，旧版本的能用？

如果用桌面版 Chrome 模拟手机浏览，或被强制重定向到 `m.youtube.com`  不知道真手机上是不是，如果是，我就可以直接在电脑上做兼容了。

**Comment by huLter** [comment]
1.旧版本可用
2.是桌面版网站，不是m开头的
3.pc上用开发者工具修改分辨率可以复现问题

**Comment by muzuiget** [comment]
哦，大概是窗口宽度太小，侧边栏被挤到屏蔽下方了。

**Comment by muzuiget** [comment]
在 v1.1.0 版本解决掉这个问题。
