### ISSUE TITLE
关于Dualsub 1.1.1的几个建议

### ISSUE THREAD

**Issue by weirhjaklweh** [muzuiget/dualsub-support#74]
首先，非常感谢作者开发这个插件，非常好用，已经用了很久。
我几乎每天都要看很多的youtube的一些教程或是有点专业的东西，主要是英语的，英语的自动字幕比较准，机器翻译比较糙，所以希望能够双语对照理解，这个插件很好的解决了我的问题。

提几个建议：
1、字幕显示问题，有些符号显示不正常，比如
https://youtu.be/GE7QA1chUzw?t=207
会将'这个字符显示为&#39;，但是系统生成的字幕没有问题
2、视频播放页的字幕设置，希望可以永久保存

**Comment by muzuiget** [comment]
> 会将'这个字符显示为'

没看懂，是不是你发帖内容也被转义？你可以用反引号包括起来，例如 `'`。

**Comment by weirhjaklweh** [comment]
> > 会将'这个字符显示为'
> 
> 没看懂，是不是你发帖内容也被转义？你可以用反引号包括起来，例如 `'`。

`会将'这个字符显示为&#39;`
具体可以看下上面那个视频的3:29，开打字幕就能看到，有很多视频都有这种情况

**Comment by muzuiget** [comment]
我明白了，是 `&#39`。

**Comment by muzuiget** [comment]
原因找到了，一条对白只转义了一次单引号，应该全部都转义。

发了个 v1.1.2 版本，修复了。

**Comment by weirhjaklweh** [comment]
> 原因找到了，一条对白只转义了一次单引号，应该全部都转义。
> 
> 发了个 v1.1.2 版本，修复了。

点个赞，单引号正常了

**Comment by muzuiget** [comment]
v1.3.0 支持记住上次使用的语言。
