### ISSUE TITLE
延迟

### ISSUE THREAD

**Issue by songyp0505** [muzuiget/dualsub-support#76]
怎么感觉新版本字幕的延迟好高呀

**Comment by muzuiget** [comment]
你是指字幕菜单出现的时间吗？

**Comment by songyp0505** [comment]
刚才仔细试了一下，感觉区别是：
当出现一句很长的英文的时候
旧版本是先把这句英文的中文先显示完整，再不停的跳英文字幕，基本能跟说话人的语速重合
新版本是先把这句英文的中文先显示完整，再一段一段的跳英文字幕，英文字幕延迟在一句话

**Comment by muzuiget** [comment]
是自动字幕吗？能不能发个测试地址。

**Comment by muzuiget** [comment]
可以确定在自动字幕上重现。

**Comment by muzuiget** [comment]
延迟问题在 v1.1.3 解决了。

**Comment by songyp0505** [comment]
谢谢！
