### ISSUE TITLE
1. 为何字幕有延迟，怎样解决呢？2. 字幕大小是否能根据视频窗口大小自动更改呢

### ISSUE THREAD

**Issue by Birdling** [muzuiget/dualsub-support#77]
对于2. 当设置字体大小时，小窗口看的可以，可是浏览视频一会儿后觉得这个视频不错我打算继续看下去，于是我打开了大屏，结果那个字幕却很小还要去调一调字幕大小，这样就很麻烦了，所以希望这里可以稍稍改进一下~

**Comment by muzuiget** [comment]
延迟问题在 v1.1.3 解决了。
