### ISSUE TITLE
一个小建议！

### ISSUE THREAD

**Issue by 1809693385** [muzuiget/dualsub-support#78]
希望大佬后续能添加更多的网站支持，比如HBO、Hulu之类的。。。

**Comment by muzuiget** [comment]
这两个都分析过了。

Hulu 而且只服务北美地区，大多视频都只有英语字幕一种，不过现在有机翻功能，这些都不是事。最大问题是字幕内容竟然加了密，时间轴倒没有。

HBO 的产品线好混乱，有 HBO GO、HBO NOW，HBO MAX，我需要像 Netflix 那样，随便用浏览器注册个账号就能看的，HBO 那些还得和网络运营商搞套餐和机顶盒，相当麻烦，成本巨大。

**Comment by muzuiget** [comment]
从 v1.2.0 已支持 Hulu。
