### ISSUE TITLE
建议增加字幕间距功能

### ISSUE THREAD

**Issue by siupangcheng** [muzuiget/dualsub-support#79]
![image](https://user-images.githubusercontent.com/14009345/81637394-c6145980-9448-11ea-935b-04adcd112343.png)
习惯了youtube官方的中文字幕间距，现在这个有点紧，不太习惯，中英文上下对应不是很好。

**Comment by muzuiget** [comment]
现在就有啊，在设置里 主题样式 -> 组件样式 里的“内间距”。

**Comment by siupangcheng** [comment]
> 现在就有啊，在设置里 主题样式 -> 组件样式 里的“内间距”。

这个功能设置过，不能解决文字与文字之间的间距。

**Comment by siupangcheng** [comment]
> 现在就有啊，在设置里 主题样式 -> 组件样式 里的“内间距”。

这是设置10x10的效果。想要最下面官方中文字幕间距的效果。左右间距

**Comment by muzuiget** [comment]
你的意思是字与字之间的间隔吧？ `全 员 恶 人` 这样？这个问题不大，下个版本加上。

**Comment by siupangcheng** [comment]
> 你的意思是字与字之间的间隔吧？ `全 员 恶 人` 这样？这个问题不大，下个版本加上。
是的。感谢！
