### ISSUE TITLE
youtube字幕播放问题 - version1.1.2

### ISSUE THREAD

**Issue by FeiyuZi** [muzuiget/dualsub-support#81]
1. 小屏播放视频的时候字幕默认按照全屏播放的长度设置，导致第一字幕过长，无法全部显示出来。
![1589319876(1)](https://user-images.githubusercontent.com/27209717/81750083-73d24780-94df-11ea-82e8-0b745f1dd4a7.jpg)
![1589319932](https://user-images.githubusercontent.com/27209717/81750089-759c0b00-94df-11ea-9cb3-1160e9cb83a1.jpg)

2. 新版字幕位置超级影响用户体验，建议把设置做成二级页面，或者减少在正常视频页面所占的空间，过多的设置选项只会让新手眼花缭乱。
![1589319985(1)](https://user-images.githubusercontent.com/27209717/81750102-7cc31900-94df-11ea-9f50-1e5ab18d19ba.jpg)

3. 如果不是有很多时间的人，我觉得应该不会去折腾这些设置。我的理解是一般用户人群，对这些设置并没有探索欲望。我希望可以有一个类似之前0.8版本的默认设置，如果可以建议，出几版比较好的设置模板，让用户去选择已经设计好的模板，增加用户的体验。（软件工程没有教我们，用户都是很懒的，让用户去做简单的选择，比让用户去设置，更能吸引用户，体验更佳）
![1589320077(1)](https://user-images.githubusercontent.com/27209717/81750130-8187cd00-94df-11ea-9d0e-11403671dbc8.jpg)

4. （我稍稍吐槽一句，我很想回滚到0.8版本，0.8版本已经完全满足我的需求了）之前版本的CSS设置模式，我个人觉得比现在的高级设置更好，虽然这样做会提高入门门槛。

最后的最后：还是很感激大佬做出这样的工具，造福人类。能理解作者的想法，想让这个工具更强大，也支持作者的做法。同时，我们大部分用户的需求其实很简单，就是一个简单的自己可以选择语言和翻译类型的双语字幕。（评价别人的作品总是比去做一个别人的作品更简单，但是呢，我觉得我的想法还是可以给大佬提供一个参考角度，一个相对同行的视角）。最后希望作品能够越来越好！

**Comment by muzuiget** [comment]
感谢你的意见。

1. 这的确是个问题，因为目前的方法就是先自定义个主题样式，把字体弄小一点，切换视频窗口时也切换一下主题样式，多点几下鼠标。

2. 你可以在设置页面里切换一下布局，默认这样做，是在不同窗口宽度下，至少显示完整。

3. 旧版本就没有默认配置，样式都是 YouTube 自带的。

4. Chrome 商店不提供历史版本，新版不支持 Firefox，所以你可以用 Firefox 版的。不过我也不打算花精力维护了，直到它自己失效。

新版本现在不但支持 YouTube 了，还支持好几个网站，现在做主要是为了通用，尽量避免为个别网站写特殊代码，等功能稳定再在界面上优化。

**Comment by muzuiget** [comment]
缩放问题在这里讨论 #87
