### ISSUE TITLE
有没有记忆功能？

### ISSUE THREAD

**Issue by fretyvi** [muzuiget/dualsub-support#82]
你好，不知道这个插件有没有打算写设置记忆功能？打比方，我看youtube我已经在主题样式里面设置好自己喜欢的格式，和主要加载的两个语言，可是，每换一个视频，都要手动在点开一次，能不能（或者我不知道的）加入在观看视频时候，就自动加载自己预设好，载入的字体和主题？

**Comment by muzuiget** [comment]
下个版本加上。

**Comment by muzuiget** [comment]
v1.3.0 已支持记住上次选择。
