### ISSUE TITLE
youtube字幕背景大小的问题 - version1.2.0

### ISSUE THREAD

**Issue by weirhjaklweh** [muzuiget/dualsub-support#83]
刚开始改版，有点摸不着头脑

仔细看了看设置，用了两天新版，总体满意，目前发现字幕背景有一点小瑕疵

![1](https://user-images.githubusercontent.com/13827306/81806775-88e6bf00-954f-11ea-8eb1-22c8ca8d0592.jpg)
使用英文字幕，字幕下方会超出字幕背景

![2020-05-13_190430](https://user-images.githubusercontent.com/13827306/81806598-42916000-954f-11ea-8a0e-6ad409499c67.jpg)
使用中文字幕，字幕下方会紧贴字幕背景，看起来很不舒服

建议增加字幕背景的大小，根据youtube的样式设置就可以，主要是左右下三个方向的，如果想复杂一点就设置成可以调节的

谢谢

**Comment by weirhjaklweh** [comment]
找到调节的选项了
调节主题样式-组建样式-內間距的大小就可以了
目前用的10X5px
出现一个新的问题，第二个数值如果调大的话，因为使用双行字幕，所以两行字幕的中间的间隙就会双倍增大，很不舒服，不过不是什么太大问题，有时间可以解决一下

**Comment by muzuiget** [comment]
要不改成4个方向都能自定义。

**Comment by weirhjaklweh** [comment]
> 要不改成4个方向都能自定义。

也是可以的，就是设置的时候略麻烦一点，每个字幕设置不同的间距大小

**Comment by muzuiget** [comment]
v1.3.0 已支持 4 个内间距。
