### ISSUE TITLE
Doesn't work on disneyplus.com

### ISSUE THREAD

**Issue by kandianying** [muzuiget/dualsub-support#84]
The latest version of chrome extension works on youtube but not disneyplus. The menu does not pop up.

**Comment by kandianying** [comment]
ver1.2.0, to be specific.

**Comment by muzuiget** [comment]
I tried and it still work fine, can you provide the video url? It should starts with `https://www.disneyplus.com/video/`

**Comment by kandianying** [comment]
Today it works fine! Thank you so much for your great extension.

**Comment by muzuiget** [comment]
So, it work again? I didn't change code relate with Disney+.
