### ISSUE TITLE
请问自动选择功能如何使用

### ISSUE THREAD

**Issue by SkeStars** [muzuiget/dualsub-support#88]
在设置说明里没有找到相关的内容

**Comment by muzuiget** [comment]
文档未更新，原本等 Chrome 审核通过就差不多能写完了。简单说两句

* 仅在所有“字幕语言”菜单为关闭时开始生效。
* 每行一个规则。

比如上中下英，简体中文优先。

```
[zh-hans, zh-cn, zh]
[en]
```

不同旧版本，语言代码都是类似通配符效果，最后的 `zh` 相当于 `zh*`，总会给你匹配一个 `zh` 开头的语言，即可能会匹配 `zh-hant` 和 `zh-tw`。

稍后再刷新官网文档吧。

**Comment by SkeStars** [comment]
已解决，感谢回答
