### ISSUE TITLE
新版Dualsub忽略了一个重要问题： 不再支持安卓手机浏览器，之前可以！

### ISSUE THREAD

**Issue by githubberers** [muzuiget/dualsub-support#89]
新版Dualsub忽略了一个重要问题：
不再支持安卓手机浏览器，之前可以！
安卓手机使用Yandex或者Kiwi，浏览器设置成桌面版，之前是一直可以使用Dualsub双字幕插件的，也是最爱的插件。新版Dualsub升级后，安卓手机再也不能使用这个绝好的插件了，非常可惜！好难过，很受伤。移动时代所有的软件都尽可能满足移动端使用，这也是趋势；但新版Dualsub不支持移动端安卓手机，是非常大的遗憾，会损失很多的用户，逼迫老用户使用之前不喜欢的其它双字幕插件。希望作者增加安卓手机模式选项，万分感谢！

**Comment by muzuiget** [comment]
具体是怎么不支持？从 #73 帖子看， 就是工具栏位置问题，最近版本已经做了兼容了，还是有别的问题吗？

**Comment by githubberers** [comment]
![Screenshot_20200515_125648_com kiwibrowser browser](https://user-images.githubusercontent.com/65432491/82115654-b9825080-9729-11ea-86d8-398f61f4ab77.jpg)
如上图所示，没有显示出可选字幕；且我确认该视频有字幕。

**Comment by muzuiget** [comment]
贴一下视频地址。

**Comment by githubberers** [comment]
https://www.youtube.com/watch?v=DOxQFi4ZI2c&t=22s
