### ISSUE TITLE
这是bug吗？macos Chrome

### ISSUE THREAD

**Issue by qin9125** [muzuiget/dualsub-support#91]
![image](https://user-images.githubusercontent.com/32502941/82148062-afc13000-9884-11ea-870d-7accea4147bc.png)
能优化一下，标题栏下的工具条大小吗？以及翻译乱码，谢谢

**Comment by muzuiget** [comment]
试了一下那个视频，Linux 里也能重现。似乎自动字幕又有另外一种格式，我试了其它视频的自动字幕，还正常，不知道这个视频是不是搞特殊。

工具条那个，窗口够大建议放在侧边栏就好了，留空还是拉慢满，反正都是要占用整个垂直空间的了。

**Comment by qin9125** [comment]
> 试了一下那个视频，Linux 里也能重现。似乎自动字幕又有另外一种格式，我试了其它视频的自动字幕，还正常，不知道这个视频是不是搞特殊。
> 
> 工具条那个，窗口够大建议放在侧边栏就好了，留空还是拉慢满，反正都是要占用整个垂直空间的了。

我倒是想把工具条放到侧边栏，可是有bug，每次还是默认标题栏下面，你必须再次刷新才会变到侧边栏，下次打开YouTube又是标题栏下面又再次必须刷新视频。。。很麻烦，不知道是不是macos的Chrome跟win的不一样

**Comment by qin9125** [comment]
> 试了一下那个视频，Linux 里也能重现。似乎自动字幕又有另外一种格式，我试了其它视频的自动字幕，还正常，不知道这个视频是不是搞特殊。
> 
> 工具条那个，窗口够大建议放在侧边栏就好了，留空还是拉慢满，反正都是要占用整个垂直空间的了。

![image](https://user-images.githubusercontent.com/32502941/82167319-f7c86d00-98ed-11ea-8a1f-2e5790980a74.png)
我把插件装到了360急速浏览器macos版，依旧有这个问题，设置的工具条显示到侧边栏，但是还是会出现显示到标题栏下边

**Comment by muzuiget** [comment]
现在的行为是先检测侧边栏是否宽度为 0，否则就自动切到标题栏。你升级到 v1.4.0，当第一次打开时，随便调整一下窗口大小，看看会不会切回侧边栏。

**Comment by qin9125** [comment]
> 现在的行为是先检测侧边栏是否宽度为 0，否则就自动切到标题栏。你升级到 v1.4.0，当第一次打开时，随便调整一下窗口大小，看看会不会切回侧边栏。

试过了，只有当窗口在比较小的时候调整变大工具条会自动到侧边栏去，但是当你的窗口本来就是比较大的时候默认还是会显示到标题栏下面，除非再刷新一遍，macos的窗口逻辑很渣的，可能win没有这问题，

**Comment by qin9125** [comment]
> 现在的行为是先检测侧边栏是否宽度为 0，否则就自动切到标题栏。你升级到 v1.4.0，当第一次打开时，随便调整一下窗口大小，看看会不会切回侧边栏。

能不能判断操作系统，macos直接保留到标题栏下算了，优化一下显示样式，

**Comment by muzuiget** [comment]
我在 MacOS 上试了，确实是这样的，下个版本修掉吧。

**Comment by qin9125** [comment]
> 我在 MacOS 上试了，确实是这样的，下个版本修掉吧。

ok，谢谢

**Comment by muzuiget** [comment]
感觉和应该和广告有关，第一次打开时，播放器会出现一次视频广告，点击 ”Skip AD“ 之后菜单就没出现了。刷新一次后，直接进入真正的视频，所以没问题。

**Comment by qin9125** [comment]
> 感觉和应该和广告有关，第一次打开时，播放器会出现一次视频广告，点击 ”Skip AD“ 之后菜单就没出现了。刷新一次后，直接进入真正的视频，所以没问题。

这也不科学，你只要刷新了，一直停留在YouTube切换看其他视频工具条也不会跑到标题栏下边，只要关了YouTube整个页面重新打开看视频工具条又会回到标题栏下边

**Comment by muzuiget** [comment]
因为刷新时，通常不会再播放一次广告，而我也一直开着广告过滤扩展来开发调试，所以没发现这种问题。

**Comment by muzuiget** [comment]
发布了 v1.4.1，你看看菜单布局是否有改进？

**Comment by qin9125** [comment]
> 发布了 v1.4.1，你看看菜单布局是否有改进？

我正想给你说，还是不行，只要设置为侧边栏，直接标题栏侧边栏都不显示，必须再次刷新页面才能出现工具条

**Comment by qin9125** [comment]
![image](https://user-images.githubusercontent.com/32502941/82395097-55d78a80-9a7d-11ea-8c32-497911ddecd0.png)
设置为标题栏每次都会显示

**Comment by muzuiget** [comment]
不显示时，按一下 F12 弹出开发者工具栏，看看 Console 里有没有错误输出。

**Comment by qin9125** [comment]
> 不显示时，按一下 F12 弹出开发者工具栏，看看 Console 里有没有错误输出。

![image](https://user-images.githubusercontent.com/32502941/82417734-8c79c900-9aae-11ea-83c0-26c65a0bd8c0.png)
看不懂

**Comment by muzuiget** [comment]
这字幕不是显示出来了吗？那么菜单是正常加载得了，只是不知道为什么被隐藏了。

**Comment by qin9125** [comment]
> 这字幕不是显示出来了吗？那么菜单是正常加载得了，只是不知道为什么被隐藏了。

之前设置了，然后就可以显示，但是侧边栏工具条只有再次刷新页面才会出现

**Comment by muzuiget** [comment]
这是每次新打开一个 YouTube 标签页都 100% 出现？
