### ISSUE TITLE
希望允许关闭工具栏

### ISSUE THREAD

**Issue by molkes** [muzuiget/dualsub-support#93]
希望在“网站 → YouTube 工具栏位置”添加关闭选项。因为填写「自动选择」后，一般用不着工具栏了，需要的时候再打开。

**Comment by muzuiget** [comment]
除了“字幕选择”菜单外，其余都能隐藏吧。

**Comment by molkes** [comment]
我还是想要完全隐藏工具栏，不更改页面布局。请考虑把这个请求放在待办清单的末尾。

**Comment by sunday10** [comment]
> 除了“字幕选择”菜单外，其余都能隐藏吧。

感觉还是先前可以css隐藏版本好用。

**Comment by muzuiget** [comment]
已在 v1.5.0 实现。
