### ISSUE TITLE
字幕太长时字幕会超出视频画面

### ISSUE THREAD

**Issue by molkes** [muzuiget/dualsub-support#94]
如图，第一行是Dualsub字幕，超出视频画面。第二行是YouTube字幕，自动换行。

![](https://user-images.githubusercontent.com/62471162/82520248-4415e600-9b56-11ea-863d-9e1da2c9bcc5.png)

**Comment by muzuiget** [comment]
解决这个比较麻烦，毕竟保留换行和双语字幕时习惯不同(一个语言占一行)，只能全屏或者缩小字体。

**Comment by molkes** [comment]
好吧，我明白了
