### ISSUE TITLE
双语字幕文件导出

### ISSUE THREAD

**Issue by outlookmusic** [muzuiget/dualsub-support#95]
请问，如何导出中英双语字幕文件呀？在设置里和文档里都没有找到选项或教程

**Comment by muzuiget** [comment]
YouTube 的话可以用 https://dualsub-exporter.netlify.app/

**Comment by outlookmusic** [comment]
非常感谢🙏

**Comment by Ding-Ye** [comment]
https://dualsub-exporter.netlify.app/ 这个网站导出字幕接口报500

**Comment by muzuiget** [comment]
@Ding-Ye 建了个新单 #188
