### ISSUE TITLE
下载了2020年5月20日版的Dualsub还是不支持安卓手机浏览器

### ISSUE THREAD

**Issue by githubberers** [muzuiget/dualsub-support#96]
![IMG_20200522_164010](https://user-images.githubusercontent.com/65432491/82648884-ffce2880-9bdd-11ea-8439-d4dff0dee672.jpg)
黄框内Dualsub插件显示的内容都是0
https://www.youtube.com/watch?v=DOxQFi4ZI2c&t=22s

**Comment by muzuiget** [comment]
在 PC 上用模拟方式重现不了，模拟不到只能找台真机来测试，这就麻烦了。

这是所有视频都是有问题？

如果先从搜索页跳到视频页，这种情况有没有问题？

试下打开 http://httpbin.org/user-agent，把返回结果截图一下，我来看看模拟 Kiwi 的 UserAgent 是否还有问题。
