### ISSUE TITLE
组件样式 背景设置等不起作用

### ISSUE THREAD

**Issue by feipinxiang** [muzuiget/dualsub-support#98]
![tZLHxJ.png](https://s1.ax1x.com/2020/05/28/tZLHxJ.png)

chrome 版本 83.0.4103.61（正式版本） （64 位）
Dualsub 1.5.0

主题样式设置了无效（全默认设置，安装后只设置了组件样式里的大号字体做测试）
测试网址 https://www.youtube.com/watch?v=WytU5uj78-4

**Comment by muzuiget** [comment]
要在“主题样式”菜单里选择一下才行，一个主题样式包含多个组件样式。

**Comment by feipinxiang** [comment]
> 要在“主题样式”菜单里选择一下才行，一个主题样式包含多个组件样式。

主题样式里默认第一字幕选中的组件样式就是大号字体，我取消了又重新勾选了再刷新u2b页面也没生效

**Comment by feipinxiang** [comment]
重新尝试了一下，也没起作用
![2020-05-28_190324.png](https://i.loli.net/2020/05/28/Eay7vtLmIYkQS1j.png)
![2020-05-28_190352.png](https://i.loli.net/2020/05/28/seQmiF5tylMBON1.png)
![2020-05-28_190317.png](https://i.loli.net/2020/05/28/WTSM3uqj2kXemxt.png)

**Comment by muzuiget** [comment]
看下文档 https://dualsub.netlify.app/zh-cn/quickstart

**Comment by feipinxiang** [comment]
> 看下文档 https://dualsub.netlify.app/zh-cn/quickstart

会了会了，感谢
