### ISSUE TITLE
Change of the Homepage?

### ISSUE THREAD

**Issue by rebelbigfeet** [muzuiget/dualsub-support#99]
Hi, did you change the homepage and the tutorials? It does not match with the add-on anymore? I thought there might be an update but I can't find one. See pictures below. Sorry for my English.

My Dualsub:
<img width="467" alt="Capture d’écran 2020-05-28 à 15 24 21" src="https://user-images.githubusercontent.com/49950822/83147440-f5d58980-a0f7-11ea-855c-2e0a8dfc1858.png">

What it shows in the tutorial:
<img width="788" alt="Capture d’écran 2020-05-28 à 15 24 14" src="https://user-images.githubusercontent.com/49950822/83147332-d2aada00-a0f7-11ea-8838-78bd1eec234f.png">

**Comment by muzuiget** [comment]
Are you using Firefox? Dualsub for Firefox keep on v0.8.1, Dualsub latest version is v1.5.0.

**Comment by yvesrognes** [comment]
> Are you using Firefox? Dualsub for Firefox keep on v0.8.1, Dualsub latest version is v1.5.0.

Yes I am. It does not update in Firefox anymore?

**Comment by muzuiget** [comment]
Yes, The new version code is not compatible with Firefox.

**Comment by rebelbigfeet** [comment]
Ok, thanks for your quick answer! I don't suppose that will change in the future? And the Firefox one won't be deleted even if it's an older version? It'd be great because I still use it.

**Comment by muzuiget** [comment]
Firefox version won't be deleted until it broken.
